### ISSUE TITLE
Reconnect won't lease TLS instance issue should non't closed!!!

### ISSUE THREAD

**Issue by andrew0x0** [aws/aws-iot-device-sdk-embedded-C#100]
Hi, guys, it's seems aws_iot_mqtt_attempt_reconnect don't release last time's TLS resource and malloc it again in follow.

/* Ignoring return code. failures expected if network is disconnected */
	rc = aws_iot_mqtt_connect(pClient, NULL);

It's should been 
    /* TLS instance should release before reconnect*/
    rc = aws_iot_mqtt_disconnect(pClient);

/* Ignoring return code. failures expected if network is disconnected */
	rc = aws_iot_mqtt_connect(pClient, NULL);

**Comment by chaurah** [comment]
Hi @andrew0x0,
      That shouldn't happen because we check for the network state before calling connect in that function. Are you seeing this leak in every instance after Attempt reconnect?

Rahul

**Comment by andrew0x0** [comment]
Hi, 
  If set reconnect to false, in sample files attempt_reconnect will called. But i am not sure state check will fix it. I will check it , and keep u information. THX.
