### ISSUE TITLE
Handling of expired MQTT Sessions / re-subscribe

### ISSUE THREAD

**Issue by lerebel103** [aws/aws-iot-device-sdk-embedded-C#1020]
Hi folks,

When using `IotMqttConnectInfo.cleanSession = false` on `v4_beta`, what is the best way of detecting that a prior session has expired please?

Our subscriptions are restored perfectly from a broker session on short disconnects/reconnects (<1 hour) by setting these on `IotMqtt_Connect()`:
```
IotMqttConnectInfo.previousSubscriptionCount
IotMqttConnectInfo.pPreviousSubscription
```

However if the session expires on the broker side as per [MQTT Persistent Sessions](https://docs.aws.amazon.com/iot/latest/developerguide/mqtt-persistent-sessions.html) I can't spot an obvious way of detecting this case so that I can re-issue past subscriptions.

Thanks for any pointers.
Will.

**Comment by abhidixi11** [comment]
Hello Will,

Thanks for reaching out. Unfortunately v4_beta does not have any way to pass on the session present flag from conn_ack to the application right now.  We will create an internal ticket to investigate the fix for this problem. 
Thanks .

**Comment by lerebel103** [comment]
Hi @abhidixi11,

Makes sense, thanks for confirming this. 

Having the session info is an improvement for sure. Ideally, would it be possible to also have the MQTT library handle this case and re-subscribe internally when `IotMqttConnectInfo.pPreviousSubscription` is present?

Thanks.

**Comment by abhidixi11** [comment]
Hello Will
Yes, that's a good suggestion.  Since pPreviousSubscription already sent by the application, it certainly can be used. I have opened a internal ticket and we will investigate and try to come up with a solution.  I'll close this issue if you do not you have any other questions. You can always open another issue. 
Thanks for reporting this problem.

**Comment by lerebel103** [comment]
Sure thing,
That's great.
Thanks you.
