### ISSUE TITLE
Host URL and port configuration

### ISSUE THREAD

**Issue by eugene345** [aws/aws-iot-device-sdk-embedded-C#103]
Is the any way to change host url and port after calling aws_iot_mqtt_init? Host url and port is configurable in my application. But looks like I can't simply reconnect with new parameters. And there is no API to release resources acquired by aws_iot_mqtt_init - can't call it with new parameters again.

**Comment by eugene345** [comment]
Maybe makes sense to move url and port to IoT_Client_Connect_Params structure to use it with aws_iot_mqtt_connect?

**Comment by chaurah** [comment]
Hi @eugene345,
     I am currently working on completely removing the Network layer init from the MQTT Client. I am making it similar to C++ SDK, where the Network layer is initialized and configured separately from the MQTT layer. This is a major breaking change however, and it will be released in a dev-3.0 branch until we have confirmed it is stable in our internal testing.

I will update this post with further information as soon as the code is out. Please let me know if you have further suggestions.

Rahul

**Comment by eugene345** [comment]
Hi @gordonwang0 ,

Please, re-open the issue. This feature is still important.

**Comment by gordonwang0** [comment]
Hi @eugene345,

We have separated the network interface from the rest of the MQTT library in v4 beta.  This should allow you to configure the network separately from MQTT.

See this [demo file](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/demos/posix/aws_iot_demo_mqtt_posix.c) for an example on Linux.
