### ISSUE TITLE
Publishing to multiple MQTT topics in real time

### ISSUE THREAD

**Issue by eugene345** [aws/aws-iot-device-sdk-embedded-C#104]
Hello,

There are few sensors in my application and I have to publish its data to multiple MQTT topics in real time. MQTT client blocks publishing of the next sensor data, waiting for the current message QOS1 response. Now I have to use separate MQTT clients for each sensor's thread to publish data in real time, which is a waste of MCU resources. 
Is there any plans to implement asynchronous MQTT client?

Best regards,
Eugene

**Comment by chaurah** [comment]
Hi @eugene345,
     We do have a plan for an Async C Client. Unfortunately, that's several months away in dev and testing time. Would it be possible for you to use the C++ SDK for your use case? That has Async APIs as well as the ability to create a custom client specific to your needs.
Please let us know if you have further questions.

Rahul

**Comment by eugene345** [comment]
Hi @chaurah,
Good to hear that you plan it.
No, unfortunately I can't use C++ SDK, because my target device is low power embedded system. I don't use any C++ libraries there, because the system is limited in resources.

Eugene

**Comment by chaurah** [comment]
Adding this request to the task in our backlog, issue will be updated and closed when the new APIs are released.

Rahul

**Comment by eugene345** [comment]
Hi @gordonwang0 ,

Please, re-open the issue. This feature is still important.

**Comment by gordonwang0** [comment]
Hello @eugene345,


We have implemented this in version 4, currently available as a beta version on [this branch](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/README.md).  Please give it a try if you have time.

Version 4's API functions are asynchronous by default.
See:
[MQTT functions](https://docs.aws.amazon.com/freertos/latest/lib-ref/html3/mqtt/mqtt_functions.html)
[Shadow functions](https://docs.aws.amazon.com/freertos/latest/lib-ref/html3/shadow/shadow_functions.html) Note that the documentation for Shadow is not finished yet, but the library is implemented.
