### ISSUE TITLE
How to ensure security of device, if AWS generated certificates are duplicated

### ISSUE THREAD

**Issue by shrinivasragolu** [aws/aws-iot-device-sdk-embedded-C#1040]
Hi All,

I got a typical requirement. (Bilateral authentication)

 We have 3 types of client authentication using 1) Download CA and cert from AWS IOT Core 2) locally created cert with AWS registered CA 3) registering local CA with AWS and using registered CA for authentication locally created cert.

My Issue:
======
For suppose, if my device certificates(device cert, Root CA, and private key), is copied/duplicated to another device at the device level, how to ensure my device authenticity? Because other devices could also communicate without any issues as they possess a downloaded certificates.

Please correct me if I am wrong. But I would like to get the solution to my problem?

Thanks in advance,
Srinivas.

**Comment by abhidixi11** [comment]
Hello @shrinivasragolu,

Thanks for contacting us.  I want to make sure I understand your question correctly.    You have copied ( or planning to copy ) the private key and the cert from one device to another. Now both devices have same set of the private key and the cert.  
Usually  private key/cert  are for a single device, so using it on another device is like identity theft and there is no guarantee that your devices is protected. 

I would recommend using different private key /cert for multiple devices, especially for production. 
Is that what you were asking ? Please let me know.
Thanks.

**Comment by lundinc2** [comment]
Hello @shrinivasragolu,

I am closing this issue as there has been no updates. Please re-open this issue should you have further questions.

Thanks!
