### ISSUE TITLE
#define for shadow topics

### ISSUE THREAD

**Issue by eugene345** [aws/aws-iot-device-sdk-embedded-C#106]
Hello,

Metadata size is half or more of incoming message size. And in most applications it is not used, I think. But RAM size is very limited in embedded systems. The doc http://docs.aws.amazon.com/iot/latest/developerguide/using-thing-shadows.html (Trim Thing Shadow Messages) suggests to republish only necessary fields to another topics.
Would be good to define the shadow topics in aws_iot_config.h, so it can be easy changed later if needed.

Best regards,
Eugene

**Comment by chaurah** [comment]
Hi @eugene345,
       I am not sure I am understanding you correctly. Are you saying we should provide a way in the config.h file to use custom shadow topics instead of the default ones?

Rahul

**Comment by eugene345** [comment]
Hi @chaurah ,

Yes, it could be very useful.

Thanks,
Eugene

**Comment by hedeshianaws** [comment]
@eugene345 I guess I am a little confused too. How would the #define'd shadow topics help with metadata reduction? Are you interested in only certain _fields_ within the shadow document instead of different topics?

**Comment by eugene345** [comment]
Hello,

If I understand the doc correctly, the best option to trim unnecessary fields (like metadata) - create a rule to republish only selected fields to another topic. In this case device has to listen at non default topics.

Best regards,
Eugene

**Comment by hedeshianaws** [comment]
@eugene345 Ok, got it, you are referring to this section "Trim Thing Shadow Messages" in the docs.

**Comment by Borschtsch** [comment]
Hi, @eugene345.

Before you dig into the message trimming, please make sure the republish works the way you think it should.
https://forums.aws.amazon.com/thread.jspa?threadID=252270

At our project we were not able to make it work reliably at all.
We banned this idea and modified the SDK so the device does not subscribe to 'accepted' topic at all. We only rely on delta now.

Regards,
-Dmitry

**Comment by eugene345** [comment]
Hi @gordonwang0 ,

Please, re-open the issue. This feature is still important.

**Comment by gordonwang0** [comment]
Hi @eugene345,

This is somewhat implemented in v4 beta.  The Shadow topics are defined in pieces in [this internal header](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/lib/include/private/aws_iot_shadow_internal.h).  You may modify them there.
