### ISSUE TITLE
JOB_EXECUTION_SUCCESS_STR in aws_iot_jobs_types.h should be JOB_EXECUTION_SUCCEEDED_STR?

### ISSUE THREAD

**Issue by goodwaterwu** [aws/aws-iot-device-sdk-embedded-C#1063]
**aws_iot_jobs_types.h**
extern const char *JOB_EXECUTION_SUCCESS_STR;

**aws_iot_jobs_types.c**
const char *JOB_EXECUTION_SUCCEEDED_STR = "SUCCEEDED";

JOB_EXECUTION_SUCCESS_STR -> JOB_EXECUTION_SUCCEEDED_STR?

**Comment by lundinc2** [comment]
Hello @goodwaterwu 

I have merged a PR that resolves this typo. Thank you for bringing this to our attention! I am closing the ticket as I believe this resolves it, but please re-open it if there is something remaining.
