### ISSUE TITLE
Request: development branch: separate mqtt and mqtt-lightweight into separate directories

### ISSUE THREAD

**Issue by rpcme** [aws/aws-iot-device-sdk-embedded-C#1065]
In the development branch, both mqtt and mqtt-lightweight are in the same directory structure.  It will not be easy for developers to include whole directory structure into IDE projects so in IDE projects developers will need to cherry pick sources from the source tree which is annoying and error prone.  I think being able to choose an entire directory reduces churn for everyone because the IDE can then just sync with the sources recursively and automatically pick up any source/include file adds or removes so refactoring will be less of an impact.

**Comment by dan4thewin** [comment]
Thank you, Richard. I'll add this to our backlog.
