### ISSUE TITLE
Request: development branch: provide mqtt_config.h template for lightweight and full mqtt separately

### ISSUE THREAD

**Issue by rpcme** [aws/aws-iot-device-sdk-embedded-C#1066]
It would be nice to have mqtt_config.h templates.  The mqtt libs depend on this file, but the customer does not know the extent of configurability, sane defaults, extrema, etc for configuration values.  Customers need to look at individual demo configs to get a rough understanding, and individual demo configs can age and not always highlight all possible configurations.

**Comment by dan4thewin** [comment]
Thank you, Richard.  I'll add this to our backlog.
