### ISSUE TITLE
connecting to a3eopakkyl2erz.iot.us-west-2.amazonaws.com

### ISSUE THREAD

**Issue by pramodjaiswal5** [aws/aws-iot-device-sdk-embedded-C#108]
Hi ,

Please help me to solve below issues.

log:
AWS IoT SDK Version 2.1.1-

DEBUG: main L#161 rootCA /home/build/Desktop/aws-iot-device-sdk-embedded-C-master/samples/linux/subscribe_publish_sample/../../../certs/VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem
DEBUG: main L#162 clientCRT /home/build/Desktop/aws-iot-device-sdk-embedded-C-master/samples/linux/subscribe_publish_sample/../../../certs/4cf974aaa2-certificate.pem.crt
DEBUG: main L#163 clientKey /home/build/Desktop/aws-iot-device-sdk-embedded-C-master/samples/linux/subscribe_publish_sample/../../../certs/4cf974aaa2-private.pem.key
Connecting...
DEBUG: iot_tls_connect L#129
. Seeding the random number generator...
DEBUG: iot_tls_connect L#137 . Loading the CA root certificate ...
DEBUG: iot_tls_connect L#143 ok (0 skipped)

DEBUG: iot_tls_connect L#145 . Loading the client cert. and key...
DEBUG: iot_tls_connect L#158 ok

DEBUG: iot_tls_connect L#160 . Connecting to a3eopakkyl2erz.iot.us-west-2.amazonaws.com/8883...
ERROR: iot_tls_connect L#163 failed
! mbedtls_net_connect returned -0x52

ERROR: main L#192 Error(-23) connecting to a3eopakkyl2erz.iot.us-west-2.amazonaws.com:8883

Thanks
Pramod

**Comment by vareddy** [comment]
Hi @pramodjaiswal5 ,
The error 0x52 that is seen above is MBEDTLS_ERR_NET_UNKNOWN_HOST (https://tls.mbed.org/api/net__sockets_8h_source.html). Could you check if you are able telnet to the host above by running: 
```
openssl s_client -connect a3eopakkyl2erz.iot.us-west-2.amazonaws.com:8883
```
You should see server certificate. 
Thank you for your interest in AWS IoT! Please let us know if you have any more questions. 
Thanks!
Varun

**Comment by pramodjaiswal5** [comment]
Hi @Varun ,

Thanks Your quick response.
I run the above command ,but NOT able to see any server certificate.
Please let me know the next step to solve Unknown host issues.

Thanks,
Pramod

**Comment by pramodjaiswal5** [comment]
Hi @vareddy ,

I have sole the issues.
**First** :  update(change) the DNS and,
**Second** : update the policy like:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Subscribe",
        "iot:Connect",
        "iot:Receive"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}
****************************************
Then its working fine.

Thanks,
Pramod

**Comment by vareddy** [comment]
That's great! I'll close this issue, please open another one if you have any more questions. 
Thanks!
Varun
