### ISSUE TITLE
Task pool size configuration

### ISSUE THREAD

**Issue by boraozgen** [aws/aws-iot-device-sdk-embedded-C#1085]
Hello,

is it planned to expose the task pool size configuration to the integrator? This is pretty important for those who want absolute control on the threads spawned by the client.

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/5a22bbeb2059b95bc21be291a9635f1e3dd11014/libraries/standard/common/src/iot_init.c#L90

**Comment by lundinc2** [comment]
Hello @boraozgen,

This is a complicated question, as there are various versions of the taskpool floating around. To answer your question in the context of the taskpool in the v4 branch of the C-SDK, there currently is no new feature work in progress for it.

**Comment by boraozgen** [comment]
Yes, I am using the v4 branch. I think it should be fairly simple to make this configurable from iot_config.h, don't you think?

**Comment by dan4thewin** [comment]
Hello, @boraozgen .  We're working on a refactored set of libraries that do not depend on a task pool.  You can see the work in progress here: https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/development

If you need a task pool and you're using FreeRTOS, please have a look at https://github.com/FreeRTOS/FreeRTOS/tree/lts-development/FreeRTOS-Plus/Source/FreeRTOS-IoT-Libraries-LTS-Beta1/abstractions/platform/freertos/private/taskpool .

**Comment by boraozgen** [comment]
Thanks for the tip, I checked out the platform headers and the platform layer seems to have changed considerably. Is the library going to be synchronous, i.e. single-threaded? Is there an ETA for the update?

**Comment by dan4thewin** [comment]
Yes, although there will be demos to show concurrent use on some reference platforms.  Much of the work is already finished and on the development branch.
