### ISSUE TITLE
How to save data into DynamoDB database

### ISSUE THREAD

**Issue by pramodjaiswal5** [aws/aws-iot-device-sdk-embedded-C#109]
Hi Team,

How to save data into DynamoDB database from/using "C" sample applications?
Please let me know the steps need to be follow.

Regards,
Pramod

**Comment by hedeshianaws** [comment]
@pramodjaiswal5 Thank you for your interest in AWS IoT. The AWS IoT Embedded C SDK is an MQTT client which can access AWS IoT data-plane. It does not interact directly with DynamoDB or an other AWS service directly. 

Instead you have to send your data to AWS IoT using the IoT Embedded C SDK. Once your data is in AWS IoT, you can used AWS Lambda or the AWS IoT Rules Engine to access Dynamo. Below are some links to get you started.

http://docs.aws.amazon.com/lambda/latest/dg/with-ddb.html
http://docs.aws.amazon.com/iot/latest/developerguide/iot-lambda-rule.html
http://docs.aws.amazon.com/iot/latest/developerguide/iot-ddb-rule.html



You will have a much better chance of getting your question answered in the AWS IoT forums. I recommend starting a new thread there as these Github issues are only monitored for SDK specific bugs and issues.
