### ISSUE TITLE
Fix misleading MQTT_RX_BUFFER_TOO_SHORT_ERROR error

### ISSUE THREAD

**Issue by BenJacques** [aws/aws-iot-device-sdk-embedded-C#1092]
I recently ran into an issue where I was getting error -32 (MQTT_RX_BUFFER_TOO_SHORT_ERROR) in an aws_iot_shadow_yield() call. It led me down a rabbit trail thinking the error was due to too large of a shadow update or something not being set right with the MQTT Rx buffer size. 

However, the issue ended up being an issue with low memory availability that was happening in this line earlier in the function:
`rc = pClient->networkStack.read(&(pClient->networkStack), pClient->clientData.readBuf, bytes_to_be_read, pTimer, &read_len);`

I was wondering if it would be better to let this error bubble up to the user rather than mask it under the current error since this can be misleading.

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/72060241a4bf9c1222c7ff9e24955851e8c2e1ca/src/aws_iot_mqtt_client_common_internal.c#L470

**Comment by dan4thewin** [comment]
Hi, @BenJacques .  I'm sorry you had this trouble.  Quite a bit has changed in our refactored version of the library.  Please have a look.  I hope it meets your needs better than older version.  https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/development
