### ISSUE TITLE
Unable to establish connection when timeout value is too large

### ISSUE THREAD

**Issue by anozaki** [aws/aws-iot-device-sdk-embedded-C#11]
I have been testing on my mac before I attemt to load this on to an iPad. Everything compiles but had connection problem when the timeout value was set (In my case it was 5000).

The problem seems to be in ConnectOrTimeoutOrExitOnError in network_openssl_wrapper.c.
The select function returns EINVAL and according to the mac's man page. "The specified time limit is invalid.  One of its components is negative or too large."

had to update timeout code to...
struct timeval timeout = {timeout_ms / 1000, (timeout_ms % 1000) * 1000};

The timeval is created in bunch of different place so I'm guessing this will happen in other places as well.

**Comment by johnrotach** [comment]
Hello Akito,

Thank you for raising this issue!  This indeed is an error with larger timeouts.  We will aim to add this fix to our next release.

BTW, I see you are targeting an iPad application so I thought I'd point our our [iOS SDK for AWS IoT](https://forums.aws.amazon.com/ann.jspa?annID=3419) which was recently released.

Thank you again.

John
AWS IoT

**Comment by anozaki** [comment]
Thanks for the link.  I'll check out the iOS release.

**Comment by bhadrip** [comment]
This bug is fixed with [the](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/aws_iot_src/protocol/mqtt/aws_iot_embedded_client_wrapper/platform_linux/openssl/network_openssl_wrapper.c#L318) release of [v1.1.0](https://github.com/aws/aws-iot-device-sdk-embedded-C/releases/tag/v1.1.0)
