### ISSUE TITLE
What happens now that there is an Amazon FreeRTOS project?

### ISSUE THREAD

**Issue by bpair** [aws/aws-iot-device-sdk-embedded-C#111]
Just curious what is the long term plan for this repository now that Amazon has taken over FreeRTOS? Will this be a non-RTOS implementation? Will the MQTT and TLS code be shared?

It sure seems like there will be more focus on
https://aws.amazon.com/freertos/

than this repository. We are using freeRTOS so I would assume we would want to move to that.

**Comment by jimisataws** [comment]
Thanks for the question and your interest in AWS IoT. At this moment, we do not have any plans to share about this repository as a result of Amazon FreeRTOS announcement.

**Comment by Borschtsch** [comment]
Hi @bpair ,

Amazon FreeRTOS is just another RTOS and new MQTT/Shadow implementations are tightly coupled with it. AWS IoT SDK can be used on any OS. I would not worry much :)

-Dmitry

**Comment by drodgers-ls** [comment]
@Borschtsch - I would caution against the statement that the "AWS IoT [Embedded C] SDK can be used on any OS".  As AWS themselves said in [this thread](https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/89), as of July 2017 the SDK has "long standing architectural issues which make this SDK difficult if not impossible to use on FreeRTOS class devices".  Now, I have not had an opportunity to dive into the Amazon FreeRTOS distribution, or compare it against the present state of this embedded C SDK, so circumstances may have changed, but from what I understand right now, if you plan on running FreeRTOS, there's no reason to use anything other than the Amazon FreeRTOS distro.

**Comment by Borschtsch** [comment]
@drodgers-ls , thanks for the answer. However, I just said it can run on any OS. I totally agree with their statement that it may be difficult to use on FreeRTOS class devices. but not impossible.

**Comment by Borschtsch** [comment]
@drodgers-ls, I didn't try to compile Amazon FreeRTOS distro to compare flash/ram usage, but quick investigation showed that its user should find his own way to develop support for the Shadow parameters - it just does not exist.
However, the Shadow parameters implementation in current SDK is the actual reason for "long standing architectural issues", everything else in the SDK works almost fine.

**Comment by chrismrutherford** [comment]
Directly Integrating the SDK with FreeRTOS  would be akin to integrating an application with a Kernel, and wouldn't make much sense.  The best way forwards would be support the SDK and FreeRTOS over a wide range of development environments and dev boards; including lower spec varieties.
