### ISSUE TITLE
Timeout on Get Shadow but getting data

### ISSUE THREAD

**Issue by kayleejacob1** [aws/aws-iot-device-sdk-embedded-C#1115]
When getting shadow with get shadow I am getting the call back and data but with Shadow_Ack_Status_t = SHADOW_ACK_TIMEOUT in the call back

**Comment by yanjos-dev** [comment]
Hi @kayleejacob1 , thank you for sharing your question. Can you provide additional information about what board, build tools, and version of the code you are using? Were you able to successfully run the shadow demo based on our getting started guides?

Here is a link to the board specific getting started guides:
https://docs.aws.amazon.com/freertos/latest/userguide/getting-started-guides.html

Here is a link related to the Shadow demo application:
https://docs.aws.amazon.com/freertos/latest/userguide/shadow-demo.html

**Comment by kayleejacob1** [comment]
No using demo but is like the shadow demo.  I using the latest 3.1.1 code

I am requesting a get from the server.  I do get the data but receive
timeout as well

Debug:
[I][AWS_IOT.cpp:791] ShadowConnect(): Shadow Init
[I][AWS_IOT.cpp:815] ShadowConnect(): Shadow Connect
[I][AWS_IOT.cpp:815] ShadowConnect(): Shadow Get
[I][AWS_IOT.cpp:590] UpdateStatusCallback(): data received is
{"state":{"desired":{"SpiffVer":0.1,"FirmwareVer":0.1,"Status":1,"UnitType":1,"WifiId":"sample1","WifiPassword":"sample","Area":1},"reported":{"SpiffVer":0.1,"FirmwareVer":0.1,"Status":254,"UnitType":1,"WifiId":"sample1","WifiPassword":"sample","Area":1.0,"Unittype":1,"Wifiid":"sample1","Wifipassword":"sample"},"delta":{"Status":1}},"metadata":{"desired":{"SpiffVer":{"timestamp":1597256257},"FirmwareVer":{"timestamp":1597256257},"Status":{"timestamp":1597256257},"UnitType":{"timestamp":1597256257},"WifiId":{"timestamp":1597256257},"WifiPassword":{"timestamp":1597256257},"Area":{"timestamp":1597256257}},"reported":{"SpiffVer":{"timestamp":1597287823},"FirmwareVer":{"timestamp":1597287823},"Status":{"timestamp":1597287823},"UnitType":{"timestamp":1597287823},"WifiId":{"timestamp":1597287823},"WifiPassword":{"timestamp":1597287823},"Area":{"timestamp":1597287823},"Unittype":{"timestamp":1597265883},"Wifiid":{"timestamp":1597265883},"Wifipassword":{"timestamp":1597265883}}},"version":2858,"timestamp":1597287865,"clientToken":"807D3A087ED1h-0"}
[I][AWS_IOT.cpp:599] UpdateStatusCallback(): Update Timeout--

Code:
 if (!connected)ShadowConnect(t_hostAddress, clientID);
    IoT_Error_t rc = FAILURE;
    rc = aws_iot_shadow_get(&mqttClient, clientID, UpdateStatusCallback,
NULL, 3, false);
    if (SUCCESS != rc) {
        ESP_LOGI(TAG, "unable to get shadow - %d", rc);
        return 11;////////////////////////////////////need to do mor error
catching later
    }
    delay(500);
    for (int i = 0; i < 6; i++) {
        aws_iot_shadow_yield(&mqttClient, 200);
        delay(500);
    }
    return shadat.stat;

Call Back:
static void  UpdateStatusCallback(const char* pThingName, ShadowActions_t
action, Shadow_Ack_Status_t status, const char* pReceivedJsonDocument,
void* pContextData) {

   // ESP_LOGI(TAG, "pThingName recived is %s", pThingName);
    IOT_UNUSED(pThingName);
   // if (action == SHADOW_GET) ESP_LOGI(TAG, "action recived is get");
   // if (action == SHADOW_UPDATE) ESP_LOGI(TAG, "action recived is
update");
  //  if (action == SHADOW_DELETE) ESP_LOGI(TAG, "action recived is
delete");
    IOT_UNUSED(action);
    ESP_LOGI(TAG, "data recived is %s", pReceivedJsonDocument);
    IOT_UNUSED(pReceivedJsonDocument);
    //ESP_LOGI(TAG, " context data recived is %s", pContextData);
    IOT_UNUSED(pContextData);

    if (SHADOW_ACK_TIMEOUT == status) {
        ESP_LOGI(TAG, "Update Timeout--");
    }
    else if (SHADOW_ACK_REJECTED == status) {
        ESP_LOGI(TAG, "Update RejectedXX");
    }
    else if (SHADOW_ACK_ACCEPTED == status) {
        ESP_LOGI(TAG, "Update Accepted !!");

    }
    if (pReceivedJsonDocument != "") {
        StaticJsonDocument<2000> doc;
        deserializeJson(doc, pReceivedJsonDocument);
        shadowdata data;
        data.firm = doc["state"]["desired"]["FirmwareVer"].as<float>();
        data.spiff = doc["state"]["desired"]["SpiffVer"].as<float>();
        data.area = doc["state"]["desired"]["Area"].as<float>();
        data.stat = doc["state"]["desired"]["Status"].as<uint8_t>();
        data.uint = doc["state"]["desired"]["UnitType"].as<uint8_t>();
        data.wifipass =
doc["state"]["desired"]["WifiPassword"].as<String>();
        data.wifiid = doc["state"]["desired"]["WifiId"].as<String>();
        TestCurrentShadow(data);
    }
}

**Comment by kayleejacob1** [comment]
Version 3.0.1 i said it wrong in last message

**Comment by kayleejacob1** [comment]
I removed these two keys and this has gone away and working correctly they both had data that were strings "WifiId":"sample1","WifiPassword":"sample"

**Comment by leegeth** [comment]
@kayleejacob1 ,

Thanks for reaching out with the issue that you are facing. We have a few questions related to the issue that you faced. 
1. Have you got the log message "Update Timeout" after receiving the complete Shadow JSON document?  
2. Can you please provide us the logs after removing the two keys that you mentioned, so as to understand what is the difference in both these cases?

**Comment by aggarg** [comment]
I am closing this issue. Feel free to re-open or create a new issue if you need anything else. 

Thanks.
