### ISSUE TITLE
Can not subscribe using ESP32 and Arduino IDE

### ISSUE THREAD

**Issue by Akshay1595** [aws/aws-iot-device-sdk-embedded-C#1152]
I want to receive a message from my AWS thing in my ESP32 board, for that I am trying subscribe function. But I am not able to subscribe to the same topic with which I publish a message, I have attached my code and log output below. Please guide me about what I am missing.

### My C code for ESP32: 
`/*
#include<WiFi.h>
#include<DHT.h>
#include<AWS_IOT.h>

#define DHT_PIN 33 // pin connected to data pin of DHT11
#define DHT_TYPE DHT11  // Type of the DHT Sensor, DHT11/DHT22

#define WIFI_SSID "Akshay_wifi" // SSID of your WIFI
#define WIFI_PASSWD "abcdabcd" //your wifi password

#define CLIENT_ID "Aksha_Humidity"// thing unique ID, this id should be unique among all things associated with your AWS account.
#define MQTT_TOPIC "aws/things/Smart_Solutions/shadow/update" //topic for the MQTT data
#define AWS_HOST "a21w079cqlmaf8-ats.iot.ap-south-1.amazonaws.com" // your host for uploading data to AWS,

DHT dht(DHT_PIN, DHT_TYPE);
AWS_IOT aws;
int count = 0;

void handler(char *topicName, int payloadLen, char *payLoad)
{
  char string[100] = {};
  sprintf(string,"%d character received and string = %s\n",payloadLen,payLoad);
  Serial.println(string);
}

void setup(){
  Serial.begin(9600);
  Serial.print("\nInitializing thing Temp_Humidity_DHT11_0 \n");

  Serial.print("\n  Initializing WIFI: Connecting to ");
  Serial.println(WIFI_SSID);
  WiFi.begin(WIFI_SSID, WIFI_PASSWD);
  Serial.print("  ");
  while(WiFi.status() != WL_CONNECTED){
    Serial.print(".");
    delay(500);
  }
  Serial.println("\n  Connected.\n  Done");

  Serial.print("\n  Initializing DHT11...");
  //dht.begin();
  Serial.println("  Done.");

  Serial.println("\n  Initializing connetction to AWS....");
  if(aws.connect(AWS_HOST, CLIENT_ID) == 0){ // connects to host and returns 0 upon success
    Serial.println("  Connected to AWS\n  Done.");
  }
  else {
    Serial.println("  Connection failed!\n make sure your subscription to MQTT in the test page");
  }
  if(aws.subscribe(MQTT_TOPIC,handler) != 0)
  {
    Serial.println("Failed subscription!\n");
  }
  else
  {
    Serial.println("Subsription Successfull!\n");
  }
  
  Serial.println("  Done.\n\nDone.\n");
}

void loop(){

     char payload[40] = "Hello from ESP32!\n";
     sprintf( payload, "Hello from ESP32 with count = %d\n",count);
     count++;
    Serial.println("Publishing:- ");
    Serial.println(payload);
     if(aws.publish(MQTT_TOPIC, payload) == 0){// publishes payload and returns 0 upon success
      Serial.println("Success\n");
    }
    else{
      Serial.println("Failed!\n");
    }
  delay(1000);
}`

### Log Output:
17:56:37.435 -> 
17:56:37.435 -> Initializing thing Temp_Humidity_DHT11_0 
17:56:37.482 -> 
17:56:37.482 ->   Initializing WIFI: Connecting to Akshay_wifi
17:56:37.529 ->   .......
17:56:41.030 ->   Connected.
17:56:41.030 ->   Done
17:56:41.030 -> 
17:56:41.030 ->   Initializing DHT11...  Done.
17:56:41.077 -> 
17:56:41.077 ->   Initializing connetction to AWS....
17:56:44.235 ->   Connected to AWS
17:56:44.235 ->   Done.
17:56:44.282 -> E (6918) AWS_IOT: Error subscribing : -30 
17:56:44.329 -> Failed subscription!
17:56:44.329 -> 
17:56:44.329 ->   Done.
17:56:44.329 -> 
17:56:44.329 -> Done.
17:56:44.329 -> 
17:56:44.329 -> Publishing:- 
17:56:44.375 -> Hello from ESP32 with count = 0
17:56:44.422 -> 
17:56:44.422 -> Failed!
17:56:44.422 -> 
17:56:45.289 -> Publishing:- 
17:56:45.289 -> Hello from ESP32 with count = 1
17:56:45.335 -> 
17:56:45.335 -> Success
17:56:45.335 -> 
17:56:46.267 -> Publishing:- 
17:56:46.314 -> Hello from ESP32 with count = 2
17:56:46.314 -> 
17:56:46.314 -> Success
17:56:46.361 -> 
17:56:47.281 -> Publishing:- 
17:56:47.281 -> Hello from ESP32 with count = 3
17:56:47.328 -> 
17:56:47.328 -> Success
17:56:47.328 -> 
17:56:48.267 -> Publishing:- 
17:56:48.314 -> Hello from ESP32 with count = 4
17:56:48.314 -> 
17:56:48.314 -> Success

**Comment by tgsong** [comment]
Hi, seems that you're not actually using the software from this repository so I don't know what exactly went wrong. Could you double check if the certificate for the thing is configured correct? I don't see you have configured that in your code. Meanwhile, please make sure the certificated is attached to the IoT thing you created, and it is activated. You can check this from the AWS IoT console.
