### ISSUE TITLE
Device connection failing on ESP32 

### ISSUE THREAD

**Issue by thehellmaker** [aws/aws-iot-device-sdk-embedded-C#116]
I am getting the following error when trying to connected to AWS IOT thing

E (10691) aws_iot: failed! mbedtls_net_connect returned -0x52
E (10692) AWS_IOT: Error(-23) connecting to a3dw9faflxgdj7.iot.us-east-1.amazonaws.com:8883,
Trying to reconnect
E (10822) aws_iot: failed! mbedtls_net_connect returned -0x52
E (10823) AWS_IOT: Error(-23) connecting to a3dw9faflxgdj7.iot.us-east-1.amazonaws.com:8883,
Trying to reconnect
E (10952) aws_iot: failed! mbedtls_net_connect returned -0x52
E (10953) AWS_IOT: Error(-23) connecting to a3dw9faflxgdj7.iot.us-east-1.amazonaws.com:8883,
Trying to reconnect
E (11083) aws_iot: failed! mbedtls_net_connect returned -0x52
E (11084) AWS_IOT: Error(-23) connecting to a3dw9faflxgdj7.iot.us-east-1.amazonaws.com:8883,
Trying to reconnect
E (11213) aws_iot: failed! mbedtls_net_connect returned -0x52
E (11214) AWS_IOT: Error(-23) connecting to a3dw9faflxgdj7.iot.us-east-1.amazonaws.com:8883,
Trying to reconnect

**Comment by vareddy** [comment]
Hi @thehellmaker,
The error returned by `mbedtls_net_connect` (-0x52) indicates that the host is unknown or it is not able to resolve the host. More information about the return codes can be found [here](https://tls.mbed.org/api/net__sockets_8h.html#a937d55e9aa02f1554a43f562a5fc24f9). Could you please check if your Wi-Fi network is active and the endpoint can be accessed by the ESP32?

Thank you for your interest in AWS IoT and please let us know if you have any more questions.
Varun

**Comment by thehellmaker** [comment]
This was the issue. I was trying to connect before Wifi was connected. THanks a lot for the help @vareddy 

But post this the error code changed to 
E (202115) aws_iot: failed! mbedtls_ssl_setup returned -0x7f00
E (202117) AWS_IOT: Error(-4) connecting to a3dw9faflxgdj7.iot.us-east-1.amazonaws.com:8883,
Trying to reconnect

I couldn't find the error code for -0x7f00 in the link that you provided.

**Comment by vareddy** [comment]
Hi @thehellmaker ,
That error code means that `mbedtls_ssl_setup` failed to allocate the memory required. That error code is found [here](https://tls.mbed.org/api/ssl_8h.html#a701ee611f7a16a261b306466c8602177). 
This [issue](https://github.com/espressif/esp-idf/issues/290) seems to match your case, could you try the fixes given here?
Thanks!
Varun

**Comment by thehellmaker** [comment]
Hi @vareddy...
Actually it was an issue because of was doing it continuously in a loop even though connect succeeded the first time. That's why it was having memory issue. It's resolved now thanks a lot.

**Comment by gpravada** [comment]
How it was resolved? 
I think i am also getting similar issue, by logs are below.
`I (24) boot: ESP-IDF v5.1-480-g79b1379662-dirty 2nd stage bootloader
I (24) boot: compile time Sep  7 2023 23:17:02
I (25) boot: chip revision: v0.4
I (29) boot.esp32c3: SPI Speed      : 80MHz
I (34) boot.esp32c3: SPI Mode       : DIO
I (39) boot.esp32c3: SPI Flash Size : 4MB
I (43) boot: Enabling RNG early entropy source...
I (49) boot: Partition Table:
I (52) boot: ## Label            Usage          Type ST Offset   Length
I (60) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (67) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (74) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (82) boot:  3 ota_0            OTA app          00 10 00010000 001f0000
I (89) boot:  4 ota_1            OTA app          00 11 00200000 001f0000
I (97) boot: End of partition table
I (101) esp_image: segment 0: paddr=00010020 vaddr=3c0c0020 size=71000h (462848) map
I (183) esp_image: segment 1: paddr=00081028 vaddr=3fc91e00 size=02a3ch ( 10812) load
I (186) esp_image: segment 2: paddr=00083a6c vaddr=40380000 size=0c5ach ( 50604) load
I (199) esp_image: segment 3: paddr=00090020 vaddr=42000020 size=b45dch (738780) map
I (317) esp_image: segment 4: paddr=00144604 vaddr=4038c5ac size=057f0h ( 22512) load
I (327) boot: Loaded app from partition at offset 0x10000
I (327) boot: Disabling RNG early entropy source...
I (339) cpu_start: Unicore app
I (339) cpu_start: Pro cpu up.
I (348) cpu_start: Pro cpu start user code
I (348) cpu_start: cpu freq: 160000000 Hz
I (348) cpu_start: Application information:
I (351) cpu_start: Project name:     udemy_esp32
I (356) cpu_start: App version:      cac14f9-dirty
I (361) cpu_start: Compile time:     Sep 10 2023 18:49:46
I (367) cpu_start: ELF file SHA256:  945d6f82a05273f2...
I (373) cpu_start: ESP-IDF:          v5.1-480-g79b1379662-dirty
I (380) cpu_start: Min chip rev:     v0.3
I (385) cpu_start: Max chip rev:     v0.99
I (390) cpu_start: Chip rev:         v0.4
I (394) heap_init: Initializing. RAM available for dynamic allocation:
I (402) heap_init: At 3FC99050 len 000436C0 (269 KiB): DRAM
I (408) heap_init: At 3FCDC710 len 00002950 (10 KiB): STACK/DRAM
I (414) heap_init: At 50000010 len 00001FD8 (7 KiB): RTCRAM
I (422) spi_flash: detected chip: generic
I (425) spi_flash: flash io: dio
I (430) sleep: Configure to isolate all GPIO pins in sleep state
I (436) sleep: Enable automatic switching of GPIO sleep configuration
I (443) app_start: Starting scheduler on CPU0
I (448) main_task: Started on CPU0
I (448) main_task: Calling app_main()
I (458) wifi_app: STARTING WIFI APPLICATION
I (458) pp: pp rom version: 9387209
I (458) net80211: net80211 rom version: 9387209
I (468) main_task: Returned from app_main()
I (478) wifi_init: rx ba win: 6
I (478) wifi_init: tcpip mbox: 32
I (478) wifi_init: udp mbox: 6
I (478) wifi_init: tcp mbox: 6
I (488) wifi_init: tcp tx win: 5744
I (488) wifi_init: tcp rx win: 5744
I (498) wifi_init: tcp mss: 1440
I (498) wifi_init: WiFi IRAM OP enabled
I (498) wifi_init: WiFi RX IRAM OP enabled
I (1178) phy_init: phy_version 970,1856f88,May 10 2023,17:44:12
I (1218) wifi_app: WIFI_EVENT_STA_START
I (1218) wifi_app: WIFI_EVENT_AP_START
I (1218) esp_netif_lwip: DHCP server started on interface WIFI_AP_DEF with IP: 192.168.0.1
I (1228) wifi_app: WIFI_APP_MSG_LOAD_SAVED_CREDENTIALS
I (1228) nvs: app_nvs_load_sta_creds: Loading Wifi credentials from flash
app_nvs_load_sta_creds: SSID: Yoshitha Password: Pastword@2021
I (1238) wifi_app: Loaded station configuration
I (1248) wifi_app: WIFI_APP_MSG_START_HTTP_SERVER
I (1258) http_server: http_server_configure: Starting server on port: '80' with task priority: '4'
I (1268) http_server: http_server_configure: Registering URI handlers
I (3318) wifi_app: WIFI_EVENT_STA_CONNECTED
I (4318) wifi_app: IP_EVENT_STA_GOT_IP
I (4318) esp_netif_handlers: sta ip: 192.168.0.102, mask: 255.255.255.0, gw: 192.168.0.1
I (4318) wifi_app: WIFI_APP_MSG_STA_CONNECTED_GOT_IP
I (4318) main: WiFi Application Connected!!
I (4328) aws_iot: AWS IoT SDK Version 3.0.1-
I (4328) aws_iot: Connecting to AWS...
I (4338) sntp_time_sync: Initializing the SNTP service
I (4338) http_server: HTTP_MSG_WIFI_CONNECT_SUCCESS`
