### ISSUE TITLE
mqttInitParams.mqttPacketTimeout_ms should be initialized.

### ISSUE THREAD

**Issue by karlnicholas** [aws/aws-iot-device-sdk-embedded-C#117]
I copied the latest code over to the TI CC3220-LAUNCHXL code and ran into an assertion fail from `aws_iot_mqtt_internal_read_packet` where it calls `countdown_ms`. Assertion caused b/c `pClient->clientData.packetTimeoutMs` was not initialized. Found the code below in the original TI code in `aws_iot_shadow.c`. Copied that code over and fixed assertion. Have made pull request regards this issue.

    /*
     * TODO AWS team forgot to initialize the newly added parameter
     * 'mqttPacketTimeout_ms', so do it here.  Due to this, this file is now
     * out of sync with the AWS v2.1.1 code base:
     */
    mqttInitParams.mqttPacketTimeout_ms = 5000;

**Comment by hedeshianaws** [comment]
Thank you for reporting this issue and submitting the pull request. This looks like a simple enough fix. I'll need to double check on that default value but we should be able to merge it shortly.

**Comment by karlnicholas** [comment]
Np. The code only fails in the TI device because they have their own implementation of timer.c. I don't know what logic they used to determine the default value, I just copied what they had there when they last ported this code over to their simplelink product line.

**Comment by vareddy** [comment]
This has been merged into master.
Thanks!
Varun
