### ISSUE TITLE
How to be notified when shadow is deleted?

### ISSUE THREAD

**Issue by iheb-eddine** [aws/aws-iot-device-sdk-embedded-C#12]
Hello,

I register to shadow attributes using this function aws_iot_shadow_register_delta.
Then I am doing a loop on aws_iot_shadow_yield and checking the return value of yield.

When the shadow is removed, I won't be notified and the yield does not return an error.
This is a serious problem for us, because in this case we should stop our service.

Is there a way to receive notification when shadow is removed?

Regards,
Iheb Eddine

**Comment by bhadrip** [comment]
Hello Iheb,

Anytime a shadow is deleted, a message is sent on the `$aws/things/thingName/shadow/delete/accepted` topic. If you can listen to this topic, then you will be notified anytime the shadow is deleted. 

Unfortunately that is not part of our shadow API currently. We will add it to our future release. 

Having said that, we can do it currently by directly subscribing to the topic.

The code will be something like this:
```
MQTTSubscribeParams subParams = MQTTSubscribeParamsDefault;
subParams.mHandler = MQTTcallbackHandler;
subParams.pTopic = "$aws/things/My-Custom-ThingName/shadow/delete/accepted";
subParams.qos = QOS_0;

INFO("Shadow Connect");
rc = aws_iot_shadow_connect(&mqttClient, &sp);
rc = mqttClient.subscribe(&subParams);
```

The `MQTTcallbackHandler` will be invoked anytime Shadow is deleted. 

Hope this helps. Please let me know if you have more questions.

Thanks
Bhadri

**Comment by chaurah** [comment]
Hi Iheb,
         We have added a callback to the Shadow Connect Parameters which can be used for delete notifications. I am closing this issue now. Please feel free to let us know if there are any other issues we can help you with.

Rahul
