### ISSUE TITLE
Load thing name/cert/private key from config.mfg file

### ISSUE THREAD

**Issue by wc2507** [aws/aws-iot-device-sdk-embedded-C#120]
I am able to connect/interact with my device thing's shadow using the web provisioning api to load the name, region, cert, and key. 

I am unclear on how to transition to using the config.mfg file to avoid having to enter the values using the web api. I have completed the following steps: 
`
`
     a) added line to build.mk:
`          project-mfg-cfg-y := config.mfg
`    
b) Open config.mfg and set aws_thingname variable with the device thing name
     c) Populate aws_cert with the path to device certificate file
     d) Populate aws_key with the path to device private key file
     e) Flash the layout with mfg partition (layout.txt)
     f)Then with other images flash mfg image (mfg-project.bin)

In these steps, my config.mfg looks like:
```
     aws_thingname=MyWiFiEvalBoard
     aws_cert=11f7d0e571-certificate.pem.crt
     aws_key=11f7d0e571-private.pem.key
```

Once completing these steps, the message I receive is: 
Failed to read thing-name. Returning!

I also receive:
```
     Object: cloud.certificate not found for reading
     Object: cloud.region not found for reading
     Object: cloud.thing not found for reading
     Object: cloud.private_key not found for reading
```

This makes me think that it is not initially reading/storing the info from the config.mfg file, but I don't know how to fix this.

(my aws_iot_config.h file contains the following):
```
     #define AWS_IOT_MQTT_HOST              "" ///< Customer specific MQTT HOST. 
     #define AWS_IOT_MQTT_PORT              8883 ///< default port for MQTT/S
     #define AWS_IOT_MQTT_CLIENT_ID         "mrvl" ///< MQTT client ID should be unique for every device
     #define AWS_IOT_MY_REGION_NAME         "us-west-2"
     #define AWS_IOT_MY_THING_NAME          "MyWiFiEvalBoard"
```

**Comment by hedeshianaws** [comment]
Thank you for using the AWS IoT C SDK. You refer to build.mk and config.mfg. These are not part of the SDK we distribute. Did you obtain the SDK through a third party?

**Comment by wc2507** [comment]
Yes we obtained the SDK from Marvell

**Comment by vareddy** [comment]
Hi @wc2507,
We are not aware of the changes that Marvell would have made to the SDK and will not be able to provide much help in configuring the modified SDK. Could you please try posting the issue in Marvell's Github repository? From a cursory look around the Marvell SDK (https://github.com/marvell-iot/aws_starter_sdk/tree/master/sdk/external/aws_iot) it seems that the SDK has diverged a lot from the current state of the AWS IoT SDK for embedded C. 
I will close this issue, please open a **new issue** if you have any more questions about the SDK.
Thanks!
Varun
