### ISSUE TITLE
Issues using aws_iot_shadow_yield

### ISSUE THREAD

**Issue by romancardenas** [aws/aws-iot-device-sdk-embedded-C#121]
Hello everyone! First of all, I want to apologise, as I am just starting developing with this SDK and I do not control several details.

I have adapted the SDK for an atmel SAMD21 using a WINC1500 peripheral.
Everything works great: It connects to AWS, it subscribes to topics and publishes messages...
However, when trying to get the thing's shadow by using `aws_iot_shadow_get`, no message is received from the get/accepted topic, but using aws console from a PC I saw that this message was correctly published.

Looking `aws_iot_shadow_yield` in more detail, I appreciated that the system waits for 8 seconds (the limit I set for waiting the response) for any message, but this message is never received.

Has anyone of you experienced a similar trouble? Is it necessary to make any intermediate action between `aws_iot_shadow_get` and the first call to `aws_iot_shadow_yield` ?

Thank you very much for your attention and if you need more information, please, ask for it.

Regards,
Román

**Comment by hedeshianaws** [comment]
Thank you for using AWS IoT. You can look at one of the shadow examples (https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/samples/linux/shadow_sample_console_echo/shadow_console_echo.c) to get a better understanding of how to use yield. The general idea is that you register for the shadow call-back, initiate the get, then loop repeatedly calling yield. Your callback will be invoked once the message is received.

**Comment by romancardenas** [comment]
Thank you for replying me,
I have checked the example given, and I am not shure if I got the full working.

In my case, the Thing Shadow will only have one parameter: "id". The JSON file would be like:
`{
  "desired": {
    "id": 0
  }
}`
When first connected to aws, the device will apply for the shadow using `aws_iot_shadow_get`. From aws console I checked that:
1- The device subscribes succesfully to `get/accepted` and `get/rejected`
2- The device waits for 2 seconds
3- The devices publishes in `'get` topic a request
4- aws publishes on `get/accepted` the shadow

However, the device calls `aws_iot_shadow_yield` for 8 seconds, but no message is received.

I don't know if the error is because something is missing. In the sample, the device uses `aws_iot_delta_subscribe`, but I don't thick this step is necessary in my case.

**Comment by chaurah** [comment]
Hi @romancardenas,
     Apologies for the long delay on this. Were you able to figure out the issue? If not, could you confirm if you're not getting any messages at all when you call shadow_yield or just the get/accepted message is not received?

Rahul

**Comment by romancardenas** [comment]
Hi, Rahul,
Unfortunately, I could not fix it.
I receive the get/accepted message. What I do not receive is any message while calling shadow_yield.

**Comment by romancardenas** [comment]
Finally I could fix it. It was a problem with the network wrapper when trying to read large messages from the socket.
Thank you very much
