### ISSUE TITLE
Supporting "Authorizing Direct Calls to AWS Services" in IOT SDK

### ISSUE THREAD

**Issue by jonsmirl** [aws/aws-iot-device-sdk-embedded-C#123]
Is this going to be supported in the SDK anytime soon? I'm getting ready to write my own code to call it. I'd rather have the use of curl and json parsing coordinated with the SDK.

https://docs.aws.amazon.com/iot/latest/developerguide/authorizing-direct-aws.html

**Comment by chaurah** [comment]
Hi @jonsmirl,
We do not have plans to add this at the moment. I will update both this and the C++ SDK issues you have opened when we have a better idea of when support will be added. Please let us know if you have any further questions.

Rahul
