### ISSUE TITLE
mbedtls_ssl_write error not passed to aws_iot_sdk

### ISSUE THREAD

**Issue by raulgotor** [aws/aws-iot-device-sdk-embedded-C#1247]
Hi, 

I'm working with the aws-iot-device-sdk in an ESP32. I have the system working for several hours with constant publishing every 5 seconds. At some random point, I start to get the error:

`E (41075) aws_iot: failed! mbedtls_ssl_write returned -0x50`,

In file network_mbedtls_wrapper.c, I found a comment that says:

`/* All other negative return values (besides MBEDTLS_ERR_SSL_WANT_READ && MBEDTLS_ERR_SSL_WANT_WRITE) indicate connection needs to be reset. Will be caught in ping request so ignored here */`

Problem is that publishing is failing, and this error doesn't seem to call the `disconnectHandler` member of the `IoT_Client_Init_Params` struct. 
I'm trying to catch the error at application level to manually restart the connection, but I've found out that at some point in the nesting functions, the error that `mbedtls_ssl_write` returns is lost, specifically at `aws_iot_mqtt_internal_send_packet`:

```c
IoT_Error_t aws_iot_mqtt_internal_send_packet(AWS_IoT_Client *pClient, size_t length, Timer *pTimer) {
 
        //..Ommited function fragment...//
 
	while(sent < length && !has_timer_expired(pTimer)) {
		rc = pClient->networkStack.write(&(pClient->networkStack),    // pClient→networkStack.write points to "mbedtls_ssl_write"
						 &pClient->clientData.writeBuf[sent],      // error last time seen is here
						 (length - sent),
						 pTimer,
						 &sentLen);
		if(SUCCESS != rc) {
			/* there was an error writing the data */
			break;
		}
		sent += sentLen;
	}
      
 
#ifdef _ENABLE_THREAD_SUPPORT_
 
        //I have _ENABLE_THREAD_SUPPORT_, so rc error value from "pClient->networkStack.write(&(pClient→networkStack)" is 
        //replaced by the result of "aws_iot_mqtt_client_unlock_mutex" which is 0
	rc = aws_iot_mqtt_client_unlock_mutex(pClient, &(pClient->clientData.tls_write_mutex));
	if(SUCCESS != rc) {
		FUNC_EXIT_RC(rc);
	}
#endif
 
	if(sent == length) {              //lengths here are different thought
		/* record the fact that we have successfully sent the packet */
		//countdown_sec(&c->pingTimer, c->clientData.keepAliveInterval);
		FUNC_EXIT_RC(SUCCESS);
 
	}
        
        //but here the successful result of "aws_iot_mqtt_client_unlock_mutex" is returned, thus I'm not able to
        //catch the error from "pClient->networkStack.write(&(pClient→networkStack)" 
 
	FUNC_EXIT_RC(rc); 
}

```

Is this the expected behavior? If so, how can I pipe those mbedtls_ssl_write to my application, so I'm able to reset the connection?

Thank you

**Comment by sarenameas** [comment]
Hello @raulgotor,

Yes this is expected. The error does get swallowed in iot_tls_write() to NETWORK_SSL_WRITE_ERROR. The IoT_Client_Init_Params.disconnectHandler is called only when aws_iot_mqtt_yield() is invoked for issues with the PINGREQ and network errors reading. It is not invoked when for network error during aws_iot_mqtt_publish(). 

When aws_iot_mqtt_publish() returns NETWORK_SSL_WRITE_ERROR you should be disconnecting and reconnecting in your code manually. Any error from mbedtls_ssl_write() makes aws_iot_mqtt_publish() return NETWORK_SSL_WRITE_ERROR to the application. Is that not happening?

**Comment by raulgotor** [comment]
Hello @sarenameas, thanks for your reply. `iot_tls_write()` is indeed returning `NETWORK_SSL_WRITE_ERROR`, but then, the error is catch at `aws_iot_mqtt_internal_send_packet`  by `rc = pClient→networkStack.write(...)`. As you can see few lines later, `rc = aws_iot_mqtt_client_unlock_mutex(...))` uses the same `IoT_Error_t` variable to hold it's return, but in this case, this last function returns no error, so previous error from `iot_tls_write()` is discarded, and 'aws_iot_mqtt_internal_send_packet' returns no error to the application code.

Thus, I cannot find a way to catch this `NETWORK_SSL_WRITE_ERROR` from the application code, without modifying the 'aws_iot_mqtt_internal_send_packet' function.

Shouldn't there be a function return in line 341 of file aws_iot_mqtt_client_common_internal.c?:

```c
		if(SUCCESS != rc) {
			/* there was an error writing the data */
			FUNC_EXIT_RC(rc);
		}
```

Also, it's being hard to me to debug on this because these errors are randomly happening after hours of connections. Do you guys have a common practice to force these errors to happen?

Thanks

**Comment by sarenameas** [comment]
Ah I see thank you for pointing this out. I was going through the workflow without \_ENABLE_THREAD_SUPPORT_ defined. That is definitely a bug. Unfortunately we cannot return right away on line 341, that you showed, because that mutex needs to get unlocked. 

For your last question mbedtls internal errors are hard to force to happen. I would suggest turning on MBEDTLS_DEBUG_C and leave the logging on and analyze those later. Also since the probability of failure unlocking a mutex is extremely low you could also, just as a temporary interim for debugging purposes, not check the return value of aws_iot_mqtt_client_unlock_mutex() in line 347:

```c
#ifdef _ENABLE_THREAD_SUPPORT_
	(void)ws_iot_mqtt_client_unlock_mutex(pClient, &(pClient->clientData.tls_write_mutex));
	//if(SUCCESS != rc) {
	//	FUNC_EXIT_RC(rc);
	//}
#endif
```

So it appears that every few hours aws_iot_mqtt_publish() is incorrectly returning success, when it was actually not successful? 

While this is very annoying, if the network error is not transient, then you will catch it again the next time you call aws_iot_mqtt_yield(). 

We are looking into the criticality of a fix for this right now and I will get back to you in a bit.

**Comment by sarenameas** [comment]
Hello @raulgotor ,

I pushed a fix to the v3 MQTT library for the issue you have described. Please check it out. It is in tag v3.1.1

https://github.com/aws/aws-iot-device-sdk-embedded-C/commit/9566e0da4ac38df04c1837963aa6700f6ef7b5e4

Please feel free to reopen or open a new issue if you have other related concerns.

**Comment by raulgotor** [comment]
Great! Many thanks for the quick fix!
