### ISSUE TITLE
AWS Jobs support

### ISSUE THREAD

**Issue by jamesjara** [aws/aws-iot-device-sdk-embedded-C#125]
hello guys, do you have already an interface to support the jobs mqtt topics? or maybe we need to implement it by ourself

**Comment by vareddy** [comment]
Hi @jamesjara ,
Thank you for your interest in the AWS IoT SDK. There is currently no interface for jobs support in the embedded C SDK and we do not have a timeline for when it will be released. 
Please let us know if you have any more questions. 
Thanks!
Varun
