### ISSUE TITLE
Only do json delta callback if json value has changed

### ISSUE THREAD

**Issue by chrismrutherford** [aws/aws-iot-device-sdk-embedded-C#128]
It would be a nice feature to only call the JSON calback when processing a delta if the value has actually changed.  I have a problem where many partially duplicated delta messages are received, I would like to ignore the parts of the messages that have been processed (are the same).  I have modified the SDK locally to only call the callback if the value has actually changed.  Thought it would be a useful feature for others.  This could be optional if all deltas must be called.

**Comment by vareddy** [comment]
Hi @chrismrutherford,
Thanks a lot for your suggestion! I agree calling the delta callback only when the value has changed would be a good feature to have. I will discuss this with my team and add it into the backlog for future features. 
Please let us know if you have any more suggestions. They are valuable for improving the SDK.
Thanks!
Varun
