### ISSUE TITLE
V4: Mosquitto Docker Test

### ISSUE THREAD

**Issue by jckgore** [aws/aws-iot-device-sdk-embedded-C#1281]
I followed the instructions today to try testing the simple TLS example against a docker mosquitto instance.

Everything worked in terms of builds and getting docker setup (minus some docker changes for Windows) but when i try to connect I get a TLS error regarding the CA on both the mosquitto log and the demo output. Am I missing something obvious?

**Comment by sarenameas** [comment]
Could you paste the error you get in the mosquitto log and the demo output?

**Comment by jckgore** [comment]
Sure thing. Just to note, I went through the steps of building the CA and certs twice just to make sure I didn't do something wrong the first time. Same result both times. The log messages in Docker seem to show it loading the config and certs without issue -  I messed up the path to the config originally and it errored until I fixed it. Now it starts without complaints.

**MQTT Client Demo (Basic TLS)**
```shell
[INFO] [DEMO] [mqtt_demo_basic_tls.c:446] Establishing a TLS session to localhost:8883.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:586] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:620] Failed to establish a TLS connection.
[WARN] [DEMO] [mqtt_demo_basic_tls.c:458] Connection to the broker failed. Retrying connection with backoff and jitter.
[INFO] [DEMO] [mqtt_demo_basic_tls.c:446] Establishing a TLS session to localhost:8883.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:586] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:620] Failed to establish a TLS connection.
[WARN] [DEMO] [mqtt_demo_basic_tls.c:458] Connection to the broker failed. Retrying connection with backoff and jitter.
[INFO] [DEMO] [mqtt_demo_basic_tls.c:446] Establishing a TLS session to localhost:8883.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:586] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:620] Failed to establish a TLS connection.
[WARN] [DEMO] [mqtt_demo_basic_tls.c:458] Connection to the broker failed. Retrying connection with backoff and jitter.
[INFO] [DEMO] [mqtt_demo_basic_tls.c:446] Establishing a TLS session to localhost:8883.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:586] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:620] Failed to establish a TLS connection.
[WARN] [DEMO] [mqtt_demo_basic_tls.c:458] Connection to the broker failed. Retrying connection with backoff and jitter.
[INFO] [DEMO] [mqtt_demo_basic_tls.c:446] Establishing a TLS session to localhost:8883.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:586] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:620] Failed to establish a TLS connection.
[WARN] [DEMO] [mqtt_demo_basic_tls.c:458] Connection to the broker failed. Retrying connection with backoff and jitter.
[ERROR] [DEMO] [mqtt_demo_basic_tls.c:464] Connection to the broker failed, all attempts exhausted.
[ERROR] [DEMO] [mqtt_demo_basic_tls.c:1343] Failed to connect to MQTT broker localhost.
[INFO] [DEMO] [mqtt_demo_basic_tls.c:1362] Short delay before starting the next iteration ....
```

**Mosquitto Server (1.6.12)**
```shell
1600337121: New connection from 172.17.0.1 on port 8883.
1600337121: OpenSSL Error[0]: error:14037418:SSL routines:ACCEPT_SR_KEY_EXCH:tlsv1 alert unknown ca
1600337121: OpenSSL Error[1]: error:140370E5:SSL routines:ACCEPT_SR_KEY_EXCH:ssl handshake failure
1600337121: Socket error on client <unknown>, disconnecting.
...
```

**Comment by jckgore** [comment]
More testing. I tried the basic TLS demo again, but compiled it to connect to the [https://test.mosquitto.org/](url) server using their CA. Running against their test server worked fine.

I also found this thread that seems to indicate there are some issues/intricacies with generating certs for mosquitto using opensll: https://github.com/eclipse/mosquitto/issues/689

**Comment by jckgore** [comment]
Problem Solved! I was using the exact same form entries for the generation of the CA and the server cert. This apparently causes issues in openssl.

Recommendation: Add a note to make sure that you instantiate the certs with different details. Also maybe give instructions for using test.mosquitto.org for testing.

**Comment by sarenameas** [comment]
Hi,

I am glad you figured it out. Thank you for the recommendation.

Just a note for other people who will come across this isse ROOT_CA_CERT_PATH should be the server.crt:

```
 #define ROOT_CA_CERT_PATH         "/mnt/c/Projects/Learning/aws-iot-device-sdk-embedded-C/server.crt"
```

Thanks.
