### ISSUE TITLE
MQTT_TX_BUFFER_TOO_SHORT_ERROR - What is max publish size?

### ISSUE THREAD

**Issue by pablosproject** [aws/aws-iot-device-sdk-embedded-C#1287]
Hi there, I have implemented a small daemon using your SDK to send device information to AWS IoT. 
I am actually reading JSON files from disk created by other processes and sending it over MQTT.

For some files, I am getting `MQTT_TX_BUFFER_TOO_SHORT_ERROR`, which means that the file is too big to be sent. I have searched the documentation, but there is no clear answer on what is the max allowed buffer size.

- What is the maximum accepted payload size?
- Is there a way to increase the TX buffer size? Ideally to reach the maximum AWS IoT supports (256KB I think)

**Comment by sarenameas** [comment]
Hello @pablosproject ,

It appears that 256KB is the max according to: https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot

The MQTT tx buffer is user defined in [aws_iot_config.h](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v3.1.0/samples/linux/subscribe_publish_sample/aws_iot_config.h#L36). You can increase it that file. You can make this as large as you need.

Thanks,
Sarena

**Comment by pablosproject** [comment]
Ok, thanks. I tried that but seems not working, probably is my configuration.

**Comment by sarenameas** [comment]
Hello @pablosproject,

Did you mean to close this ticket? Please feel free to open a new one or reopen this if you have any more questions.

**Comment by pablosproject** [comment]
Hi @sarenameas. Yes, I did close this as it's pretty clear how to configure. It's still not working for me, but it's a problem of the integrated micro I am using. Thanks.
