### ISSUE TITLE
how create things with this SDK to the remote IoT

### ISSUE THREAD

**Issue by wsilverky** [aws/aws-iot-device-sdk-embedded-C#129]
After I created things and certificates in AWS IoT ,I was able to use the SDK.
I have thousands of devices, and I need one device to one thing.
 what should I do,I find some code like 'create things' in Python SDK which this SDK don't have.

**Comment by vareddy** [comment]
Hi @wsilverky ,
Thank you for your interest in AWS IoT!
What you are referring to is the [AWS SDK for Python](https://boto3.readthedocs.io/en/latest/reference/services/iot.html#IoT.Client.create_thing) and not the [AWS IoT SDK](https://github.com/aws/aws-iot-device-sdk-python). The AWS SDK allows you to create and manage devices, whereas the AWS IoT SDK allows these devices to interact with AWS IoT over the MQTT protocol. 
For bulk creation and management of devices, you could use the AWS Python SDK to create them and each device could run any of the AWS IoT SDKs (C++, Python, node.js etc) to interact with AWS IoT. 
You could also use the [AWS IoT Device Management](https://aws.amazon.com/iot-device-management/features/) to onboard devices in bulk.
Please let us know if you have any more questions.
Thanks!
Varun

**Comment by wsilverky** [comment]
@vareddy hi,I studied the AWS SDK for Python and AWS SDK for CPP, em,My requirement is that the device can create things remotely, get certificates, and be able to implement iot connections.
your SDK is for PC, or create in the IoT cloud.
My device wants to connect to the thing in the cloud automatic，How can I do this? what steps should I do to batch flash ?
I can't flash an independent certificate on every device.
