### ISSUE TITLE
AWS IOT DEVICE SDK EMBEDDED C - FLEET PROVISIONING

### ISSUE THREAD

**Issue by rupans** [aws/aws-iot-device-sdk-embedded-C#1298]
I am trying to access the fleet provisioning code from aws-iot-device-sdk-embedded-C.git. I have checked out the code from the following github repository:

https://github.com/aws/aws-iot-device-sdk-embedded-C.git

I have then switched to the V4_deprecated branch but the files and changes associated with fleet provisioning is not present within these files. I was wondering if someone could tell me how I could access the fleet provisioning changes for embedded C SDK to develop my IoT device please?

**Comment by rupans** [comment]
I think I have now fixed my problem

**Comment by sarenameas** [comment]
Hello @rupans ,

On the v4_beta_deprecated branch it appears that the fleet provisioning demos, source, and docs are still availble:

- [demos\src\Provisioning](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta_deprecated/demos/src/Provisioning)
- [libraries\aws\provisioning](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta_deprecated/libraries/aws/provisioning)
- [doc\lib\provisioning.txt](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta_deprecated/doc/lib/provisioning.txt)

It's good to hear you think you fixed your problem. Do you any further questions? 

Thanks,
Sarena

**Comment by rupans** [comment]
Hi,

Thank you very much I think I have spotted my mistake.

Kind Regards,

Rupan
