### ISSUE TITLE
Shadow connect fail

### ISSUE THREAD

**Issue by cliffgibson** [aws/aws-iot-device-sdk-embedded-C#13]
i just upgrade from sdk1.0.1 to 1.1.0 on my embedded linux device. when i run the shadow sample app, i always got error in aws_iot_shadow_connect(), error code=-3. same behavior for mbedtls and openssl. i put a retry loop there and sometimes it 'may' successfully connect after 10-20 trials, sometimes not. can you help pls? thanks

**Comment by bhadrip** [comment]
Hello @cliffgibson ,

Thanks for updating the SDK. Did you have this connectivity issue with 1.0.1 ?

In some devices, we have observed that increasing the timeout for receiving [CONNACK] (http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349769) from server has fixed this variability issue. 
This could be changed in [this](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/aws_iot_src/shadow/aws_iot_shadow.c#L82) place. Increase it to 5 seconds,
```
ConnectParams.mqttCommandTimeout_ms = 5000;
```

Let us know if this helps.

Bhadri

**Comment by chaurah** [comment]
Hi @cliffgibson,
        We have released a fix for the issue raised by dfszb above, in the v2.0.0 of the SDK. Please download and use the latest version of the SDK and let us know if you are still facing connection issues.

Rahul
