### ISSUE TITLE
SDK should allow JSMN_ARRAY and JSMN_OBJECT in delta callbacks

### ISSUE THREAD

**Issue by chrismrutherford** [aws/aws-iot-device-sdk-embedded-C#130]
I tweaked the SDK so that I could receive JSMN_ARRAY and  JSMN_OBJECT in  delta callbacks.  The rest of the library just treats the data as a string, meaning that the contents can be used opaquely in aws_iot_shadow_add_reported / aws_iot_shadow_add_desired, without causing any parse errors.

The advantage of this is that only the callback hander needs to know how to parse the object, so it doesn't have to be a generic library feature.  I found this really useful, as processing primitive number/string values is a bit limiting.  Is it something that you would consider adding?  I could send a patch so you can see what I mean.

**Comment by vareddy** [comment]
Hi @chrismrutherford,
Thanks a lot for your suggestion! I've added it to our backlog of improvements to the SDK. This would improve the flexibility in the parsing shadow jsons immensely. 
If possible, could you also provide a pull request with the changes you would like to see in the parsing? It would make it easier to include in future versions of the SDK.
Thanks!
Varun

**Comment by chrismrutherford** [comment]
I've created the pull request.  I has a couple of other changes, hopefully it will still be clear what I've added.  Also, I'm working on a STM32 platform and haven't tested the changes on Linux, other than making sure it builds.

**Comment by vareddy** [comment]
Hi @chrismrutherford,
We will merge and test the pull request and push to master when we have completed our testing.
Thanks a lot!
Varun

**Comment by chrismrutherford** [comment]
When setting up the jsonStruct_t, don't forget to set type to SHADOW_JSON_OBJECT, otherwise it tries to add quotes when doing update response.

**Comment by chrismrutherford** [comment]
This issue is important to me.  I'd prefer to see a resolution, either way, rather than just closing the ticket because it has been open for a few weeks.  Please reopen the ticket.

**Comment by dcgaws** [comment]
Hello @chrismrutherford, thank you for your patience! Please take a look at [version 4 of the Embedded C SDK](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta). In particular, [the new Shadow demo](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/demos/src/aws_iot_demo_shadow.c#L289) and library show how the app has been given full control over parsing delta documents.
