### ISSUE TITLE
Need help on delta change

### ISSUE THREAD

**Issue by amarnath87** [aws/aws-iot-device-sdk-embedded-C#132]
Hi, 

I am testing sample 'shadow_sample_console_echo' , while shadow is being updated DeltaCallback is not called. How to capture the delta changes in DeltaCallback. I have tried updating the shadow from console as well as from 'shadow_sample' but could not hit the callback.  Please help me to get into callback.

Thanks,
Amarnath

**Comment by liuszeng** [comment]
Hi @amarnath87 ,

Thank you very much for using AWS IoT Embedded C SDK.

You probably want to check the following things and see if they match for the shadow echo sample you are running and the AWS IoT console you are using:
1. Region
You can find the region used in the sample by checking your endpoint configuration. You can find the region used in the console by checking on the top right of the page. To make the shadow echo sample work, those two regions need to be the same.
2. Shadow name
You want to make sure the the shadow name configured in the sample and the shadow name you are trying to update in the console matches with each other.
3. Shadow JSON change
Note that delta message will only be triggered when there is a difference between the desired and reported section of the shadow JSON document. What the sample is going to do is basically watch for delta messages and update the reported state to match with the desired state in the delta callback. When trying to update the shadow JSON document in console, please make sure you are always updating the desired state.

Hope the above helps.

Thanks,
Liusu

**Comment by amarnath87** [comment]
Hi @liuszeng,

Thank you for your kind response. 

I had make sure that the sample followed above said all the three points but my issue remains. Please let me know any other aspects should be taken care.


Thanks,
Amarnath

**Comment by liuszeng** [comment]
Hi @amarnath87 ,

I was able to run the shadow echo sample and have it interact with the changes I made in AWS IoT Console. You can find my configuration details as follows. Let's see if there is anything different on your side.

- Sample configuration header file
```
#ifndef SRC_SHADOW_IOT_SHADOW_CONFIG_H_
#define SRC_SHADOW_IOT_SHADOW_CONFIG_H_

// Get from console
// =================================================
#define AWS_IOT_MQTT_HOST              "<RANDOM_STRING>.iot.us-east-1.amazonaws.com" ///< Customer specific MQTT HOST. The same will be used for Thing Shadow
#define AWS_IOT_MQTT_PORT              8883 ///< default port for MQTT/S
#define AWS_IOT_MQTT_CLIENT_ID         "c-sdk-client-id" ///< MQTT client ID should be unique for every device
#define AWS_IOT_MY_THING_NAME 		   "AWS-IoT-C-SDK" ///< Thing Name of the Shadow this device is associated with
#define AWS_IOT_ROOT_CA_FILENAME       "aws-iot-rootCA.crt" ///< Root CA file name
#define AWS_IOT_CERTIFICATE_FILENAME   "8d23e57394-certificate.pem.crt" ///< device signed certificate file name
#define AWS_IOT_PRIVATE_KEY_FILENAME   "8d23e57394-private.pem.key" ///< Device private key filename
// =================================================
...
```
- Console screen shots
Editing the shadow JSON doc:
![image](https://user-images.githubusercontent.com/14796906/35352417-aff05fea-00f8-11e8-8a8f-e30004292127.png)
Saving to send out the update request:
![image](https://user-images.githubusercontent.com/14796906/35353629-97b721a8-00fc-11e8-9479-4cfa5ef858a8.png)

Things I did:
1. Start `shadow_console_echo` sample and wait for it to finish shadow initialization.
2. Update shadow JSON doc in AWS IoT console.
3. `shadow_console_echo` sample spits out delta message arrival and updating reported state.
4. Shadow JSON doc in AWS IoT console shows "desired" and "reported" in sync.

Thanks,
Liusu

**Comment by amarnath87** [comment]
Hi @liuszeng,

Thank you for your efforts for helping on this issue. I have followed your instructions and now I am able to get delta changes.

Thanks,
Amarnath
