### ISSUE TITLE
build error on Ubuntu 16.04

### ISSUE THREAD

**Issue by puffie** [aws/aws-iot-device-sdk-embedded-C#1323]
I tried to follow the instruction given in the README on ubuntu 16.04, and getting following error. Any thought please?

Scanning dependencies of target retry_utils_posix
[  1%] Building C object platform/posix/CMakeFiles/retry_utils_posix.dir/retry_utils_posix.c.o
[  3%] Linking C shared library ../../lib/libretry_utils_posix.so
[  3%] Built target retry_utils_posix
Scanning dependencies of target clock_posix
[  5%] Building C object platform/posix/CMakeFiles/clock_posix.dir/clock_posix.c.o
[  6%] Linking C shared library ../../lib/libclock_posix.so
[  6%] Built target clock_posix
Scanning dependencies of target sockets_posix
[  8%] Building C object platform/posix/transport/CMakeFiles/sockets_posix.dir/src/sockets_posix.c.o
[ 10%] Linking C shared library ../../../lib/libsockets_posix.so
[ 10%] Built target sockets_posix
Scanning dependencies of target plaintext_posix
[ 12%] Building C object platform/posix/transport/CMakeFiles/plaintext_posix.dir/src/plaintext_posix.c.o
[ 13%] Linking C shared library ../../../lib/libplaintext_posix.so
[ 13%] Built target plaintext_posix
Scanning dependencies of target openssl_posix
[ 15%] Building C object platform/posix/transport/CMakeFiles/openssl_posix.dir/src/openssl_posix.c.o
/opt/sun/aws-iot-device-sdk-embedded-C/platform/posix/transport/src/openssl_posix.c: In function ‘Openssl_Connect’:
/opt/sun/aws-iot-device-sdk-embedded-C/platform/posix/transport/src/openssl_posix.c:515:36: warning: passing argument 1 of ‘SSL_CTX_new’ makes pointer from integer without a cast [-Wint-conversion]
         pSslContext = SSL_CTX_new( TLS_client_method() );
                                    ^
In file included from /opt/sun/aws-iot-device-sdk-embedded-C/platform/posix/transport/include/openssl_posix.h:53:0,
                 from /opt/sun/aws-iot-device-sdk-embedded-C/platform/posix/transport/src/openssl_posix.c:33:
/usr/include/openssl/ssl.h:2131:10: note: expected ‘const SSL_METHOD * {aka const struct ssl_method_st *}’ but argument is of type ‘int’
 SSL_CTX *SSL_CTX_new(const SSL_METHOD *meth);
          ^
[ 17%] Linking C shared library ../../../lib/libopenssl_posix.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libssl.a(ssl_lib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libssl.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
platform/posix/transport/CMakeFiles/openssl_posix.dir/build.make:97: recipe for target 'lib/libopenssl_posix.so' failed
make[2]: *** [lib/libopenssl_posix.so] Error 1
CMakeFiles/Makefile2:313: recipe for target 'platform/posix/transport/CMakeFiles/openssl_posix.dir/all' failed
make[1]: *** [platform/posix/transport/CMakeFiles/openssl_posix.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dachalco** [comment]
Hi @puffie 

How did you install `libssl` and which version are you using? We require at least `v1.1.0`.

**Comment by puffie** [comment]
Hi @dachalco 
I'm using the vanilla openssl installed on Ubuntu 16.04. Guess I will have to update the openssl on my machine.
Thanks for your response.

**Comment by yanjos-dev** [comment]
@puffie I'm closing this issue for now. Please reopen this issue if you have any questions or would like any help.
