### ISSUE TITLE
jsonStruct_t should have pApplicationHandlerData member

### ISSUE THREAD

**Issue by chrismrutherford** [aws/aws-iot-device-sdk-embedded-C#134]
Hi,
In my local copy I added a void *pApplicationHandlerData to jsonStruct_t like:
```c++
struct jsonStruct {
     const char *pKey; ///< JSON key
     void *pData; ///< pointer to the data (JSON value)
     JsonPrimitiveType type; ///< type of JSON
     jsonStructCallback_t cb; ///< callback to be executed on receiving the Key value pair
     void *pApplicationHandlerData; // Pointer to extra data, optional, useful for C++ callback handler
 };
```

 This allows the callback to access an application context.  e.g. Using pApplicationHandlerData a very thin C++ application could pass in a 'this' pointer like:

```c++
    for (std::list<ShadowDelta*>::iterator it = mShadowDeltaList.begin(); it != mShadowDeltaList.end(); it++)
    {
        ShadowDelta *shadowDelta = *it;
        shadowDelta->getJsonStruct()->cb = gJsonItemCallback;
        shadowDelta->getJsonStruct()->pApplicationHandlerData = shadowDelta;
        TSK_PRINTF("register key %s\n", shadowDelta->getJsonStruct()->pKey);
        rc = aws_iot_shadow_register_delta(&mClient, shadowDelta->getJsonStruct());
    }
```
and then in the callback access the object like:
```c++
    static void gJsonItemCallback(const char *pJsonString, uint32_t JsonStringDataLen, jsonStruct_t *pContext)
    {
        if(pContext != NULL && pContext->pApplicationHandlerData != NULL)
        {
            ShadowDelta *shadowDelta = (ShadowDelta *)pContext->pApplicationHandlerData;
            shadowDelta->jsonDeltaCallback(pJsonString,JsonStringDataLen,pContext);
        }
    }
```
I've noticed that aws_iot_mqtt_subscribe already has pApplicationHandlerData, which can be used in the same way, so it seems reasonable that shadow callbacks should have a similar mechanism. 

FYI I'm aware of the C++ implementation, however I'd rather use the C version with my own thin C++ wrapper, as this is more appropriate for tiny embedded devices.

**Comment by hedeshianaws** [comment]
Thank you for the feedback. I will pass it along to the team for consideration.

**Comment by chrismrutherford** [comment]
I hope it gets in, I use this extensively in my application.   Thanks.

**Comment by chrismrutherford** [comment]
This issue is important to me.  I'd prefer to see a resolution, either way, rather than just closing the ticket because it has been open for a few weeks.  Please reopen the ticket.

**Comment by chrismrutherford** [comment]
This is literally a one line change, where a void * member is added to jsonStruct.  If it helps I can create a merge request for this.

**Comment by gordonwang0** [comment]
Sure, any PR is appreciated 😄

**Comment by David-Haim** [comment]
Hi, what is the status of it?

In my company we're using the C sdk in our C++ application since we've preferred to use the more robust C sdk than the buggish C++ sdk.
 
we're wrapping the C sdk in extremely thin C++ wrapper just like the OP suggested and currently we cannot send any context to the disconnection callback in the device shadow case (and hence, no way of informing your app instance the client is disconnected).

we need this feature :)

**Comment by dcgaws** [comment]
Hello @chrismrutherford, please check out the delta callback signature in version 4 of our Embedded C SDK. An example usage can be found [here in our Shadow demo](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/demos/src/aws_iot_demo_shadow.c#L289). There is now an optional context pointer that is opaque to the library.
