### ISSUE TITLE
Missing PortingGuide.md

### ISSUE THREAD

**Issue by gannaramu** [aws/aws-iot-device-sdk-embedded-C#1355]
Embedded C SDK porting guide link at the this link [https://aws.amazon.com/iot-core/resources/#AWS_IoT_device_SDKs](https://aws.amazon.com/iot-core/resources/#AWS_IoT_device_SDKs) is broken. I remember fixing and issue in it at #1328

**Comment by leegeth** [comment]
@gannaramu 

Thanks for bringing this issue to our attention. Yes you have added the porting guide to the CSDK V3. It can be found here in this link https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v3.1.2/PortingGuide.md. However the AWS IoT doc link seems to be broken. We will address this issue.

**Comment by yourslab** [comment]
It looks like the link is no longer broken, and we have a [porting guide here](https://github.com/aws/aws-iot-device-sdk-embedded-C#porting-guide-for-20200900-and-newer-releases), so I will close this issue.
