### ISSUE TITLE
Timeout while performing shadow get.

### ISSUE THREAD

**Issue by amarnath87** [aws/aws-iot-device-sdk-embedded-C#137]
Hi,

I have integrated this iot sdk to my multi-threaded application. Following the samples, created a separate thread to do shadow get. Callback being received with time out always. where as in sample I am able to get the callback with complete shadow.  I tried giving more time out in get and yield calls but time out happens always. I did not find any difference from sample to my code. Please let me know how can I address this time out issue.

Thanks & Regards,
Amarnath

**Comment by huguesBouvier** [comment]
Hello,

I would suggest the following troubleshooting steps as there are multiple reasons why callbacks might not be invoked:
-	It could be because a previous function is not called or returns an error. Before “shadow get” is called, the following functions need to have been called and the status they return need to be successful.
    	aws_iot_shadow_init
    	aws_iot_shadow_connect
    	aws_iot_shadow_get
-	 Are you updating the same thing with the example and with your OS? It could also be a credential issue.
-	If you go in your AWS console, select AWS-IOT and on the left columns select “test”  ( https://docs.aws.amazon.com/iot/latest/developerguide/view-mqtt-messages.html ) Subscribe to “#” and launch your code, It will help you a lot in troubleshooting! You can see the messages from your device and the response from the cloud:
     Do you see your device message. If no, it could be a connect problem
     Do you see the broker response? If it is connection refused it could be credentials problem. If the message is correct, the problem would be more in setting up the callback.
Best,

Hugues

**Comment by amarnath87** [comment]
@huguesBouvier,

Thank you for response. 

I have no issue with connection but the problem is time out. Received  SHADOW_ACK_TIMEOUT in callback [https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/tests/unit/src/aws_iot_tests_unit_shadow_null_fields_helper.c](url).

Thanks,
Amarnath

**Comment by huguesBouvier** [comment]
Hello,

From https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html 
Your thing needs to have less than 50 attributes and the JSON document needs to be less than 8Kb so it could  definitely be an issue!

Look at your file  \samples\linux\shadow_sample\aws_iot_config.h 
And check the size
#define AWS_IOT_MQTT_RX_BUF_LEN 512 ///< Any message that comes into the device should be less than this buffer size. If a received message is bigger than this buffer size the message will be dropped.
It defines the max size of a shadow:
#define SHADOW_MAX_SIZE_OF_RX_BUFFER AWS_IOT_MQTT_RX_BUF_LEN+1 ///< Maximum size of the SHADOW buffer to store the received Shadow message
If you kept the define unchanged it will not work, as the parameter is set to 512 by default

1.	There should be a warning sent if that buffer limit is exceeded but it needs to be enabled. You can do so by defining #ifdef ENABLE_IOT_WARN (and other error messages)  in aws_iot_log.h.  You can put the defines in your project or at the top of the file.
2.	Does the service works if you try with a smaller shadow (so we can narrow down the issue to shadow size)?
3.	When “spying” messages from the cloud what does the host reply to your shadow GET command?
Thanks,

Hugues

**Comment by amarnath87** [comment]
Hi,

I have been trying with modified size only as below
#define AWS_IOT_MQTT_RX_BUF_LEN 8*1024

But I could not get the shadow contents.

If I keep shadow size less than  512 characters then I am able to get shadow document in my app. One thing I am not understanding is how come sample code is able to  get 8KB data and why my application is not able to. FYI, all sizes and connection requisites are same in sample and my application. 


Regards,
Amarnath

**Comment by huguesBouvier** [comment]
Hello,

At this stage of troubleshooting I will need more data, it is hard to say without comparing your code with the C SDK samples and checking what are the differences. 
Could you please post a log with all the debug messages enabled? From post above, you can do so by defining #ifdef ENABLE_IOT_WARN (and other error messages) in aws_iot_log.h. You can put the defines in your project or at the top of the file.
The logs contains a lot of information, maybe there is one in there that could help me troubleshoot where the problem come from.

Thank you,

Regards,
Hugues

**Comment by amarnath87** [comment]
Hi Hugues,

Thank you for your response and sorry for late reply.

As you said ENABLE_IOT_WARN  is enabled by default with sample code and same is used in my application also. Please find the code and debug logs from sample and from my app.

Logs:-
From Sample: [https://pastebin.com/9pzQaZEr](url)
From myapp: [https://pastebin.com/Sahw38up](url)

Sample Code:-
shadow_console_echo.c: [https://ideone.com/Lbw6js](url)
aws_iot_config.h : [https://ideone.com/vaHwtS](url)
Makefile: [https://ideone.com/oYIUE7](url)

myapp code:-
MqttInterface.c: [https://ideone.com/tDNTXa](url)
aws_iot_config.h : [https://ideone.com/VeKHMK](url)
Makefile : [https://ideone.com/4MGR1G](url)


Please let me know if anything required. 

Regards,
Amarnath

**Comment by huguesBouvier** [comment]
Hello,

I read through the code, and it seems very similar to the sample code. The logs are also pretty similar, however, when parsing through the logs, it seems to be missing some information:
For example, I am not able to see the messages:
1.	It should have passed through here
IOT_INFO("Shadow Init"); 
2.	The most important one, the return status from shadow get.
IOT_ERROR("An error occurred in the loop %d", rc);   

Could you also  give me a log of the MQTT messages from your IOT console, I would like to check any potential refused messages from the server.
You need togo in your AWS console, select AWS-IOT and on the left columns select “test” ( https://docs.aws.amazon.com/iot/latest/developerguide/view-mqtt-messages.html ) Subscribe to “#” and launch your code,.

Thank you

**Comment by amarnath87** [comment]
Hi @huguesBouvier,

I could not see any kind of logs except connect and certificate validation logs. According to configuration in Makefile all kind of logs are enabled. If enable ENABLE_IOT_TRACE too many logs are getting flushed. Please let me know what I am missing to get all types of logs. 

Please find the  MQTT messages from IOT console which I got from "test".
[https://codebeautify.org/online-json-editor/cbf952d0]()

Regards,
Amarnath

**Comment by huguesBouvier** [comment]
Hi @amarnath87 ,

You can enable messages by defining ENABLE_IOT_.... at the top of aws_iot_log.h this should give a lot more messages.
The log that you sent helps a lot, it shows that the shadow request is working, making its way to the broker and we can see its reply.

Just to double check “6F:01:77:C8:A0:AE” is your thing name? Is it the same name that you used for both the sample and your app?
Would it be possible for you to zip the whole app? It would be a lot easier if I can reproduce it.

**Comment by amarnath87** [comment]
Hi @huguesBouvier,

Please find my sample code attached as zip.
[https://www.transfernow.net/33frc7c15a88](url)
Password: Iot$%G^*etS@(a)m

Please let me know if anything required.

Regards,
Amarnath

**Comment by amarnath87** [comment]
Hi,

I am able to get the full shadow contents now. If I link static library built from example [https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/master/samples/linux/subscribe_publish_library_sample](url) to my app then not able to get shadow. But used Makefile from [https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/master/samples/linux/shadow_sample](url) and added my app source files to build steps. Now I am able to get the shadow contents. I have no idea what makes difference between these two steps.

Regards,
Amarnath
