### ISSUE TITLE
Support for larger payload transmission

### ISSUE THREAD

**Issue by snap40ben** [aws/aws-iot-device-sdk-embedded-C#1394]
I'm willing to transmit bigger payloads to reduce the time waiting for ACKs, but the SDK right now needs to allocate memory for the entire payload before being passed to the MQTT layer.

Is it planned to add a possibility to send a payload chunks by chunks, allowing to transmit bigger payloads without having to allocate memory for all of it at once?

**Comment by lundinc2** [comment]
Hi @snap40ben,

Assuming you are looking at the latest code. There are currently no plans for such a feature. The coreMQTT library will not have memory allocation inside of it, and the size of the buffers is delegated to the application. 

Thanks,

Carl

Thanks,

Carl

**Comment by snap40ben** [comment]
Hi @lundinc2,

Thanks for your answer. Yes, currently looking at the 202011 release.

So if I understand correctly, if I want to transmit a 10kB payload I have to allocate all of it in RAM to be given to coreMQTT for transmission, and can only free it after the PUBACK is received (using qos1)?

As opposed to allocating 1kB at a time, having it written on the tcp socket, allocating the next 1kB, up until 10kB, and waiting for a PUBACK for the complete packet?

**Comment by abhidixi11** [comment]
Hello @snap40ben ,

Thanks for follow-up. 
`So if I understand correctly, if I want to transmit a 10kB payload I have to allocate all of it in RAM to be given to coreMQTT for transmission, and can only free it after the PUBACK is received (using qos1)?`

Yes that's correct if you want to send 10KB payload in a single publish message, that's the only way right now. 

`As opposed to allocating 1kB at a time, having it written on the tcp socket, allocating the next 1kB, up until 10kB, and waiting for a PUBACK for the complete packet?`

You can send 10 publish messages. By using this approach, you need less RAM, but it will end up sending 10 publish messages and will receive 10 PUBACKs . 

The library does not handle chucked MQTT publishes. I'm assuming that you want 10 writes to socket, but for the same publish message. In that case, you still have to keep the 10KB data till the PUBACK is received correct ? 

Thanks.

**Comment by snap40ben** [comment]
Hello, 

Thank you both. My current method is sending 10 publish messages and receiving 10 PUBACKs, the time waiting for the PUBACK makes the transmission speed quite low for our application, thus me looking for alternatives (we're still using SDK 3.0.1 but looking at upgrading).

Thanks for your help, I will find something.
