### ISSUE TITLE
Make file Deletes everything

### ISSUE THREAD

**Issue by ashutoshvct** [aws/aws-iot-device-sdk-embedded-C#14]
In my Macos i downloaded the SDK and i clicked the make file and it started removing apps from my pc.
You should have a warning stating that do not open the make file.

**Comment by johnrotach** [comment]
Hello @ashutoshvct,

We are looking into this issue and trying to reproduce.  Can you provide more detail on what you did prior to observing this?  Did you clone from GitHub or download the Linux/Mac OS port tarball from S3?  In which directory was the makefile located when you double clicked on it?  Specifically which applications (and locations) were removed?

In the meantime we will continue to try and reproduce on our end.

John

**Comment by ashutoshvct** [comment]
Hi,
I had downloaded a tarball. My downloads folder was affected and application folder.
I had  created it in users/…/aws_iot/my_app

**Comment by johnrotach** [comment]
Thanks for getting back to us.  A couple more questions:

Specifically what makefile did you double-click?  When you do this in OS X, what application is invoked to run the makefile?

**Comment by ashutoshvct** [comment]
in samples i clicked the make file and it opened a terminal and started removing my apps.

**Comment by johnrotach** [comment]
Hello @ashutoshvct,

We have now verified what we believe to be the issue.  The file permissions on the makefile had the executable flag set.  This allowed you to execute the makefile directly and OS X interpreted it as a shell script.  If this flag was set appropriately OS X would not have allowed you to execute the file by double-clicking it.

It is important to call out the correct way to use a makefile is not to execute the makefile itself, but rather to run the `make` utility taking the Makefile as an input file.  This is done by simply running `make` from within the respective samples directory:

```
cd sample_apps/subscribe_publish_sample/
make
```

We are in the process of pushing out a release that removes the executable flag from all of the files in this repository.  This will prevent accidental execution of any of the files in the future.  We apologize for any inconvenience this has caused you and appreciate you bringing this to our attention.

John

**Comment by bhadrip** [comment]
[v1.1.1](https://github.com/aws/aws-iot-device-sdk-embedded-C/releases/tag/v1.1.1) fixes this issue.

**Comment by ashutoshvct** [comment]
Hi,
Thanks for the support!!!
