### ISSUE TITLE
SSL_connect failed to perform TLS handshake

### ISSUE THREAD

**Issue by nenadilic84** [aws/aws-iot-device-sdk-embedded-C#1400]
When using the default setting of the AWS API gateway, I was facing the issue with the `http_demo_basic_tls.c` example:
```
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:586] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:620] Failed to establish a TLS connection.
```
while the `curl` was working just fine. 

@yourslab, can you share more details?

**Comment by yourslab** [comment]
AWS API Gateway requires SNI to be enabled. The fix for this is to set 
```
opensslCredentials.sniHostName = SERVER_HOST;
```
That being said, the demo will be updated to enable this setting by default.

**Comment by yourslab** [comment]
Currently have a PR to enable SNI by default
https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1402

**Comment by dan4thewin** [comment]
Hi, @nenadilic84 .  Are your TLS handshakes succeeding now?

**Comment by yourslab** [comment]
PR to enable SNI has been merged.

I have been in touch with @nenadilic84 and seems like all the issues have been resolved, but please feel free to reach out if there are more.

**Comment by yourslab** [comment]
Closing this as there doesn't seem to be any further inquiries but please feel free to reach out again
