### ISSUE TITLE
Git clone is unclean

### ISSUE THREAD

**Issue by boraozgen** [aws/aws-iot-device-sdk-embedded-C#1407]
Hi all,

This seems pretty obvious to me, but maybe I am doing something wrong. I'm on Windows. Cloning the repo with submodules results in an unclean state, due to some symbolic links pointing to the ignored submodules. The symlinks are README.md Makefile.common files in the test directories of the sub-libraries.
```
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   libraries/aws/device-defender-for-aws-iot-embedded-sdk (modified content)
        modified:   libraries/aws/device-shadow-for-aws-iot-embedded-sdk (modified content)
        modified:   libraries/aws/jobs-for-aws-iot-embedded-sdk (modified content)
        modified:   libraries/standard/coreHTTP (modified content)
        modified:   libraries/standard/coreJSON (modified content)
        modified:   libraries/standard/coreMQTT (modified content)
        modified:   libraries/standard/corePKCS11 (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
```

Running git status in the affected submodule:
```
$ git status
HEAD detached at 0882657
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   test/cbmc/include/README.md
        modified:   test/cbmc/proofs/Makefile.common
        modified:   test/cbmc/proofs/README.md
        modified:   test/cbmc/sources/README.md
        modified:   test/cbmc/stubs/README.md

no changes added to commit (use "git add" and/or "git commit -a")
```

These files are invalid symlinks due to the ignored submodules and they are regarded as modified by git.

**Comment by aggarg** [comment]
Did you clone the submodules as well? I used the following command on windows:

```
git clone git@github.com:aws/aws-iot-device-sdk-embedded-C.git --recurse-submodules
```

And I do not see anything unclean:
```
λ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

Thanks.

**Comment by boraozgen** [comment]
Yes, I clone the submodules too. It is probably an issue of my system then. I'll check with the PCs of my colleagues and report the results here.

**Comment by boraozgen** [comment]
Apparently this issue occurs when the git configuration [`core.symlinks`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks) is set to `true` on Windows. I just set mine to false using `git config --global core.symlinks false` and now it clones cleanly.
