### ISSUE TITLE
 ninja: error: unknown target 'install'

### ISSUE THREAD

**Issue by vijayrakesh13** [aws/aws-iot-device-sdk-embedded-C#1424]
Hi,

I'm trying into integrate aws-iot-device-sdk-embedded-C into Yocto. do_install failed with an error "ninja: error: unknown target 'install'". Kindly please help me to fix the above issue.

`-- Configuring done
 -- Generating done
-- Build files have been written to: /home/poky/bsp/tmp/work/aarch64-poky-linux/aws/1.0-r0/build
[0/2] /home/poky/bsp/tmp/work/aarch64-poky-linux/aws/1.0-r0/recipe-sysroot-native/usr/bin/cmake -P /home/poky/bsp/tmp/work/aarch64-poky-linux/aws/1.0-r0/build/CMakeFiles/VerifyGlobs.cmake
ninja: error: unknown target 'install'
WARNING: /home/poky/bsp/tmp/work/aarch64-poky-linux/aws/1.0-r0/temp/run.do_install.15415:1 exit 1 from 'eval ${DESTDIR:+DESTDIR=${DESTDIR} }VERBOSE=1 cmake --build '/home/poky/bsp/tmp/work/aarch64-poky-linux/aws/1.0-r0/build' "$@" -- ${EXTRA_OECMAKE_BUILD}'
ERROR: Task (/home/poky/src/meta-application/recipes-bleapp/aws/aws_1.0.bb:do_install) failed with exit code '1'`

Thanks & Regards,
Vijay Rakesh.

**Comment by yourslab** [comment]
Hi Vijay,

The `install` target is not yet readily available, but we are working on it:
https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/309

Best regards,
Oscar

**Comment by vijayrakesh13** [comment]
Hi Oscar,

Is there any other way to add AWS IOT SDK libraries to Yocto Build?

Thanks & Regards,
Vijay

**Comment by yourslab** [comment]
You will need to include the sources and includes from the `source` directory of each library. From there, you can make an AWS IoT Recipe to integrate with your Yocto Build as [shown here](https://variwiki.com/index.php?title=Yocto_Hello_World#Sample_C_.22Hello.2C_world.21.22_program):

**Comment by rpcme** [comment]
this is related to this issue (the last couple responses anyway)

https://github.com/aws/meta-aws/issues/89

There will be a recipe created that targets the eSDK.  Otherwise, customers can create a recipe that fulfills the requirement in their custom app layer.

As a default, we will not be installing the demo apps to the rootfs since they require specific configuration, likely going to be done in local.conf for prototyping.  But in the end, no one is going to ship the demo programs.

Ideally, we have an install target that installs built shared libraries, an .so for each defined embedded c sdk library.

**Comment by vijayrakesh13** [comment]
@rpcme Thanks for the reply. I was trying to do the same to copy the shared libraries by writing a custom recipe with reference to the aws-iot-sdk-cpp.bb files. do_configure and do_compile were successful but do_install fails. I can see .so files created but couldn't able to do_install with ninja: error: unknown target 'install'. As I'm writing a recipe for the first time, I'm confused about making changes in .bb file or CMakeLists.txt would eliminate the mentioned error. Any suggestions would be really helpful.

**Comment by rpcme** [comment]
Yeah, as @yourslab says, the install target is not applicable to this SDK right now - there is nothing to put to rootfs.

But I'm curious - how are you trying to do this?  In contrast to the CPP project, the CMakefiles here are really only applicable to the demos so I don't think the Cmake process here is applicable to your project - it would only serve as a guide? I think you would just need to include this repo in your SRC checkout for your recipe and then organize your own project makefiles accordingly.

It will be easier when I get this into eSDK - but I apologize that's not ready yet.

**Comment by vijayrakesh13** [comment]
Thank you @rpcme. @yourslab Is the "openssl_posix.h" is from aws_iot_sdk? I had included all sources and includes, but the compilation fails with "openssl_posix.h" file not found. I searched in aws library sources, but I couldn't find any, or do have to install any package library?

**Comment by rpcme** [comment]
Hello @vijayrakesh13 

openssl_posix.h is here 

https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/platform/posix/transport/include

The way this is organized is the 'platform' can be replaced with other bsp - like for microcontroller.  The 'posix' platform is effectively linux.

**Comment by vijayrakesh13** [comment]
@rpcme  Thank You!

**Comment by yourslab** [comment]
Hi @vijayrakesh13 @rpcme

`aws-iot-device-sdk-embedded-C` now supports installation.

Documentation can be found in the [README](https://github.com/aws/aws-iot-device-sdk-embedded-C#installation).
