### ISSUE TITLE
Build requires mosquitto.h but not found?

### ISSUE THREAD

**Issue by rpcme** [aws/aws-iot-device-sdk-embedded-C#1427]
I did a clean build of tip of main and received:

```bash
[  5%] Building C object demos/jobs/jobs_demo_mosquitto/CMakeFiles/jobs_demo_mosquitto.dir/jobs_demo_mosquitto.c.o
/home/ANT.AMAZON.COM/elberger/src/aws-iot-device-sdk-embedded-C/demos/jobs/jobs_demo_mosquitto/jobs_demo_mosquitto.c:52:10: fatal error: mosquitto.h: No such file or directory
 #include <mosquitto.h>
          ^~~~~~~~~~~~~
compilation terminated.
demos/jobs/jobs_demo_mosquitto/CMakeFiles/jobs_demo_mosquitto.dir/build.make:62: recipe for target 'demos/jobs/jobs_demo_mosquitto/CMakeFiles/jobs_demo_mosquitto.dir/jobs_demo_mosquitto.c.o' failed
make[2]: *** [demos/jobs/jobs_demo_mosquitto/CMakeFiles/jobs_demo_mosquitto.dir/jobs_demo_mosquitto.c.o] Error 1
CMakeFiles/Makefile2:766: recipe for target 'demos/jobs/jobs_demo_mosquitto/CMakeFiles/jobs_demo_mosquitto.dir/all' failed
make[1]: *** [demos/jobs/jobs_demo_mosquitto/CMakeFiles/jobs_demo_mosquitto.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Is this expected for the build? I didn't set any environment variables.

**Comment by yourslab** [comment]
Hi @rpcme 

The Jobs demo in C SDK uses the Mosquitto Client Library to communicate with AWS IoT Core. That package is usually called `libmosquitto-dev` if installing through `apt` or `mosquitto-dev` if installing through `yum`.

Best regards,
Oscar

**Comment by rpcme** [comment]
@yourslab I didn't see this specifically called out in the documentation. Can you please add it?

**Comment by yourslab** [comment]
That's a good point. I do prefer having it as a 3rdparty submodule too.

**Comment by rpcme** [comment]
I was shown the documentation here:
https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/demos/jobs/jobs_demo_mosquitto

Perhaps need a table with per-demo requirement links?

Also, still, it would be nice to know the version or minimum version.

**Comment by yourslab** [comment]
Thanks for your feedback. I have done the following in [this PR](https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1436):
- Add table of required build dependencies for demos and tests in README
- If mosquitto library is not installed, build it from source for the AWS Jobs demo (using a newly added submodule in the demo directory)

Coming up next
- Create an install target

**Comment by yourslab** [comment]
The PR to resolve the issues mentioned above have been resolved.
