### ISSUE TITLE
AWS IoT Shadow Questions

### ISSUE THREAD

**Issue by rclai** [aws/aws-iot-device-sdk-embedded-C#143]
Not sure where to ask this, but I'm sure a dev from AWS would have the answer.

If the thing shadow consists of four fields in its state and the (physical) thing publishes a `shadow/update` payload that has a reported state that only has one of those 4 fields, will the thing shadow drop the three other fields from its state?

Another question is, if an application has published a `shadow/update` with a `desired` state, does the (physical) thing need to publish a `shadow/update` payload that sets the `desired` field to `null`(obv as well as its newly reported state) or will the shadow service automatically set it to `null` once the reported and desired fields match?

**Comment by gordonwang0** [comment]
Hi @rclai,

1. The Shadow document **will not** drop the other 3 fields in your example.  The new reported field will be updated, and the other 3 fields will not change.
2. The Shadow service **will not** set the `desired` field to `null` once the `desired` and `reported` states match.  You may publish an update that sets the relevant `desired` fields to `null` and remove them from the Shadow document.  However, this generally isn't necessary and most applications I've seen don't do this.

Let me know if you have any more questions.

**Comment by rclai** [comment]
@gordonwang0 thanks for that.

Another question, if a thing publishes a `shadow/update`, is it going to receive an `update/delta` back or will the shadow service know not to send an `update/delta` to the thing that originated the update?

**Comment by gordonwang0** [comment]
Hi @rclai,

All devices subscribed to `update/delta` will receive a delta message, including the device that published the update.

**Comment by rclai** [comment]
I see, so how do you ignore an `update/delta` that originated from itself?

**Comment by gordonwang0** [comment]
If you publish a unique `clientToken` with your shadow update, the messages received on `update/delta` will also contain that `clientToken`.  So you can identify which device published the update using the `clientToken`.

**Comment by chrismrutherford** [comment]
With the c sdk, when in a shadow delta callback, what is the best way to obtain the clientToken?  

AFIK the pJsonString in the callback contains a filtered string, and the JsonStringDataLen represents this.  i.e. the clientToken has been stripped off.  jsonStruct_t does not have a clientToken.

**Comment by gordonwang0** [comment]
Hi @chrismrutherford,

The `clientToken` should be accessible using `pJsonString`.  For example, if you set a debugger breakpoint in `shadow_sample.c:windowActuate_Callback`, you'll see something like this:

`pJsonString -> "false},\"metadata\":{\"windowOpen\":{\"timestamp\":1521066627}},\"clientToken\":\"some-client-token\"}"`
`JsonStringDataLen = 5`

`JsonStringDataLen` gives the length of the JSON value ("false").  If you read past that, you'll get the `clientToken`.

**Comment by chrismrutherford** [comment]
Hi @gordonwang0, Thanks for clarifying.  Would it be worthwhile to add it as an explicit parameter in the callback, making the token extraction a library feature?

**Comment by gordonwang0** [comment]
That is definitely something we can look in to.

For now, an easy way to extract the `clientToken` is to call `extractClientToken` (declared in `aws_iot_shadow_json.h`) on `shadowRxBuf` while in the delta callback.

**Comment by chrismrutherford** [comment]
I think there is a problem when calling extractClientToken from inside a delta.  The callback is passed a pointer that has an offset into shadowRxBuf, indexing the start of the JSON value, however because the start of the 'upper' JSON object is missing, jsmn_parse is returning -2.  if the pointer can be 'rewound' to the start of the shadowRxBuf then it would probably work.

```
extractClientToken (pJsonDocument=0x20033e8f <shadowRxBuf+63> "34},\"metadata\":{\"xKey\":{\"timestamp\":1521721536}},\"clientToken\":\"cmr_thing_name-30\"}",
    pExtractedClientToken=0x200163d0 <ucHeap+70044> "") at aws_iot_shadow_json.c:480
(gdb) print tokenCount
$3 = -2
(gdb) 
```

**Comment by chrismrutherford** [comment]
indeed, if I declare extern char shadowRxBuf[SHADOW_MAX_SIZE_OF_RX_BUFFER]; and pass this into extractClientToken when in the callback then everything is fine.

**Comment by gordonwang0** [comment]
Yes, you'll need to declare `shadowRxBuf` as an `extern` variable before calling `extractClientToken`.  Good to see you got it working.

**Comment by gordonwang0** [comment]
Hi @chrismrutherford,

We've decided not to include the client token in the delta callback, since it's possible to get it by calling `extractClientToken` on `shadowRxBuf`.  Closing issue.
