### ISSUE TITLE
Connection without x.509 certificates

### ISSUE THREAD

**Issue by asadislam94** [aws/aws-iot-device-sdk-embedded-C#144]
Hi,
Is it possible to use this library without using client side certificates for TLS?

I am not using the Amazon server and dont want to use certificates for each device. I am going to use CA root certificate for server authentication.

Is this possible with this SDK?
Thanks

**Comment by huguesBouvier** [comment]
Hello,

If you comment out in network_mbedtls_wrapper.c:
- line 146:_" ret = mbedtls_x509_crt_parse_file(&(tlsDataParams->clicert), pNetwork->tlsConnectParams.pDeviceCertLocation);
	if(ret != 0) {
		IOT_ERROR(" failed\n  !  mbedtls_x509_crt_parse returned -0x%x while parsing device cert\n\n", -ret);
		return NETWORK_X509_DEVICE_CRT_PARSE_ERROR;
	}"_
- line 152: _ret = mbedtls_pk_parse_keyfile(&(tlsDataParams->pkey), pNetwork->tlsConnectParams.pDevicePrivateKeyLocation, "");
	if(ret != 0) {
		IOT_ERROR(" failed\n  !  mbedtls_pk_parse_key returned -0x%x while parsing private key\n\n", -ret);
		IOT_DEBUG(" path : %s ", pNetwork->tlsConnectParams.pDevicePrivateKeyLocation);
		return NETWORK_PK_PRIVATE_KEY_PARSE_ERROR;
	}_
- line 197: _if((ret = mbedtls_ssl_conf_own_cert(&(tlsDataParams->conf), &(tlsDataParams->clicert), &(tlsDataParams->pkey))) !=
	   0) {
		IOT_ERROR(" failed\n  ! mbedtls_ssl_conf_own_cert returned %d\n\n", ret);
		return SSL_CONNECTION_ERROR;
	}_

It should work as is.
Best,

Hugues

**Comment by asadislam94** [comment]
Thanks. It worked.
