### ISSUE TITLE
wakeup device from sleep using mqtt

### ISSUE THREAD

**Issue by Abishek05** [aws/aws-iot-device-sdk-embedded-C#146]
Is there a way to wakeup device(esp32) from deep sleep by issuing a command to a topic subscribed by the device?. I looked into qos1 feature of mqtt which is a queing system, and when i wakeup the device i should be able to process the messages which were sent even when the device is asleep. Is there any examples to use qos1 in the application layer? So with this i can timely wakeup and process the messages.

**Comment by huguesBouvier** [comment]
I don't know the specifics about esp32 but for the SDK, you can see QOS1 being used in subscribe_publish_cpp_sample and in subscribe_publish_library_sample.
Your solution should work, it would trigger coutinuous retries until your device wakes up. Be careful though:
1. You device could receive more than twice the same message
2. You Keep alive interval need to be long enough that you don't lose connection while your device is asleep.
Best
