### ISSUE TITLE
cannot reconnect to the iot.

### ISSUE THREAD

**Issue by yaoguoqiang1224** [aws/aws-iot-device-sdk-embedded-C#1464]
After our equipment is online for a long time, it will be disconnected. The specific log is as follows:

#define MBEDTLS_ERR_NET_UNKNOWN_HOST -0x0052
/**< Failed to get an IP address for the given hostname. */

aws_iot_mqtt_connect client_id: **** abnormal -23.

The device cannot reconnect to the iot.

**Comment by lundinc2** [comment]
Hi @yaoguoqiang1224,

What version of the C-SDK are you using?

Thanks,

Carl

**Comment by yaoguoqiang1224** [comment]
3.0.1

**Comment by yaoguoqiang1224** [comment]
3.1.1

**Comment by muneebahmed10** [comment]
HI @yaoguoqiang1224,

Can you provide some more details on the disconnection/reconnection? Do you know what is causing the disconnect?

I searched the version 3 code for your logs, and MBEDTLS_ERR_NET_UNKNOWN_HOST just seems to be from `include/mbedtls/net_sockets.h` in mbedTLS, not the C SDK. As for a -23 error code, the closest I found was this:
```
mbedtls-2.16.6/include/mbedtls/blowfish.h:#define MBEDTLS_ERR_BLOWFISH_HW_ACCEL_FAILED                   -0x0017  /**< Blowfish hardware accelerator failed. */
```
I'm unsure if this is the same error you are getting. Are there any additional logs you can provide?

Additionally, as version 3 of the CSDK and its associated MQTT library are deprecated (and only accepting bug fixes), I would also recommend trying out the latest released version [202012.01](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/202012.01) of the CSDK using the [current version](https://github.com/FreeRTOS/coreMQTT/tree/v1.1.0) of the MQTT library.

Thank you

**Comment by yourslab** [comment]
Also, is this error specific to the Linux distribution of v3, or are you running this on an esp by any chance?

**Comment by pvyawaha** [comment]
Closing this issue now, please reopen if you have more questions on the same topic.
