### ISSUE TITLE
Running mqtt_demo_mutual_auth (tag 202011.00) under Ubuntu 18.04

### ISSUE THREAD

**Issue by rupans** [aws/aws-iot-device-sdk-embedded-C#1500]
However there is an issue when I run this under Ubuntu 18.04. Here are the messages when I run the mqtt_demo_mutual_auth app:

...
...
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:699] Failed to receive data over network: SSL_read failed: ErrorStatus=EVP lib.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:699] Failed to receive data over network: SSL_read failed: ErrorStatus=EVP lib.
[ERROR] [MQTT] [core_mqtt.c:1537] CONNACK recv failed with status = MQTTNoDataAvailable.
[ERROR] [MQTT] [core_mqtt.c:1808] MQTT connection failed with status = MQTTNoDataAvailable.

When I try to install libssl-dev I can see that I have the latest version. I have included the extract below:

rupan@rupan-HP-250-G6-Notebook-PC:~/austin/aws-iot-device-sdk-embedded-c/build/bin$ sudo apt-get install libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version (1.1.1-1ubuntu2.1~18.04.6).
The following packages were automatically installed and are no longer required:
  cmake-data libjsoncpp1 librhash0 libuv1
Use 'sudo apt autoremove' to remove them.
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

**Comment by lundinc2** [comment]
Hi @rupans,

This looks like it could possibly be an issue with your iot policy. Can you try checking your policy for any errors, or posting it here? 

Can you verify that you have a similar issue using mosquitto?

`mosquitto_pub -d -p 8883 -t {topic} --cafile {root_ca_cert} --cert {device_cert} --key {device_key} -i {thing_name} -h {endpoint} -m "Hello"`

You can install mosquitto with `sudo apt-get install mosquitto-clients`

**Comment by rupans** [comment]
Hi lundinc,

https://eu-west-2.console.aws.amazon.com/iot/home?region=eu-west-2#/policy/rupan_espdevkit2_amazon_freertos_policy

I will verify with mosquitto_pub as that looks like a useful tool

**Comment by lundinc2** [comment]
Hi @rupans 

Unfortunately I cannot view that link, as it is to your personal AWS account, can you post the json here?

**Comment by rupans** [comment]
Hi lundinc2,

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:PutMetricFilter",
        "logs:PutRetentionPolicy"
      ],
      "Resource": [
        "*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": "iot:Connect",
      "Resource": "arn:aws:iot:eu-west-2:661600587188:*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Publish",
      "Resource": "arn:aws:iot:eu-west-2:661600587188:*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Subscribe",
      "Resource": "arn:aws:iot:eu-west-2:661600587188:*"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Receive",
      "Resource": "arn:aws:iot:eu-west-2:661600587188:*"
    }
  ]
}

**Comment by lundinc2** [comment]
Hi @rupans,

I have deleted the above post for you as it included your account id. It looks like you are missing a glob in the Publish, connect, subscribe, actions.

**Comment by lundinc2** [comment]
Can you repost your policy with the account id censored?

**Comment by muneebahmed10** [comment]
Hi @rupans,

I see you're using tag 202011.00, which includes an older version of the OpenSSL-based transport interface. Based on your OpenSSL error messages, I suspect that `SSL_read` might actually be returning 0, indicating that the remote server wishes to close the connection. This will be the case when your AWS IoT permissions have not been configured correctly.

Can you double check that you have followed the [instructions](https://docs.aws.amazon.com/iot/latest/developerguide/create-iot-resources.html) for configuring your device certificate and policies?

Additionally, I would recommend updating to the latest tag, [202012.01](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/202012.01), as it contains an updated TLS transport implementation.

Thank you

**Comment by muneebahmed10** [comment]
Hi @rupans,

Did the above [post](https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/1500#issuecomment-747079088) resolve your issue? We will close this issue if we do not hear back from you.

Thank you

**Comment by pvyawaha** [comment]
Closing this ticket now , please reopen if you have more questions.

**Comment by rupans** [comment]
Hi,

Sorry was on holiday. Yes thank you for your help in resolving the issue

Kind Regards,

Rupan

**Comment by William-ferns** [comment]
Hi Rupan,

we are facing same issue, as if we have integrated python sdk to cross verify the certifications of AWS it is working fine but Embedded c SDK is having issue with the same certifications what you have faced earlier, please can you give the information how did solve the issue please let me know.

Thanks and regards,
william

**Comment by rupans** [comment]
Hi,

I am not a support engineer and it could be many issues I suspect you would
get better results opening a ticket.

Kind Regards,

Rupan
