### ISSUE TITLE
https failed to resolve URL

### ISSUE THREAD

**Issue by surya-teja-p** [aws/aws-iot-device-sdk-embedded-C#1501]
Hi,

I am trying to use IotHttpsClient_Connect() for HTTPS POST request by connecting to custom URL in NON-TLS mode but I 'am facing following errors in ESP32. Kindly please help me.

Error Log:
3 470 [iot_thread] [ERROR][NET][4700] Failed to resolve URL.
4 471 [iot_thread] [ERROR][HTTPS Client][4710] Failed to connect to the server at URL on port 443 with error: 4
5 471 [iot_thread] [ERROR][HTTPS Client][4710] Error in IotHttpsClient_Connect(). Error code 203.

Best Regards,
Surya.

**Comment by lundinc2** [comment]
Hello @surya-teja-p,

What version of the C-SDK are you using? Do you mind expanding on your use case a bit more? 

Traditionally port 443 requires TLS, and port 80 would be used for plaintext HTTP.

Thanks,

Carl

**Comment by surya-teja-p** [comment]
Hi carl,

In non-TLS mode I was able to connect to "postman-echo.com" as well as "www.google.com" with port 443 but when I connect to my custom URL it is resulting the mentioned failure.

Thanks,
surya

**Comment by surya-teja-p** [comment]
Hi Carl,

Issue got resolved,

Thanks,
Surya

**Comment by lundinc2** [comment]
Happy to hear that Surya, please re-open this issue should you need further assistance.
