### ISSUE TITLE
Typo in shadow demo

### ISSUE THREAD

**Issue by boraozgen** [aws/aws-iot-device-sdk-embedded-C#1507]
Hi all, found a typo:

Should be `SHADOW_REPORTED_JSON_LENGTH`

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d2e37908a571c661d0c631f2d87e8a64a637ea7a/demos/shadow/shadow_demo_main/shadow_demo_main.c#L843

**Comment by lundinc2** [comment]
Hii @boraozgen,

Thanks for this report, I have taken a look and provided an update in two separate PRs. They are still pending review.

**Comment by lundinc2** [comment]
Hi @boraozgen,

Both PRs are merged now, thanks again for helping us keep our documentation up to date. Please re-open this issue should you have further comments.
