### ISSUE TITLE
Shadow_GetTopicString example has an undefined macro

### ISSUE THREAD

**Issue by boraozgen** [aws/aws-iot-device-sdk-embedded-C#1508]
`SHADOW_TOPIC_STRING_TYPE_UPDATE_DELTA` does not exist. Is `ShadowTopicStringTypeUpdateDelta` meant here?

This also applies to the example code in `shadow.h`.

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/3d9a8d47dbdf6729c447ddcb8a808bcc8996435b/demos/shadow/shadow_demo_main/shadow_demo_main.c#L778

**Comment by boraozgen** [comment]
Same for the status type:

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/3d9a8d47dbdf6729c447ddcb8a808bcc8996435b/demos/shadow/shadow_demo_main/shadow_demo_main.c#L771

**Comment by lundinc2** [comment]
Hii @boraozgen,

Thanks for this report, I have taken a look and provided an update in two separate PRs. They are still pending review.

**Comment by lundinc2** [comment]
Hi @boraozgen,

Both PRs are merged now, thanks again for helping us keep our documentation up to date. Please re-open this issue should you have further comments.

**Comment by boraozgen** [comment]
Hi @lundinc2,

I found another bug in the same example.
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/3d9a8d47dbdf6729c447ddcb8a808bcc8996435b/demos/shadow/shadow_demo_main/shadow_demo_main.c#L775-L776

Here the size of the pointer is read (i.e 4). `thingName` should be declared as an array instead of a pointer.

**Comment by lundinc2** [comment]
Thanks @boraozgen, I will fix this.

**Comment by lundinc2** [comment]
I have opened https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1527 @boraozgen
