### ISSUE TITLE
Resubscribe fails when auto-reconnect not enabled

### ISSUE THREAD

**Issue by kevinduk** [aws/aws-iot-device-sdk-embedded-C#1510]
This is a question on v3.1.1.

PR #548 added the resubscribed flag to MessageHandlers. The flag is set when a topic has been resubscribed. If the flag is set then there will be no further resubscribes on that topic. That is fine.

The resubscribed flag is reset when there is an MQTT disconnection, **but it is only reset if auto-reconnect is enabled** - see function _aws_iot_mqtt_internal_yield.

If auto-reconnect is not enabled then the resubscribed flag is never reset and there are no way to resubscribe to the previous topics. This is a problem for me.

My application manages reconnections itself, so the auto-reconnect feature of the library is disabled. On reconnecting to AWS, my application calls aws_iot_mqtt_resubscribe to resubscribe to the previous topics. On the first re-connection the library does resubscribe to previous topics (because the resubscribed flag is 0) but on subsequent re-connectionions the library does not resubscribe to previous topics because the resubscribe flag is now 1.

If I edit_aws_iot_mqtt_internal_yield to always reset the resubscribed flags when there is a disconnect, then the library always resubscribes to topics when the application calls aws_iot_mqtt_resubscribe.

My question is: Is it valid to call the aws_iot_mqtt_resubscribe function if auto-reconnect is disabled?

If it is valid then the library must always reset the reconnected flag on a disconnection.

If it is not valid then how should I resubscribe to previous topics when I reconnect.

Thank you for your help,

Kevin

**Comment by muneebahmed10** [comment]
Hi @kevinduk,

Thank you for bringing this issue to our attention. Looking through the API, it is valid to manually attempt a reconnect with [aws_iot_mqtt_attempt_reconnect](http://aws-iot-device-sdk-embedded-c-docs.s3-website-us-east-1.amazonaws.com/aws__iot__mqtt__client__connect_8c.html#a06f1274703467ebdb1d22dd85921753c), which calls `aws_iot_mqtt_resubscribe`. I've created #1514 to address this and always clear the resubscribe flags regardless of whether auto-reconnect is enabled. Can you confirm that this fix addresses your issue?

Thank you

**Comment by kevinduk** [comment]
Hi Muneeb,
I have tested the changes and they have fixed the issue.
Thank you and best wishes,
Kevin

**Comment by muneebahmed10** [comment]
Hi @kevinduk,

That's great to hear! I've merged the PR and the changes are included in tag [v3.1.5](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v3.1.5). Please let us know by opening a new issue if you have any further questions.

Thank you
