### ISSUE TITLE
Didn't get the mqtt_demo_mutual_auth executable app.

### ISSUE THREAD

**Issue by ipce2** [aws/aws-iot-device-sdk-embedded-C#1520]
[cmake_log.txt](https://github.com/aws/aws-iot-device-sdk-embedded-C/files/5752578/cmake_log.txt)
I followed the steps as :
https://docs.aws.amazon.com/iot/latest/developerguide/iot-embedded-c-sdk.html 
After the cmake .. and make, There are many files in the build/bin:
http_demo_basic_tls  mqtt_demo_basic_tls   pkcs11_demo_management_and_rng      pkcs11_demo_sign_and_verify
http_demo_plaintext  mqtt_demo_plaintext   pkcs11_demo_mechanisms_and_digests
 jobs_demo_mosquitto  mqtt_demo_serializer  pkcs11_demo_objects.

but  no mqtt_demo_mutual_auth executable app in the build/bin. My OS is ubuntu 18.04.1.

**Comment by yourslab** [comment]
Hi @ipce2. In the instructions, `CLIENT_CERT_KEY_PATH` needs to be changed to `CLIENT_CERT_PATH`.

Can you please modify `demo_config.h` to fix this? Also, you can force the MQTT mutual auth demo to build by entering:
```make mqtt_demo_mutual_auth```

We will update the instructions. Thank you for pointing this out.

**Comment by ipce2** [comment]
> Hi @ipce2. In the instructions, `CLIENT_CERT_KEY_PATH` needs to be changed to `CLIENT_CERT_PATH`.
> 
> Can you please modify `demo_config.h` to fix this? Also, you can force the MQTT mutual auth demo to build by entering:
> `make mqtt_demo_mutual_auth`
> 
> We will update the instructions. Thank you for pointing this out.

Thanks for your reply,I will try.
