### ISSUE TITLE
Accessing named shadow  using Embedded C sdk

### ISSUE THREAD

**Issue by anubhav1** [aws/aws-iot-device-sdk-embedded-C#1522]
Hi,

**How to access a named shadow(not classic shadow)?** 
I want to access my named  shadow _ESP32NamedShadow_ which arn is

`arn:aws:iot:region:XXXXXXXXXXXXX:thing/ESP32DevKitC/ESP32NamedShadow`
I do not find any option to provide shadow name in connection parameters. I found only this :

```
typedef struct {
	const char *pMyThingName; ///< Every device has a Thing Shadow and this is the placeholder for name
	const char *pMqttClientId; ///< Currently the Shadow uses MQTT to connect and it is important to ensure we have unique client id
	uint16_t mqttClientIdLen; ///< Currently the Shadow uses MQTT to connect and it is important to ensure we have unique client id
	pApplicationHandler_t deleteActionHandler;	///< Callback to be invoked when Thing shadow for this device is deleted
} ShadowConnectParameters_t;
```
which is asking for thing name and not the shadow name. Can we access only classic shadow using sdk?

**Comment by leegeth** [comment]
@anubhav1,

Thanks for reaching out to us with your question. 

Guessing from the the structure pasted as part of the question, you are using the V3 embedded C SDK. Can you please confirm if that is the version of the SDK you are using?

As you have correctly suspected, the V3 SDK only supports the classic shadow. 

However, we are currently working on adding support for named shadows through [PR #56](https://github.com/aws/Device-Shadow-for-AWS-IoT-embedded-sdk/pull/56) and [PR #1387](https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1387). Please note that these changes are made on top of a [newer version of device shadow library](https://github.com/aws/Device-Shadow-for-AWS-IoT-embedded-sdk/tree/v1.0.2), which has different APIs as compared to the V3 SDK. Please check it out and see if it will help you. Please also let us know if you have any further questions or concerns.

**Comment by anubhav1** [comment]
How to check the version of C SDK?

**Comment by leegeth** [comment]
@anubhav1,

If you are using git, the command `git describe --tags --abbrev=0` will help you find the latest git tag of your SDK code. This will be the either the version of the SDK or the closest release version of the SDK you are using(In case if it is a direct clone of the master/main branch).
Alternatively the files `README.md` and `CHANGELOG.md` in the SDK will have mentions about the release version of the SDK.

**Comment by anubhav1** [comment]
The version is 3.0.1

**Comment by leegeth** [comment]
@anubhav1 

Thanks for confirming it. So the SDK you are using is V3 SDK(v3.x.x version of SDK).  So, as mentioned already Named Shadow support is not there in that version of the SDK.
Did you get a chance to check the PRs( [PR #56](https://github.com/aws/Device-Shadow-for-AWS-IoT-embedded-sdk/pull/56/) and [PR #1387](https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1387)) and the[ latest version of Shadow library](https://github.com/aws/Device-Shadow-for-AWS-IoT-embedded-sdk/tree/v1.0.2) to see if it helps your requirements?

**Comment by anubhav1** [comment]
Not yet. This functionality is not the priority right now in my project. So I will look later. Closing the issue for now.
