### ISSUE TITLE
SSL_read failure with ErrorStatus=EVP lib (202012.01)

### ISSUE THREAD

**Issue by alozach** [aws/aws-iot-device-sdk-embedded-C#1537]
We are migrating from the v4_beta_deprecated branch to the tag 202012.01, bue we have the following messages repeated over and over when we try to subscribe to a MQTT channel (same problem with _mqtt_demo_mutual_auth_):
```
...
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:761] Failed to receive data over network: SSL_read failed: ErrorStatus=EVP lib.
[ERROR] [MQTT] [core_mqtt_serializer.c:2395] A single byte was not read from the transport: transportStatus=-1.
[ERROR] [MQTT] [core_mqtt.c:1320] Receiving incoming packet length failed. Status=MQTTRecvFailed
[ERROR] [MQTT] [core_mqtt.c:2196] Exiting process loop due to failure: ErrorStatus=MQTTRecvFailed
...
```

Everything works fine on the v4_beta_deprecated branch, where we use the mbed TLS network interface, not OpenSSL

We saw [this issue](https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/1500), but we don't think it's a policy error since we had no problems on the v4_beta_deprecated branch, and we don't have this issue using _mosquitto_pub_

Is there an implementation of _NetworkContext_ using MbedTLS, or should we try implementing it ourself?

**Comment by yourslab** [comment]
Just to confirm, are you able to receive the CONNACK (Connection Acknowledgement) from the MQTT broker at all? Is it only failing with subscription? Does it happen consistently or occasionally? 

As a matter of fact, we do have an implementation of NetworkContext using mbedTLS in the FreeRTOS repository:
https://github.com/FreeRTOS/FreeRTOS/blob/master/FreeRTOS-Plus/Source/Application-Protocols/network_transport/freertos_plus_tcp/using_mbedtls/using_mbedtls.c
All that you need to do is change these functions to call POSIX Sockets API (`send`, `recv`) instead of FreeRTOS+TCP Sockets API (`FreeRTOS_send`, `FreeRTOS_recv`):
https://github.com/FreeRTOS/FreeRTOS/blob/master/FreeRTOS-Plus/Source/Utilities/mbedtls_freertos/mbedtls_freertos_port.c#L110-L198

Although, my guess is that the root cause isn't with OpenSSL itself, and you shouldn't really have to switch to mbedTLS. This error is returned when the MQTT broker would like to close the connection. Is the demo modified in any way to cause this to happen?

**Comment by yourslab** [comment]
Another thing that would help is a packet capture with Wireshark and similar so we can determine why the MQTT broker is cutting your connection

**Comment by alozach** [comment]
I receive the CONNACK, but I always have the error when I call MQTT_SUBSCRIBE followed by MQTT_ProcessLoop:
```
[DEBUG] [MQTT] [core_mqtt_serializer.c:459] Encoded size for length 192 is 2 bytes.
[DEBUG] [MQTT] [core_mqtt_serializer.c:1594] CONNECT packet remaining length=192 and packet size=195.
[DEBUG] [MQTT] [core_mqtt.c:1782] CONNECT packet size is 195 and remaining length is 192.
[DEBUG] [MQTT] [core_mqtt_serializer.c:459] Encoded size for length 192 is 2 bytes.
[DEBUG] [MQTT] [core_mqtt_serializer.c:1493] Length of serialized CONNECT packet is 195.
[DEBUG] [MQTT] [core_mqtt.c:645] BytesSent=195, BytesRemaining=0
[DEBUG] [MQTT] [core_mqtt.c:666] Successfully sent packet at time 99068.
[DEBUG] [MQTT] [core_mqtt.c:1807] Sent 195 bytes of CONNECT packet.
[DEBUG] [MQTT] [core_mqtt_serializer.c:2387] No data was received from the transport.
[DEBUG] [MQTT] [core_mqtt_serializer.c:459] Encoded size for length 2 is 1 bytes.
[DEBUG] [MQTT] [core_mqtt.c:770] BytesReceived=2, BytesRemaining=0, TotalBytesReceived=2.
[INFO] [MQTT] [core_mqtt.c:886] Packet received. ReceivedBytes=2.
[INFO] [MQTT] [core_mqtt_serializer.c:970] CONNACK session present bit not set.
[INFO] [MQTT] [core_mqtt_serializer.c:912] Connection accepted.
[INFO] [MQTT] [core_mqtt.c:1563] Received MQTT CONNACK successfully from broker.
[INFO] [MQTT] [core_mqtt.c:1829] MQTT connection established with the broker.

[DEBUG] [MQTT] [core_mqtt_serializer.c:459] Encoded size for length 82 is 1 bytes.
[DEBUG] [MQTT] [core_mqtt_serializer.c:1076] Subscription packet remaining length=82 and packet size=84.
[DEBUG] [MQTT] [core_mqtt.c:1870] SUBSCRIBE packet size is 84 and remaining length is 82.
[DEBUG] [MQTT] [core_mqtt_serializer.c:459] Encoded size for length 82 is 1 bytes.
[DEBUG] [MQTT] [core_mqtt_serializer.c:1744] Length of serialized SUBSCRIBE packet is 84.
[DEBUG] [MQTT] [core_mqtt.c:645] BytesSent=84, BytesRemaining=0
[DEBUG] [MQTT] [core_mqtt.c:666] Successfully sent packet at time 99518.
[DEBUG] [MQTT] [core_mqtt.c:1898] Sent 84 bytes of SUBSCRIBE packet.

[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:761] Failed to receive data over network: SSL_read failed: ErrorStatus=EVP lib.
[ERROR] [MQTT] [core_mqtt_serializer.c:2397] A single byte was not read from the transport: transportStatus=-1.
[ERROR] [MQTT] [core_mqtt.c:1320] Receiving incoming packet length failed. Status=MQTTRecvFailed
[ERROR] [MQTT] [core_mqtt.c:2192] Exiting process loop due to failure: ErrorStatus=MQTTRecvFailed
```

I managed to have a working demo, the root cause was indeed a bad formatted topic, which did not follow my policy

But my application still fails, even when I send the same parameters to MQTT_Subscribe that I send in the working demo
I agree OpenSSL is not to blame, and I suppose the problem comes from my application, but I don't know where. 

Here is a tcpdump, from the connection of my application to ~10s after the first error log: 
[tcpdump_iot.pcap.gz](https://github.com/aws/aws-iot-device-sdk-embedded-C/files/5966238/tcpdump_iot.pcap.gz)

**Comment by yourslab** [comment]
What is the topic filter you are using?

**Comment by alozach** [comment]
The value `preprod/432e9cdc-638b-48a6-b1f8-e37ee1a0a557/downlink/iotDeviceMessaging/info` works in the demo, but raises the error in my application

**Comment by yourslab** [comment]
In your application, are you possible using multiple threads? The MQTT context itself is not thread safe.

**Comment by alozach** [comment]
I managed to make the subscription work, the root cause was the buffer given to `MQTT_Init`, which became invalid at some point of my process.

But I'm still having some errors when calling `ProcessLoop`, but not consistently:
`[Transport_OpenSSL_Sockets] [openssl_posix.c:761] Failed to receive data over network: SSL_read failed: ErrorStatus=DH lib`
and
`[Transport_OpenSSL_Sockets] [openssl_posix.c:814] Failed to send data over network: SSL_write of OpenSSL failed: ErrorStatus=DH lib`

I'm calling MQTT_ProcessLoop in an infinite loop in a separate thread, could it be the cause of those errors since the MQTT context is not thread safe? Should I make all my `coreMQTT` calls (Init, Publish, ProcessLoop,...) from a unique thread?

**Comment by yourslab** [comment]
You can create separate MQTT contexts with the same `TransportInterface_t` but different `MQTTFixedBuffer_t`. For each thread, use a different context. The reason for doing so is that `MQTTFixedBuffer_t` will be populated with MQTT messages to be sent or received. Suppose you are about to send data but then you receive data right before sending, the data about to be sent will become garbage. You can also use synchronization primitives like mutexes or queues. A good example of how this is done is shown here:
https://github.com/FreeRTOS/freertos-mqtt-agent

**Comment by alozach** [comment]
It was indeed a thread problem, everything works fine now, thank you!

**Comment by mukesh-2538** [comment]
@alozach how did you solve the issue?

**Comment by alozach** [comment]
@mukesh-2538  I had a separate thread calling `MQTT_ProcessLoop` in a loop, I solved the issue it calling `MQTT_Subscribe` in this thread, and ensuring this thread has been stopped before calling again `MQTT_Connect` or other SDK functions after a disconnection
