### ISSUE TITLE
aws port for Lwip and FreeRTOS

### ISSUE THREAD

**Issue by tushartp** [aws/aws-iot-device-sdk-embedded-C#156]
Hello,

As most of the embedded devices are running small MCU, it would be worth to add support for Lwip network stack and FreeRTOS OS support.
Are there any plans to add support for it?

**Comment by gordonwang0** [comment]
Hello @tushartp,

Currently, we have no plans to support lwIP.  We’ve noted your request for this feature, and we’ll prioritize it based on customer requests and our current priorities.

For FreeRTOS support, please see [the Amazon FreeRTOS project](https://github.com/aws/amazon-freertos).
