### ISSUE TITLE
what is the error of Error(-12)?

### ISSUE THREAD

**Issue by SaberOwO** [aws/aws-iot-device-sdk-embedded-C#157]
[root@centos7 subscribe_publish_sample]# ./subscribe_publish_sample 

AWS IoT SDK Version 2.3.0-

DEBUG:   main L#159 rootCA /locker/aws-iot-device-sdk-embedded-C-master/samples/linux/subscribe_publish_sample/../../../certs/rootCA.crt
DEBUG:   main L#160 clientCRT /locker/aws-iot-device-sdk-embedded-C-master/samples/linux/subscribe_publish_sample/../../../certs/fd79201d02-certificate.pem.crt
DEBUG:   main L#161 clientKey /locker/aws-iot-device-sdk-embedded-C-master/samples/linux/subscribe_publish_sample/../../../certs/fd79201d02-private.pem.key
Connecting...
DEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to a1ax6iiaxvtypw.iot.ap-northeast-2.amazonaws.com/8883...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 2):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 18:DA:D1:9E:26:7D:E8:BB:4A:21:58:CD:CC:6B:3B:4A
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name      : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
issued  on        : 2006-11-08 00:00:00
expires on        : 2036-07-16 23:59:59
signed using      : RSA with SHA1
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 3F:92:87:BE:9D:1D:A4:A3:7A:9D:F6:28:2E:77:5A:C4
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name      : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
issued  on        : 2015-05-12 00:00:00
expires on        : 2025-05-11 23:59:59
signed using      : RSA with SHA-256
EC key size       : 256 bits
basic constraints : CA=true, max_pathlen=0
subject alt name  : 
key usage         : Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 5C:70:1E:E5:C2:B1:85:61:08:9A:53:5C:B1:18:98:C3
issuer name       : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.iot.ap-northeast-2.amazonaws.com
issued  on        : 2017-07-25 00:00:00
expires on        : 2018-07-26 23:59:59
signed using      : ECDSA with SHA256
EC key size       : 256 bits
basic constraints : CA=false
subject alt name  : iot.ap-northeast-2.amazonaws.com, *.iot.ap-northeast-2.amazonaws.com
key usage         : Digital Signature
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   iot_tls_connect L#246  ok
    [ Protocol is TLSv1.2 ]
    [ Ciphersuite is TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384 ]

DEBUG:   iot_tls_connect L#248     [ Record expansion is 29 ]

DEBUG:   iot_tls_connect L#253   . Verifying peer X.509 certificate...
DEBUG:   iot_tls_connect L#262  ok

DEBUG:   iot_tls_connect L#272   . Peer certificate information    ...

DEBUG:   iot_tls_connect L#274       cert. version     : 3
      serial number     : 5C:70:1E:E5:C2:B1:85:61:08:9A:53:5C:B1:18:98:C3
      issuer name       : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
      subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.iot.ap-northeast-2.amazonaws.com
      issued  on        : 2017-07-25 00:00:00
      expires on        : 2018-07-26 23:59:59
      signed using      : ECDSA with SHA256
      EC key size       : 256 bits
      basic constraints : CA=false
      subject alt name  : iot.ap-northeast-2.amazonaws.com, *.iot.ap-northeast-2.amazonaws.com
      key usage         : Digital Signature
      ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

ERROR: main L#190 Error(-12) connecting to a1ax6iiaxvtypw.iot.ap-northeast-2.amazonaws.com:8883
------------------------------------------------------------------------

Hello, I just follow the progress of tutorial. But when I run the ./subscribe_publish_sample, it keeps poping: ERROR: main L#190 Error(-12) connecting to a1ax6iiaxvtypw.iot.ap-northeast-2.amazonaws.com:8883 Can you help me to find what is wrong here? Thank you very much!

**Comment by gordonwang0** [comment]
Hello @SaberOwO,

`-12` is `NETWORK_SSL_READ_ERROR`.

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/760380eed421ff1afed50abe5d7eb313908c4ffe/include/aws_iot_error.h#L78

Something is probably wrong with the `pConnectParams` parameter of the `aws_iot_mqtt_connect` call on line 188.

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/760380eed421ff1afed50abe5d7eb313908c4ffe/samples/linux/subscribe_publish_sample/subscribe_publish_sample.c#L188

For example, setting `pConnectParams.isCleanSession = false` will cause a connection to fail because AWS IoT only supports clean sessions.  There are many other possible failure reasons.  Can you post what each member of `pConnectParams` is set to when you call `aws_iot_mqtt_connect`?

**Comment by gordonwang0** [comment]
Please let me know if you need any more help on this.  Closing issue.

**Comment by jflynn129** [comment]
Same issue using the as delivered subscribe_publish_sample that is delivered in the embedded C SDK:

ERROR: main L#190 Error(-12) connecting to a1075elwyht7bd.iot.us-west-2.amazonaws.com:443

I didn't modify anything in subscribe_publish_sample.c, only updated aws_iot_config.h as described in the README (download mbedtls to compile, the security certificates, and set a policy).  BTW, I'm compiling on Ubuntu.

The parameter settings are:
        connectParams.keepAliveIntervalInSec = 600;
        connectParams.isCleanSession = true;
        connectParams.MQTTVersion = MQTT_3_1_1;
        connectParams.pClientID = AWS_IOT_MQTT_CLIENT_ID;
        connectParams.clientIDLen = (uint16_t) strlen(AWS_IOT_MQTT_CLIENT_ID);
        connectParams.isWillMsgPresent = false;
The output in its entirety is:

AWS IoT SDK Version 3.0.1-

DEBUG:   main L#159 rootCA /home/jim/AWS/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/rootCA.crt
DEBUG:   main L#160 clientCRT /home/jim/AWS/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/be7945653d-certificate.pem.crt
DEBUG:   main L#161 clientKey /home/jim/AWS/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/be7945653d-private.pem.key
Connecting...
DEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to a1075elwyht7bd.iot.us-west-2.amazonaws.com/443...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 2):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 18:DA:D1:9E:26:7D:E8:BB:4A:21:58:CD:CC:6B:3B:4A
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name      : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
issued  on        : 2006-11-08 00:00:00
expires on        : 2036-07-16 23:59:59
signed using      : RSA with SHA1
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 3F:92:87:BE:9D:1D:A4:A3:7A:9D:F6:28:2E:77:5A:C4
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name      : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
issued  on        : 2015-05-12 00:00:00
expires on        : 2025-05-11 23:59:59
signed using      : RSA with SHA-256
EC key size       : 256 bits
basic constraints : CA=true, max_pathlen=0
subject alt name  : 
key usage         : Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 53:A5:8B:08:C9:5D:59:62:DE:90:E0:B2:9E:43:68:69
issuer name       : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.iot.us-west-2.amazonaws.com
issued  on        : 2017-11-22 00:00:00
expires on        : 2018-11-23 23:59:59
signed using      : ECDSA with SHA256
EC key size       : 256 bits
basic constraints : CA=false
subject alt name  : iot.us-west-2.amazonaws.com, *.iot.us-west-2.amazonaws.com
key usage         : Digital Signature
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   iot_tls_connect L#246  ok
    [ Protocol is TLSv1.2 ]
    [ Ciphersuite is TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384 ]

DEBUG:   iot_tls_connect L#248     [ Record expansion is 29 ]

DEBUG:   iot_tls_connect L#253   . Verifying peer X.509 certificate...
DEBUG:   iot_tls_connect L#262  ok

DEBUG:   iot_tls_connect L#272   . Peer certificate information    ...

DEBUG:   iot_tls_connect L#274       cert. version     : 3
      serial number     : 53:A5:8B:08:C9:5D:59:62:DE:90:E0:B2:9E:43:68:69
      issuer name       : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
      subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.iot.us-west-2.amazonaws.com
      issued  on        : 2017-11-22 00:00:00
      expires on        : 2018-11-23 23:59:59
      signed using      : ECDSA with SHA256
      EC key size       : 256 bits
      basic constraints : CA=false
      subject alt name  : iot.us-west-2.amazonaws.com, *.iot.us-west-2.amazonaws.com
      key usage         : Digital Signature
      ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication


ERROR: main L#190 Error(-12) connecting to a1075elwyht7bd.iot.us-west-2.amazonaws.com:443


Should the sample that is delivered in the SDK compile and run without modification?

**Comment by jflynn129** [comment]
@gordonwang0 this was closed, but rather than re-open a new one, I just commented above.  Maybe it is a simple config issue on my part...

**Comment by jflynn129** [comment]
@gordonwang0 BTW, is there a tutorial or a step-by-step example which goes over setting up the certificates, policies and other required settings that must be followed to use this sample?

**Comment by jflynn129** [comment]
@gordonwang0 Also, debugging through this some, it looks like the error being returned is 0x7880 (MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY ) so why would the AWS connection be closed?  what really confuses me is that this is the stock sample that is delivered with the SDK and it isn't working per the documented instructions...

**Comment by gordonwang0** [comment]
Hi @jflynn129,

Has your problem been solved in #183?

**Comment by jflynn129** [comment]
Yes it was, thanks for checking.

**Comment by DiegoHeras** [comment]
Got the same problem. Please, could you help us saying how you fix it?

**Comment by gordonwang0** [comment]
The issue here was one with [Policies](https://docs.aws.amazon.com/iot/latest/developerguide/iot-policies.html), where the attached device policy did not allow connection.

BTW -- please open a new issue for additional questions.  We generally don't respond (in a timely manner) to closed issues.

**Comment by Vieufoux** [comment]
Hi @gordonwang0,

I revoke the certificate from cloud side when the device already connected. After a few minutes, the device get NETWORK_SSL_READ_ERROR = -12 as well. 

I hope that the device can get a detailed error to indicate that the certificate has been revoked and then apply a new one. But It seems certificate revoke and the policy limitation will both cause this error, so I can't distinguish which one caused the -12 error. Is there a better solution to distinguish them?

**Comment by ahtashambaig** [comment]
Hi.. I need help with the same issue for Network_SSL_READ_ERROR.... in my program i need to connect to multiple AWS MQTT topics including device shadow. The device gets connected to server and also subscribe to few topics random number of topics and return NETWORK_SSL_READ_ERROR

**Comment by ahtashambaig** [comment]
Number of MQTT topics are 12

**Comment by ahtashambaig** [comment]
Also to be mentioning this is not the always occuring situation sometimes the code works fine
