### ISSUE TITLE
Multi-thread support problem

### ISSUE THREAD

**Issue by Iot-lilei** [aws/aws-iot-device-sdk-embedded-C#158]
There is a description about multi-thread in samples/README.md "The yield API should be called periodically to process the PING request as well as read any messages in the receive buffer. It should be called once at least every TTL/2 time periods to ensure disconnect does not happen. There can only be one yield in progress at a time. Therefore, in multi-threaded scenarios one thread can be a dedicated yield thread while other threads handle other operations." 
So I started a thread running aws_iot_mqtt_yield() for every 100ms and another thread to publish data every 5 seconds. However, there is a client state control besides real ssl data transport. So, in this case,   the aws_iot_mqtt_publish() would immediately return an error code -30 because the client would stay in CLIENT_STATE_CONNECTED_YIELD_IN_PROGRESS most of the time, not CLIENT_STATE_CONNECTED_IDLE.
Is this how it is used? Or do I miss something?

Regards

**Comment by huguesBouvier** [comment]
Hi,

What you just explained is the good method. One dedicated thread for yield and one for publish. I am sorry but I am not sure why your are experiencing that issue. You should not get stuck in CLIENT_STATE_CONNECTED_YIELD_IN_PROGRESS.

There are examples in the code that do just that, please see: \tests\integration\src\aws_iot_test_basic_connectivity.c. It does a yield + publish.

Also make sure that you have -lpthread declared and that you have defined _ENABLE_THREAD_SUPPORT_.

Regards,

Hugues

**Comment by Iot-lilei** [comment]
Hi, 
Sorry for not pasting my code. My yield thread looks like this:
void *recv_thrd_func(void *arg){
	IoT_Error_t rc = FAILURE;
	AWS_IoT_Client *pclient = (AWS_IoT_Client *)arg;
	while(!recv_thread_exit){
		rc = saic_iot_mqtt_yield(pclient, 100);
		if(rc != SUCCESS){
			IOT_ERROR("Mqtt yield error: %d", rc);
		}
	}
	IOT_INFO("Receive thread exit!");
}
My core code of publish thread looks like this:
while((NETWORK_ATTEMPTING_RECONNECT == rc || NETWORK_RECONNECTED == rc || SUCCESS == rc)
		  && (publishCount > 0 || infinitePublishFlag)) {
		sleep(5);
		sprintf(cPayload, "{\"SDK\": \"hello from SDK\", \"count\": %d}", i++);
		paramsQOS0.payloadLen = strlen(cPayload);
		rc = saic_iot_mqtt_publish(&client, upd_topic, strlen(upd_topic), &paramsQOS0);
		if(publishCount > 0) {
			publishCount--;
		}
		printf("rc=%d, count=%d\n", rc, publishCount);
		if(publishCount == 0 && !infinitePublishFlag) {
			break;
		}
	}
I checked the codes in aws_iot_test_basic_connectivity.c. Not like my codes, the yield thread will sleep 500ms before each yield. So the yield cycle would be 500+100=600ms. This give a chance for publish thread to change the client state in yield thread sleeping time. And the publish thread will also keep trying to publish, not willing to success in just one shoot.  
It is clear that the client could only be in one state and there are no semaphores or conditions to synchronize the state change. So the only way to change the client state(then the ssl recv or send could really happen) would be keep trying. Is this how it works?
If I was right, I think maybe it does not make too much sense to split publish and yield in multi-thread.  Any way, the yield and publish could not happen at the same time.

**Comment by Iot-lilei** [comment]
Hi,

I think if the client is in CLIENT_STATE_CONNECTED_YIELD_IN_PROGRESS state, the aws_iot_mqtt_publish() will return MQTT_CLIENT_NOT_IDLE_ERROR because of the following lines in the function:
	clientState = aws_iot_mqtt_get_client_state(pClient);
	if(CLIENT_STATE_CONNECTED_IDLE != clientState && CLIENT_STATE_CONNECTED_WAIT_FOR_CB_RETURN != clientState) {
		FUNC_EXIT_RC(MQTT_CLIENT_NOT_IDLE_ERROR);
	}
So, if the yield thread locks the state in CLIENT_STATE_CONNECTED_YIELD_IN_PROGRESS, the publish thread will keep trying and will not exit the loop. 

Besides, putting a sleep before the yield works in the case that the publish loop keeps trying without any sleep.

Regards,
