### ISSUE TITLE
Library Version not updated

### ISSUE THREAD

**Issue by mukund-electronics** [aws/aws-iot-device-sdk-embedded-C#1581]
Library Version not updated include/aws_iot_version.h

 */
#ifndef SRC_UTILS_AWS_IOT_VERSION_H_
#define SRC_UTILS_AWS_IOT_VERSION_H_

/**
 * @brief MAJOR version, incremented when incompatible API changes are made.
 */
#define VERSION_MAJOR 3
/**
 * @brief MINOR version when functionality is added in a backwards-compatible manner.
 */
#define VERSION_MINOR 0
/**
 * @brief PATCH version when backwards-compatible bug fixes are made.
 */
#define VERSION_PATCH 1
/**
 * @brief TAG is an (optional) tag appended to the version if a more descriptive verion is needed.
 */
#define VERSION_TAG ""

**Comment by dan4thewin** [comment]
Hi, @mukund-electronics .
I can't seem to locate this file.  I'm wondering if this comes from before we adopted the date-based versioning scheme for the C SDK, or before we switched to using main as our default branch.

**Comment by mukund-electronics** [comment]
For example, in the sample

**Comment by aggarw13** [comment]
Hi @mukund-electronics

1. Thank you for sharing the links and pointing out the issue. The files you have shared belong to the v3.x series of the SDK, We will make sure to update the version in the tag we create for the v3 SDK series.  🙂

2. The date-based versioning is not valid for the v3.x series of the SDK. We started using date-based versioning only from the [202009.00](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/202009.00) release onwards. (**Note**: The date-based version releases are not backwards compatible with the v3.x SDK series.)

**Comment by archigup** [comment]
Hi, I am closing this issue. If you have further questions, please feel free to open a new issue.
