### ISSUE TITLE
Update MQTT client ID for all MQTT demos via Cmake

### ISSUE THREAD

**Issue by rpcme** [aws/aws-iot-device-sdk-embedded-C#1583]
Instead of having -DTHING_NAME cmake property to update the thing name for a subset of MQTT related demos, use -DCLIENT_ID property to change this value for all demos.

There are three reasons, and possibly more.
1. The change aligns the demos with best practice for the AWS IoT thing name to match the MQTT Client ID. 
2. The change makes life easier for developers needing to modify the client id for all MQTT demos.
3. The change applies consistent build and runtime behavior across all demos.

**Comment by yourslab** [comment]
The pull request to fix this issue has been merged
