### ISSUE TITLE
Emit configurable options to demo output

### ISSUE THREAD

**Issue by rpcme** [aws/aws-iot-device-sdk-embedded-C#1584]
It is useful to emit configurable options to standard output so the individual running the demo knows which options have been consumed by the build process.  For example, if the individual running the demo requires a specific client id, the individual cannot verify that the configuration has been made at runtime.

Specifically, I am running the mqtt_demo_mutual_auth demonstration and have changed the client id in the header file, but the expected behavior did not change. I have no knowledge if the configuration has been included in the build or if I made the configuration in the wrong place and I'm experiencing the same behavior.

**Comment by yourslab** [comment]
The pull request to fix this issue has been merged.
New output is as follows:
```
Using values in test_config.h to define the following macros for http_system_test:
ROOT_CA_CERT_PATH
SERVER_HOST
HTTPS_PORT
Found the following definitions for http_system_test: ROOT_CA_CERT_PATH, SERVER_HOST, HTTPS_PORT
All required definitions for http_system_test were found - Adding to default target.

Using values in test_config.h to define the following macros for mqtt_system_test:
BROKER_PORT
Using the passed CMake arguments to define the following macros for mqtt_system_test:
CLIENT_IDENTIFIER = three
BROKER_ENDPOINT = foo
Found the following definitions for mqtt_system_test: CLIENT_IDENTIFIER, BROKER_ENDPOINT, BROKER_PORT
WARNING: mqtt_system_test missing definitions for macros: ROOT_CA_CERT_PATH, CLIENT_CERT_PATH, CLIENT_PRIVATE_KEY_PATH
To run mqtt_system_test, define required macros in mqtt_system_test/demo_config.h.
```
