### ISSUE TITLE
Enquiry about C SDK for Windows

### ISSUE THREAD

**Issue by Abhi2109** [aws/aws-iot-device-sdk-embedded-C#1586]
Hi,
I was wondering if by any ways do we have support for Windows platform for C SDK or only Linux?

**Comment by yourslab** [comment]
It is possible to compile the SDK by using [Cygwin](https://cygwin.com/). It is not officially supported, but you would be able to build any demo from the SDK as a Windows executable. Theoretically, it should be possible to create a native Windows port by providing [platform code in the following directory for Windows](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/platform).

**Comment by muneebahmed10** [comment]
Hi @Abhi2109,

Did the [above](https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/1586#issuecomment-796416228) response answer your query? We will close this issue if we do no hear back from you.

Thanks

**Comment by yourslab** [comment]
Closing this issue due to staleness
