### ISSUE TITLE
declared without an initial value. see mqttSubscribe() in ota_demo

### ISSUE THREAD

**Issue by vikivivi** [aws/aws-iot-device-sdk-embedded-C#1588]
* The following 2 files has risk of comparing with undefined value.
  * `demos/ota/ota_demo_core_mqtt/ota_demo_core_mqtt.c`
    * function: `static OtaMqttStatus_t mqttSubscribe()`
  * `demos/ota/ota_demo_core_http/ota_demo_core_http.c`
    * function: `static OtaMqttStatus_t mqttSubscribe()`

* My comments are inline with the below code.
* git branch: main branch with commit hash 0f23637ad68ce33a9165c2c14102ff4e35e748b4

Question: Is there any issue with this code? It will only work well if pthread_mutex_lock() always take TRUE branch.

```C
static OtaMqttStatus_t mqttSubscribe()
{
  OtaMqttStatus_t otaRet = OtaMqttSuccess;
  MQTTStatus_t mqttStatus;  /* Declared without an initial value */

  ...
  if( pthread_mutex_lock( &mqttMutex ) == 0 )  /* In case taking FALSE branch */
  {
    mqttStatus = MQTT_Subscribe( ... ); /* mqttStatus will not updated */
  }
  else
  {
    LogError( ... );
  }

  ...
  if( mqttStatus != MQTTSuccess ) /* mqttStatus can be any random value if mutex_lock is FALSE */
  { 
    LogError( ( "Failed to send SUBSCRIBE ..." ) );
    otaRet = OtaMqttSubscribeFailed;
  }
  else
  {
    ...
  }

  registerSubscriptionManagerCallback( ... );  /* Still continue register callback if above failed ? */

  return otaRet;  /* May falsely returned OtaMqttSuccess without MQTT subscribed */
}
```

**Comment by pvyawaha** [comment]
Thank you for reporting this , the fix for this is merged https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/1593. Closing the issue now, please reopen for same topic or create a new one for other.
