### ISSUE TITLE
Assertion `globalSubscribePacketIdentifier == packetIdentifier' failed`

### ISSUE THREAD

**Issue by vijayrakesh13** [aws/aws-iot-device-sdk-embedded-C#1592]
Hi,

Some times I get an error as `shadow_demo_helpers.c:503: HandleOtherIncomingPacket: Assertion 'globalSubscribePacketIdentifier == packetIdentifier' failed` which results in exiting my application. After subscribing to a few topics I'm calling `receiveSingleIteration(&mqttContext, 100, true)` in while loop to receive mqtt messages. How to avoid above error?

Thanks & Regards,
Vijay Rakesh

**Comment by yourslab** [comment]
Hi Vijay,

Can you please try increasing the value of this macro?
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/shadow/shadow_demo_main/shadow_demo_helpers.c#L150

**Comment by vijayrakesh13** [comment]
Hi @yourslab,

Increased to 2s, but Is there any recommended value?

**Comment by yourslab** [comment]
It will always change depending on your latency to AWS IoT Core. You may have to use a larger value the farther you are from the AWS region.

**Comment by vijayrakesh13** [comment]
Ok, thank you. Just for conformation, subscribing to job topics within shadow demo example application will not raise `globalSubscribePacketIdentifier == packetIdentifier` error, right?

**Comment by yourslab** [comment]
It can occur if you receive the SUBACK of an earlier subscription attempt. It would be ideal to wait for the SUBACK of the current subscription attempt before moving on to the next.

**Comment by vijayrakesh13** [comment]
Thank you! @yourslab
