### ISSUE TITLE
Building the documentation and then copying the output to another location fails

### ISSUE THREAD

**Issue by beewoolie** [aws/aws-iot-device-sdk-embedded-C#1598]
Per the documentation:

`python3 tools/doxygen/generate_docs.py`

should build the documentation, which it does.  Then, copying 'docs/doxygen/output/html' to another location doesn't yield a working documentation tree.  There are hard-coded paths starting with /library/

**Comment by ravibhagavandas** [comment]
Hi @beewoolie 

To copy over the doxygen output to a different location, you can run the tool with the option `--zip` or `-z` as shown here:
https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/tools/doxygen#generate-doxygen-zipfile

The option will generate a zip file (provided that the doxygen runs without any warnings) named `doxygen.zip` in the directory where the tool is run.

You can unzip the file to any location of your choice.

**Comment by archigup** [comment]
Hi @beewoolie, I am resolving this issue. Feel free to open another issue if you have further questions on this topic.
