### ISSUE TITLE
shadow connect possible memory leak

### ISSUE THREAD

**Issue by dfszb** [aws/aws-iot-device-sdk-embedded-C#16]
It looks like the documentation does not describe the scenario when on startup the AWS connect call fails (because of network not being available for example).
I used a connect loop similar to the one mentioned in https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/13 however it looks like this will leak the handles that are supposed to be cleaned by iot_tls_destroy.
If add this call to 
IoT_Error_t aws_iot_mqtt_connect(MQTTConnectParams *pParams) {
...
	pahoRc = MQTTConnect(&c, &data);
	if(MQTT_NETWORK_ALREADY_CONNECTED_ERROR == pahoRc) {
		rc = NETWORK_ALREADY_CONNECTED;
	} else if(SUCCESS != pahoRc) {
        // this is a hack, but otherwise we'll leak those buffers on every connection attempt
		iot_tls_destroy(NULL); 
		rc = CONNECTION_ERROR;
	}
	return rc;
...
, then the memory leak goes away (i.e. memory usage no longer increases, and valgrind also seems to be reasonably happy).

**Comment by chaurah** [comment]
Hi,
     That is a very good suggestion. We have been tracking this issue internally as well. We already have a fix in place that is included with the next release of the Embedded C SDK. Please let us know if you have any further questions about this issue.

	 Thank you for using AWS IoT and the Embedded C SDK.

Rahul

**Comment by dfszb** [comment]
Thx, looking forward to see the changes (I assume they'll solve the problem in a cleaner way compared to my small hack).

**Comment by chaurah** [comment]
Hi,
   This has been fixed in v2.x of the SDK. Please download the latest release and let us know if you continue to see memory leaks.

Rahul
