### ISSUE TITLE
Questions on how to use MQTT lib in a C++ Object Oriented approach.

### ISSUE THREAD

**Issue by jcracine-cimeq** [aws/aws-iot-device-sdk-embedded-C#1600]
Hello,
For the last couple of days I've been working on trying to make a C++ wrapper to use in the project I'm currently on. I'm quite familiar with mosquitto's C++ wrapper so I've worked with MQTT libs a little. I've read the basic demo, but as I'm coding the wrapper, I have a hard time to properly code the whole subscription/unsubscription sections and the event callback because I don't quite grasp how to properly decipher the global variables used in the demos.

Here is some things I was wondering you could help me with:
1. Are the globalPacketIdentifiers (both subscribe and unsubscribe) related to a specific topic subscribed to?
2. I don't really understand how the globalSubAckStatus variable is used and why the variable is global.
3. Why the loggin_stack.h and the logging_levels.h are located in the demo folder if they are required by openssl_posix library.

I thank you in advance.

**Comment by leegeth** [comment]
Hi @jcracine-cimeq,

Thank you for bringing this question to our attention.  From your question, I assume that you are referring to the mqtt_demo_basic_tls. Please let us know if that is not the demo you are referring to.

With the above assumption, please find my answers to the question below.
This demo uses a single thread for the application. For example, in the demo for the subscriptions, the function call MQTT_Subscribe sends out an MQTT SUBSCRIBE packet to the broker. Following that, a call to MQTT_ProcessLoop attempts to read any incoming packets from the broker and a SUBACK packet may be received. This triggers the eventCallback in the same thread and checks if the SUBACK is received for the SUBSCRIBE packet itself by matching the packetIds of the SUBSCRIBE and SUBACK. See also the [design  diagram of the demo](https://docs.aws.amazon.com/embedded-csdk/202103.00/lib-ref/docs/doxygen/output/html/mqtt_demo.html).

1. In the demo, the global variables globalSubscribePacketIdentifier and globalUnsubscribePacketIdentifier are used to check if the ACKs are received for the SUBSCRIBE and UNSUBSCRIBE packets respectively. It is not specific to the topics, but a packet identifier is used for identifying the MQTT packets. In this specific case, it will be SUBSCRIBE and UNSUBSCRIBE packets. A single SUBSCRIBE or UNSUBSCRIBE packets can contain multiple topics, but in the demo it only uses one topic. Please refer to the [MQTT 3.1.1 specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718063) for more details about SUBSCRIBE packet.
2.  The global variable globalSubAckStatus is used for reading the status of the subscription returned by the broker in the SUBACK MQTT packet. The variable is made global as it is updated in the eventCallback and is used in the application main logic to decide if a SUBSCRIBE packet need to be resent for the subscription topic or not. If the subscription is not accepted by the broker, a SUBSCRIBE packet will be resent after a delay.
3. Logging stack headers can be defined by the application for the platform it is using. For example the [logging_stack.h](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/logging-stack/logging_stack.h) and [logging_levels.h](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/logging-stack/logging_levels.h) in this repository are used by the demo applications created for Linux platform.

**Comment by jcracine-cimeq** [comment]
Hi @leegeth,
This is indeed the demo I was talking about. Thank you for taking the time to answer my questions.

1. I understand better the role of the packetIdentifier now.
2. Ok, so in the case that there is more than one topic for subscription, globalSubAckStatus would need to be able to contain all of the status for each individual topic if I understood correctly.

**Comment by leegeth** [comment]
@jcracine-cimeq 

Thanks for your quick response. If there are a multiple topics in the SUBSCRIBE packet, a return code for each will be received in the same order as that of the topics sent in SUBSCRIBE packet. Please refer to the [MQTT 3.1.1 specification for the SUBACK packet](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718068) here for more details about the return codes. Hope this answers your question. Please let us know if you have more questions.

**Comment by jcracine-cimeq** [comment]
This answered my questions. So I'm all good for the moment. Thank you for the support.
