### ISSUE TITLE
Error while doing cmake

### ISSUE THREAD

**Issue by lpbittoo** [aws/aws-iot-device-sdk-embedded-C#1601]
[root@localhost aws-iot-device-sdk-embedded-C-main]# cmake -S. -Bbuild && cd build
CMake Error: The source directory "" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by ravibhagavandas** [comment]
Hi @lpbittoo,
Could you tell what version of cmake is used and on which platform (Linux/Windows/MACOS) are you building ?

Please note that the repo requires cmake version 3.2.0 or higher and as of now, only building on linux is supported.

**Comment by vikivivi** [comment]
@lpbittoo 
> CMake Error: The source directory "" does not exist.

Have you change directory into the source code directory before you run cmake ? The first 5 lines of file CMakeLists.txt from source code directory is shown.
```sh
cd aws-iot-device-sdk-embedded-C 
head -n5 ./CMakeLists.txt 
```
```text
# Project information.
cmake_minimum_required( VERSION 3.2.0 )
project( AwsIotDeviceSdkEmbeddedC
         VERSION 202103.00
         LANGUAGES C )
```

**Comment by muneebahmed10** [comment]
Hi @lpbittoo 

What version of `cmake` are you using? Can you try updating it?

Additionally, you shouldn't need to run CMake as root, the projects in this repository can be configured without needing root permissions.

**Comment by archigup** [comment]
Hi @lpbittoo, I'm resolving this issue. If you have more questions on this, please feel free to open another issue.
