### ISSUE TITLE
Fleet Provisioning with Latest C SDK

### ISSUE THREAD

**Issue by deepsworld** [aws/aws-iot-device-sdk-embedded-C#1604]
I am not able to find any provisioning related demos or APIs in the latest tag. However, I did find the API with source code in the v4_deprecated branch. Please provide your feedback on the below questions: 

Is there any alternatives that I can use in the latest tag? 

Do you think it is feasible to port that API to current version? 

Any other suggestion on fleet provisioning with C?

**Comment by aggarw13** [comment]
Hi @deepsworld, thank you for enquiry about a Fleet Provisioning library in the latest C-SDK.  
Yes, currently, there does not exist a library for the Fleet Provisioning library in the latest C-SDK `main` branch or releases from [202009.00](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/202009.00) onwards.

The Fleet Provisioning library in the `v4_beta_deprecated` branch is based on an older MQTT stack (present in that branch) that is not compatible with the newer `coreMQTT` library present in the latest C-SDK releases. Thereby, porting the old Fleet Provisioning library to the new MQTT stack can involve significant changes (though you can see our `aws/amazon-freertos` repository for reference on porting of old MQTT library to the `coreMQTT` library for reference [here](https://github.com/aws/amazon-freertos/tree/202012.00/libraries/c_sdk/standard/mqtt)). 

We do have a plan to provide a new library and demo(s) for using the Fleet Provisioning feature of IoT Core in C-SDK. Please keep an eye out for updates to the C-SDK repository.

**Comment by archigup** [comment]
Hi @deepsworld, I am resolving this issue. Feel free to open another issue if you have further questions on this topic.
