### ISSUE TITLE
How to configure TLS mutual authentication using PKCS11 engine

### ISSUE THREAD

**Issue by zlhk100** [aws/aws-iot-device-sdk-embedded-C#1609]
Hi Experts,

We develop security IOT solution using AWS IOT embedded C SDK to create TLS secure connection for MQTT and HTTPS.  TLS mutual authentication is used right now.  Unfortunately current SDK high level APIs take openssl credentials from Linux file as following code sequence.     How can we configure AWS SDK/openssl to use PKCS11 engine to access openssl credentials stored on PKCS11 based hardware secure storage and also what AWS SDK should we use in this case?

Look forward to your feedbacks and much appreciated!
Lei Zhou
            
    opensslCredentials.pRootCaPath =  sCredFiles[2]; // ROOT_CA_CERT_PATH;      
    opensslCredentials.pClientCertPath = sCredFiles[1]; //CLIENT_CERT_PATH;     
    opensslCredentials.pPrivateKeyPath = sCredFiles[3]; //CLIENT_PRIVATE_KEY_PATH;
    opensslCredentials.sniHostName = mIotHubCreds->mConnString; // AWS_IOT_ENDPOINT;
    opensslStatus = Openssl_Connect( &mNetworkContext,                          
                                         &serverInfo,                           
                                         &opensslCredentials,                   
                                         TRANSPORT_SEND_RECV_TIMEOUT_MS,        
                                         TRANSPORT_SEND_RECV_TIMEOUT_MS );_     
==================================================================

**Comment by zlhk100** [comment]
Any comments?   Thank you!

**Comment by paulbartell** [comment]
@zlhk100 : The CSDK does not currently have openssl engine support. You will need to modify the code a bit to accomplish this.

You'll need the [libp11](https://github.com/OpenSC/libp11) openssl engine, which will allow you to use openssl to perform public/private key operations using your HSM, while symmetric crypto operations will still occur using the 

Locate the relevant pkcs11 shared library for your HSM. I'll use softhsm2 as an example below, but this should work the same with any other pkcs11 module.

## Install prereqs
```
apt install openssl libengine-pkcs11-openssl libsofthsm2 gnutls-bin
```

## Initialize softhsm2
```
mkdir -p /etc/softhsm
mkdir -p ~/tokens
echo "directories.tokendir = $HOME/tokens" > /etc/softhsm/softhsm2.conf
echo "objectstore.backend = file" >> /etc/softhsm/softhsm2.conf
```

## initialize the token
```
softhsm2-util --init-token --slot 0 --label token1 --so-pin 12345 --pin 1234
```

## Generate the RSA key
```
p11tool --provider /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so --login --set-pin 1234 --generate-rsa --bits 2048 --label test-key
p11tool --provider /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so --login --set-pin 1234 --list-privkeys
```

## Determine the pkcs11 uri 
Use the output from from the call to --list-privkeys to determine a suitable PKCS11 URI. Add "pin-value" to avoid interactive login.
for example:
```
export PKCS11_URI="pkcs11:serial=c581129715faa4e1;token=token1;object=test-key;type=private;pin-value=1234"
```
## Generate a self signed certificate:
```
openssl req -engine pkcs11 -new -key $PKCS11_URI -keyform engine -out req.pem -text -x509 -subj "/CN=Testing123"
openssl x509 -engine pkcs11 -signkey $PKCS11_URI -keyform engine -in req.pem -out cert.pem
```

## Openssl engine API
You will need to configure openssl to use the correct engine. You can do so using either an openssl config file or entirely using the API:

You'll need to modify platform/posix/transport/src/openssl_posix.c by making the following changes:

### Add code similar to this to initialize the engine:
```
OPENSSL_init_crypto( OPENSSL_INIT_ENGINE_ALL_BUILTIN, NULL );

ENGINE * pk11 = ENGINE_by_id( "pkcs11" );
ENGINE_ctrl_cmd_string( pk11, "MODULE_PATH", "/usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so", 0 );
ENGINE_ctrl_cmd_string( pk11, "PIN", "1234", 0 );
ENGINE_init( pk11 );
```
The calls to OPENSSL_init_crypto and ENGINE_ctrl_cmd_string could be replaced by settings in your /etc/ssl/openssl.cnf


### Modify the setPrivateKey method to call the following:
```
SSL_CTX_set_client_cert_engine( pSslContext, pk11 ); // this line may not be required.
ENGINE_set_default( pk11, ENGINE_METHOD_ALL ); // Use the engine for all ciphers that the engine supports
ENGINE_set_default_RSA( pk11 ); // Or select specific ciphers
ENGINE_set_default_ECDH( pk11 );

EVP_PKEY* pkey = ENGINE_load_private_key( pk11, "pkcs11:serial=c581129715faa4e1;token=token1;object=test-key;type=private;pin-value=1234", NULL, NULL );
SSL_CTX_use_PrivateKey( pSslContext, pkey );
```

## Resources

The best references I've found regarding libpkcs11 and openssl engines are:

libp11 docs: https://github.com/OpenSC/libp11/blob/master/README.md
nginx: https://github.com/nginx/nginx/blob/master/src/event/ngx_event_openssl.c
curl: https://github.com/curl/curl/blob/b09c8ee15771c614c4bf3ddac893cdb12187c844/lib/vtls/openssl.c
openssl s_client: https://github.com/openssl/openssl/blob/master/apps/s_client.c.

**Comment by zlhk100** [comment]
Thanks @paulbartell for detailed reference code and information.  Totally make sense and will try the approach in our prototype.

More questions in same area:
       1>  In our use cases,  IOT devices will maintain multiple mutual-authN TLS connections on different ports using AWS CSDK.  1st TLS to AWS hosted MQTT broker on port 8883,  2nd TLS to proprietary service running out of local machine on port 5000, and 3rd TLS to another proprietary service on port 5003.      Does AWS CSDK expect/support this type of concurrent openssl connections assuming also pkcs11 engine integration to access underneath HSM for secret managements?
       2> Does AWS CSDK support TLS server mode?   eg.  On one of above TLS connection,  IOT device might need to listen for/accept incoming TLS connecting request, and provide certain proprietary service.   
             If it's not expected for AWS CSDK, any recommendation?    Consider IOT resource constraint and want to stick to AWS CSDK without pulling more 3rd party library eg. cURL for supporting this server mode.

Thanks in advance!
Lei

**Comment by paulbartell** [comment]
> Thanks @paulbartell for detailed reference code and information. Totally make sense and will try the approach in our prototype.
> 
> More questions in same area:
> 1> In our use cases, IOT devices will maintain multiple mutual-authN TLS connections on different ports using AWS CSDK. 1st TLS to AWS hosted MQTT broker on port 8883, 2nd TLS to proprietary service running out of local machine on port 5000, and 3rd TLS to another proprietary service on port 5003. Does AWS CSDK expect/support this type of concurrent openssl connections assuming also pkcs11 engine integration to access underneath HSM for secret managements?

This should be fully supported. You will need to allocate a separate openssl context for each connection. This means a separate call to Openssl_Connect and a separate NetworkContext_t for each TLS connection.

> 2> Does AWS CSDK support TLS server mode? eg. On one of above TLS connection, IOT device might need to listen for/accept incoming TLS connecting request, and provide certain proprietary service.
> If it's not expected for AWS CSDK, any recommendation? Consider IOT resource constraint and want to stick to AWS CSDK without pulling more 3rd party library eg. cURL for supporting this server mode.
> 

This library is intended primarily for devices that act as TCP clients, so listening on a socket is not supported by the API. Implementing this with the normal openssl  and linux socket api is not terribly complex. Here's an [example](https://wiki.openssl.org/index.php/Simple_TLS_Server) of how you might do so.

> Thanks in advance!
> Lei

**Comment by zlhk100** [comment]
Much appreciated @paulbartell for accurately answering my questions.    Have a great day,   Lei
