### ISSUE TITLE
libopenssl_posix.so: undefined symbol: TLS_client_method

### ISSUE THREAD

**Issue by una801** [aws/aws-iot-device-sdk-embedded-C#1611]
hi.
I crosscompile to put the AWS C SDK on the ARM board.
These errors occur when you insert the compiled executable into the board and run it.
openssl version is OpenSSL 1.0.2h 3 May 2016 It
I don't know what caused the error.
The compilation was already successful with this version of openssl, so I don't know why this error occurs.
When I did cmake, I erased the rt library file part from the cmakelist and compiled it. (I don't write it, but I keep getting errors when compiling) Is this the cause?
No matter how hard I look, I don't know what the problem is.
![image](https://user-images.githubusercontent.com/76464228/113253500-490ffe00-9300-11eb-9245-c78cdbe0acd4.png)

**Comment by vikivivi** [comment]
I can see similar behaviour if my Raspberry Pi target sysroot filesystem is installed with `libssl1.0-dev_1.0.2q-2_armhf.deb` and `libssl1.0.2_1.0.2q-2_armhf.deb`

Try to use a newer OpenSSL v1.1.1. This problems goes away when my Raspberry Pi target sysroot filesystem is installed with `libssl1.1_1.1.1d-0+deb10u6+rpt1_armhf.deb` and `libssl-dev_1.1.1d-0+deb10u6+rpt1_armhf.deb`. Perform grep on your target filesystem `/usr/include/openssl/ssl.h`

```sh
host$ grep -rn TLS_client_method ./
./usr/include/openssl/ssl.h:1869:#define SSLv23_client_method    TLS_client_method
./usr/include/openssl/ssl.h:1874:__owur const SSL_METHOD *TLS_client_method(void);
./usr/include/openssl/ssl.h:1909:__owur const SSL_METHOD *DTLS_client_method(void); /* DTLS 1.0 and 1.2 */
```

**Comment by yourslab** [comment]
Yes, as @vikivivi mentioned, `TLS_client_method` is only defined is OpenSSL 1.1 or later. You can, however, substitute the call with one of the equivalent functions from 1.0.2:
https://www.openssl.org/docs/man1.0.2/man3/SSLv3_method.html

**Comment by una801** [comment]
TLS_Client_Method()
Referring to the link you sent us, we changed it to TLSv1_client_method or TLSv1_2_client_method.

The symbol error doesn't come up.

`[INFO] [DEMO] [mqtt_demo_mutual_auth.c:628] Establishing a TLS session to a1pybjm6f2tb2x-ats.iot.ap-northeast-2.amazonaws.com:8883.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:603] Creation of a new SSL_CTX object failed.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:672] Failed to establish a TLS connection.
[WARN] [DEMO] [mqtt_demo_mutual_auth.c:649] Connection to the broker failed. Retrying connection after 188 ms backoff.
`
An error occurs that cannot be generated this way. How can we solve these errors?

There was no modification of the code because the demo package was compiled and inserted.
In the case of openssl version upgrade, the default-set openssl version within the ARM board is 1.0.2.h version and cannot be upgraded (which has been initialized before).;( )

The same version of the device succeeded in the test, what is the cause?

**Comment by una801** [comment]
I added SSL_Library_Init(); to a part of the openssl_posix.c file and those errors no longer occur.
(Changed TSL name)

There was only an error message saying that I couldn't connect because I didn't have a certificate, so I created a folder called certificates in the ARM device and put the certificates in it.

In doing so, these errors occur.
```
# ./mqtt_demo_mutual_auth 
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:628] Establishing a TLS session to a1pybjm6f2tb2x-ats.iot.ap-northeast-2.amazonaws.com:8883.
./mqtt_demo_mutual_auth: symbol lookup error: /usr/lib/libopenssl_posix.so: undefined symbol: SSL_set1_host

```

It also seems to be incompatible with openssl 1.0.2 version of function, just like the TLS_client above, so what should I change to?

**Comment by yourslab** [comment]
There is no similar function in 1.0.2. The function's responsibility is to perform hostname validation. If you need this functionality in 1.0.2, please refer to this link:
https://wiki.openssl.org/index.php/Hostname_validation

**Comment by vikivivi** [comment]
> In the case of openssl version upgrade, the default-set openssl version within the ARM board is 1.0.2.h version and cannot be upgraded

@una801 For your info, OpenSSL v1.0.2 is already End of Life (EOL) since December 31, 2019. There is no security fixes if vulnerabilities are found. Continue building IoT devices with EOL packages would be at risk. Just my 2 cents.

**Comment by yourslab** [comment]
Closing this issue as the original issue has been resolved. As recommended by @vikivivi, if you are expecting to use this application in production, please upgrade to 1.1.0 or above.
