### ISSUE TITLE
AWS IoT Jobs VS OTA Agent

### ISSUE THREAD

**Issue by ncohen17** [aws/aws-iot-device-sdk-embedded-C#1612]
Hi, 
I wanted to know what is the difference between the AWS IoT Jobs and OTA Update Agent examples demo provided in this repo ? 

Jobs:
https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/demos/jobs/jobs_demo_mosquitto

OTA:
https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/demos/ota

**Comment by archigup** [comment]
Hi @ncohen17,

The Jobs demo demonstrates the use of the [AWS IoT Jobs library](https://github.com/aws/Jobs-for-AWS-IoT-embedded-sdk). The library aids with using the [AWS IoT Jobs service](https://docs.aws.amazon.com/iot/latest/developerguide/iot-jobs.html) by providing functions to build and recognize the MQTT topic strings used for the Jobs service's [MQTT APIs](https://docs.aws.amazon.com/iot/latest/developerguide/jobs-mqtt-api.html). The Jobs service is used by OTA, but is more general. 

The OTA demo is for demonstrating the use of the [AWS IoT OTA library](https://github.com/aws/ota-for-aws-iot-embedded-sdk), which works with the [AWS IoT OTA Update service](https://docs.aws.amazon.com/freertos/latest/userguide/freertos-ota-dev.html). It provides functionality to manage notifications of newly available updates, download the updates, and perform cryptographic verification of the firmware updates.

**Comment by archigup** [comment]
Hi, closing this issue. Feel free to open a new issue if you have further questions on this topic.
