### ISSUE TITLE
how can i use  aws-iot-device-sdk-embedded-C/demos/mqtt/  demo to send sensor value to AWS

### ISSUE THREAD

**Issue by pragnesh036** [aws/aws-iot-device-sdk-embedded-C#1615]
I am using STM32MP157-DK2.  
I am successfully run the code of aws-iot-device-sdk-embedded-C/demos/mqtt/mqtt_demo_mutual_auth
But I need to send my sensor data to AWS using the demo code  
how can I use the MQTT Demo code to send my sensor data?
any idea about this
suggest any proper way to send my sensor data to AWS

**Comment by muneebahmed10** [comment]
Hi @pragnesh036,

Any data you want to send to AWS can be set as the [payload of a publish packet](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/5c43daf505c8f43c0a8b39264d8ad053a59d1086/demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c#L1235) and published to AWS IoT Core. Note that whichever device or service you want to receive your data will need to be subscribed to the [topic that you publish on](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/5c43daf505c8f43c0a8b39264d8ad053a59d1086/demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c#L1233). You should replace the topic and publish information in the demo with what is used by your application.

**Comment by muneebahmed10** [comment]
Hi @pragnesh036,

I will close this issue. Please open a new issue if you have any other questions.

Thank you
