### ISSUE TITLE
problem with migrating from sdk 3.0.1 to sdk 3.1.2

### ISSUE THREAD

**Issue by ClaudioBaldo** [aws/aws-iot-device-sdk-embedded-C#1616]
I am cross compiling the sdk to be implemented on a third party hardware, and I am having some issues with the openssl library (which is installed on my building machine "openssl is already the newest version (1.1.1f-1ubuntu2.3)").
Going in order, the problem is with the compiler not finding the include files in openssl_utest.c:
#include "mock_unistd_api.h"
#include "mock_openssl_api.h"
#include "mock_sockets_posix.h"
#include "mock_stdio_api.h"
**can`t find them anywhere**, but I can find the unistd_api.h, openssl_api.h, sockets_posix.h, stdio_api.h in the "mocks" folder, so I have changed the include to:
#include "mocks/unistd_api.h"
#include "mocks/openssl_api.h"
#include "sockets_posix.h"
#include "mocks/stdio_api.h"

After this the compiler will complain about redefinition in the  openssl_api.h:
struct ssl_st, etc...
which are already defined in my toolchain:
FX30S2/wp77-toolchain/sysroots/armv7a-neon-poky-linux-gnueabi/usr/include/openssl/ossl_typ.h

and also about implicit declarations of most of the functions used in the source openssl_utest.c:
Sockets_Connect_ExpectAnyArgsAndReturn( socketStatus ) for instance.

So my question is if the problem is with the toolchain not supporting the mocks and what work around do I have to this problem?

**Comment by abhidixi11** [comment]
Hello @ClaudioBaldo 
Thanks for reaching out. 
Are you using V3 CSDK or the latest SDK available? 
V3 CSDK is tagged here: https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v3.1.2 , which uses mbedTLS. 
Are you porting V3 SDK to work with openSSL ?  
Thanks!

**Comment by yourslab** [comment]
Is there a reason why you need to build the unit tests? Are you passing `-DBUILD_TESTS=1` to cmake?

**Comment by ClaudioBaldo** [comment]
I have been using the V3 CSDK (v3.0.1) with mbedTLS and just wanted to update to the latest, there is not real reason to port to openssl, also the target I am cross-compiling to only supports openssl v1.0.2 which may be a problem?
When checking the repository you have tagged, I see that the aws_iot_version.h shows version v3.0.1 while the repository is tagged as v3.1.2....

**Comment by yourslab** [comment]
The files you are describing in the original post only exist in 202009.00 and later. openssl_utest.c does not exist in any V3 distribution.

**Comment by ClaudioBaldo** [comment]
ok, I did clone the latest v3.1.2 for mbedTLS, is there any benefit of using the openssl instead? and if yes, is there a version which can be used with openssl v1.0.2?

**Comment by yourslab** [comment]
Not really much of an advantage. Actually, mbedTLS will likely utilize less memory than OpenSSL. Also, V3 does not support OpenSSL out of the box unless you provide your own implementation.

**Comment by ClaudioBaldo** [comment]
ok, what about the QOS2? I saw that implemented for the openssl but not for mbedTLS. MbedTLS only seems supporting QOS0 and QOS1.

**Comment by abhidixi11** [comment]
Hello @ClaudioBaldo 
>MbedTLS only seems supporting QOS0 and QOS1.

MQTT QOS is independent of OpenSSL or mbedTLS. So I'm not sure what exactly you mean.
The latest CSDK (main branch / 202103.00 release) supports QOS2, is that what you were indicating ? The latest C-SDK does not have mbedTLS port, but all the libraries (coreMQTT for MQTT) are independent of any TLS stack. If you provide your transport implementation, you will able use mbedTLS. 
Thanks.

**Comment by ClaudioBaldo** [comment]
Thanks

**Comment by yourslab** [comment]
Closing the issue. If you encounter any problems, feel free to open another.

**Comment by ClaudioBaldo** [comment]
It would fantastic if you could consider providing a branch of this sdk for aws to work with mbedTLS right away, as this new one works with openSSL "The latest CSDK (main branch / 202103.00 release) supports QOS2, is that what you were indicating ? The latest C-SDK does not have mbedTLS port".
Understand we can change the transport layer but it would save us time if we can get this already bundled and ready to go, one of the main reasons for us to work with aws is to avoid `heavy lifting` and to focus on our applicaiton`s development.
We will most likely look at this ourselves but with all the development still to go is not set as a priority.
just wanted to comment on this, sorry for being late and feel free to close this issue once again.

**Comment by abhidixi11** [comment]
Thanks for the feedback @ClaudioBaldo. We do have a port for mbedTLS in our [FreeRTOS repository](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS-Plus/Source/Application-Protocols/network_transport); which uses FreeRTOS-TCP.   Both CSDK and FreeRTOS repositories  use the exact same MQTT library.  OpenSSL is more common with Linux platforms so we have port for it here in CSDK. In future, we may consider having mbedTLS port in CSDK.
