### ISSUE TITLE
Question regarding JITR/ JITP 

### ISSUE THREAD

**Issue by mukesh-2538** [aws/aws-iot-device-sdk-embedded-C#1617]
I am planning for JITP/ JITR  process for my iot-device produced on scale.
According to AWS documents, we have to send a CA certificate along with the device certificate when connecting to the AWS- Iot core for the first time.
![image](https://user-images.githubusercontent.com/68813288/114807660-6e9f0c00-9dc4-11eb-86b6-adc8012d345b.png)

**Does the coremqtt library send the CA certificates along with the device cerficates?**
If not what is the procedure for doing this?

**Comment by vikivivi** [comment]
Does this help?
https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/
