### ISSUE TITLE
Some S3 has migrated from digicert BaltimoreCyberTrustRoot to Amazon Trust Services

### ISSUE THREAD

**Issue by vikivivi** [aws/aws-iot-device-sdk-embedded-C#1618]
Some S3 bucket from some of these AWS Regions (HTTPS: EU-WEST-3, EU-NORTH-1, ME-SOUTH-1, AP-NORTHEAST-3, AP-EAST-1, and US-GOV-EAST-1) has migrated from digicert BaltimoreCyberTrustRoot Root CA to use Amazon Trust Services root CA certificate (AmazonRootCA1.pem .. AmazonRootCA4.pem).

Reference: 
https://aws.amazon.com/blogs/storage/reminder-amazon-s3-and-amazon-cloudfront-migrating-service-certificates-to-amazon-trust-services-starting-march-23-2021/

You might want to update these demo with additional notes.
* demos/ota/ota_demo_core_http/
* demos/http/http_demo_s3_download/
* demos/http/http_demo_s3_download_multithreaded/
* demos/http/http_demo_s3_upload/

Or you may want to demonstrate concatenate these 2 root CA (BaltimoreCyberTrustRoot and AmazonRootCA1) into a single CA bundle?

**Comment by sukhmanm** [comment]
Hi @vikivivi,

Apologies for the late response -- thanks for your patience on this issue. 

Thank you for notifying us about the outdated certificate references in the aforementioned HTTP demos. We are working on updating all references to the Baltimore Cybertrust Root CA to highlight the migration to ATS certificates, as well as the [Starfield Root CA certificate](https://www.amazontrust.com/repository/SFSRootCAG2.pem) used for cross-signing. All demos you had identified will be updated accordingly. 

Let us know if you have any additional comments/questions on this topic. Thanks.

**Comment by vikivivi** [comment]
Hi @sukhmanm,

Just a note, in case someone implementing OTA download firmware from AWS-S3. With a single invalid certificate, the OTA procedure will be dead. It is worth using multiple CA certificates (in PEM format) and concatenate them together as CA-bundle for TLS in FreeRTOS implementation.

**Comment by sukhmanm** [comment]
Hi @vikivivi,

Unfortunately the current demos only load in the first certificate found in the file path specified. However, depending on the region in question, the update should only need to be made once. Alternatively, it may be possible to configure a custom  [CloudFront domain](https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-https-requests-s3/) with a S3 origin, in order to have more control of the certificates involved in TLS negotiation.

**Comment by sukhmanm** [comment]
Hi @vikivivi,

I'm going to close this ticket as there appear to be no further updates. Please feel free to open another ticket if you have any further questions or concerns regarding this topic. Thank you.
