### ISSUE TITLE
Long Shadow messages

### ISSUE THREAD

**Issue by mukesh-2538** [aws/aws-iot-device-sdk-embedded-C#1619]
I am using mqtt-mutual-auth-demo for receiving messages from a named shadow. 

I am able to receive small messages, but then the shadow document is big and lots of fields, my application fails. Is there a limit on the size of message received  in the demo code?  Mqtt has a limit of 128KB but shadow document is 1KB (Shadow has a limit of 8 KB).
If the shadow messages are long it is not invoking eventcallback().
I am using  shadowprefix/get/accepted to receive the document.
Could multiple nesting be a cause for this?

**Comment by boraozgen** [comment]
Did you try increasing the network buffer size?

**Comment by muneebahmed10** [comment]
Hi @mukesh-2538,

Can you try increasing the size of the [network buffer](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c#L124) when running the demo?

Thanks

**Comment by mukesh-2538** [comment]
Thankyou, Increasing the network buffer size worked.
