### ISSUE TITLE
How to generate documents with doxygen

### ISSUE THREAD

**Issue by tjeneh** [aws/aws-iot-device-sdk-embedded-C#1620]
Hello,

I am trying to generate documentation but keep running into errors / warning saying "warning: unable to resolve reference" and  "error: Tag file 'libraries/standard/coreMQTT/docs/doxygen/output/mqtt.tag' does not exist or is not a file"

output after running "doxygen docs/doxygen/config.doxyfile"

<img width="1212" alt="Screen Shot 2021-04-19 at 2 02 35 PM" src="https://user-images.githubusercontent.com/17261119/115282182-e6986980-a117-11eb-8f5b-9d27e430e468.png">

**Comment by muneebahmed10** [comment]
Hi @tjeneh,

The doxygen in the C SDK depends on the generated tag files for each submoduled library. To generate the doxygen output for the CSDK, you have to generate it for each library first. We wrote a [Python script](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/tools/doxygen) to do this for us, which you can invoke with
```
python3 tools/doxygen/generate_docs.py
```
with an optional `--zip` flag to create a zipfile.

Additionally, it looks like you're using the latest doxygen version 1.9+, while our configuration files were written with 1.8.20. Not all of the doxygen configuration files have been updated for 1.9, and there are some inconsistencies in the sidebar when using version 1.9.1, so I'd recommend downloading version 1.8.20 from [here](https://sourceforge.net/projects/doxygen/files/rel-1.8.20/). It looks like you might be using a Mac, so you can build it from source using CMake and place it in your `PATH` before `/usr/local/bin` (or wherever you have `doxygen` installed).

Let us know if you have further questions

**Comment by paulbartell** [comment]
@tjeneh I'm going to close this issue since it has been open for over a week. Feel free to re-open the issue if you need further assistance with generating doxygen documentation.
