### ISSUE TITLE
How can use this sdk in a STM32Cube IDE project?

### ISSUE THREAD

**Issue by lohenzoo** [aws/aws-iot-device-sdk-embedded-C#1622]
I'm working on a IOT project using AWS and a STM32f767ZI board using the STM32Cube IDE but I can't an example of how to load this sdk into the project to use it.

**Comment by paulbartell** [comment]
@lohenzoo We have an example project for the STM32f767ZI board targeting the ac6 / SW4STM32 development environment in the [amazon-freertos reference integration repository](https://github.com/aws/amazon-freertos/tree/master/projects/st/stm32l475_discovery/ac6 ).

You might try using the "import SW4STM32" option in STM32CubeIDE with one of the pre-made project files or by manually adding the .c files for each library as well as the associated ports and configuration files for each library.

The documentation for each library contains a porting guide which outlines the different configuration options available: https://github.com/aws/aws-iot-device-sdk-embedded-C.

For ST-Micro specific questions, the best place to get FreeRTOS-related support is the FreeRTOS forum [STMicro Partner section](https://forums.freertos.org/c/partners-sponsors/stmicroelectronics/30).

Feel free to create a forum post or re-open this issue if you need further assistance.
