### ISSUE TITLE
Download file 

### ISSUE THREAD

**Issue by Abhi2109** [aws/aws-iot-device-sdk-embedded-C#1623]
Hi,
I want to know can we download the file from AWS server?

**Comment by paulbartell** [comment]
@Abhi2109 Can you please clarify which file you are referring to?

**Comment by Abhi2109** [comment]
Let's say i have uploaded any file abc.jon (Just an example) to blob or whatever storage mechanism AWS supports , afterwards if i need to download that same file from AWS repositories can i do that?

**Comment by aggarw13** [comment]
Hi @Abhi2109, can you explain about the client platform where you want to download the file into from AWS? 
If your platform represents a micro-controller based device where you are developing an application in C, you can refer to our [HTTP S3 Download demo]() for an example of downloading a file from S3.

If your platform can use a more high level language (like C++, Java, Python), you can refer to the language-specific Device SDK mentioned here: https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html

**Comment by Abhi2109** [comment]
Do you can have sample code to upload the file ?

**Comment by Abhi2109** [comment]
I am interested in C as using extern i can use same functionalities/headers for C++ as well.

**Comment by paulbartell** [comment]
@Abhi2109 I believe this demo is similar to what you are looking for: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/202103.00/demos/http/http_demo_s3_upload/http_demo_s3_upload.c .

If you are running on linux, windows, or Apple OSX, you might find that the [AWS C++ SDK](https://github.com/aws/aws-sdk-cpp) and [example code](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/examples-s3-objects.html) better fits your use case.

**Comment by Abhi2109** [comment]
This AWS S3 resource is a part of AWS IoT Core?

**Comment by Abhi2109** [comment]
Ok.. I got it thanks for your help.
