### ISSUE TITLE
MQTT_ProcessLoop returned with status = MQTTRecvFailed.

### ISSUE THREAD

**Issue by mukesh-2538** [aws/aws-iot-device-sdk-embedded-C#1625]
I am modifying mqtt_mutual_auth demo code for my embedded application. 

**TASK:**
I want to subcribe to a list of topics (Count = 10)

`mqttStatus = MQTT_Subscribe( pMqttContext,
                                 pGlobalSubscriptionList,
                                 sizeof( pGlobalSubscriptionList ) / sizeof( MQTTSubscribeInfo_t ),
                                 globalSubscribePacketIdentifier );`
pGlobalSubcriptionList is populated with 10 topic names and their respective lengths.

**ISSUE:**
I am getting a MQTTrecvFailed status code while doing this.

**Experimentation:**
I tried subscribing to lesser number of topics instead of 10 at once. In this case my application is working perfectly.
The maximum limit till the application works without throwing MQTTrecvfailed message is **8**.
I have set my Network buffer size to 8KB.

**Questions:**

1. Is there a limitation from the COREMQTT library on number of subscription sent at once?
2. Is there an limitation on AWS IOT Core on number of subscriptions it can receive at once from the same client?
3. Is there any parameter i should tweak in my demo code to achieve this?

**Code structure:**

```
main()

{
    mqttinit();

    connect();    // this function has its own MQTT_processloop();

    subscribe(); // this function has its own MQTT_processloop();

    while(1)
    {
          MQTT_processloop();           // receive incoming publish messages.
    }
}
```

**Comment by paulbartell** [comment]
@mukesh-2538 
1) There is a limit on the number of outstanding messages waiting for acknowledgement from the server in coreMQTT. It is configurable using the MQTT_STATE_ARRAY_MAX_COUNT config item. See [core_mqtt_config_default.h](https://github.com/FreeRTOS/coreMQTT/blob/main/source/include/core_mqtt_config_defaults.h) for more details.

2) You can view the AWS IoT core limits on [this page](https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot). Note that "A single SUBSCRIBE request has a quota of 8 subscriptions.". This may be the limit you are running into.

3) You may be able to work around this limit by sending multiple SUBSCRIBE messages, each with a maximum of 8 topics.
