### ISSUE TITLE
esp32: Error(-12) connecting to axxxxxxxxxxxxx-ats.iot.us-east-2.amazonaws.com:8883

### ISSUE THREAD

**Issue by HenriqueLeal2910** [aws/aws-iot-device-sdk-embedded-C#1626]
I am following this project "https://aws.amazon.com/pt/blogs/iot/creating-object-recognition-with-espressif-esp32/",
but after upload in my Esp32 cam and following through the terminal this error always happens. Unfortunately, I don't have much knowledge, I tried to find some error during the process, but I couldn't.
I thought it was a problem in esp32, but I managed to use it in Arduino.idle and accessing the camera through Http.
Thanks for any help.

Terminal-
␛[0;32mI (28) boot: compile time 23:23:52␛[0m
␛[0;32mI (28) boot: chip revision: 1␛[0m
␛[0;32mI (32) boot_comm: chip revision: 1, min. bootloader chip revision: 0␛[0m
␛[0;32mI (39) qio_mode: Enabling default flash chip QIO␛[0m
␛[0;32mI (44) boot.esp32: SPI Speed      : 40MHz␛[0m
␛[0;32mI (49) boot.esp32: SPI Mode       : QIO␛[0m
␛[0;32mI (53) boot.esp32: SPI Flash Size : 4MB␛[0m
␛[0;32mI (58) boot: Enabling RNG early entropy source...␛[0m
␛[0;32mI (63) boot: Partition Table:␛[0m
␛[0;32mI (67) boot: ## Label            Usage          Type ST Offset   Length␛[0m
␛[0;32mI (74) boot:  0 nvs              WiFi data        01 02 00009000 00006000␛[0m
␛[0;32mI (82) boot:  1 phy_init         RF data          01 01 0000f000 00001000␛[0m
␛[0;32mI (89) boot:  2 factory          factory app      00 00 00010000 00100000␛[0m
␛[0;32mI (97) boot: End of partition table␛[0m
␛[0;32mI (101) boot_comm: chip revision: 1, min. application chip revision: 0␛[0m
␛[0;32mI (108) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x272f8 (160504) map␛[0m
␛[0;32mI (175) esp_image: segment 1: paddr=0x00037320 vaddr=0x3ffb0000 size=0x04414 ( 17428) load␛[0m
␛[0;32mI (183) esp_image: segment 2: paddr=0x0003b73c vaddr=0x40080000 size=0x00404 (  1028) load␛[0m
␛[0;32mI (184) esp_image: segment 3: paddr=0x0003bb48 vaddr=0x40080404 size=0x044d0 ( 17616) load␛[0m
␛[0;32mI (199) esp_image: segment 4: paddr=0x00040020 vaddr=0x400d0020 size=0xa12f8 (660216) map␛[0m
␛[0;32mI (440) esp_image: segment 5: paddr=0x000e1320 vaddr=0x400848d4 size=0x1763c ( 95804) load␛[0m
␛[0;32mI (497) boot: Loaded app from partition at offset 0x10000␛[0m
␛[0;32mI (497) boot: Disabling RNG early entropy source...␛[0m
␛[0;32mI (498) psram: This chip is ESP32-D0WD␛[0m
␛[0;32mI (503) spiram: Found 64MBit SPI RAM device␛[0m
␛[0;32mI (507) spiram: SPI RAM mode: flash 40m sram 40m␛[0m
␛[0;32mI (512) spiram: PSRAM initialized, cache is in low/high (2-core) mode.␛[0m
␛[0;32mI (519) cpu_start: Pro cpu up.␛[0m
␛[0;32mI (523) cpu_start: Application information:␛[0m
␛[0;32mI (528) cpu_start: Project name:     sample-aws-iot␛[0m
␛[0;32mI (533) cpu_start: App version:      1␛[0m
␛[0;32mI (538) cpu_start: Compile time:     Apr 27 2021 23:22:54␛[0m
␛[0;32mI (544) cpu_start: ELF file SHA256:  213a1a768f817a19...␛[0m
␛[0;32mI (550) cpu_start: ESP-IDF:          3.40200.210118␛[0m
␛[0;32mI (555) cpu_start: Starting app cpu, entry point is 0x40082838␛[0m
␛[0;32mI (0) cpu_start: App cpu up.␛[0m
␛[0;32mI (1446) spiram: SPI SRAM memory test OK␛[0m
␛[0;32mI (1447) heap_init: Initializing. RAM available for dynamic allocation:␛[0m
␛[0;32mI (1447) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM␛[0m
␛[0;32mI (1453) heap_init: At 3FFBAB58 len 000254A8 (149 KiB): DRAM␛[0m
␛[0;32mI (1460) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM␛[0m
␛[0;32mI (1466) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM␛[0m
␛[0;32mI (1472) heap_init: At 4009BF10 len 000040F0 (16 KiB): IRAM␛[0m
␛[0;32mI (1479) cpu_start: Pro cpu start user code␛[0m
␛[0;32mI (1484) spiram: Adding pool of 4096K of external SPI memory to heap allocator␛[0m
␛[0;32mI (1505) spi_flash: detected chip: generic␛[0m
␛[0;32mI (1505) spi_flash: flash io: qio␛[0m
␛[0;32mI (1505) cpu_start: Starting scheduler on PRO CPU.␛[0m
␛[0;32mI (0) cpu_start: Starting scheduler on APP CPU.␛[0m
␛[0;32mI (1513) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations␛[0m
␛[0;32mI (1563) esp32: Base MAC Address read from EFUSE BLK0.␛[0m
␛[0;32mI (1573) esp32: 0x3ffb444c   10 52 1c 69 0e e0                                 |.R.i..|␛[0m
I (1583) wifi:wifi driver task: 3ffcb3fc, prio:23, stack:6656, core=0
␛[0;32mI (1583) system_api: Base MAC address is not set␛[0m
␛[0;32mI (1583) system_api: read default base MAC address from EFUSE␛[0m
I (1613) wifi:wifi firmware version: 1865b55
I (1613) wifi:wifi certification version: v7.0
I (1613) wifi:config NVS flash: enabled
I (1613) wifi:config nano formating: disabled
I (1613) wifi:Init data frame dynamic rx buffer num: 32
I (1623) wifi:Init management frame dynamic rx buffer num: 32
I (1623) wifi:Init management short buffer num: 32
I (1633) wifi:Init static tx buffer num: 16
I (1633) wifi:Init tx cache buffer num: 32
I (1643) wifi:Init static rx buffer size: 1600
I (1643) wifi:Init static rx buffer num: 10
I (1643) wifi:Init dynamic rx buffer num: 32
␛[0;32mI (1653) wifi_init: rx ba win: 6␛[0m
␛[0;32mI (1653) wifi_init: tcpip mbox: 32␛[0m
␛[0;32mI (1663) wifi_init: udp mbox: 6␛[0m
␛[0;32mI (1663) wifi_init: tcp mbox: 6␛[0m
␛[0;32mI (1663) wifi_init: tcp tx win: 5744␛[0m
␛[0;32mI (1673) wifi_init: tcp rx win: 5744␛[0m
␛[0;32mI (1673) wifi_init: tcp mss: 1440␛[0m
␛[0;32mI (1683) wifi_init: WiFi IRAM OP enabled␛[0m
␛[0;32mI (1683) wifi_init: WiFi RX IRAM OP enabled␛[0m
␛[0;32mI (1693) esp32: Setting WiFi configuration SSID CasaLeal...␛[0m
␛[0;32mI (1793) phy: phy_version: 4500, 0cd6843, Sep 17 2020, 15:37:07, 0, 0␛[0m
I (1793) wifi:mode : sta (10:52:1c:69:0e:e0)
␛[0;32mI (1793) sccb: pin_sda 26 pin_scl 27
␛[0m
␛[0;32mI (1803) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (1903) gpio: GPIO[35]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (1903) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (1913) gpio: GPIO[39]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
I (1913) wifi:new:<7,1>, old:<1,0>, ap:<255,255>, sta:<7,1>, prof:1
I (2773) wifi:state: init -> auth (b0)
␛[0;32mI (2773) gpio: GPIO[36]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (2773) gpio: GPIO[21]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (2783) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (2793) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
I (2803) wifi:state: auth -> assoc (0)
␛[0;32mI (2803) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
I (2813) wifi:state: assoc -> run (10)
␛[0;32mI (2813) gpio: GPIO[25]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (2823) gpio: GPIO[23]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (2833) gpio: GPIO[22]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (2843) camera: Allocating 1 frame buffers (234 KB total)␛[0m
I (2853) wifi:connected with CasaLeal, aid = 1, channel 7, 40U, bssid = ac:84:c6:a2:98:22
I (2863) wifi:security: WPA2-PSK, phy: bgn, rssi: -35
I (2863) wifi:pm start, type: 1

I (2873) wifi:AP's beacon interval = 102400 us, DTIM period = 1
␛[0;32mI (2903) camera: Allocating 234 KB frame buffer in OnBoard RAM␛[0m
␛[0;32mI (3123) esp32: AWS IoT SDK Version 3.0.1-␛[0m
␛[0;32mI (3123) esp32: Starting server on port: '80'␛[0m
␛[0;32mI (3123) esp32: Registering URI handlers␛[0m
␛[0;32mI (4073) esp_netif_handlers: sta ip: 192.168.68.124, mask: 255.255.255.0, gw: 192.168.68.1␛[0m
␛[0;32mI (4073) esp32: Connecting to AWS...␛[0m
␛[0;31mE (7903) esp32: Error(-12) connecting to aixxxxxxxxxxxxxxxxx-ats.iot.us-east-2.amazonaws.com:8883␛[0m

-

**Comment by sukhmanm** [comment]
Hi @HenriqueLeal2910,

Could you confirm that you have pasted the correct `private.pem.key` and `certificate.pem.crt` files into the certs directory? As well as attached the correct policy to`myesp32-cam-example,`as described [here](https://aws.amazon.com/pt/blogs/iot/creating-object-recognition-with-espressif-esp32/#:~:text=creating%20an%20aws%20iot%20device)? The error code -12 (`NETWORK_SSL_READ_ERROR`) suggests a generic network error is being returned from `mbedtls_ssl_read().`If it's not a credential or setup issue, would you be able to provide the complete error log for the connection attempt? Thanks.

**Comment by HenriqueLeal2910** [comment]
Hello @sukhmanm,
Sorry for the delay, I ended up deleting everything and doing the steps again, I don't know what could have been. But unfortunately I ran into another problem, in the Monitor it always freezes in the `Registering URI handler`.

![image](https://user-images.githubusercontent.com/83354670/117213283-cb914f00-add1-11eb-8f39-745602a29e19.png)

thanks

**Comment by aggarw13** [comment]
Hi @HenriqueLeal2910, sorry for the delay in responding. Are you still facing an issue with the issue of connection failure?

**Comment by HenriqueLeal2910** [comment]
Hello @aggarw13 , no problem. Yes unfortunately! Still freazing on `Registering URI handler`.

Regarts,
leal Henrique

**Comment by yourslab** [comment]
Hi @HenriqueLeal2910. Freezing occurs when when starting the HTTP server provided by the ESP-IDF. I would suggest opening an issue in their repository: https://github.com/espressif/esp-idf

**Comment by yourslab** [comment]
I'll be closing this issue but if you find a problem with the Embedded C SDK, please feel free to open another issue here
