### ISSUE TITLE
MQTT Session(TLS Session) Killed

### ISSUE THREAD

**Issue by una801** [aws/aws-iot-device-sdk-embedded-C#1627]
Hello
Among AWS-IoT-Embedded-C SDK, we are using IoT Core using MQTT-Mutual-auth.

I added the parts I wanted to send to the Publish section and reduced the delay time.

In about 10 minutes, Killed pops up in TLS Session connection during Mqtt reconnection.
(MQTT_PUBLISH_COUNT_PER_LOOP has been set to 20.)

Is there anything else I need to set up?
In what circumstances do these errors and unreachable situations occur?

Error Like :
```
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:1043] Sending Publish to the MQTT topic Dpico/ElecBus/Bus1.
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:1043] Sending Publish to the MQTT topic Dpico/ElecBus/Bus1.
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:462] Incoming QOS : 1.
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:476] Incoming Publish Topic Name: Dpico/ElecBus/Bus1 matches subscribed topic.
Incoming Publish message Packet Id is 1.
Incoming Publish Message : 987F17F3  gangwon1565  A0 00 65 0D 0A 00 35 0D.


[INFO] [DEMO] [mqtt_demo_mutual_auth.c:1067] Unsubscribing from the MQTT topic Dpico/ElecBus/Bus1.
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:791] UNSUBSCRIBE sent for topic Dpico/ElecBus/Bus1 to broker.


[INFO] [DEMO] [mqtt_demo_mutual_auth.c:462] Incoming QOS : 1.
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:476] Incoming Publish Topic Name: Dpico/ElecBus/Bus1 matches subscribed topic.
Incoming Publish message Packet Id is 2.
Incoming Publish Message : 8CF602A7  gangwon1565  91 80 7F 7F 79 C0 00 04.


[INFO] [DEMO] [mqtt_demo_mutual_auth.c:1086] Disconnecting the MQTT connection with a1pybjm6f2tb2x-ats.iot.ap-northeast-2.amazonaws.com.
[INFO] [MQTT] [core_mqtt.c:2129] Disconnected from the broker.
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:279] Establishing a TLS session to a1pybjm6f2tb2x-ats.iot.ap-northeast-2.amazonaws.com:8883.
Killed
```
Log Info in core_mqtt or demo version was annotated due to device overload.

**Comment by sukhmanm** [comment]
Hi @una801,

Does the still error occur when the delay isn't reduced? It seems there are no explicit error logs in the output provided - it may be that the size of the network buffer is insufficient and requires modification in the [configs](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/8aebd12f8353e4cfaa040daeb0a2603aa0950be7/demos/mqtt/mqtt_demo_mutual_auth/demo_config.h#L162). 

The MQTT disconnect is expected behavior in the demo after all publishes are sent, but the lack of this [success log](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/8aebd12f8353e4cfaa040daeb0a2603aa0950be7/demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c#L1568) as well as any error logs suggests a possible network error. Could you verify if the above modifications affect the output?

**Comment by una801** [comment]
I'm sorry, I didn't understand what you meant when the delay didn't decrease.

This error causes the mqtt session to kill, with a delay in reading the data (there is no problem with the data being sent). 
Previously, the mutual_auth demo that outputs hello world does not detect this phenomenon, but it seems that there is a problem while reading the can data received by the device on the payload by adding socket CAN communication part.
I don't even know where the message "killed" comes from.

Do you mean the overload of the device that runs it in data transfer to the IOT Core?
(Due to power consumption?)
Would it be better if I send the data to QoS0?

**Comment by sukhmanm** [comment]
@una801, could you please specify which code version and platform you are using?

> I'm sorry, I didn't understand what you meant when the delay didn't decrease.

Apologies if I was unclear. In your initial comment you had mentioned you "reduced the delay time" -- which delay were you referring to specifically? Was it `DELAY_BETWEEN_PUBLISHES_SECONDS`? My question earlier was just aiming to clarify if this abrupt failure is occurring even when your delay changes aren't applied to the demo -- can you confirm if this is true?

> This error causes the mqtt session to kill, with a delay in reading the data (there is no problem with the data being sent).

Could you elaborate on the observed "delay in reading the data" (specifically, what is "data" referencing here)? If you are referring to the receipt of ACK packets, some "delay" can be expected as`MQTT_ProcessLoop()`will wait for a response from the broker (up to`MQTT_PROCESS_LOOP_TIMEOUT_MS`). `MQTT_ProcessLoop()`returns various codes for failed network send/recv, invalid packets, etc. if it encounters an error. Can you confirm that there is no error returned from this function?

**Comment by una801** [comment]
I'm sorry. I was embarrassed because it was such a sudden error that I left a question.
First, I cross-compile this mutual_auth demo in arm format and put it on the ARM board to test it.

openssl version is 1.1.1d and the environment that was crosscompiled is ubuntu 16.04.(Use version 16 due to GLIBC version of ARM board.)

I'll show you the code I modified and the code.
First of all, I modified the delay time for the define part.
#define MAX_OUTGOING_PUBLISHES              ( 5U )

```
#define MQTT_PACKET_ID_INVALID              ( ( uint16_t ) 0U )

#define MQTT_PROCESS_LOOP_TIMEOUT_MS        ( 500U )

#define MQTT_KEEP_ALIVE_INTERVAL_SECONDS    ( 60U )

#define DELAY_BETWEEN_PUBLISHES_SECONDS     ( 1U )

#define MQTT_PUBLISH_COUNT_PER_LOOP         ( 10U )

#define MQTT_SUBPUB_LOOP_DELAY_SECONDS      ( 5U )
```

Instead of dealing with delay Seconds as a define, we split the time into smaller pieces using the usleep function.
(Publish and main side)

Next is the code part.

```
static int publishToTopic( MQTTContext_t * pMqttContext )
{
	int returnStatus = EXIT_SUCCESS;
	MQTTStatus_t mqttStatus = MQTTSuccess;
	uint8_t publishIndex = MAX_OUTGOING_PUBLISHES;
	uint32_t publishCount = 0;
	const uint32_t maxPublishCount = MQTT_PUBLISH_COUNT_PER_LOOP;	
	char message[1024]={0x00, };
	int s, i;
	int nbytes;
	struct sockaddr_can addr;
	struct ifreq ifr;
	struct can_frame frame;
	int j;
	char *canData;
	char temp[3];
	char canId[10];
	char id1[] = "98F101D0";
	char id2[]="98F103D0";
	char id3[]="8CF606A6";
	char id4[]="98F105D0";
	char id5[]="98F106D0";
	char id6[]="98F205F3";
	char id7[]="98F501F0";
	char id8[]="98F502F0";
	char id9[]="98F503F0";
	char id10[]="98F210F3";
	char id11[]="98F211F3";
	char id12[]="98F212F3";
	char id13[]="98F213F3";
	char id14[]="98F201F3";
	char id15[]="98F202F3";
	char id16[]="98F206F3";
	char id17[]="98F207F3";
	char id18[]="98F208F3";
	char id19[]="98F209F3";
	char id20[]="98F20AF3";
	char id21[]="98F20BF3";
	char id22[]="98F20DF3";
	char id23[]="985F17F3";
	char id24[]="987F17F3";
	char id25[]="986017F3";
	char id26[]="8CF602A1";
	char id27[]="8CF601A0";
	char id28[]="985017F3";
	char id29[]="98F701F5";
	char id30[]="8CF603A2";
	char id31[]="98FF2B49";
	char id32[]="98F20CF3";
	char id33[]="98F221F3";
	char id34[]="98F222F3";
	char id35[]="988017F3";
	char id36[]="98A917F3";
	char id37[]="98F203F3";
	char id38[]="98F214F3";
	char id39[]="980018F3";
	char id40[]="98F20EF3";
	char id41[]="98F104D0";
	char id42[]="8CF605A5";
	char id43[]="8CF605A4";
	char id44[]="8CF601A7";
	char id45[]="8CF602A7";
	char id46[]="8CF603A7";
	char id47[]="8CF609A9";
	char serial[]="gangwon1565";

	if((s=socket(PF_CAN, SOCK_RAW, CAN_RAW))<0){
		perror("Socket");
		return 1;
	}

	strcpy(ifr.ifr_name, "can0");
	ioctl(s, SIOCGIFINDEX, &ifr);

	memset(&addr, 0, sizeof(addr));
	addr.can_family=AF_CAN;
	addr.can_ifindex=ifr.ifr_ifindex;

	if(bind(s,(struct sockaddr*)&addr, sizeof(addr))<0)    {
		perror("Bind");
		return 1;
	}


	assert( pMqttContext != NULL );

	returnStatus = getNextFreeIndexForOutgoingPublishes( &publishIndex );

	if( returnStatus == EXIT_FAILURE )
	{
		LogError( ( "Unable to find a free spot for outgoing PUBLISH message.\n\n" ) );
	}
	else
	{

		canData=malloc(sizeof(char)*100);
		nbytes=read(s,&frame,sizeof(struct can_frame));

		if(nbytes<0){
			perror("Read");
			return 1;
		}
		sprintf(canId, "%X", frame.can_id);
		strcpy(canData, canId);
		strcat(canData, "  ");
		strcat(canData, serial);
		strcat(canData, "  ");
		sprintf(temp,"%02X", frame.data[0]);
		strcat(canData, temp);
		for(j=1;j<frame.can_dlc;j++){
			sprintf(temp,"%02X",frame.data[j]);
			strcat(canData, " ");
			strcat(canData,temp);
		}			


		outgoingPublishPackets[ publishIndex ].pubInfo.qos = MQTTQoS0;
		outgoingPublishPackets[ publishIndex ].pubInfo.pTopicName = MQTT_EXAMPLE_TOPIC;
		outgoingPublishPackets[ publishIndex ].pubInfo.topicNameLength = MQTT_EXAMPLE_TOPIC_LENGTH;
		outgoingPublishPackets[ publishIndex ].pubInfo.pPayload = canData;
		outgoingPublishPackets[ publishIndex ].pubInfo.payloadLength = sizeof(char)*140;;
		outgoingPublishPackets[ publishIndex ].packetId = MQTT_GetPacketId( pMqttContext );

		mqttStatus = MQTT_Publish( pMqttContext,
				&outgoingPublishPackets[ publishIndex ].pubInfo,
				outgoingPublishPackets[ publishIndex ].packetId );

		free(canData);

		if( mqttStatus != MQTTSuccess )
		{
			LogError( ( "Failed to send PUBLISH packet to broker with error = %s.",
						MQTT_Status_strerror( mqttStatus ) ) );
			cleanupOutgoingPublishAt( publishIndex );
			returnStatus = EXIT_FAILURE;
		}
		else
		{
			//   LogInfo( ( "PUBLISH sent for topic %.*s to broker with packet ID %u.\n\n",
			//              MQTT_EXAMPLE_TOPIC_LENGTH,
			//             MQTT_EXAMPLE_TOPIC,
			//              outgoingPublishPackets[ publishIndex ].packetId ) );
		}

		usleep(150000);	


	}

	return returnStatus;
}
```

Many of the IDs declared char in the PublishtoTopic function must be passed to the IoT Core through ID parsing (if the id is true), but because the mqtt session continues to be cut off, only the id has been declared with char and other conditional statements such as if statements have been erased.


```
static int subscribePublishLoop( MQTTContext_t * pMqttContext )
{
	int returnStatus = EXIT_SUCCESS;
	MQTTStatus_t mqttStatus = MQTTSuccess;
	uint32_t publishCount = 0;
	const uint32_t maxPublishCount = MQTT_PUBLISH_COUNT_PER_LOOP;

	assert( pMqttContext != NULL );

	if( returnStatus == EXIT_SUCCESS )
	{

		LogInfo( ( "Subscribing to the MQTT topic %.*s.",
					MQTT_EXAMPLE_TOPIC_LENGTH,
					MQTT_EXAMPLE_TOPIC ) );
		returnStatus = subscribeToTopic( pMqttContext );
	}

	if( returnStatus == EXIT_SUCCESS )
	{

		mqttStatus = MQTT_ProcessLoop( pMqttContext, MQTT_PROCESS_LOOP_TIMEOUT_MS );

		if( mqttStatus != MQTTSuccess )
		{
			returnStatus = EXIT_FAILURE;
			LogError( ( "MQTT_ProcessLoop returned with status = %s.",
						MQTT_Status_strerror( mqttStatus ) ) );
		}
	}


	if( ( returnStatus == EXIT_SUCCESS ) && ( globalSubAckStatus == MQTTSubAckFailure ) )
	{

		//  LogInfo( ( "Server rejected initial subscription request. Attempting to re-subscribe to topic %.*s.",
		//             MQTT_EXAMPLE_TOPIC_LENGTH,
		//            MQTT_EXAMPLE_TOPIC ) );
		returnStatus = handleResubscribe( pMqttContext );
	}

	if( returnStatus == EXIT_SUCCESS )
	{

		for( publishCount = 0; publishCount < maxPublishCount; publishCount++ )
		{
			//   LogInfo( ( "Sending Publish to the MQTT topic %.*s.",
			//             MQTT_EXAMPLE_TOPIC_LENGTH,
			//             MQTT_EXAMPLE_TOPIC ) );
			returnStatus = publishToTopic( pMqttContext );

			mqttStatus = MQTT_ProcessLoop( pMqttContext, MQTT_PROCESS_LOOP_TIMEOUT_MS );


			if( mqttStatus != MQTTSuccess )
			{
				LogError( ( "MQTT_ProcessLoop returned with status = %s.",
							MQTT_Status_strerror( mqttStatus ) ) );
				returnStatus = EXIT_FAILURE;
				break;
			}

			//     LogInfo( ( "Delay before continuing to next iteration.\n\n" ) );

			usleep( 150000 );
		}
	}

	if( returnStatus == EXIT_SUCCESS )
	{
		//     LogInfo( ( "Unsubscribing from the MQTT topic %.*s.",
		//                MQTT_EXAMPLE_TOPIC_LENGTH,
		//               MQTT_EXAMPLE_TOPIC ) );
		returnStatus = unsubscribeFromTopic( pMqttContext );
	}

	if( returnStatus == EXIT_SUCCESS )
	{

		mqttStatus = MQTT_ProcessLoop( pMqttContext, MQTT_PROCESS_LOOP_TIMEOUT_MS );

		if( mqttStatus != MQTTSuccess )
		{
			returnStatus = EXIT_FAILURE;
			LogError( ( "MQTT_ProcessLoop returned with status = %s.",
						MQTT_Status_strerror( mqttStatus ) ) );
		}
	}

	//  LogInfo( ( "Disconnecting the MQTT connection with %.*s.",
	//             AWS_IOT_ENDPOINT_LENGTH,
	//            AWS_IOT_ENDPOINT ) );

	if( returnStatus == EXIT_FAILURE )
	{

		( void ) disconnectMqttSession( pMqttContext );
	}
	else
	{
		returnStatus = disconnectMqttSession( pMqttContext );
	}

	globalSubAckStatus = MQTTSubAckFailure;

	return returnStatus;
}

/*-----------------------------------------------------------*/

int main( int argc,
		char ** argv )
{
	int returnStatus = EXIT_SUCCESS;
	MQTTContext_t mqttContext = { 0 };
	NetworkContext_t networkContext = { 0 };
	OpensslParams_t opensslParams = { 0 };
	bool clientSessionPresent = false, brokerSessionPresent = false;
	struct timespec tp;

	( void ) argc;
	( void ) argv;

	networkContext.pParams = &opensslParams;


	( void ) clock_gettime( CLOCK_REALTIME, &tp );

	srand( tp.tv_nsec );

	returnStatus = initializeMqtt( &mqttContext, &networkContext );

	if( returnStatus == EXIT_SUCCESS )
	{
		for( ; ; )
		{

			returnStatus = connectToServerWithBackoffRetries( &networkContext, &mqttContext, &clientSessionPresent, &brokerSessionPresent );

			if( returnStatus == EXIT_FAILURE )
			{

				LogError( ( "Failed to connect to MQTT broker %.*s.",
							AWS_IOT_ENDPOINT_LENGTH,
							AWS_IOT_ENDPOINT ) );
			}
			else
			{

				clientSessionPresent = true;


				if( brokerSessionPresent == true )
				{
					//  LogInfo( ( "An MQTT session with broker is re-established. "
					//             "Resending unacked publishes." ) );

					returnStatus = handlePublishResend( &mqttContext );
				}
				else
				{
					//  LogInfo( ( "A clean MQTT connection is established."
					//             " Cleaning up all the stored outgoing publishes.\n\n" ) );

					cleanupOutgoingPublishes();
				}


				returnStatus = subscribePublishLoop( &mqttContext );
			}

			if( returnStatus == EXIT_SUCCESS )
			{

				//     LogInfo( ( "Demo completed successfully." ) );
			}

			( void ) Openssl_Disconnect( &networkContext );

			//  LogInfo( ( "Short delay before starting the next iteration....\n" ) );
			usleep( 200000 );
		}
	}

	return returnStatus;
}
```
Except inside the PublishToTopic function that sends direct data, only the Delay time was modified in the SubPubLoop and Main function.

When CAN data is received from Socket CAN and CAN Port set up on the device, as in the Publish function, the data is sent to the IoT Core.
This was what Delay Reading Data meant.

Despite continuous sending CAN Data without any problems, I couldn't read CAN Data from the device, and suddenly Mqtt Session was killed.

However, after several tests, this is one of the reasons for Mqtt Killed, and in some tests, mqtt Disconnect and re-connect may result in a TLS connection failure and mqtt being killed in the end for a variety of reasons.
(The maximum connection time with the IoT Core was approximately 10 minutes, and then killed.)

As a result, I suspect that my device, which is not a code problem, has been overloaded in receiving and handing over data.
I don't know if this has ever occurred to other users, but I wonder if it's better to communicate using Qos0, which consumes less power, or modify the Network Buffer.
(Actually, I don't know exactly what network buffer does.)

Or is it possible to overload the delay too short? (1.5 seconds, 2 seconds...)

**Comment by aggarw13** [comment]
Hi @una801, thank you for sharing the code snippet you're testing with.
It looks like you're facing 3 different forms of failure:
1. >[ERROR] [DEMO] [mqtt_demo_mutual_auth.c:888] Unable to find a free spot for outgoing PUBLISH message.
This error message means that application isn't receiving PUBACK response packets for the MQTT Publish messages sent (through `MQTT_Publish` API), and thus, the array holding record of all PUBLISH messages attempted, **outgoingPublishPackets**, isn't being cleared.

The issue can be from either the timeout used for `MQTT_ProcessLoop` call being insufficient (as the call after `publishToTopic` is responsible for receiving PUBACK as well as incoming Publish) OR the network receive buffer being full to be able to receive the PUBACK.
How often do you see this issue?
 
2. >[INFO] [DEMO] [mqtt_demo_mutual_auth.c:278] Establishing a TLS session to a1pybjm6f2tb2x-ats.iot.ap-northeast-2.amazonaws.com:8883.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:269] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:672] Failed to establish a TLS connection.
[WARN] [DEMO] [mqtt_demo_mutual_auth.c:313] Connection to the broker failed. Retrying connection after 754 ms backoff.
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:278] Establishing a TLS session to a1pybjm6f2tb2x-ats.iot.ap-northeast-2.amazonaws.com:8883.
Killed

The presence of **Killed** in Linux environment seems like a signal from the operating system to kill the demo application if the application isn't taking too many resources (like memory).

>When CAN data is received from Socket CAN and CAN Port set up on the device, as in the Publish function, the data is sent to the IoT Core.
This was what Delay Reading Data meant.

It seems like your test application creates a new socket in each call to `publishToTopic` but there isn't any cleanup of the created socket, thereby, potentially causing a lot of memory leak (as each loop involves 10 calls to the `publishToTopic`, thereby, generating 10 sockets per loop). 

Can you check with re-running your tests with a socket close logic in the `publishToTopic` function?

**Comment by una801** [comment]
Wow!!
The cause was there.
Unlimited socket generation included in the repeat statement was the cause of overload.

Thank you very much. Thanks to the kind and detailed explanation, I was able to solve the error!

Let me close the issue.
Be happy!

**Comment by aggarw13** [comment]
I'm glad that adding the cleanup logic fixed the issues for you! 😀
