### ISSUE TITLE
SSL_read failed: ErrorStatus=DH lib

### ISSUE THREAD

**Issue by jcracine-cimeq** [aws/aws-iot-device-sdk-embedded-C#1629]
Hi, I'm currently working on a C++ wrapper around the SDK for a project and after a while, I start getting these error messages in my methods that handle the republishing and resubscribing (basically the same as [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/8aebd12f8353e4cfaa040daeb0a2603aa0950be7/demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c#L1333)). If I wait longer, the communication just stop working between my Raspberry Pi and the Thing on AWS IoT Core.

Here is what the error logs look like:
`[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:761] Failed to receive data over network: SSL_read failed: ErrorStatus=DH lib. `
`[AwsMqttCommunication] MQTT Process returned with error status: MQTTRecvFailed`

I search online for an answer, but that wasn't fruitful.
Thanks in advance.

**Comment by mukesh-2538** [comment]
Do you have multipe threads running in your code?

**Comment by jcracine-cimeq** [comment]
I think I do. I'm using this SDK along with the C++ wrapper for Mosquitto, and if I recall, the library handle all the loop processing in a background thread. Is it because the SDK isn't thread-safe?

**Comment by mukesh-2538** [comment]
Yes, this is the most probable reason for the failure.

**Comment by jcracine-cimeq** [comment]
I'll do some tests to verify if this was the cause. I noticed [this C++ SDK repository](https://github.com/aws/aws-iot-device-sdk-cpp) as I was delving for informations. Could this be a long term, viable alternative of the C SDK?

**Comment by alfred2g** [comment]
HI @jcracine-cimeq,
The C-SDK is intended for embedded systems with focus on small devices with limited resources.
The C++ SDK is intended for larger systems where resources are somewhat abundant.

**Comment by jcracine-cimeq** [comment]
> HI @jcracine-cimeq,
> The C-SDK is intended for embedded systems with focus on small devices with limited resources.
> The C++ SDK is intended for larger systems where resources are somewhat abundant.

Ok, and I imagine a Single Board Computer would work kinda well with the later, right?

**Comment by abhidixi11** [comment]
Hello @jcracine-cimeq 
The failure you have seeing, is stemming from the network. It is most likely due to idle MQTT connection. The keep-alive period may be expiring and AWS IoT core is probably disconnecting MQTT connection.  
What is the keep alive timeout value  have you set ?

**Comment by aggarw13** [comment]
Hi @jcracine-cimeq, am checking in to see whether you are still facing the SSL read issue? 

If yes, does your application periodically call the `MQTT_ProcessLoop` function in the C++ wrapper for executing the keep-alive functionality? If your application has time periods of no communication with the IoT Core broker for more than the keep-alive period, then it is required to call the `MQTT_ProcessLoop` to make sure that that `PINGREQ` packet is sent out by the library to the broker in less than the keep-alive period to keep the connection alive.

**Comment by jcracine-cimeq** [comment]
Hi @aggarw13. I'm still having the SSL read issue. I can confirm I'm calling MQTT_ProcessLoop periodically. I'm still working on things but I think the reason stems from my app using multithreading, so I'm working on making my wrapper thread-safe.

**Comment by aggarw13** [comment]
@jcracine-cimeq, one suggestion to ascertain whether multi-threading is the cause of the issue can be by testing the wrapper only in a single threaded application and seeing whether you see the same error.

**Comment by yourslab** [comment]
Hi @jcracine-cimeq. Do you still have any issues after making the wrapper thread-safe?

**Comment by yourslab** [comment]
I'm closing this issue now since we haven't heard back in a while but please feel free to re-open if needed
