### ISSUE TITLE
NVS partition size in application

### ISSUE THREAD

**Issue by hvishu** [aws/aws-iot-device-sdk-embedded-C#163]
Is there a way to get the NVS partition size from the application (from source code of examples/get-started/hello_world/main/hello_world_main.c

**Comment by gordonwang0** [comment]
Hi @hvishu,

If your board manufacturer provides a function for checking NVS partition size, you can call that from the application.  This SDK does not have that functionality.

**Comment by hvishu** [comment]
We only produce the board for our product.  Using Partition.csv (custom partition table), the size of the NVS is allocated.  I just wanted not to hardcode the NVS partition size into the application.  That's why I was checking for any interfaces that can be used by the application to get the partition size.
Guess esp_partition_find_first does return esp_partition_t, which contains the partition size, need to check whether it works.

**Comment by gordonwang0** [comment]
Hi @hvishu,

You can try using those functions.  But this seems to be an Espressif question, not directly related to this SDK.  Please raise a question with Espressif for more help on this.  Closing issue.
