### ISSUE TITLE
"mqtt_demo_mutual_auth" demo Compile error

### ISSUE THREAD

**Issue by naluckstar** [aws/aws-iot-device-sdk-embedded-C#1632]
The problem points are as follows:

root@hlk:/home/hlk/Desktop/aws/aws-iot-device-sdk-embedded-C/build# make help | grep demo
... http_demo_s3_download
... http_demo_plaintext
... http_demo_mutual_auth
... http_demo_s3_upload
... http_demo_s3_download_multithreaded
... http_demo_basic_tls
... shadow_demo_main
... pkcs11_demo_objects
... pkcs11_demo_management_and_rng
... pkcs11_demo_sign_and_verify
... pkcs11_demo_mechanisms_and_digests
... ota_demo_core_http
... ota_demo_core_mqtt
... mqtt_demo_serializer
... mqtt_demo_mutual_auth
... mqtt_demo_subscription_manager
... mqtt_demo_plaintext
... mqtt_demo_basic_tls
... defender_demo
... jobs_demo_mosquitto
root@hlk:/home/hlk/Desktop/aws/aws-iot-device-sdk-embedded-C/build# make mqtt_demo_mutual_auth
[ 33%] Built target sockets_posix
[ 66%] Built target openssl_posix
[ 66%] Built target clock_posix
Scanning dependencies of target mqtt_demo_mutual_auth
[100%] Building C object demos/mqtt/mqtt_demo_mutual_auth/CMakeFiles/mqtt_demo_mutual_auth.dir/mqtt_demo_mutual_auth.c.o
In file included from /home/hlk/Desktop/aws/aws-iot-device-sdk-embedded-C/demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c:63:0:
/home/hlk/Desktop/aws/aws-iot-device-sdk-embedded-C/demos/mqtt/mqtt_demo_mutual_auth/demo_config.h:105:0: warning: "CLIENT_CERT_PATH" redefined
 #define CLIENT_CERT_PATH    "certificates/a920ff033b-certificate.pem.crt"
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from /home/hlk/Desktop/aws/aws-iot-device-sdk-embedded-C/demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c:63:0:
/home/hlk/Desktop/aws/aws-iot-device-sdk-embedded-C/demos/mqtt/mqtt_demo_mutual_auth/demo_config.h:117:0: warning: "CLIENT_PRIVATE_KEY_PATH" redefined
 #define CLIENT_PRIVATE_KEY_PATH    "certificates/a920ff033b-private.pem.key"
 ^
<command-line>:0:0: note: this is the location of the previous definition
[100%] Building C object demos/mqtt/mqtt_demo_mutual_auth/CMakeFiles/mqtt_demo_mutual_auth.dir/__/__/__/libraries/standard/coreMQTT/source/core_mqtt.c.o
[100%] Building C object demos/mqtt/mqtt_demo_mutual_auth/CMakeFiles/mqtt_demo_mutual_auth.dir/__/__/__/libraries/standard/coreMQTT/source/core_mqtt_state.c.o
[100%] Building C object demos/mqtt/mqtt_demo_mutual_auth/CMakeFiles/mqtt_demo_mutual_auth.dir/__/__/__/libraries/standard/coreMQTT/source/core_mqtt_serializer.c.o
[100%] Building C object demos/mqtt/mqtt_demo_mutual_auth/CMakeFiles/mqtt_demo_mutual_auth.dir/__/__/__/libraries/standard/backoffAlgorithm/source/backoff_algorithm.c.o
[100%] Linking C executable ../../../bin/mqtt_demo_mutual_auth
../../../lib/libopenssl_posix.so: undefined reference to `TLS_client_method'
../../../lib/libopenssl_posix.so: undefined reference to `SSL_set1_host'
../../../lib/libopenssl_posix.so: undefined reference to `SSL_set_default_read_buffer_len'
collect2: error: ld returned 1 exit status
demos/mqtt/mqtt_demo_mutual_auth/CMakeFiles/mqtt_demo_mutual_auth.dir/build.make:201: recipe for target 'bin/mqtt_demo_mutual_auth' failed
make[3]: *** [bin/mqtt_demo_mutual_auth] Error 1
CMakeFiles/Makefile2:1636: recipe for target 'demos/mqtt/mqtt_demo_mutual_auth/CMakeFiles/mqtt_demo_mutual_auth.dir/all' failed
make[2]: *** [demos/mqtt/mqtt_demo_mutual_auth/CMakeFiles/mqtt_demo_mutual_auth.dir/all] Error 2
CMakeFiles/Makefile2:1648: recipe for target 'demos/mqtt/mqtt_demo_mutual_auth/CMakeFiles/mqtt_demo_mutual_auth.dir/rule' failed
make[1]: *** [demos/mqtt/mqtt_demo_mutual_auth/CMakeFiles/mqtt_demo_mutual_auth.dir/rule] Error 2
Makefile:552: recipe for target 'mqtt_demo_mutual_auth' failed
make: *** [mqtt_demo_mutual_auth] Error 2
root@hlk:/home/hlk/Desktop/aws/aws-iot-device-sdk-embedded-C/build#

What's the problem？
1.SDK: https://github.com/aws/aws-iot-device-sdk-embedded-C/releases/tag/202103.00
2.Reference documents: https://docs.aws.amazon.com/zh_cn/iot/latest/developerguide/iot-embedded-c-sdk.html

**Comment by naluckstar** [comment]
Thank you very much for your help. The problem has been solved, but your web tutorial needs to be updated. The command "sudo apt get install libssl dev" gets version 1.0.2, which is really problematic.

**Comment by aggarw13** [comment]
Hi @naluckstar, thank you for pointing the issue with the default installation. 
I tried reproducing your issue on Docker containers for Ubuntu 21.04, 18.04 and 16.04 but each of them obtained OpenSSL version 1.1.1 (after updating the sources) for `apt-get install libssl-dev`. 
Can you share the details of your environment that is causing the `apt-get install libssl-dev` to install v1.0.2?

**Comment by yourslab** [comment]
Seems like this issue has been inactive for a while so I will be closing it. If you have further inquiries, please feel free to open another.
