### ISSUE TITLE
How do I compile and generate a static library

### ISSUE THREAD

**Issue by Kelephant** [aws/aws-iot-device-sdk-embedded-C#1637]
I generated the project files as follows, but I want to generate static libraries during compilation (such as libclock_posix.a, libopenssl_posix.a), what should I do? I know this can be done by modifying the Makefile, but I wonder if the project has parameters to automatically generate static libraries

**Here is my compilation process**
export CC=mips-linux-uclibc-gnu-gcc 
export CXX=mips-linux-uclibc-gnu-g++ 
export AR=mips-linux-uclibc-gnu-ar

mkdir build && cd build

cmake .. -DOPENSSL_INCLUDE_DIR=/home/wqk/aws/output/include/openssl -DOPENSSL_LIBRARIES=/home/wqk/aws/output/lib -DOPENSSL_CRYPTO_LIBRARY=/home/wqk/aws/output/lib/libcrypto.so -DOPENSSL_SSL_LIBRARY=/home/wqk/aws/output/lib/libssl.so -DBUILD_SHARED_LIBS=ON -DLIB_RT=/opt/mips-gcc472-glibc216-64bit/mips-linux-gnu/libc/usr/lib/librt.so -DOPENSSL_ROOT_DIR=/home/wqk/aws/output/include -DCMAKE_INSTALL_RPATH=/home/wqk/aws/output/lib

**Comment by aggarw13** [comment]
Hi @KevinIoT, for building libraries as static archives, we expose a `BUILD_SHARED_LIBRARIES` Cmake variable as can be seen [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/202103.00/CMakeLists.txt#L54-L57)

In the CMake command you have shared, you just need to make sure to set the variable to off as `-DBUILD_SHARED_LIBRARIES=OFF` which will configure the generate build configuration to only build `.a` libraries/

**Comment by KevinIoT** [comment]
Thank you for your answer!  I use this parameter, but after I make, I still generate a dynamic library. I want to get the static library files of the following three libraries. What should I do？

**Comment by Kelephant** [comment]
> Hi @KevinIoT, for building libraries as static archives, we expose a `BUILD_SHARED_LIBRARIES` Cmake variable as can be seen [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/202103.00/CMakeLists.txt#L54-L57).
> 
> In the CMake command you have shared, you just need to make sure to set the variable to `OFF` as `-DBUILD_SHARED_LIBRARIES=OFF` which will configure the generated Makefiles to only build `.a` libraries.
> 
> Hope that helps

Thank you for your answer @aggarw13 ! When I manually set the ALLOW_SHARED_LIBRARIES variable of cmakelist file to off, I received the following errors

`CMake Error at platform/posix/CMakeLists.txt:14 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "clock_posix".


CMake Error at platform/posix/transport/CMakeLists.txt:45 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "openssl_posix".


CMake Error at tools/cmake/install.cmake:130 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "aws_iot_defender".
Call Stack (most recent call first):
  CMakeLists.txt:129 (include)


CMake Error at tools/cmake/install.cmake:130 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "aws_iot_shadow".
Call Stack (most recent call first):
  CMakeLists.txt:129 (include)


CMake Error at tools/cmake/install.cmake:130 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "aws_iot_jobs".
Call Stack (most recent call first):
  CMakeLists.txt:129 (include)`

**Comment by aggarw13** [comment]
> Thank you for your answer @aggarw13 ! When I manually set the ALLOW_SHARED_LIBRARIES variable of cmakelist file to off, I received the following errors

Can you try with a clean build directory to make sure that use of `-DBUILD_SHARED_LIBRARIES=OFF` CMake parameter does not work for you?

For the issues relating to installation, can you share the exact CMake commands you're using so that I can reproduce the issue?

**Comment by aggarw13** [comment]
@Kelephant, I tested installing libraries built as static archives and noticed an issue with our CMake configuration for `install` target for static archive library builds. 
I have opened a PR #1641 to fix the missing support. Can you try the change and let us know if it resolves the erros you are seeing?

**Comment by Kelephant** [comment]
@aggarw13 I am relatively new to cmake. I just used your solution and the verification passed, thank you for your help!
