### ISSUE TITLE
Cross platform supporting for Windows 10.

### ISSUE THREAD

**Issue by zlhk100** [aws/aws-iot-device-sdk-embedded-C#1638]
We are integrating aws iot  csdk in our security application to do secure mqtt/https/tls client/pkcs#11 for tls mutual authN.  The designing goal for us targets at cross platform portability with proper modularization between OS/platform independent and PAL just like the way aws IOT cSDK does.

Currently we have our application up running on Linux based OS.   Next step we plan to bring up the software stack on Windows 10 to support equivalent sets of functionalities as on Linux (eg. secure mqtt/https/tls client/pkcs#11 for tls mutual authN).   

Would much appreciate your recommendations on Windows 10 bringing up strategy?   eg.
1>.  How to bring up mqtt/https mutual authN?

Regards,
Lei

**Comment by yourslab** [comment]
This has been asked before in the following thread:
https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/1586

Copying my answer from there:

> It is possible to create a native Windows port by providing [platform code in the following directory](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/platform) for Windows. Essentially, substituting the [POSIX calls](https://man7.org/linux/man-pages/man2/socket.2.html) to [WinSockets calls](https://docs.microsoft.com/en-us/windows/win32/api/Nspapi/nf-nspapi-getaddressbynamea).
> 
> Another alternative is to compile the SDK for Windows by using [Cygwin](https://cygwin.com/), which maps the POSIX calls used by the SDK into Windows API calls. It is not officially supported, but you would be able to build any demo from the SDK as a Windows executable.
>

**Comment by yourslab** [comment]
Hi, I'll be closing this issue now as it's been inactive for a while but if you have any follow-up inquiries, please feel free to open another issue.
