### ISSUE TITLE
API aws_iot_mqtt_subscribe() don't support to define topic name in stack memory

### ISSUE THREAD

**Issue by tidyjiang8** [aws/aws-iot-device-sdk-embedded-C#164]
Hi,
The API `aws_iot_mqtt_subscribe()` is used to subscribe some topic, and its 2nd parameter is the topic name, but I found that if I define topic name in stack, like this
``` c
void test(AWS_IoT_Client *client)
{
    char topic_name[128];
    IoT_Error_t rc = FAILURE;

    memset(topic_name, 0, sizeof(topic_name));
    strcpy(topic_name, "$aws/things/MyIoTButton/shadow/update/delta");
    rc = aws_iot_mqtt_subscribe(client, topic_name, strlen(topic_len), xxx, xxx);
    /// rc == SUCCESS, but xxx_cb will not be called when the topic is published at most time
}
``` 
Then, even thought its return code indicates SUCCESS, there is a great possibility that `xxx_cb` will not be called when the topic is published.

But If I define topic name like this, 
``` python
void test(AWS_IoT_Client *client)
{
    aws_iot_mqtt_subscribe(client, "$aws/things/MyIoTButton/shadow/update/delta", strlen("$aws/things/MyIoTButton/shadow/update/delta"), xxx, xxx);
}
```
The `xxx_cb` will always be called when the topic is published.

I think its not reasonable,

**Comment by huguesBouvier** [comment]
Hi,

You are correct, this is an issue. Thank you very much for reporting it!

Best,

Hugues

**Comment by tidyjiang8** [comment]
yes, that's the root caurse

**Comment by gordonwang0** [comment]
Hi @tidyjiang8,

We added a note in the documentation about stack parameters needing to remain in scope during an API call, #175.  A true fix to this problem (copying parameters) isn't planned at this time.  Closing issue.
