### ISSUE TITLE
Is there any document about ota_demo_core_mqtt

### ISSUE THREAD

**Issue by Kelephant** [aws/aws-iot-device-sdk-embedded-C#1640]
Is there any document about ota_demo_core_mqtt?  I want to know the role of this demo and OTA's work guide

**Comment by yourslab** [comment]
A good place to start is the [Getting Started section of the README.md](https://github.com/aws/aws-iot-device-sdk-embedded-C#getting-started) with emphasis on [Prerequisites for the AWS Over-The-Air Update (OTA) demos](https://github.com/aws/aws-iot-device-sdk-embedded-C#prerequisites-for-the-aws-over-the-air-update-ota-demos).

**Comment by Kelephant** [comment]
@yourslab When I configure and run ota_mqtt_demo_core according to the method of the document, the following error is reported. What should I do?

**errors**
`
[INFO] [MQTT] [core_mqtt.c:886] Packet received. ReceivedBytes=2.
[INFO] [MQTT] [core_mqtt_serializer.c:970] CONNACK session present bit not set.
[INFO] [MQTT] [core_mqtt_serializer.c:912] Connection accepted.
[INFO] [MQTT] [core_mqtt.c:1563] Received MQTT CONNACK successfully from broker.
[INFO] [MQTT] [core_mqtt.c:1829] MQTT connection established with the broker.
[INFO] [DEMO] [ota_demo_core_mqtt.c:1098] MQTT connection successfully established with broker.


[ERROR] [OTA] [ota_os_posix.c:136] Failed to send event to OTA Event Queue: mq_send returned error: OtaOsStatus_t=129 ,errno=Function not implemented
[ERROR] [OTA] [ota.c:2951] Failed to add even message to OTA event queue: send returned error: OtaOsStatus_t=OtaOsEventQueueSendFailed
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
[ERROR] [OTA] [ota_os_posix.c:169] Failed to receive OTA Event: mq_reqeive returned error: OtaOsStatus_t=130 ,errno=Function not implemented
`

**Comment by yourslab** [comment]
Can you please share details about the environment you are using? It's likely that this error is caused when `CONFIG_POSIX_MQUEUE=y` is not set in the kernel config.

**Comment by Kelephant** [comment]
@yourslab After I recompiled the kernel, MQ_ Open is working properly. However, the demo is still unable to download the S3 file. The operation is as follows：

[root@Ingenic-uc1_1:iot]# ./ota_demo_core_mqtt 
[INFO] [DEMO] [ota_demo_core_mqtt.c:1508] OTA over MQTT demo, Application version 1.9.2
[ERROR] [OTA] [ota_os_posix.c:94] >>>>>>>>>>>>>>>> OTA_QUEUE_NAME:/mqueue

[INFO] [DEMO] [ota_demo_core_mqtt.c:983] Establishing a TLS session to a2do2a7gpc6nwp-ats.iot.us-west-2.amazonaws.com:8883.
[INFO] [DEMO] [ota_demo_core_mqtt.c:1132] Creating an MQTT connection to a2do2a7gpc6nwp-ats.iot.us-west-2.amazonaws.com.
[INFO] [MQTT] [core_mqtt.c:886] Packet received. ReceivedBytes=2.
[INFO] [MQTT] [core_mqtt_serializer.c:970] CONNACK session present bit not set.
[INFO] [MQTT] [core_mqtt_serializer.c:912] Connection accepted.
[INFO] [MQTT] [core_mqtt.c:1563] Received MQTT CONNACK successfully from broker.
[INFO] [MQTT] [core_mqtt.c:1829] MQTT connection established with the broker.
[INFO] [DEMO] [ota_demo_core_mqtt.c:1098] MQTT connection successfully established with broker.


[INFO] [OTA] [ota.c:2839] Current State=[RequestingJob], Event=[Start], New state=[RequestingJob]
[INFO] [DEMO] [ota_demo_core_mqtt.c:1295] SUBSCRIBE topic $aws/things/testclient/jobs/notify-next to broker.


[INFO] [OTA] [ota_mqtt.c:381] Subscribed to MQTT topic: $aws/things/testclient/jobs/notify-next
[INFO] [MQTT] [core_mqtt.c:886] Packet received. ReceivedBytes=3.
[INFO] [DEMO] [ota_demo_core_mqtt.c:831] Received SUBACK.


[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [MQTT] [core_mqtt.c:886] Packet received. ReceivedBytes=2.
[INFO] [MQTT] [core_mqtt.c:1162] Ack packet deserialized with result: MQTTSuccess.
[INFO] [MQTT] [core_mqtt.c:1175] State record updated. New state=MQTTPublishDone.
[INFO] [DEMO] [ota_demo_core_mqtt.c:848] PUBACK received for packet id 2.


[INFO] [OTA] [ota.c:2839] Current State=[WaitingForJob], Event=[RequestJobDocument], New state=[WaitingForJob]
[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [MQTT] [core_mqtt.c:886] Packet received. ReceivedBytes=100.
[INFO] [MQTT] [core_mqtt.c:1045] De-serialized incoming PUBLISH packet: DeserializerResult=MQTTSuccess.
[INFO] [MQTT] [core_mqtt.c:1058] State record updated. New state=MQTTPublishDone.
[INFO] [DEMO] [mqtt_subscription_manager.c:91] Invoking subscription callback of matching topic filter: TopicFilter=$aws/things/+/jobs/#, TopicName=$aws/things/testclient/jobs/$next/get/accepted
[INFO] [OTA] [ota.c:2240] No active job available in received job document: OtaJobParseErr_t=OtaJobParseErrNoActiveJobs
[INFO] [OTA] [ota.c:2839] Current State=[WaitingForJob], Event=[ReceivedJobDocument], New state=[CreatingFile]
[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0

**Comment by Kelephant** [comment]
@yourslab Thank you for your help. I've solved it.

**Comment by yourslab** [comment]
I'm closing this issue now but feel free to open another one if you encounter more problems

**Comment by stringofevents** [comment]
Guess your fucked

temp. 1111
