### ISSUE TITLE
ota_demo_core_mqtt：The platform is in the self-test state while the job is not

### ISSUE THREAD

**Issue by Kelephant** [aws/aws-iot-device-sdk-embedded-C#1643]
This error occurred when I ran the ota_demo_core_mqtt program

[INFO] [DEMO] [ota_demo_core_mqtt.c:1508] OTA over MQTT demo, Application version 0.9.2
[INFO] [DEMO] [ota_demo_core_mqtt.c:983] Establishing a TLS session to ayi8otvxdbes1-ats.iot.us-west-2.amazonaws.com:8883.
[INFO] [DEMO] [ota_demo_core_mqtt.c:1132] Creating an MQTT connection to ayi8otvxdbes1-ats.iot.us-west-2.amazonaws.com.
[INFO] [MQTT] [core_mqtt.c:886] Packet received. ReceivedBytes=2.
[INFO] [MQTT] [core_mqtt_serializer.c:970] CONNACK session present bit not set.
[INFO] [MQTT] [core_mqtt_serializer.c:912] Connection accepted.
[INFO] [MQTT] [core_mqtt.c:1563] Received MQTT CONNACK successfully from broker.
[INFO] [MQTT] [core_mqtt.c:1829] MQTT connection established with the broker.
[INFO] [DEMO] [ota_demo_core_mqtt.c:1098] MQTT connection successfully established with broker.

[INFO] [OTA] [ota.c:2839] Current State=[RequestingJob], Event=[Start], New state=[RequestingJob]
[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1295] SUBSCRIBE topic $aws/things/debug_ipc/jobs/notify-next to broker.

[INFO] [OTA] [ota_mqtt.c:381] Subscribed to MQTT topic: $aws/things/debug_ipc/jobs/notify-next
[INFO] [MQTT] [core_mqtt.c:886] Packet received. ReceivedBytes=3.
[INFO] [DEMO] [ota_demo_core_mqtt.c:831] Received SUBACK.

[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [MQTT] [core_mqtt.c:886] Packet received. ReceivedBytes=2.
[INFO] [MQTT] [core_mqtt.c:1162] Ack packet deserialized with result: MQTTSuccess.
[INFO] [MQTT] [core_mqtt.c:1175] State record updated. New state=MQTTPublishDone.
[INFO] [DEMO] [ota_demo_core_mqtt.c:848] PUBACK received for packet id 2.

[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [OTA] [ota.c:2839] Current State=[WaitingForJob], Event=[RequestJobDocument], New state=[WaitingForJob]
[INFO] [MQTT] [core_mqtt.c:886] Packet received. ReceivedBytes=597.
[INFO] [MQTT] [core_mqtt.c:1045] De-serialized incoming PUBLISH packet: DeserializerResult=MQTTSuccess.
[INFO] [MQTT] [core_mqtt.c:1058] State record updated. New state=MQTTPublishDone.
[INFO] [DEMO] [mqtt_subscription_manager.c:91] Invoking subscription callback of matching topic filter: TopicFilter=$aws/things/+/jobs/#, TopicName=$aws/things/debug_ipc/jobs/$next/get/accepted
[INFO] [OTA] [ota.c:1645] Extracted parameter: [key: value]=[execution.jobId: AFR_OTA-ota4]
[INFO] [OTA] [ota.c:1645] Extracted parameter: [key: value]=[execution.jobDocument.afr_ota.streamname: AFR_OTA-38052115-908c-4a8d-99c0-73baedaff9fd]
[INFO] [OTA] [ota.c:1645] Extracted parameter: [key: value]=[execution.jobDocument.afr_ota.protocols: ["MQTT"]]
[INFO] [OTA] [ota.c:1645] Extracted parameter: [key: value]=[filepath: /system/nfs/demo]
[INFO] [OTA] [ota.c:1684] Extracted parameter: [key: value]=[filesize: 253370]
[INFO] [OTA] [ota.c:1684] Extracted parameter: [key: value]=[fileid: 0]
[INFO] [OTA] [ota.c:1645] Extracted parameter: [key: value]=[certfile: /system/nfs/cert/ecdsasigner.crt]
[INFO] [OTA] [ota.c:1575] Extracted parameter [ sig-sha256-ecdsa: MEQCIBzJ7/7VvR9wwIP55Y41SA8gzhyp... ]
[INFO] [OTA] [ota.c:1684] Extracted parameter: [key: value]=[fileType: 1]
[INFO] [OTA] [ota.c:2199] Job document was accepted. Attempting to begin the update.
[INFO] [OTA] [ota.c:2323] Job parsing success: OtaJobParseErr_t=OtaJobParseErrNone, Job name=AFR_OTA-ota4
**[WARN] [OTA] [ota.c:972] Rejecting new image and rebooting:The platform is in the self-test state while the job is not.**
[INFO] [OTA] [ota.c:2839] Current State=[CreatingFile], Event=[ReceivedJobDocument], New state=[CreatingFile]
[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1594]  Received: 0   Queued: 0   Processed: 0   Dropped: 0

**Comment by dachalco** [comment]
@pvyawaha Could you take a look?

**Comment by pvyawaha** [comment]
Hello, 

Can you check if PlatformImageState.txt file was already created before running the demo. It might be present due to previous demo run which was stopped.

**Comment by Kelephant** [comment]
@pvyawaha Thank you very much for your help.
I found the PlatformImageState.txt file, but when was it created? What is its function?
When Ota is over, the file still exists. Do I need to delete it manually

**Comment by pvyawaha** [comment]
The file is created when OTA process starts and used for keeping the state of update file , if it is new, in self-test or valid. After OTA is complete the file will be still present but with valid state. If the application is stopped without proper closing then it can have a state that was incorrect. For example it was left in self-test in your case but the job in service was not in same state as it was either cancelled or aborted.

**Comment by Kelephant** [comment]
@pvyawaha thanks !
