### ISSUE TITLE
Ram and Flash testing

### ISSUE THREAD

**Issue by hvishu** [aws/aws-iot-device-sdk-embedded-C#165]
In our product, we required to do Ram and Flash testing.  Flash testing is being done using NVS, how to test Ram.
ESP32 WROOM module is used as the replacement for the older microcontroller.  In the older microcontroller, these tests have been carried out.

**Comment by gordonwang0** [comment]
Hi @hvishu,

This is a question you should raise with your hardware manufacturer.  Closing issue.

**Comment by hvishu** [comment]
Here we are using ESP32WROOM module, I want to know how can I verify the RAM inside the ESP32 intact?  And SPI flash which is part of wroom module?

**Comment by totszwai** [comment]
@hvishu but the issue you raised has nothing to do with aws-iot-device-sdk-embedded-C, none of the source deal with any flash or hardware memory of any sort.

**Comment by gordonwang0** [comment]
Hi @hvishu,

Please raise this question with Espressif.  We are unable to help with issues regarding vendor hardware.

**Comment by hvishu** [comment]
ok will do.
