### ISSUE TITLE
DEMO:shadow_demo_main   disconnect  after 1min

### ISSUE THREAD

**Issue by wildwindyevan** [aws/aws-iot-device-sdk-embedded-C#1650]
the laster version 202103.00
I build this code on MAC  OSX  11.0.1  openssl  version is  1.1.1j
 Run the demo "shadow_demo_main"
I tried to modify the code  to make once MQTTconnect success and subscribes success   without "do while".
 Finally 
1 in the first 30s after connected ,subscribes handler function  works . after 30s,  nothing happens.
2 the shadow  will disconnect in 1min when using  the  "Activity"  in   aws iot console .

Do I need keep ping every 1min ?
Why could  the MQTT client  not reconnected ?

 Attach the parameters for MQTT.
================
#define AWS_IOT_ENDPOINT_LENGTH      ( ( uint16_t ) ( sizeof( AWS_IOT_ENDPOINT ) - 1 ) )
#define CLIENT_IDENTIFIER_LENGTH     ( ( uint16_t ) ( sizeof( CLIENT_IDENTIFIER ) - 1 ) )
#define ALPN_PROTOCOL_NAME           "\x0ex-amzn-mqtt-ca"
#define ALPN_PROTOCOL_NAME_LENGTH    ( ( uint16_t ) ( sizeof( ALPN_PROTOCOL_NAME ) - 1 ) )
#define CONNECTION_RETRY_MAX_ATTEMPTS            ( 5U )
#define CONNECTION_RETRY_MAX_BACKOFF_DELAY_MS    ( 5000U )
#define CONNECTION_RETRY_BACKOFF_BASE_MS         ( 500U )
#define CONNACK_RECV_TIMEOUT_MS                  ( 1000U )
#define MAX_OUTGOING_PUBLISHES              ( 5U )
#define MQTT_PACKET_ID_INVALID              ( ( uint16_t ) 0U )
#define MQTT_PROCESS_LOOP_TIMEOUT_MS        ( 2000U )
#define MQTT_KEEP_ALIVE_INTERVAL_SECONDS    ( 60U )
#define TRANSPORT_SEND_RECV_TIMEOUT_MS      ( 500 )
#define METRICS_STRING                      "?SDK=" OS_NAME "&Version=" OS_VERSION "&Platform=" HARDWARE_PLATFORM_NAME "&MQTTLib=" MQTT_LIB
#define METRICS_STRING_LENGTH               ( ( uint16_t ) ( sizeof( METRICS_STRING ) - 1 ) )

**Comment by yourslab** [comment]
Yes, that is just the nature of MQTT:

> It is the responsibility of the Client to ensure that the interval between Control Packets being sent does not exceed the Keep Alive value. In the absence of sending any other Control Packets, the Client MUST send a PINGREQ Packet

You set `MQTT_KEEP_ALIVE_INTERVAL_SECONDS=60U`, so if your code does not send a PUBLISH or any other control packet within 60 seconds, the MQTT server will close the connection. You can also call `MQTT_ProcessLoop` before 60 seconds expires since you will likely need to receive Shadow updates from the server anyway.

**Comment by wildwindyevan** [comment]
Thanks  It works。  
Actually， it dont need use any ping function when using  device CPP  SDK v1

**Comment by yourslab** [comment]
You unplugged the cable, so the TCP connection is no longer alive. In order to re-establish connection, you can call the function `EstablishMqttSession ` after getting `mqttStatus == 4`.

**Comment by wildwindyevan** [comment]
So strange it works after calling "EstablishMqttSession"
