### ISSUE TITLE
File access path in sdk execution

### ISSUE THREAD

**Issue by una801** [aws/aws-iot-device-sdk-embedded-C#1652]
Hello
Using IoT Core via mqtt_demo_mutual_auth.

I cross-compile sdk and put it in the form of ARM to use it. As a result, you must enter the path of the file as an absolute path in the run setting at device boot time.

As far as I know, there is no file path or direct file writing in sdk other than the certificate path, is there any additional function that runs along the file path?

I'm looking at each header file, but I don't think there's a path setting other than the certificate path yet, but I'm inquiring because it didn't run at boot time.
(The relative path is temporarily not recognized in the background and must be used absolutely.))
Or is the dynamic library affected by the path?

I am inquiring if there is any part of setting the path that I missed because the header file I use is too wide.

**Comment by yourslab** [comment]
Yes, I don't believe we read any files besides certificates & private keys. You can also use relative path, and it's relative to where you run `cmake`.

**Comment by una801** [comment]
I've fixed the problem. Thank you.
