### ISSUE TITLE
 Failed to receive data over network: SSL_read failed: ErrorStatus=EVP lib.

### ISSUE THREAD

**Issue by wildwindyevan** [aws/aws-iot-device-sdk-embedded-C#1654]
Platform : linux armv4
Hw: NXP imx6
#openssl version -a
OpenSSL 1.1.0k  28 May 2019 (Library: OpenSSL 1.1.1g  21 Apr 2020)
built on: Mon Jun 14 13:57:08 2021 UTC
platform: linux-armv4
options:  bn(64,32) rc4(char) des(long) idea(int) blowfish(ptr) 
compiler: /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -fPIC -pthread -Wall -O3   -mfloat-abi=hard -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DNDEBUG
OPENSSLDIR: "/usr/local/openssl111/ssl"
ENGINESDIR: "/usr/local/openssl111/lib/engines-1.1"

After checking  CA root file ,   the function "Openssl_Recv" was called  and left the error for a  long time  as  a recycle action .
But  maybe in 2~30mins, it works . Mqtt connected.
I need help to find out any parameters to fix it
================================
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:766] Failed to receive data over network: SSL_read failed: ErrorStatus=EVP lib.

**Comment by vikivivi** [comment]
What is your setting for `TRANSPORT_SEND_RECV_TIMEOUT_MS` ? Personally, I am setting to `2000` which works better in some heavy multi-layer structured corporate network.

**Comment by dan4thewin** [comment]
Hi, @wildwindyevan .  Are you using coreMQTT to connect to AWS IoT core?  Are you running one of the demos?  Can you take a packet capture?

**Comment by wildwindyevan** [comment]
> setting

500. And then  2000 does not work  also

**Comment by wildwindyevan** [comment]
> Hi, @wildwindyevan . Are you using coreMQTT to connect to AWS IoT core? Are you running one of the demos? Can you take a packet capture?

yes  coreMQTT .I will try a demo

**Comment by wildwindyevan** [comment]
it works after changing another cer and  private key.
