### ISSUE TITLE
MQTT Disconnecting - 'CLIENT_INITIATED_DISCONNECT' in aws logs

### ISSUE THREAD

**Issue by vamsi1105** [aws/aws-iot-device-sdk-embedded-C#1655]
We are using ESP32 and communicating to AWS via MQTT. While sending the data from web to controller, we are sending 12K data. ESP32 is returning '-1' generic error and no much information found about this error.  While debug it was found that aws_iot_mqtt_yield(&client,100) is returning -1. After changing the yield time from 100ms to 2000ms aws_iot_mqtt_yield(&client,2000) , It is receiving the data without any issues. 

I have enabled the cloud-watch and checked the logs while transmitting the data. I found one log saying 'CLIENT_INITIATED_DISCONNECT'. Check the log below.

Controller : ESP32-WROOM32D
SDK: ESP-IDF V3.2
MQTT Tx Buffer length: 3584
MQTT Rx Buffer length: 21504

{
    "timestamp": "2021-06-16 17:24:54.955",
    "logLevel": "INFO",
    "traceId": "4e7c309d-8e38-7f42-0aa2-f7cb5d6478c2",
    "accountId": "------------",
    "status": "Success",
    "eventType": "Disconnect",
    "protocol": "MQTT",
    "clientId": "apso_xrv/axs0054",
    "principalId": "84c9d00684ea012899908247bc9bfcfb99dce3f71eb6b074f92866f61cd99394",
    "sourceIp": "49.37.152.11",
    "sourcePort": 57689,
    "disconnectReason": "CLIENT_INITIATED_DISCONNECT"
}

![image](https://user-images.githubusercontent.com/86263073/122819173-ba57bf80-d2f7-11eb-98e5-eb6985851a22.png)

**Comment by yourslab** [comment]
This is a known issue with the espressif distribution but is already fixed in our own repository in release tag [v3.1.4](https://github.com/aws/aws-iot-device-sdk-embedded-C/releases/tag/v3.1.4). I would suggest opening an issue here so that Espressif can expedite fixing the issue in their own fork: https://github.com/espressif/esp-aws-iot
