### ISSUE TITLE
Error: message cannot be displayed in specified format 

### ISSUE THREAD

**Issue by shrinivasragolu** [aws/aws-iot-device-sdk-embedded-C#1658]
Hi All,

We have been using aws-iot-device-sdk-embedded-C version 3.0.1 since long time. Recent times we have not verified MQTT client from AWS console. Now when I try to run the subscribe_publish_sample application from the device, I am receiving the messages but errors marked on each message on aws mqtt client "test" , 
<img width="1260" alt="Screenshot 2021-07-01 at 2 56 02 PM" src="https://user-images.githubusercontent.com/54833801/124100919-80678580-da7c-11eb-89aa-549aaf620b38.png">
such as 

"message cannot be displayed in specified format". 

Any input or changes required to fix this issue

**Comment by shrinivasragolu** [comment]
Any help to view the telemetry messages?

Thanks in advance,
Srinivas.

**Comment by muneebahmed10** [comment]
Hi @shrinivasragolu,

You've likely just set the console to output the messages in JSON format, while the actual payloads are only strings. You can change the display format of your subscription by clicking "Edit" in the top right corner: 
<img width="817" alt="Screen Shot 2021-07-14 at 4 55 57 PM" src="https://user-images.githubusercontent.com/54290492/125707572-11a73998-f690-41e7-a0de-63842b49a80f.png">

**Comment by yourslab** [comment]
Hi @shrinivasragolu. Did this solve your issue?

**Comment by shrinivasragolu** [comment]
Thanks you so much. I could resolve this issue with the muneebahmad input.

Closing this issue
