### ISSUE TITLE
SPIFFs connection

### ISSUE THREAD

**Issue by Mohits2103** [aws/aws-iot-device-sdk-embedded-C#1661]
I am using ESP-IDF and am trying to integrate SPIFFs into (aws-iot-device-sdk-embedded-C/demos/http/http_demo_s3_upload/)

Basically, I am trying to send a file(say image) into s3 bucket which is in SPIFFs partiton. Please suggest me how to use the same..

Regards,

**Comment by ravibhagavandas** [comment]
Hello,

Espressif provides an example of how to use the SPIFFS partition in their IDF:
https://github.com/espressif/esp-idf/tree/master/examples/storage/spiffs
You could use the sample to do standard file operations using the SPI flash.  To upload the object to S3 you need to replace `DEMO_HTTP_UPLOAD_DATA` in the demo with the contents of the file.

**Comment by muneebahmed10** [comment]
Hi @Mohits2103,

Did the [above](https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/1661#issuecomment-877367819) response answer your question?

We will close this issue if we do not hear back from you
