### ISSUE TITLE
software agents

### ISSUE THREAD

**Issue by edbek** [aws/aws-iot-device-sdk-embedded-C#1673]
For IoT industry, the task of creating software agents has long been overdue. For example, interpreters for state machines of the SCXML or BT (behavior trees). Can this be expected?

**Comment by yourslab** [comment]
This SDK is more concerned with connectivity to the cloud. As such, we have protocol agents like the coreMQTT Agent that provides thread-safe equivalents to the coreMQTT library: https://github.com/FreeRTOS/coreMQTT-Agent
