### ISSUE TITLE
Add PlatformIO library manifests

### ISSUE THREAD

**Issue by emilmelnikov** [aws/aws-iot-device-sdk-embedded-C#1684]
PlatformIO has a library manager that knows [how to install dependencies from git repositories](https://docs.platformio.org/en/latest/librarymanager/quickstart.html#project-dependencies).
It would be great to be able to use libraries from this SDK just by referencing them in `platformio.ini`.
This requires adding [`library.json`](https://docs.platformio.org/en/latest/librarymanager/config.html) to repositories.

Is this something you could consider to add or accept PRs?

**Comment by alfred2g** [comment]
Hi,
I will take your request to your team and we will get back to your with an answer, if it is a  yes, PRs are always welcome !

**Comment by abhidixi11** [comment]
Hello @emilmelnikov , 
We use manifest file [like this ](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/manifest.yml) in our other repositories. Would it be helpful if we put one this repository as well?  I would be then consistent with our other repositories.

**Comment by emilmelnikov** [comment]
Initially I wanted to be able to run `pio lib install <AWS_LIB>` in a PlatformIO project, and get all dependencies, but apparently it doesn't make sense because one has to configure libraries like `coreHTTP` and `coreMQTT` anyway. It could work for libraries without dependencies though (e.g. for `coreJSON`).

**Comment by abhidixi11** [comment]
Thanks @emilmelnikov for the reply.
We are considering to put manifest like our other repositories.  Do you need anything else from us at this time ?  Otherwise we will close this issue. Please feel free to reach out to us if you have any further questions.
