### ISSUE TITLE
I use port 443 to connect to mqtt of aws, but I cannot connect successfully.

### ISSUE THREAD

**Issue by Kelephant** [aws/aws-iot-device-sdk-embedded-C#1695]
I use port 443 to connect to mqtt of aws, but I cannot connect successfully.

I am using mqtt demo mutual auth demo, and modified AWS_MQTT_PORT to 443, the certificate is also configured (the certificate is provided by the customer, and they work normally), and the following error is reported. What is the reason?

code：
[mqtt_demo_mutual_auth.zip](https://github.com/aws/aws-iot-device-sdk-embedded-C/files/6975287/mqtt_demo_mutual_auth.zip)

log：
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:269] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:674] Failed to establish a TLS connection.
2021-08-12 15:48:39 warn    [AoniAwsConnectToServerWithBackoffRetries:340]Connection to the broker failed. Retrying connection after 25 ms backoff.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:269] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:674] Failed to establish a TLS connection.
2021-08-12 15:48:44 warn    [AoniAwsConnectToServerWithBackoffRetries:340]Connection to the broker failed. Retrying connection after 462 ms backoff.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:269] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:674] Failed to establish a TLS connection.
2021-08-12 15:48:50 warn    [AoniAwsConnectToServerWithBackoffRetries:340]Connection to the broker failed. Retrying connection after 1686 ms backoff.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:269] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:674] Failed to establish a TLS connection.
2021-08-12 15:48:52 warn    [AoniAwsConnectToServerWithBackoffRetries:340]Connection to the broker failed. Retrying connection after 2469 ms backoff.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:269] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:674] Failed to establish a TLS connection.
2021-08-12 15:51:03 warn    [AoniAwsConnectToServerWithBackoffRetries:340]Connection to the broker failed. Retrying connection after 1876 ms backoff.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:269] SSL_connect failed to perform TLS handshake.
[ERROR] [Transport_OpenSSL_Sockets] [openssl_posix.c:674] Failed to establish a TLS connection.
2021-08-12 15:51:10 warn    [AoniAwsConnectToServerWithBackoffRetries:335]Connection to the broker failed, all attempts exhausted.

**Comment by Kelephant** [comment]
@aggarw13 Can you help me ？

**Comment by aggarw13** [comment]
Hi @Kelephant, from the zip artifact you have shared, I see a different Root CA certificate being used in the following logic of the `demo_config.h` file. Is this file the same as [Amazon Root CA 1](https://www.amazontrust.com/repository/AmazonRootCA1.pem) which is the certificate required for verifying server certificate provided by IoT Core in the TLS handshake process? 
```
#if USED_443
    #define ROOT_CA_CERT_PATH    "/config/cacert.pem.linux"
#endif
```

**Comment by Kelephant** [comment]
When I use Amazon root CA 1 to connect, I still report the same error. @aggarw13

**Comment by aggarw13** [comment]
@Kelephant, can you confirm that you're using the [202103.00](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/202103.00) version of the repository. I have verified that the MQTT Mutual Auth demo in the release is able to connect to AWS IoT Core on port 443. Here are the logs (with the endpoint redacted)

```
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:628] Establishing a TLS session to <endpoint-id>-ats.iot.us-west-2.amazonaws.com:443.
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:1327] Creating an MQTT connection to <endpoint-id>-ats.iot.us-west-2.amazonaws.com.
[INFO] [MQTT] [core_mqtt.c:886] Packet received. ReceivedBytes=2.
[INFO] [MQTT] [core_mqtt_serializer.c:970] CONNACK session present bit not set.
[INFO] [MQTT] [core_mqtt_serializer.c:912] Connection accepted.
[INFO] [MQTT] [core_mqtt.c:1563] Received MQTT CONNACK successfully from broker.
[INFO] [MQTT] [core_mqtt.c:1829] MQTT connection established with the broker.
[INFO] [DEMO] [mqtt_demo_mutual_auth.c:1096] MQTT connection successfully established with broker.


[INFO] [DEMO] [mqtt_demo_mutual_auth.c:1359] A clean MQTT connection is established. Cleaning up all the stored outgoing publishes.
```

Can you also check whether you're able to connect to successfully run the demo from the release version of the repository without making any code modifications (i.e. from a fresh clone) like you have made in the ZIP artifact shared? 

For the connection with TLS ALPN extension on port 443 with IoT Core to work, it is required that the `CLIENT_USERNAME` and `CLIENT_PASSWORD` macros are not defined. I don't see them being defined in the shared ZIP artifact, but can you confirm that they are not defined in the build commands you're use for testing?

**Comment by hrishikesheb** [comment]
Hi @aggarw13 I am trying to run the mqtt_demo_mutual_auth demo. As you said the code will run without any modifications. I am following this documentation which shows how to run the mqtt_demo_mutual_auth demo.

https://docs.aws.amazon.com/iot/latest/developerguide/iot-embedded-c-sdk.html

Everything runs fine till I run cmake but after that when I run make to generate executable file it runs for a few seconds and gives the error. The error image is attached below

![Capture1](https://user-images.githubusercontent.com/70017670/132810372-428a957c-e570-4867-8c73-69fd1ce84177.PNG)

**Comment by gshvang** [comment]
Closing the issue as the fix has been merged in the repository. Thanks
