### ISSUE TITLE
Could not update shadow with JSON document sizeof 5KB

### ISSUE THREAD

**Issue by amarnath87** [aws/aws-iot-device-sdk-embedded-C#171]
Hi,

I am trying to update the shadow with JSON document sizeof 5KB. The shadow update api returns SUCCESS status but the shadow is not updated with my contents. There are no messages seen under Test subscribed to #. Please let me know how to update the big chunk of JSON document. 

Here is my JSON document which I am trying to update

https://gist.github.com/amarnath87/2914176b07b8042dd5023ea2a98aebeb

According to aws documentation we can update upto 8 KB.
https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#w116aac15d123b9b3

Regards,
Amarnath

**Comment by ravibhagavandas** [comment]
Hi Amarnath,

AWS IoT publishes the error messages for a shadow update to the topic named: $aws/things/<thingName>/shadow/update/rejected. 
See AWS doc here: https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html#update-rejected-pub-sub-topic
The message is of json format and should contain the specific error code and description of the error: (https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-document-syntax.html#device-shadow-example-error-json)

For clarification, this topic (and other topics starting with $) wont be part of the # subscription, so you will not be able to see the error messages under the test client subscribed to #.

**Comment by amarnath87** [comment]
Hi Ravishankar,

Thank you for your response.

As per I know by subscribe to # will give messages for all topics including error messages. Anyways I have done as you said subscribing to the topic - '$aws/things/DeviceThing/shadow/update/rejected'  still I could not see any messages. Please help me to debug in SDK side. I have added few debug logs in internal APIs in SDK and they are returning success status. Please direct me to pin point this issue.

Regards,
Amarnath

**Comment by ravibhagavandas** [comment]
I tried to reproduce the issue in my setup.  After changing the AWS_IOT_MQTT_TX_BUF_LEN (maximum mqtt tx buffer value) here https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/6086838f6278fe660b94c86be125e3634f12a56f/samples/linux/shadow_sample/aws_iot_config.h#L36 , I was able to successfully update the json shadow document. I used linux shadow example for the update.

Could you explain your test setup and also provide the debug logs? Also see if you can increase the MQTT buffer size using the macro above.

**Comment by amarnath87** [comment]
Are you able to update the complete JSON document https://gist.github.com/amarnath87/2914176b07b8042dd5023ea2a98aebeb 

I am using linux shadow example on ubuntu. I had this issue even after increasing the size of both TX and RX buffer sizes.

The log says 'Failed to parse JSON: -1'. I did debug and  identified that issue is with jsmn_parse(). jsmn_alloc_token() in jsmn_parse() returns NULL due to token count is exceeding the max limit MAX_JSON_TOKEN_EXPECTED. After increasing the MAX_JSON_TOKEN_EXPECTED limit in https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/samples/linux/shadow_sample/aws_iot_config.h#L47  I could update complete JSON.

**Comment by ravibhagavandas** [comment]
Glad that you could update the JSON document now.
I was able to update the JSON document https://gist.github.com/amarnath87/2914176b07b8042dd5023ea2a98aebeb after changing MQTT TX buffer size, but I verified using AWS IOT console. 
MAX_JSON_TOKEN_EXPECTED  is the maximum number of json tokens available at any time, so you need to also increase this parameter for the delta callbacks to succeed.

**Comment by ravibhagavandas** [comment]
I am closing this issue. Feel free to reopen the issue if you have further questions.
