### ISSUE TITLE
AWS IoT with TCP connection

### ISSUE THREAD

**Issue by h4m3d92** [aws/aws-iot-device-sdk-embedded-C#1719]
Hi guys,

We are trying to move our IoT devices to AWS. The devices are using M2M (STM32+SIM800L) communication, So we've used "MQTT Plaintext Demo" SDK C.
The device opens a TCP socket (SIM8000L does not support TLS) and sends the following packet to "Things endpoint" address on the ports 8883 and 443:
10 17 00 04 4D 51 54 54 04 02 07 D0 00 0B 74 68 69 6E 67 2F 74 65 73 74 33
or:
10 11 00 04 4D 51 54 54 04 02 07 D0 00 05 74 65 73 74 33

But the server does not reply the "CONNACK" message. I know I need to be authorized at the beginning. May you give me a C or python SDK code which do this over TCP socket? A procedure will work too (The AWS documents are not detailed about TCP)

**Comment by archigup** [comment]
Hi, the examples in this repository use TCP. Authorization to AWS IoT is handled through client certificates. Can see instructions for setting up the certificates for authorization [here](https://github.com/aws/aws-iot-device-sdk-embedded-C#aws-iot-account-setup) and [here](https://github.com/aws/aws-iot-device-sdk-embedded-C#configuring-mutual-authentication-demos-of-mqtt-and-http).

The Plaintext Demo you mentioned uses TCP through OpenSSL (see the code for our plaintext transport interface [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/platform/posix/transport/src/plaintext_posix.c))

**Comment by dachalco** [comment]
Hi @h4m3d92 

If I understand correctly, you're looking to connect to IoT Core using separate TLS/TCP/MQTT stacks. Did you have any success referring to code Archit linked or is there any way we can further assist?

**Comment by h4m3d92** [comment]
Hi @archigup 
Thank you for the information. Unfortunately we are using M2M solution and we cannot use the code you've shared.
Also SIM800L does not support TLS, we have to use just TCP socket.

**Comment by h4m3d92** [comment]
Hi @dachalco 
We cannot use TLS connection due to our hardware structure. We have to use TCP serializer because we use SIM800L module [https://docs.aws.amazon.com/freertos/latest/lib-ref/embedded-csdk/202009.00/lib-ref/docs/doxygen/output/html/mqtt_demo_serializer.html](url)
Here is the library I've used for this purpose [https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/mqtt/mqtt_demo_serializer/mqtt_demo_serializer.c](url)

I reached to the strings I've mention above with this procedure.

**Comment by dan4thewin** [comment]
Hi, @h4m3d92 .   As I understand it, AWS IoT requires TLS (see https://docs.aws.amazon.com/iot/latest/developerguide/transport-security.html ).  Some searching suggests there might be TLS support in the SIM800 series, but I can't vouch for that.

**Comment by h4m3d92** [comment]
Hi @dan4thewin 
Yes, It seems despite some AWS IoT documents, TCP connection is not supported!
Thank you
