### ISSUE TITLE
Compiling with gcc-arm-none-eabi-7-2017-q4-major unsuccessful

### ISSUE THREAD

**Issue by jflynn129** [aws/aws-iot-device-sdk-embedded-C#172]
When compiling with the latest ARM GCC compiler, there are multiple failures with:
./../../src/aws_iot_json_utils.c: In function 'parseUnsignedInteger8Value':
../../../src/aws_iot_json_utils.c:90:95: error: expected ')' before 'SCNu8'
  if(('-' == (char) (jsonString[token->start])) || (1 != sscanf(jsonString + token->start, "%" SCNu8, i))) {
 
I see that there was previously an issue on this but no comments regarding the plans or timeline to fix.

**Comment by gordonwang0** [comment]
Hey @jflynn129,

Thanks for bringing this up.  It looks like that source file is including `inttypes.h`, which might not exist on some systems.  I'll make a pull request to address that.

**Comment by gordonwang0** [comment]
Hello,

This issue should be addressed by the above pull request.  Please let me know if you encounter any other errors.  Closing issue.

**Comment by jflynn129** [comment]
Thank you.
