### ISSUE TITLE
Facing Errors while creating cmake files for executing AWS embedded C

### ISSUE THREAD

**Issue by Shivampatel001** [aws/aws-iot-device-sdk-embedded-C#1726]
Executing aws-iot-device-sdk-embedded-C after editing all the necessary certificates and keys in aws-iot-device-sdk-embedded-C

Step 1 ->Open Terminal in UBUNTU

Step 2 ->Navigate to aws-iot-device-sdk-embedded-C root folder

      cd aws-iot-device-sdk-embedded-C
Step 3 -> Create a build directory and navigate to build

     mkdir build 
     cd build
Step 4 -> Enter the following CMake command to generate the Makefiles needed to build

          cmake ..

Step 5 -> Enter the following command to build the executable app file.

         make
Step 6 -> Run the mqtt_demo_mutual_auth app with this command.

        cd bin
       ./mqtt_demo_mutual_auth

Type of Errors after executing step 4(cmake .. )

---> CMake Error at platform/posix/transport/CMakeLists.txt:48 (include):
include could not find load file:
/home/deadpool/Desktop/aws-iot-device-sdk-embedded-C-main/aws-iot-device-sdk-embedded-C-main/libraries/standard/corePKCS11/pkcsFilePaths.cmake

---> CMake Error at tools/cmake/install.cmake:18 (include):
include could not find load file:
/home/deadpool/Desktop/aws-iot-device-sdk-embedded-C-main/aws-iot-device-sdk-embedded-C-main/libraries/aws/device-defender-for-aws-iot-embedded-sdk/defenderFilePaths.cmake
Call Stack (most recent call first):
CMakeLists.txt:139 (include)

-->>Mosquitto was not installed. It will be built from source to run jobs_demo_mosquitto.
CMake Error at demos/jobs/jobs_demo_mosquitto/CMakeLists.txt:22 (add_subdirectory):
The source directory
/home/deadpool/Desktop/aws-iot-device-sdk-embedded-C-main/aws-iot-device-sdk-embedded-C-main/demos/jobs/jobs_demo_mosquitto/libmosquitto
does not contain a CMakeLists.txt file.

-->>CMake Error at demos/jobs/jobs_demo_mosquitto/CMakeLists.txt:30 (set_target_properties):
set_target_properties Can not find target to add properties to:
mosquitto_rr

**Comment by yourslab** [comment]
From the root directory of the repository, do a `git submodule update --init --recursive --checkout`

**Comment by yourslab** [comment]
Hi @Shivampatel001, did this work for you?

**Comment by Shivampatel001** [comment]
Yes @yourslab it worked for me thank you so much

**Comment by Shivampatel001** [comment]
@yourslab  I am facing a new error can you help 
When i'm trying to execute the  command after navigating to bin folder
    ./mutual_demo_authenciate 
it shows no directory found

**Comment by yourslab** [comment]
You should do `ls` first to check the name of the program. Most likely it is `./mqtt_mutual_auth_demo`

**Comment by Shivampatel001** [comment]
@yourslab sir the name is ./mqtt_demo_mutual_auth but when iam tryins list directory(ls) command the bin folder is empty.

**Comment by yourslab** [comment]
Have you run `make` from the build directory? If you did, what is the output?

**Comment by Shivampatel001** [comment]
@yourslab  yes I executed make command after executing cmake ..

**Comment by yourslab** [comment]
Can you please show the output after entering `make` so that we can help you debug?

**Comment by Shivampatel001** [comment]
Yes @yourslab sir
![Screenshot from 2021-09-29 10-08-29](https://user-images.githubusercontent.com/70810342/135204658-f6a3eb53-2b3e-4088-9d73-d7b7284da3fa.png)

**Comment by yourslab** [comment]
Please try to run `make mqtt_mutual_auth_demo`. It looks like it is not adding to the default `make` target because some flags are not defined. Please make sure you ran CMake as shown here: https://github.com/aws/aws-iot-device-sdk-embedded-C#configuring-mutual-authentication-demos-of-mqtt-and-http

**Comment by Shivampatel001** [comment]
@yourslab  executing make  mqtt_demo_mutual_auth didnt work
error:
make: *** No rule to make target 'mqtt_demo_mutual_auth'.  Stop.

**Comment by Shivampatel001** [comment]
@yourslab  I am so much confused with this thing

**Comment by Shivampatel001** [comment]
@yourslab  I executed make mqtt_demo_mutul_auth and I got this as outpu
![Screenshot from 2021-09-30 00-48-09](https://user-images.githubusercontent.com/70810342/135334639-badbbc4b-5107-480d-9781-3679920da8da.png)

**Comment by yourslab** [comment]
Please follow the instructions in the link I sent you. You have not defined `AWS_IOTENDPOINT`, `CLIENT_CERT_PATH`, `CLIENT_PRIVATE_KEY_PATH`.

**Comment by Shivampatel001** [comment]
@yourslab ok sir I will try and get back to you

**Comment by Shivampatel001** [comment]
@yourslab  sir I am not able to do this , can you do it for me please?

**Comment by yourslab** [comment]
When compiling with CMake, you must run the following command:
```
cmake -S . -Bbuild
-DAWS_IOT_ENDPOINT="<your-aws-iot-endpoint>" -DCLIENT_CERT_PATH="<your-client-certificate-path>" -DCLIENT_PRIVATE_KEY_PATH="<your-client-private-key-path>"

**Comment by yourslab** [comment]
Hello, @Shivampatel001. Were you able to resolve the issue?

**Comment by Shivampatel001** [comment]
No @yourslab  I got same error every time so I decided to quit this project.
