### ISSUE TITLE
How to send telemetry data using MQTT_DEMO_MUTUAL_AUTH 

### ISSUE THREAD

**Issue by hrishikesheb** [aws/aws-iot-device-sdk-embedded-C#1739]
Hello sir,
I am successfully able to run the demo by publishing a "Hello world" message. But I wanted to send telemetry data from the device to the AWSIoT cloud, can you tell me if it is possible with this demo.

**Comment by yanjos-dev** [comment]
Hi @hrishikesheb, are you familiar with this documentation?
https://docs.aws.amazon.com/iot/latest/developerguide/iot-tutorials.html

This would be a good starting point.

**Comment by hrishikesheb** [comment]
@yanjos-dev Thank you very much this documentation was super helpful. I will go through and see if I have any more doubts.

**Comment by hrishikesheb** [comment]
Hi @yanjos-dev is there any demo c code which sends telemetry data which can be viewed in AWSIoT.

**Comment by yanjos-dev** [comment]
Can you provide some additional information about your use case and how you would like to view the data? The MQTT demo that you have ran should allow you to see the data published to the topic in the AWS IoT console. This demo documentation shows an example of how you should see "Hello World" in the console.
https://docs.aws.amazon.com/freertos/latest/userguide/mqtt-demo-ma.html

**Comment by hrishikesheb** [comment]
Yes I have successfully published a "Hello World" message and also viewed it in the AWSIoT console. Type of data is the time series data. If I run this code in any device running ubuntu OS the same thing will happen it will just keep on publishing "Hello World" message instead I want it to connect to AWSIoT and start sending sensor data which looks like this.


```
{
    "timestamp": 1601048303,
    "sensorId": 28,
    "sensorData": [
        {
        "sensorName": "Wind speed",
        "sensorValue": 34.2211224
        }
    ]
}

```
I know there is no fixed code to do this but I want to demonstrate the concept of device telemetry.

**Comment by tianmc1** [comment]
Hi @hrishikesheb ,

In the MQTT mutual auth example, the action of publishing to a MQTT topic is done in [publishToTopic()](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/a54643fe39bc90a964c96716bc8055097d099ab5/demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c#L1245) and the payload of the publish is defined in [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/a54643fe39bc90a964c96716bc8055097d099ab5/demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c#L1269). If you replace this payload with your telemetry data, it will show up in AWS IoT console where you see the "Hello World" message previously.

**Comment by abhidixi11** [comment]
Hello @hrishikesheb 
I'm closing this issue, if you have any further questions please feel free to open another issue. 
Thanks.
