### ISSUE TITLE
Is it support on NuttX?

### ISSUE THREAD

**Issue by PierrePeng** [aws/aws-iot-device-sdk-embedded-C#1741]
I am trying to use AWS-IoT on our first-generation production which runs on the NuttX system. 

I wanna is it supports NuttX?  I encouters difficulties from porting OpenSSL which is neccessary library for the AWS-IoT.

**Comment by yanjos-dev** [comment]
Hi @PierrePeng, this will depend on the library. Some libraries do not have hardware specific dependencies while other libraries require some porting to be done. What libraries are you interested in using?

**Comment by PierrePeng** [comment]
It seems difficult for me to port the OpenSSL to Cortex-M33. And there are some questions that confused me.

1. According to README.MD, [OpenSSL](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/a54643fe39bc90a964c96716bc8055097d099ab5/platform/CMakeLists.txt#L5) is a dependency library for demos and tests. So can I build this project if I don't have OpenSSL? 
2. If **Yes**, how can I configure the CMakeList?
3. If **No**, Can I use wolfSSL instead of OpenSSL?

**Comment by ravibhagavandas** [comment]
Hi @PierrePeng 

The C-sdk libraries rely only on a [transport interface](https://github.com/FreeRTOS/coreMQTT/blob/main/source/interface/transport_interface.h)  which can be ported to any underlying libraries not necessarily OpenSSL.

For sample reference of how to implement transport interface using mbedtls or wolfssl with FreeRTOS+TCP stack you can refer the files [here](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS-Plus/Source/Application-Protocols/network_transport/freertos_plus_tcp). Implementation can be customized to allow other TCP/IP stacks of your choice. 

Openssl is much larger code base and is typically used to run on the high resourceful systems such as linux.  Whereas mbedtls or wolfssl are more optimized for resource constrained systems. Is there any specific use case for selecting OpenSSL ? Both Mbedtls and wolfssl are ported to multiple platforms and you can find porting guides in their respective webpages.

**Comment by ravibhagavandas** [comment]
Hello,
Did this answer your question? We will close the issue if we don't hear back from you soon.

**Comment by ravibhagavandas** [comment]
We will close this issue due to inactivity. If you have any other questions please open a new issue.
