### ISSUE TITLE
MQTT retained messages not working 

### ISSUE THREAD

**Issue by MaazSk** [aws/aws-iot-device-sdk-embedded-C#1747]
Hi,

I am using AWS to connect my esp32 to the AWS services, When I am trying a simple publish from the device then I am able to publish a message but when I am using retained messages to publish to the AWS then the client is getting disconnected. I tried the same using MQTTFx and also from the console dashboard of AWS but every time I am getting disconnected when I set the messages to retain.

Any help would be grateful!

Thanks in advance.

**Comment by aggarg** [comment]
Would you please elaborate your setup? Do you have a client running on ESP32 subscribed to a topic and it gets disconnected when you publish a retained message? Also, which code are you using on the client? 

Thanks.

**Comment by MaazSk** [comment]
Hi @aggarg,

Sorry for the delay in response.

Setup:
I am using MQTTFx as a client to connect with the AWS server. The connection is successful between the AWS server and MQTTFx.

I am trying to publish retained message from MQTTFx to the AWS server on the topic `device_id/retained_messages`. Whenever I publish a message with the MQTT retained flag the client gets disconnected. On the other hand, if I publish a message without the retain flag I am able to receive the message.

Also if we try the same from the dashboard provided by AWS the client gets disconnected if I select retain messages and publish any message on the above topic.

Any help would be grateful

Thanks in advance!

**Comment by aggarg** [comment]
I tested the following:

1. Subscribe to the `test/retainedmsg` topic:
```
mosquitto_sub -h <aws_iot_endpoint> -p 8883 --cafile <path_to_ca> --cert <path_to_cert> --key <path_to_key> -t "test/retainedmsg"
```

2. Publish a retained message on the same topic:
```
mosquitto_pub -h <aws_iot_endpoint> -p 8883 --cafile <path_to_ca> --cert <path_to_cert> --key  <path_to_key> -t "test/retainedmsg" -m "Hello" -r
```
Note that `-r` flag is for retained message. I verified that the message was retained by terminating the `mosquitto_sub` and re-subscribing - I got the message again as expected. 

By any chance, are you using the same client ID for 2 clients? If not, can you enable [AWS IoT Logging](https://docs.aws.amazon.com/iot/latest/developerguide/configure-logging.html) and check what you get in logs?

Thanks.

**Comment by MaazSk** [comment]
I will try the above steps today and will update you the same

**Comment by jasonpcarroll** [comment]
Since you have not updated - I am going to close this issue. If there is still a problem, please re-open the issue. Thank you.
