### ISSUE TITLE
Fleet Provisioning.

### ISSUE THREAD

**Issue by buneshwarEc** [aws/aws-iot-device-sdk-embedded-C#1759]
Hi ,
I'm new to iot-aws.
I went through the process for demo of fleet provisioning.
I stuck at How to i burn this on device.
This is working perfectly when i run at console but how do i the same on the device.

I've went through the freeRTOS guide and flashed the default demo.
[https://docs.aws.amazon.com/freertos/latest/userguide/getting_started_espressif.html](url)

Device - ESP32
OS - Ubuntu 20.04

**Comment by abhidixi11** [comment]
Hello @buneshwarEc 
I believe you have asked the same question [here](https://github.com/aws/amazon-freertos/issues/3431), therefore I'm closing this issue. If you have any further questions please ask on the other thread or open a new issue. 
Thanks !
