### ISSUE TITLE
Error in Connecting to AWS IoT - iot_tls_connect L#164  failed

### ISSUE THREAD

**Issue by rajeshupadhyay** [aws/aws-iot-device-sdk-embedded-C#176]
Hello,

I am trying to run sample program subscribe_publish_sample on raspberry PI. Program is giving bellow error. 
------------------
pi@raspberrypi:~/aws-iot-device-sdk-embedded-C/samples/linux/subscribiot_tls_connect L#164  failede_publish_sample $ ./subscribe_publish_sample 

AWS IoT SDK Version 3.0.0-

DEBUG:   main L#159 rootCA /home/pi/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/iotRootCA.pemiot_tls_connect L#164  failediot_tls_connect L#164  failed
DEBUG:   main L#160 clientCRT /home/pi/aws-iot-device-sdk-embedded-iot_tls_connect L#164  failedC/samples/linux/subscribe_publish_sample/../../../certs/deviceCert.crt
DEBUG:   main L#161 clientKey /home/pi/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/devicePrivatekey.pem
Connecting...
DEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  okiot_tls_connect L#164  failed

DEBUG:   iot_tls_connect L#161   . Connecting to /443...
ERROR: iot_tls_connect L#164  failed
  ! mbedtls_net_connect returned -0x52iot_tls_connect L#164  failed

ERROR: main L#190 Error(-23) connecting to :443
---------------

I also ran below command to check the connectivity. 
-------------------------
pi@raspberrypi:~/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample $ openssl s_client -connect a9ixr6j2yr276.iot.ap-southeast-1.amazonaws.com:443
CONNECTED(00000003)
depth=2 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2006 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primary Certification Authority - G5
verify return:1
depth=1 C = US, O = Symantec Corporation, OU = Symantec Trust Network, CN = Symantec Class 3 ECC 256 bit SSL CA - G2
verify return:1
depth=0 C = US, ST = Washington, L = Seattle, O = "Amazon.com, Inc.", CN = *.iot.ap-southeast-1.amazonaws.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=Washington/L=Seattle/O=Amazon.com, Inc./CN=*.iot.ap-southeast-1.amazonaws.com
   i:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 ECC 256 bit SSL CA - G2
 1 s:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 ECC 256 bit SSL CA - G2
   i:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIEnzCCBEWgAwIBAgIQC4VI8jyFC01jI7Dqk0IqHTAKBggqhkjOPQQDAjCBgDEL
MAkGA1UEBhMCVVMxHTAbBgNVBAoTFFN5bWFudGVjIENvcnBvcmF0aW9uMR8wHQYD
VQQLExZTeW1hbnRlYyBUcnVzdCBOZXR3b3JrMTEwLwYDVQQDEyhTeW1hbnRlYyBD
bGFzcyAzIEVDQyAyNTYgYml0IFNTTCBDQSAtIEcyMB4XDTE3MTEyMjAwMDAwMFoX
DTE4MTEyMzIzNTk1OVowfDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCldhc2hpbmd0
b24xEDAOBgNVBAcMB1NlYXR0bGUxGTAXBgNVBAoMEEFtYXpvbi5jb20sIEluYy4x
KzApBgNVBAMMIiouaW90LmFwLXNvdXRoZWFzdC0xLmFtYXpvbmF3cy5jb20wWTAT
BgcqhkjOPQIBBggqhkjOPQMBBwNCAARvyz22pdKSyntrVYreFGtPDGggPObtqF3M
hPJG9p9vkM19lls0tyNZdq9dqrEaOOES9rMyyT141IDgSbN51jUdo4ICojCCAp4w
TwYDVR0RBEgwRoIgaW90LmFwLXNvdXRoZWFzdC0xLmFtYXpvbmF3cy5jb22CIiou
aW90LmFwLXNvdXRoZWFzdC0xLmFtYXpvbmF3cy5jb20wCQYDVR0TBAIwADAOBgNV
HQ8BAf8EBAMCB4AwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMGEGA1Ud
IARaMFgwVgYGZ4EMAQICMEwwIwYIKwYBBQUHAgEWF2h0dHBzOi8vZC5zeW1jYi5j
b20vY3BzMCUGCCsGAQUFBwICMBkMF2h0dHBzOi8vZC5zeW1jYi5jb20vcnBhMB8G
A1UdIwQYMBaAFCXwiuFLetkBlQrtxlPxjHgf2fP4MCsGA1UdHwQkMCIwIKAeoByG
Gmh0dHA6Ly9yYy5zeW1jYi5jb20vcmMuY3JsMFcGCCsGAQUFBwEBBEswSTAfBggr
BgEFBQcwAYYTaHR0cDovL3JjLnN5bWNkLmNvbTAmBggrBgEFBQcwAoYaaHR0cDov
L3JjLnN5bWNiLmNvbS9yYy5jcnQwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdgDd
6x0reg1PpiCLga2BaHB+Lo6dAdVciI09EcTNtuy+zAAAAV/l7yDuAAAEAwBHMEUC
ICEG9HvGBgmKIqa2/hvCNUUDMGynbTDXT3y9rZNBFbCgAiEA0It1uRbKdOwGYvPc
lVLYJ+mFCisZNQ9yYQh8R1z8+WQAdwCkuQmQtBhYFIe7E6LMZ3AKPDWYBPkb37jj
d80OyA3cEAAAAV/l7yEnAAAEAwBIMEYCIQDJdqzuLgqfeOix20MtKCq9aKGIcLTv
fv8lm+9H2VeLYAIhAIC2WOjKLS2/i7KvwucT2ryflQWJR3FF2CqWAQHj+VQEMAoG
CCqGSM49BAMCA0gAMEUCIASETsvvJw7pKH6r3gejDs4wCBIp+miVpejxriELF0xs
AiEA8LJSnbQJe07mRVyEmB57SvRRpvIYc9mAwRX7MJMOP6s=
-----END CERTIFICATE-----
subject=/C=US/ST=Washington/L=Seattle/O=Amazon.com, Inc./CN=*.iot.ap-southeast-1.amazonaws.com
issuer=/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 ECC 256 bit SSL CA - G2
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2623 bytes and written 302 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-ECDSA-AES256-GCM-SHA384
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-AES256-GCM-SHA384
    Session-ID: 5AEAC542D3C12431B34D8C5DEC87ABE7F111A5A9D6BCE6612701F149EA1364F9
    Session-ID-ctx: 
    Master-Key: 6536B911C0891CB84D3E78EE40DBC51CD781E0FFEAB8ED302E6A8371B7AEF315A491D899C5CB8F9236A63F9C1CA9CBB1
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1525335362
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---

DONE
-------------------------

What could be the reason? I tried to search for solution. Didn't get any pointer on solution.

Thanks & Regards
Rajesh

**Comment by ravibhagavandas** [comment]
**! mbedtls_net_connect returned -0x52iot_tls_connect L#164 failed**
mbedtls error -0x52 maps to MBEDTLS_ERR_NET_UNKNOWN_HOST - which means probably the mqtt broker host name is incorrect in the code.
Could you verify if the mqtt broker host name is correctly defined to **a9ixr6j2yr276.iot.ap-southeast-1.amazonaws.com** in your code. https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/6086838f6278fe660b94c86be125e3634f12a56f/samples/linux/subscribe_publish_cpp_sample/aws_iot_config.h#L26

**Comment by rajeshupadhyay** [comment]
Hi,

Thanks ravibhagvandas for help. I had a typo in the Host name, hence I was getting that previous error.
After, correcting that typo, program is proceeding ahead but failing with different error.
--------------------------------------
pi@raspberrypi:~/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample $ ./subscribe_publish_sample 

AWS IoT SDK Version 3.0.0-

DEBUG:   main L#159 rootCA /home/pi/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/iotRootCA.pem
DEBUG:   main L#160 clientCRT /home/pi/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/deviceCert.crt
DEBUG:   main L#161 clientKey /home/pi/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/devicePrivatekey.pem
Connecting...
DEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to a9ixr6j2yr276.iot.ap-southeast-1.amazonaws.com/443...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 2):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 18:DA:D1:9E:26:7D:E8:BB:4A:21:58:CD:CC:6B:3B:4A
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name      : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
issued  on        : 2006-11-08 00:00:00
expires on        : 2036-07-16 23:59:59
signed using      : RSA with SHA1
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 3F:92:87:BE:9D:1D:A4:A3:7A:9D:F6:28:2E:77:5A:C4
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name      : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
issued  on        : 2015-05-12 00:00:00
expires on        : 2025-05-11 23:59:59
signed using      : RSA with SHA-256
EC key size       : 256 bits
basic constraints : CA=true, max_pathlen=0
subject alt name  : 
key usage         : Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 0B:85:48:F2:3C:85:0B:4D:63:23:B0:EA:93:42:2A:1D
issuer name       : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.iot.ap-southeast-1.amazonaws.com
issued  on        : 2017-11-22 00:00:00
expires on        : 2018-11-23 23:59:59
signed using      : ECDSA with SHA256
EC key size       : 256 bits
basic constraints : CA=false
subject alt name  : iot.ap-southeast-1.amazonaws.com, *.iot.ap-southeast-1.amazonaws.com
key usage         : Digital Signature
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

ERROR: iot_tls_connect L#232  failed
  ! mbedtls_ssl_handshake returned -0x7780

ERROR: main L#190 Error(-4) connecting to a9ixr6j2yr276.iot.ap-southeast-1.amazonaws.com:443

--------------------------------------
I have checked the policy document. It contains all required permissions(some posts referred to not having permissions in policy document causing the error).
My system date is also correct(again, some post also mentioned this as reason for error).

**Comment by ravibhagavandas** [comment]
#define MBEDTLS_ERR_SSL_FATAL_ALERT_MESSAGE               -0x7780  /**< A fatal alert message was received from our peer. */

This means that tls server has disconnected from client  as it didn't complete the negotiation. Possible issue will be with the client certificate. Did you create the client certificate using AWS console ? Could you verify that certificate is proper?

**Comment by rajeshupadhyay** [comment]
Thanks @ravibhagavandas  for answer. I think, I made some mistake in key and certificate creation. 
I deleted my existing certificates & keys and recreated it afresh on AWS. Compiled the sample program with updated key/certificates.
Finally It worked. I was able to connect.
Thanks again for your help

**Comment by totszwai** [comment]
@ravibhagavandas Possible to enhance the error message to give better details? I faced this problem before too, and it took me a while to isolate the issue.
