### ISSUE TITLE
 Failed to receive data In eventcallback with large JSON payload

### ISSUE THREAD

**Issue by Heena2411** [aws/aws-iot-device-sdk-embedded-C#1764]
HI,
I am using AWS SDK on my laptop having Ubuntu 20.04.
I am trying to send costume JSON payload in desired state. While JSON data length is large, not able to get response in eventcallback. With smaller data it is working fine.
Tried by changing NETWORK_BUFFER_SIZE, AWS_PAYLOAD_BUFF_SIZE. does this issue related to JSON payload length? Is there any limitation on length?
 
 working payload:
 {
	"state": {
		"desired": {
			"a": 11111222223333333333111111111111111111111111111111190011111111111111111111111111111111111111111111111111111111111123,
			"b": 456,
			"c": 111,
			"d": 222,
			"e": 333,
			"f": 444,
			"g": 555,
			"h": 1
		}
	},
	"clientToken": "023798"
}

Payload with no response:
{
	"state": {
		"desired": {
			"a": 11111222223333311111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111133333111111111111111111111111111111190011111111111111111111111111111111111111111111111111111111111123,
			"b": 456,
			"c": 111,
			"d": 222,
			"e": 333,
			"f": 444,
			"g": 555,
			"h": 1
		}
	},
	"clientToken": "023798"
}

**Comment by jasonpcarroll** [comment]
Thank you for bringing this to our attention. The team is looking into it.

**Comment by Heena2411** [comment]
Thanks for quick response.
I am referring **eventCallback( MQTTContext_t * pMqttContext, MQTTPacketInfo_t * pPacketInfo, MQTTDeserializedInfo_t * pDeserializedInfo )** and able to get payload print in **updateDeltaHandler** with small payload.

**Comment by jasonpcarroll** [comment]
Hi @Heena2411,
Sorry for the late response - I did not see that you replied. I was wondering if you could provide me with some additional information. Is this for an mqtt demo - if so which one? What version of the code are you using?

**Comment by pvyawaha** [comment]
Hello @Heena2411 ,

Closing this ticket now but please reopen if you need support on the same topic.
