### ISSUE TITLE
Alternative to `aws_iot_mqtt_yield()`

### ISSUE THREAD

**Issue by MaazSk** [aws/aws-iot-device-sdk-embedded-C#1782]
I am using aws-iot-device-sdk with esp-idf. I am unable to receive messages to which I have subscribed. I read the documentation that I need to call `aws_iot_mqtt_yield()` function faster than the publish message. But I believe the aws subscribe functionality should work on event base or in callback fashion. So whenever I receive a message I should get an event or a callback. So is there any alternative to it.

**Comment by archigup** [comment]
Hi, if you would like a callback based API, you could use the newer [coreMQTT](https://github.com/FreeRTOS/coreMQTT) library with the [coreMQTT-Agent](https://github.com/FreeRTOS/coreMQTT-Agent). The coreMQTT Agent provides an API that uses callbacks like you describe.

**Comment by MaazSk** [comment]
Okay, 

I will give it a try and if I have any issue will let you know

Thank you!
