### ISSUE TITLE
How to run OTA update application on linux

### ISSUE THREAD

**Issue by Hemanth826-dev** [aws/aws-iot-device-sdk-embedded-C#1787]
Hi Sir/Madam,
  
I'm new to this domain, and i want to run the ota updates on linux. I tried to schedule a FreeRTOS OTA Updatejob for running the demo application in the sdk on linux. I first changed the application version from 0.9.2 to 0.9.3 and built it and uploaded the binary file in s3 bucket, then changed it back to 0.9.2 and built the application and ran it. The application was able to recieve the update job and download the binary file, but it was not able to restart the new application and it gave this error.

[INFO] [OTA] [ota.c:2632] Received final block of the update.
[INFO] [DEMO] [ota_demo_core_mqtt.c:1598] Received: 54 Queued: 54 Processed: 50 Dropped: 0
[ERROR] [OTA] [ota_pal_posix.c:164] Failed to load cert from either file or predefined string.
[ERROR] [OTA] [ota_pal_posix.c:323] File signature check failed at EXTRACT pkey from signer certificate.
[ERROR] [OTA] [ota_pal_posix.c:515] Failed to pass sig-sha256-ecdsa signature verification: -419430400.
[ERROR] [OTA] [ota.c:2659] Failed to close the OTA file: Error=(OtaPalBadSignerCert:0x000000)
[ERROR] [OTA] [ota.c:1227] Failed to ingest data block, rejecting image: ingestDataBlock returned error: OtaErr_t=-3
[INFO] [DEMO] [ota_demo_core_mqtt.c:1598] Received: 54 Queued: 54 Processed: 53 Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1598] Received: 54 Queued: 54 Processed: 53 Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1598] Received: 54 Queued: 54 Processed: 53 Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1598] Received: 54 Queued: 54 Processed: 53 Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1598] Received: 54 Queued: 54 Processed: 53 Dropped: 0
[INFO] [DEMO] [ota_demo_core_mqtt.c:1598] Received: 54 Queued: 54 Processed: 53 Dropped: 0

can you please suggest me the proper steps to do this and can you please suggest me if there is any documentation related to OTA updates on linux.

Thankyou,
Hemanth

**Comment by n9wxu** [comment]
It appears that the signing certificates are not installed in the demo application.  Make sure that the certificate used to sign the uploaded image are also referenced in the demo either by copying the certificate into the source code (highly discouraged in production) or by referencing the file to load.
https://docs.aws.amazon.com/freertos/latest/userguide/ota-code-sign-cert-win.html
https://docs.aws.amazon.com/freertos/latest/userguide/dev-guide-ota-security.html

**Comment by Hemanth826-dev** [comment]
Could you please tell me where i should install the certificate in application, since i didn't find it in both the config files demo_config.h and ota_config.h.

**Comment by tianmc1** [comment]
Hi @Hemanth826-dev ,
The certificate can be put at put [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/5da3a389cda566469ee5d79142961d30461ea570/platform/posix/ota_pal/source/ota_pal_posix.c#L56) ota_pal_posix.c. Please let us know if this works.

**Comment by tianmc1** [comment]
When running OTA on a real embedded device, the activation step would reset the device to boot into the newly downloaded image. This is not feasible on the POSIX port, so the "activateNewImage returned error: Manual reset required" error message is expected in this case. What error did you encounter when you run the downloaded binary?

**Comment by Hemanth826-dev** [comment]
Hi @tianmc1 

The downloaded binary file did not have the executable permission, so i was not able to execute. After changing the permissions manually i was able to run the downloaded binary file. Thankyou for your help.

Thankyou,
Hemanth
