### ISSUE TITLE
How would I get the IPV4 address of a device within the Mutual Auth demo example

### ISSUE THREAD

**Issue by readysteadygo2006** [aws/aws-iot-device-sdk-embedded-C#1788]
Hi,

I'm building an application using the AWS SDK Mutual Auth demo as a starting point.

I want to get the IPV4 address of the device.

Normally I could use code such shown below to get the IP:
```
esp_netif_t *netif = **????**
esp_netif_ip_info_t ip_info;
esp_netif_get_ip_info(netif, &ip_info);
printf("My IP: " IPSTR "\n", IP2STR(&ip_info.ip));
```

However in the context of the demo example how do I initialize netif?

Thanks for any help you can provide!

**Comment by tianmc1** [comment]
Hi @readysteadygo2006 ,

The demos in aws-iot-device-sdk-embedded-C runs on a POSIX machine (e.g. a laptop). Therefore the ESP specific code does not apply here. If you are running the demo on Linux, you can use [getifaddrs](https://man7.org/linux/man-pages/man3/getifaddrs.3.html) to get information including IP address on the network interfaces. If the code is later used on a FreeRTOS embedded device, you can use [FreeRTOS_GetAddressConfiguration()](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/API/FreeRTOS_GetAddressConfiguration.html).
