### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by linsijia1002** [aws/aws-iot-device-sdk-embedded-C#1792]
![image](https://user-images.githubusercontent.com/17610352/159680101-88cf5377-d11e-428a-b727-41f76ed5fbf7.png)

please tell me why it compile fail, thank u  :)

**Comment by pvyawaha** [comment]
Hello @linsijia1002 ,

Are you using any release or main branch ? I will try to reproduce it on main branch and share update here.

**Comment by linsijia1002** [comment]
> Hello @linsijia1002 ,
> 
> Are you using any release or main branch ? I will try to reproduce it on main branch and share update here.

yes， i am in main branch.

**Comment by linsijia1002** [comment]
@[pvyawaha](https://github.com/pvyawaha) hello
Is there something wrong with my compilation environment? I always think there is something wrong with my OpenSSL library. Can you give me an analysis direction

**Comment by jasonpcarroll** [comment]
Hi @linsijia1002,
Sorry for the very late reply. Are you still having this issue?
Best,
Jason

**Comment by archigup** [comment]
Closing this issue; feel free to reopen if you are still facing this issue.
