### ISSUE TITLE
Connectivity preference  

### ISSUE THREAD

**Issue by sumanclimote** [aws/aws-iot-device-sdk-embedded-C#1793]
Does the SDK have a means of have multiple RF connectivity for data routing and means to choose the best suitable one if the performance is degraded? 

I mean if we have WIFI and GPRS connectivity, do we have a means to choose WIFI as default if there is a performance issue the IOT core shall choose to alternative communication channel till the first (preferred) channel is performing better.

**Comment by alfred2g** [comment]
I Don’t see any baked in functionality to do what you want.  you could create you own custom sockets transport layer which tracks performance,  periodically checking if session should switch to GPRS/wifi based on whatever criteria.
Or you could just have two sockets open simultaneously but you’d have to avoid namespace collisions.

**Comment by sumanclimote** [comment]
Thanks for sharing it.
