### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by linsijia1002** [aws/aws-iot-device-sdk-embedded-C#1794]
![image](https://user-images.githubusercontent.com/17610352/160223943-136bafd4-7cc3-4562-a312-31067907cd4f.png)

Could you please help me to check the cause of compilation failure, thanks

**Comment by alfred2g** [comment]
On some systems cc is a symbolic link to gcc, clang, or some other compiler
what you can try is to define CC as an env variable, and/or create a link cc -> gcc
export CC=/path/to/gcc
ln -s /usr/bin/cc /path/to/gcc

**Comment by linsijia1002** [comment]
> 

It's done, thank you~
