### ISSUE TITLE
aws_iot_mqtt_attempt_reconnect() only fails for subsribe after 2nd reconnection.

### ISSUE THREAD

**Issue by taka-shirasu** [aws/aws-iot-device-sdk-embedded-C#1795]
I use the manual reconnect for the MQTT service when the Wi-Fi gets reconnected. I noticed that "subscribe" will stop working after the 2nd reconnection onwards but this is not the case for "publish" and also for the 2nd reconnection. Is this a feature on the AWS IoT Core side or a bug on the AWS SDK kit?

**Comment by taka-shirasu** [comment]
https://docs.google.com/document/d/1PfqNQNrrz0z_zbLjRPhGYh1IT4QjtDhEzknMuQX_UGg/edit?usp=sharing
Here are some screenshots.

**Comment by jasonpcarroll** [comment]
Hi @taka-shirasu,
Thank you for reaching out. Could you let me know what version/commit ID you are using?
Best,
Jason

**Comment by chinglee-iot** [comment]
Close this issue first. Please re-open this issue if information updated.
