### ISSUE TITLE
Shadow Timeout, when trying to get shadow using aws_iot_shadow_get() 

### ISSUE THREAD

**Issue by shubhamkumargupta** [aws/aws-iot-device-sdk-embedded-C#18]
I am using sample apps/shadow_sample.c to continuously get shadow by replacing aws_iot_shadow_update() with aws_iot_shadow_get().
Side by side I am using Mqtt.fx to Pub/Sub on shadow update topics. 
It work fine when I update shadow using Mqtt.fx with following json : 
{
    "state": {
        "reported": {
            "status": "BootUp"
        }
    }
}

Then after some time I update the thing Shadow using Mqtt.fx by Json : 
{
	"state": {
		"reported": {
			"status": "BootUp"
		},
		"desired": {
			"status": "Ready",
			"conf": {
				"measurementInterval": "5",
				"publishInterval": "10"
			}
		}
	}
}

Now, I getShadow using sample_shadow program it starts throwing error in shadow callback function SHADOW_ACK_TIMEOUT.
But, its working fine by Subscribing through Mqtt.fx on update/accepted topic. I have also seen the AWS IoT limit regarding message size and no. of level in Json. Is there any other limit related to C-SDK.

**Comment by shubhamkumargupta** [comment]
Got the issue need to change the size of macro AWS_IOT_MQTT_TX_BUF_LEN in aws_iot_config.h file.

**Comment by chaurah** [comment]
Hi Shubham,
       Glad to hear that you were able to sort the issue out. Please let us know if you have any further questions. Thank you for using AWS IoT.

Rahul
