### ISSUE TITLE
Getting error when Compile the code

### ISSUE THREAD

**Issue by truong32ct** [aws/aws-iot-device-sdk-embedded-C#180]
pi@raspberrypi://home/pi/Desktop $ gcc testdb.c -o testdb -std=c99  `mysql_config --cflags --libs`
In file included from testdb.c:14:0:
/home/pi/aws-iot-device-sdk-embedded-C/include/aws_iot_mqtt_client_interface.h:54:28: fatal error: aws_iot_config.h: No such file or directory
 #include "aws_iot_config.h"
                            ^
compilation terminated.
 
I am using raspberry pi 3 publish message, my code involves involve some other sources. I did not put the source file (.c file) in the aws-iot directory. When I try to compile the code, it failed even I pointed properly to the directory of the aws folders. So how can I compile the code when I did not put it in aws directory?

**Comment by gordonwang0** [comment]
Hi @truong32ct,

Have you specified the include paths to `gcc` with the `-I` option?

**Comment by truong32ct** [comment]
I already did it when adding some flag to point to the path, thank you godonwang0. Sorry for late response.

**Comment by truong32ct** [comment]
I have a new question: I am trying to publish a message from AWS IoT to control my Raspberry Pi (I am using aws_iot_mqtt_subscribe on my Raspberry Pi to subscribe the message from AWS IoT). However, It receives the message but it does not execute my command. My code at that point is:

rc = aws_iot_mqtt_subscribe(&client, "temperature", 11, QOS0, iot_subscribe_callback_handler, NULL);
		if(rc == SUCCESS) {
		time_t current_time;
		current_time = time(NULL);
		
		char* c_time_string;
		c_time_string = ctime(&current_time);
		printf("current time: %s",c_time_string);
		if (mysql_query(con, "INSERT INTO data VALUES(112,223,false,current_time)")) {
			finish_with_error(con);
    		}
		}

I put it outside of the while loop: while((NETWORK_ATTEMPTING_RECONNECT == rc || NETWORK_RECONNECTED == rc || SUCCESS == rc)
		  && (publishCount > 0 || infinitePublishFlag))

**Comment by gordonwang0** [comment]
Hi @truong32ct,

Are you calling `aws_iot_mqtt_yield`?  This function must be called for incoming messages to be processed.

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/include/aws_iot_mqtt_client_interface.h#L175-L192

**Comment by truong32ct** [comment]
Thank you. I did it. But how can I define what exactly what the topicName is? 
I publish a message with the topic of "temperature" but when using "if condition", the topicName is not "temperature'.  How can I get exactly that result?
![image](https://user-images.githubusercontent.com/14815789/40064965-d48ee59e-588a-11e8-972e-3bb3a7c6ab83.png)

![image](https://user-images.githubusercontent.com/14815789/40064933-bd6963c6-588a-11e8-8cca-033db7b24d0f.png)

**Comment by gordonwang0** [comment]
Hi @truong32ct,

You should use `strncmp` (or if the string lengths can be bounded by a known constant, `strcmp`) to compare the strings.  Something like:

```c
#include <string.h>

#define TOPIC           "temperature"
#define TOPIC_LENGTH    (sizeof(TOPIC) - 1) /* 11 */

...

if(topicNameLen == TOPIC_LENGTH && strcmp(topicName, TOPIC) == 0 )
{
    /* Topics match. */
}
```

**Comment by truong32ct** [comment]
Hi @gordonwang0 ,
I tried to do your instruction but it still does not work. I execute these and I got these result. this function strcmp(topicName, TOPIC) return 117 which mean that the topicName and TOPIC (I define as "temperature") does not match. I do not know which part of the code is wrong and how to find the topicName?

![image](https://user-images.githubusercontent.com/14815789/40092667-b0e44388-58e8-11e8-9925-fff23bac11be.png)
![image](https://user-images.githubusercontent.com/14815789/40092681-c7ec4832-58e8-11e8-9f6b-5403197da8ac.png)

**Comment by truong32ct** [comment]
Hi @gordonwang0
I did it, I did not know that when clicking on "Publish to Topic" button, the topic name will be combined with the message and be sent to my Raspberry, so I have to leave the message as blank.
But can you tell me the different between _if(strcmp(topicName, "temperature")==0)_ and _if(topicName== "temperature")_ using function strcm it works well but another one does not?
![image](https://user-images.githubusercontent.com/14815789/40102906-ea23d5e6-5915-11e8-8aab-9c55d4663844.png)

**Comment by gordonwang0** [comment]
Hi @truong32ct,

In C, the string `"temperature"` is stored somewhere in memory.

```c
/* This line compares if the pointer values are equal.  It checks if the memory address
pointed to by topicName is the same as the memory address of the string "temperature".
It doesn't check if the characters in the strings are equal. */
if( topicName == "temperature" )

/* strcmp is a function that compares the characters in the strings. It will check if the strings
match. The string length check is critical: if it's missing, strcmp could read past the end of the
string. */
if(topicNameLen == TOPIC_LENGTH && strcmp(topicName, TOPIC) == 0 )
```

**Comment by truong32ct** [comment]
Hi @gordonwang0 ,
I got it, your answer was very detailed and helpful. Now I can handle this matter well with this issue. 
Thank you very much.

**Comment by gordonwang0** [comment]
You're welcome.  Let me know if you need any more help.  Closing issue.
