### ISSUE TITLE
How to use mbedtls

### ISSUE THREAD

**Issue by Zevolusion** [aws/aws-iot-device-sdk-embedded-C#1802]
If I using main branch, how to switch openssl to mbedtls? @butlerpaul

**Comment by dachalco** [comment]
Hi @Zevolusion 

Are you looking to build the demos with mbedtls or a separate project with mbedtls?

These stacks are in the platform layer so they can be swapped. There's a [porting guide](https://github.com/aws/aws-iot-device-sdk-embedded-C#porting-guide-for-20200900-and-newer-releases) giving all the details behind platform code. There's also existing mbedtls+corePKCS11 platform code you may [reference here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/platform/posix/transport/src/mbedtls_pkcs11_posix.c). Finally, you can also create your own transport layer and authentication steps as needed.

**Comment by Zevolusion** [comment]
Thanks @dachalco 
1. I try to build the demo with mbedtls first. What arguments should passed into cmake? Or should modify the CMakeLists?
2. What did u mean a separate project?

**Comment by ClaudioBaldo** [comment]
we are trying to compile the library for a yocto device which only supports openssl 1.0.2, would you have any example which just use mbdetls? As the "..._simple_tls" still implements and rely on openssl.

/* OpenSSL sockets transport implementation. */
#include "openssl_posix.h"

**Comment by ClaudioBaldo** [comment]
we are trying to compile the library for a yocto device which only supports openssl 1.0.2, would you have any example which just use mbdetls? As the "..._simple_tls" still implements and rely on openssl.

/* OpenSSL sockets transport implementation. */
#include "openssl_posix.h"

I understand the "porting" idea but I thought the whole point of having examples from aws team was to avoid user from "heavy lifting" and to speed up the time to market.

**Comment by ravibhagavandas** [comment]
I agree that we don't have all demos examples ported for all transport implementations. We will look into how best we can accommodate this to the demos. However you can look into functions `EstablishMqttSession` and `DisconnectMqttSession` in file  [mqtt_operations.c](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/fleet_provisioning/fleet_provisioning_with_csr/mqtt_operations.c). The provide Mbedtls implementation examples which can be directly consumed into demos.

**Comment by ravibhagavandas** [comment]
I will close the issue due to inactivity. Please open an issue if you still have questions.
