### ISSUE TITLE
Attempting a TLS connection to a3uvulybovep9z-ats.iot.us-west-2.amazonaws.com:8883

### ISSUE THREAD

**Issue by tritrantdt** [aws/aws-iot-device-sdk-embedded-C#1806]
ommiting target configuration...
[ DEBUG ] TX: b'conf set time_hwm 1653281746\r\n' (_send_cmd) (provision.py:_send_cmd)
[ DEBUG ] RX: b'\r\x1b[K<INF>  2577380 [MQTTAgent ] Attempting a TLS connection to a3uvulybovep9z-ats.iot.us-west-2.amazonaws.com:8883. (mqtt_agent_task.c:1101)\r\n' (_send_cmd) (provision.py:_send_cmd)
Traceback (most recent call last):
  File "C:\iot-reference-stm32u5\tools\provision.py", line 935, in <module>
    main()
  File "C:\iot-reference-stm32u5\tools\provision.py", line 922, in main
    target.conf_commit()
  File "C:\iot-reference-stm32u5\tools\provision.py", line 275, in conf_commit
    self._send_cmd(b"conf set", key, self._staged_config[key])
  File "C:\iot-reference-stm32u5\tools\provision.py", line 107, in _send_cmd
    raise TargetDevice.ReadbackError()
__main__.TargetDevice.ReadbackError

**Comment by n9wxu** [comment]
Have you configured the certificate and private key with values linked to this endpoint?
Have you added the Amazon root ca to your device so the endpoint tls can be validated by your device?

**Comment by paulbartell** [comment]
Github Issue were not enabled for the iot-reference-stm32u5 repository. I've now enabled them.

@tritrantdt : As a temporary workaround you may do either of the following:
1. Erase the external NOR flash with STM32CubeProgrammer **OR**
2. Set an invalid wifi ssid via the serial console (putty, terraterm, screen, or similar), reset, then re-run provision.py.

```
conf set wifi_ssid
conf commit
reset
```

**Comment by aggarg** [comment]
I am closing this issue. Please feel free to reopen or create a new one if you still face any issue.
