### ISSUE TITLE
Fleet provisioning library compilation issues

### ISSUE THREAD

**Issue by manav-eheat** [aws/aws-iot-device-sdk-embedded-C#1807]
We are trying to implement the Fleet provisioning using the following reference 
https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/demos/fleet_provisioning/fleet_provisioning_with_csr
We are facing many compilation errors (attached). Please help providing the package and libraries which are built completely for Fleet provisioning for embedded-C SDK.
thanks,
eHeat

**Comment by jasonpcarroll** [comment]
Hi @manav-eheat,
Sorry for the late reply. I do not see your attached logs. If you could please re-attach or just past them here - I will look into this issue.
Best,
Jason Carroll

**Comment by paulbartell** [comment]
@manav-eheat : For Espressif platforms, we recommend using the [esp-aws-iot component](https://github.com/espressif/esp-aws-iot) which contains many of the same libraries used in this repository. 

You may also reference our [esp32c3 reference integration](https://github.com/FreeRTOS/iot-reference-esp32c3) for some setup guidance. Most of it should be applicable to other SoCs from Espressif.

Regarding fleet provisioning, the most applicable reference for you is probably our [Windows Simulator Fleet Provisioning Demo](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS-Plus/Demo/AWS/Fleet_Provisioning_Windows_Simulator/Fleet_Provisioning_With_CSR_Demo) which is explained on [this page](https://www.freertos.org/iot-fleet-provisioning/demo.html).

Newer SoCs from Espressif also have a [Digital Signature](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/ds.html) peripheral, meant for storing private keys, which may be preferable to storing keys in NVS or SPIFFS.

corePKCS11 does not have a DS peripheral backend available. For certificate storage, you might consider enabling the espressif [Virtual Filesystem](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/vfs.html) and [SPIFFS]  components and replacing pkcs11 calls with mbedtls native functions like mbedtls_x509_crt_parse_file or using functions like mbedtls_x509_crt_parse_der with the [NVS](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_flash.html) module.

If a DS peripheral is not available on your platform, you may also store private keys in flash. We recommend that you always encrypt private keys at rest.
