### ISSUE TITLE
AWS IoT reconnection

### ISSUE THREAD

**Issue by mkonnov** [aws/aws-iot-device-sdk-embedded-C#182]
Hi everyone.
I'm working with ESP32 powered by battery cells.
I need to continuously turn WiFI off to save power and, consequently, continuously close the TLS socket.

Do smbd have any working code / reference to a working code that closes and reopens the connection successfully ?
Thanks !

**Comment by lt72** [comment]
Hi mkonnov,
the publish/subscribe sample has some code that handle disconnect, and attempts to reconnect. 
I am not sure that covers your scenario, but worth verifying.
Please take a look at the sample file [subscribe_publish_library_sample.c](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/samples/linux/subscribe_publish_sample/subscribe_publish_sample.c) abd let us know if that addresses your needs.

**Comment by mkonnov** [comment]
@lt72 Thanks ! I'll report as only I have any result.

**Comment by mkonnov** [comment]
I just took a look at this file and it seems there's no `aws_iot_shadow_disconnect()` is used.
But I see there's `aws_iot_mqtt_attempt_reconnect(pClient)` is used.
Would it fit into my need of constant intentional disconnection ?

**Comment by mkonnov** [comment]
@ravibhagavandas 
Thank you.
This way, I can shut down the wifi connection without of invoking `aws_iot_mqtt_attempt_reconnect`, correct ? Of course, after tweaking the exponential backoff interval defines.

**Comment by ravibhagavandas** [comment]
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/samples/linux/subscribe_publish_sample/subscribe_publish_sample.c#L225

Yes, the loop here attempts to reconnect every time after a given interval upto the maximum interval specified as above.

**Comment by mkonnov** [comment]
Thanks everyone.
That's works.
