### ISSUE TITLE
sample program 'subscribe_publish_sample not working' on Ubuntu Linux doesn't work

### ISSUE THREAD

**Issue by jflynn129** [aws/aws-iot-device-sdk-embedded-C#183]
I downloaded the AWS Embedded C SDK (https://github.com/aws/aws-iot-device-sdk-embedded-C/) to a Ubuntu Linux machine and have been trying to run the subscribe_publish_sample that is contained in it.

I am following the README instructions for building the subscribe_publish_sample and downloaded mbedTLS from https://github.com/ARMmbed/mbedtls, put it into the external library directory, then generated a set of certificates from https://us-west-2.console.aws.amazon.com/iot/home?region=us-west-2#/certificatehub, then created a policy that enables iot:* [by the way, there is minimal mention for creating the certificates or policy in the README instructions. It would be good to give a link to something that describes their operation/use]. 

After this, the sample program compiles without issue, but when running, it always ends up throwing a:
ERROR: main L#190 Error(-12) connecting to a1075elwyht7bd.iot.us-west-2.amazonaws.com:443 error.

The complete output generated by the program is:

```
AWS IoT SDK Version 3.0.1-
DEBUG: main L#159 rootCA /home/jim/AWS/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/rootCA.crt
DEBUG: main L#160 clientCRT /home/jim/AWS/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/be7945653d-certificate.pem.crt
DEBUG: main L#161 clientKey /home/jim/AWS/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample/../../../certs/be7945653d-private.pem.key
Connecting...
DEBUG: iot_tls_connect L#130
. Seeding the random number generator...
DEBUG: iot_tls_connect L#138 . Loading the CA root certificate ...
DEBUG: iot_tls_connect L#144 ok (0 skipped)
DEBUG: iot_tls_connect L#146 . Loading the client cert. and key...
DEBUG: iot_tls_connect L#159 ok
DEBUG: iot_tls_connect L#161 . Connecting to a1075elwyht7bd.iot.us-west-2.amazonaws.com/443...
DEBUG: iot_tls_connect L#180 ok
DEBUG: iot_tls_connect L#182 . Setting up the SSL/TLS structure...
DEBUG: iot_tls_connect L#223
SSL state connect : 0
DEBUG: iot_tls_connect L#226 ok
DEBUG: iot_tls_connect L#228
SSL state connect : 0
DEBUG: iot_tls_connect L#229 . Performing the SSL/TLS handshake...
DEBUG: _iot_tls_verify_cert L#49
Verify requested for (Depth 2):
DEBUG: _iot_tls_verify_cert L#51 cert. version : 3
serial number : 18:DA:D1:9E:26:7D:E8:BB:4A:21:58:CD:CC:6B:3B:4A
issuer name : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
issued on : 2006-11-08 00:00:00
expires on : 2036-07-16 23:59:59
signed using : RSA with SHA1
RSA key size : 2048 bits
basic constraints : CA=true
key usage : Key Cert Sign, CRL Sign
DEBUG: _iot_tls_verify_cert L#54 This certificate has no flags
DEBUG: _iot_tls_verify_cert L#49
Verify requested for (Depth 1):
DEBUG: _iot_tls_verify_cert L#51 cert. version : 3
serial number : 3F:92:87:BE:9D:1D:A4:A3:7A:9D:F6:28:2E:77:5A:C4
issuer name : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
issued on : 2015-05-12 00:00:00
expires on : 2025-05-11 23:59:59
signed using : RSA with SHA-256
EC key size : 256 bits
basic constraints : CA=true, max_pathlen=0
subject alt name :
key usage : Key Cert Sign, CRL Sign
DEBUG: _iot_tls_verify_cert L#54 This certificate has no flags
DEBUG: _iot_tls_verify_cert L#49
Verify requested for (Depth 0):
DEBUG: _iot_tls_verify_cert L#51 cert. version : 3
serial number : 53:A5:8B:08:C9:5D:59:62:DE:90:E0:B2:9E:43:68:69
issuer name : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
subject name : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.iot.us-west-2.amazonaws.com
issued on : 2017-11-22 00:00:00
expires on : 2018-11-23 23:59:59
signed using : ECDSA with SHA256
EC key size : 256 bits
basic constraints : CA=false
subject alt name : iot.us-west-2.amazonaws.com, *.iot.us-west-2.amazonaws.com
key usage : Digital Signature
ext key usage : TLS Web Server Authentication, TLS Web Client Authentication
DEBUG: _iot_tls_verify_cert L#54 This certificate has no flags
DEBUG: iot_tls_connect L#246 ok
[ Protocol is TLSv1.2 ]
[ Ciphersuite is TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384 ]
DEBUG: iot_tls_connect L#248 [ Record expansion is 29 ]
DEBUG: iot_tls_connect L#253 . Verifying peer X.509 certificate...
DEBUG: iot_tls_connect L#262 ok
DEBUG: iot_tls_connect L#272 . Peer certificate information ...
DEBUG: iot_tls_connect L#274 cert. version : 3
serial number : 53:A5:8B:08:C9:5D:59:62:DE:90:E0:B2:9E:43:68:69
issuer name : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
subject name : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.iot.us-west-2.amazonaws.com
issued on : 2017-11-22 00:00:00
expires on : 2018-11-23 23:59:59
signed using : ECDSA with SHA256
EC key size : 256 bits
basic constraints : CA=false
subject alt name : iot.us-west-2.amazonaws.com, *.iot.us-west-2.amazonaws.com
key usage : Digital Signature
ext key usage : TLS Web Server Authentication, TLS Web Client Authentication
ERROR: main L#190 Error(-12) connecting to a1075elwyht7bd.iot.us-west-2.amazonaws.com:443

```
I investigated some because it was previously stated that a -12 error is the result of incorrect connectParams, I haven’t modified the connectParams in the subscribe_publish_sample, but for the record, they are:

> connectParams.keepAliveIntervalInSec = 600;
> connectParams.isCleanSession = true;
> connectParams.MQTTVersion = MQTT_3_1_1;
> connectParams.pClientID = AWS_IOT_MQTT_CLIENT_ID;
> connectParams.clientIDLen = (uint16_t) strlen(AWS_IOT_MQTT_CLIENT_ID);
> connectParams.isWillMsgPresent = false;
> 

I’ve investigated this some to determine what the error means, and what I found was that the AWS servers are closing the connection per the mbedtls error code that is returned (0x7880 - MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY) within the iot_tls_read (in the network_mbedtls_wrapper.c).

Either the sample program has an issue, the setup instructions are omitting something, or some AWS dashboard setting must be modified for the sample program to work.  I’m not sure what, but I would like to actually see the sample program work per the README instructions.  

Can someone look at this and let me know what the issue is?

**Comment by lt72** [comment]
@ravibhagavandas: Ravi ,could you please look into this issue?

**Comment by ravibhagavandas** [comment]
From the debug logs and setup, it looks like certificates are fine and ssl negotiation completed but the connect failed afterwards. This could probably be a permission problem.
Additional to the setup above, did you also perform following:
 1. Create a thing in AWS Iot console (Refer doc [here](https://docs.aws.amazon.com/iot/latest/developerguide/register-device.html))
2. Attach the certificates to thing (Refer doc [here](https://docs.aws.amazon.com/iot/latest/developerguide/attach-cert-thing.html)). You also need to also attach the iot policy to this certificate.
3. Use the same thing name in subscribe_publish_sample config file:
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/samples/linux/subscribe_publish_library_sample/aws_iot_config.h#L29

**Comment by jflynn129** [comment]
@ravibhagavandas I have created a thing in the AWS Iot console and I created a policy, ie:
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "arn:aws:iot:us-west-2:405405341537:topic/replaceWithATopic"
    }
  ]
}

I connected the policy to the certificate and the certificate is attached to the Thing.  The Thing name is 'AWS-IoT-C-SDK' in the aws_iot_config.h file.  What else can I do, it still says: 
ERROR: main L#190 Error(-12) connecting to a1075elwyht7bd.iot.us-west-2.amazonaws.com:443

BTW, I also tried connecting to port 8883, no difference.  I see it is negotiating the ssl connections successfully, but then fails.  I put some logging into the wrapper file and captured:
JMF: iot_tls_write called
JMF: write SUCCESS!
JMF: iot_tls_read called
JMF: read ERROR! ret=-30848 (0x7880)

which is why I know that  the AWS servers are closing the connection per the mbedtls returned error code  (0x7880 = MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY)

**Comment by ravibhagavandas** [comment]
As you can see from the above policy,  it grants iot operations to only a specific topic which is "replaceWithATopic"

To get connected to IOT you need to allow iot:Connect permission to the mqtt broker. A sample policy template would look something like this: 
``
{
    "Version": "2012-10-17",
    "Statement": [
    {
        "Effect": "Allow",
        "Action": "iot:Connect",
        "Resource":"arn:aws:iot:<aws-region>:<aws-account-id>:*"
	}, 
    {
        "Effect": "Allow",
        "Action": "iot:Publish",
        "Resource": "arn:aws:iot:<aws-region>:<aws-account-id>:*"
    },
    {
         "Effect": "Allow",
         "Action": "iot:Subscribe",
         "Resource": "arn:aws:iot:<aws-region>>:<aws-account-id>:*"
    },
    {
         "Effect": "Allow",
         "Action": "iot:Receive",
         "Resource": "arn:aws:iot:<aws-region>:<aws-account-id>:*"
    }
    ]
} 
``
If you need to be less permissive you can replace the wildcards (*) with specific topic names (for iot:Publish, iot:Subscribe)

**Comment by jflynn129** [comment]
I edited my policy to read:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "arn:aws:iot:us-west-2:405405341537:topic/replaceWithATopic"
    }
  ]
}

```
And the example is now working as expected.  Is there a document that better explains this you can point me to. It wasn't clear in the sample README about all these steps or the capabilities you can enact with policies.
Thank you, I'll close this issue now.

**Comment by ashishbharadwaj100** [comment]
Change the policy and use this link everything will be ok 

https://medium.com/tensoriot/aws-iot-creating-your-first-cloud-bound-device-d8dca0695f43
