### ISSUE TITLE
Problem with delta callbacks when an array of objects changes

### ISSUE THREAD

**Issue by teemuniiranen** [aws/aws-iot-device-sdk-embedded-C#184]
Seems like I can't receive delta message when the only change relates to an array of objects.

Delta is received when the arrays is empty or when I add the first item but after the first item delta callback function does not get called. Also when removing the final item the delta callback is called.

I see correct messages after each modification in AWS IoT tester when subscribing to $aws/things/thingName/shadow/update/delta but only on device side when first item is added or final deleted.

Version used: linux_mqtt_mbedtls-2.1.1

Have someone encountered the similar issue? Many thanks!

**Comment by huguesBouvier** [comment]
From https://docs.aws.amazon.com/iot/latest/developerguide/using-device-shadows.html and https://docs.aws.amazon.com/iot/latest/developerguide/using-device-shadows.html, you cannot update part of the array. Arrays are treated like a value. You have to give a new array every time.

**Comment by huguesBouvier** [comment]
Sorry, I may be missing the problem. You are not seeing any delta callback even when the full array is updated? Or you would like a work around solution so you don't have to update the full array to get a delta callback?

**Comment by teemuniiranen** [comment]
I can't see any delta callback when the full array of objects is updated. Only when array is empty or after deletion new array is updated with one object.

**Comment by huguesBouvier** [comment]
Hey,

I made the test, it works for me. Array are not treated any differently than any other value. Did you manage to get it work with something else than an array?
1. Shadow delta get generated when the DESIRED state is different than the reported state. So you need to use the function: **aws_iot_shadow_add_reported** at least once in the beginning then use **aws_iot_shadow_add_desired**
2. Is your application registering the callback? **aws_iot_shadow_register_delta**

**Comment by teemuniiranen** [comment]
Hey,

It works for all other values but only with empty arrays and arrays that has size of one. I tried also update from empty array to two items but the result is same. Can you share the example that you tested with?

**Comment by teemuniiranen** [comment]
Problem solved finally!

Problem was in following default buffer lengths that were just too small:
#define AWS_IOT_MQTT_TX_BUF_LEN
#define AWS_IOT_MQTT_RX_BUF_LEN

It was really difficult to spot and I suggest adding this to README.md as a troubleshooting case. Many thanks!
