### ISSUE TITLE
Tunnelling services

### ISSUE THREAD

**Issue by GiulioDallaVecchia** [aws/aws-iot-device-sdk-embedded-C#1840]
Hi all,

I'm struggling to understand how I can establish a connection to my web-server. I'm working on a project, running on a STM32 microcontroller, where it's running a HTTP server. I need to access to that HTTP server from anywhere in the world, but I don't understand how I can achieve that. I've seen that with AWS I can redirect the TCP traffic to a specific device, right? I think that my device has to open a connect to AWS a register to it. After that I need to generate a URL with whom a client can connect to the web server.

Can you help me?

Thanks a lot in advance!

GDV

**Comment by shubnil** [comment]
Hi,
Thanks for posting this interesting use-case. We are looking into the same and will add more once we have more data.

**Comment by archigup** [comment]
As far as I can tell, this does not have anything to do with the CSDK repo and libraries? The CSDK does not include any HTTP server software, only an HTTP client library.

**Comment by GiulioDallaVecchia** [comment]
Yes, but I don't need to create a http server. I already have a server that is running on my board. I want to understand how, with AWS, I can contact that server when my board is connected under a private network (without using a public IP + DNS). From what I understood with AWS I can create a tunnel so that, with a public URL I can connect to my private http server that is running on my private network.

**Comment by alfred2g** [comment]
Hello @GiulioDallaVecchia,
I can recommend a few solutions and technologies with AWS ( [AWS direct connect facility](https://aws.amazon.com/directconnect/) ) , but I am afraid my solution might not be the optimal for your usecase 
For better support with AWS services and how to connect them together I would recommend you to ask that question at: https://repost.aws where it will get much better traction.
I will close this issue as we are not the best here to give it its full potential.
Please reopen if you have any other question or concern.
