### ISSUE TITLE
If the cloud platform is disconnected, the sdk will not call back the disconnected state

### ISSUE THREAD

**Issue by guowusheng** [aws/aws-iot-device-sdk-embedded-C#1847]
Currently, a problem has been found: sometimes when the connection with the cloud platform is disconnected, the sdk will not call back the disconnected state

**Comment by guowusheng** [comment]
![image](https://user-images.githubusercontent.com/83354085/210976204-1c1816df-084d-4a69-ae8e-248094b46961.png)
![image](https://user-images.githubusercontent.com/83354085/210976272-63e5a632-cc04-4e9c-a73e-e23dd7e2aa82.png)

**Comment by AniruddhaKanhere** [comment]
Hello @guowusheng,

Thank you for reaching out to us.
If I understand correctly, when your device is disconnected from the broker the code fails to call the callback (`aws_iot_disconnect_handler` highlighted above). Is that accurate?

Also, may I ask which platform are you using? Also, have you tried stepping through the code to see what happens during a disconnect?

Thanks,
Aniruddha

**Comment by alfred2g** [comment]
Closing for 7 days inactivity, please reopen when more information are available
