### ISSUE TITLE
Support need to build for arm architecture

### ISSUE THREAD

**Issue by georgethomas08** [aws/aws-iot-device-sdk-embedded-C#1854]
Hi Team,

I'm facing difficulty in using this library on arm based embedded system, If you have any detailed video or step by step documentation of using this library on arm based system Please do share

**Comment by Skptak** [comment]
Hey @georgethomas08 sorry to hear that you're having issues getting this to build for an ARM based system. I was wondering if you could provide some more information about what exactly you're trying to do and what the issues you are facing are?
The CSDK does contain a [Getting Started Guide](https://github.com/aws/aws-iot-device-sdk-embedded-C#getting-started) that goes the steps and instructions for how to run many of the demos that exist in the repository. I'd highly recommend starting here if you haven't!
If you can provide the requested information about your errors and use case I'd be more than happy to assist you with any problems you're facing!
