### ISSUE TITLE
*** No targets specified and no makefile found.

### ISSUE THREAD

**Issue by borch84** [aws/aws-iot-device-sdk-embedded-C#187]
Hi, I just git cloned the repo https://github.com/aws/aws-iot-device-sdk-embedded-C.git to my raspberrypi and went through the samples, I am trying to compile the subscribe_publish_sample but I got no targets specified and no makefile found. 

Am I missing something? 

Thank you.

`pi@raspberrypi:~/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample $ make 
make -C ../../../external_libs/mbedTLS
make[1]: Entering directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/pi/aws-iot-device-sdk-embedded-C/external_libs/mbedTLS'
Makefile:63: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspberrypi:~/aws-iot-device-sdk-embedded-C/samples/linux/subscribe_publish_sample $ `

**Comment by truong32ct** [comment]
You have download mbedTLS library and copy it into ...external/mbedTLS directory

**Comment by borch84** [comment]
hi @truong32ct , I was able to compile it, I was missing the mbedTLS library. Thank you.

**Comment by hokephyllis** [comment]
This totally helped me too.  Thanks.   I had the mbTLS one dir too deep for the makefile to find it.
