### ISSUE TITLE
Question about the transport

### ISSUE THREAD

**Issue by jamesluo11** [aws/aws-iot-device-sdk-embedded-C#1872]
I'm trying to port the aws iot sdk embeded c to our embededed system, which runs on FreeRTOS and ARM. 
When i executed the cmake, i found the SDK have dependency on OpenSSL library, and i have no configuration to avoid this check.
I think in most embeded system, there is  mbedtls instead. 
![图片](https://github.com/aws/aws-iot-device-sdk-embedded-C/assets/92912812/7f6dfd1a-cf3e-4c03-b194-a5d3fd4b7c50)

**Comment by ActoryOu** [comment]
Hi @jamesluo11,
Thanks for your feedback.

If I understand your issue completely, you're now running FreeRTOS based on ARM chip set, which is not POSIX system.
In this repository, we're now supporting posix only. ([posix directory under platform](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/main/platform/posix))

I'd suggest you to 
1. Take [Featured FreeRTOS IoT Reference Integration(with NXP RT1060)](https://www.freertos.org/NXP-RT1060-SE050/) as reference.
    - We provide an example based on NXP RT1060 + FreeRTOS with lots of libraries integrated and [the repository](https://github.com/FreeRTOS/iot-reference-nxp-rt1060) is also an open source.
1. Take FreeRTOS as reference.
    - There are many [demo applications](https://www.freertos.org/a00102.html) as reference, and all demos are running on FreeRTOS.
    - Or you can refer to [FreeRTOS/FreeRTOS repo](https://github.com/FreeRTOS/FreeRTOS/tree/main/) to see how we integrate the libraries into FreeRTOS.

BTW, I suggest to post the question on [FreeRTOS Forum](https://forums.freertos.org/).
There are many experts answering questions.

Let me know if you have further questions.

Thanks.

**Comment by ActoryOu** [comment]
Hi @jamesluo11,
I'm closing this issue since there is no further questions.
Feel free to create a new one if any further questions.

Thanks!
