### ISSUE TITLE
Requesting examples without SSL

### ISSUE THREAD

**Issue by karthikkumarb** [aws/aws-iot-device-sdk-embedded-C#1873]
Hi, Do you have any samples which can be connected to different brokers without the use of SSL, I need to connect using username and password not with any SSL certificates.

**Comment by ActoryOu** [comment]
Hi @karthikkumarb,
Here is a [MQTT demo without TLS](https://www.freertos.org/mqtt/basic-mqtt-example.html) on FreeRTOS.org.
You can refer to that document and try it on [FreeRTOS/FreeRTOS repo](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS-Plus/Demo/coreMQTT_Windows_Simulator/MQTT_Plain_Text).

BTW, I'll suggest to ask generic question on [FreeRTOS Forum](https://forums.freertos.org/).
There are lots of experts helping users hand on.

Thanks.

**Comment by karthikkumarb** [comment]
Thanks

**Comment by ActoryOu** [comment]
I'm closing this issue, feel free to reopen it if you have further questions.

**Comment by karthikkumarb** [comment]
Hi @ActoryOu, 
Sorry for reopening this, I was able to get the plaintext working on a Linux machine, But I am looking for an example where we do only subscribe and wait for published messages from the broker. In the Plaintext example, it subscribes and publishes to the same topic.
