### ISSUE TITLE
In order to increase the number of topics which defines in the stack need to modified. 

### ISSUE THREAD

**Issue by SwapnaBaviskarEmr** [aws/aws-iot-device-sdk-embedded-C#1879]
We are using the aws sdk 3.1.0  and want to increase the number of topics to subscribe to 14.  

Have a question on which #define(s) in the AWS SDK code should be changed to support 14 topics?

In the aws_iot_config.h :
**#define AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS   10 ///< Maximum number of topic filters the MQTT client can handle at any given time. This should be increased appropriately when using Thing Shadow**

Should we change the AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS   to 14.

Also do we need to change the MAX_THINGNAME_HANDLED_AT_ANY_GIVEN_TIME to 14.
**#define MAX_THINGNAME_HANDLED_AT_ANY_GIVEN_TIME   10 ///< We could perform shadow action on any thing Name and this is maximum Thing Names we can act on at any given time**

Please let me know.

Thanks and Regards,
Swapna.

**Comment by rawalexe** [comment]
Hello Swapna, 
We apologize for the lack of documentation, I'll bring this to the team's Subject Matter Expert and get back to you ASAP.

Best Regards,
AR

**Comment by rawalexe** [comment]
Hello Swapna,
After looking into it, you may change the values within the config file as per your need should you have enough memory for it.

Also, Please update the SDK to the latest version if possible.

Best Regards,
AR

**Comment by SwapnaBaviskarEmr** [comment]
Hi,

Thanks for your response.
Memory is not an issue. 
Can you please point me to the document where it is documented which defines we need to change in the aws_iot_config.h file to subscribe to topics. 

Thanks and Regards,
Swapna.

**Comment by rawalexe** [comment]
Greetings,
These old repos aren't very well maintained and documented. I manually looked into the code and at glance, the only concern I had was of memory. Unfortunately this is the best I have: http://aws-iot-device-sdk-embedded-c-docs.s3-website-us-east-1.amazonaws.com/index.html  for you for now.

**Comment by rawalexe** [comment]
I'm closing the issue for now, please let us know if you have any other questions.
