### ISSUE TITLE
ERROR: main L#195 Error(-41) connecting to mqtt_broker:8883

### ISSUE THREAD

**Issue by borch84** [aws/aws-iot-device-sdk-embedded-C#188]
Hi, I am testing the subscribe_publish_sample but I am getting this error:

ERROR: main L#195 Error(-41) connecting to mqtt_broker:8883

I checked the RC -41 which is: MQTT_CONNACK_NOT_AUTHORIZED_ERROR 

I already added the username and password of my mqtt broker inside the task_mqtt_report function:

connectParams.pUsername = "user"; 
connectParams.usernameLen = (uint16_t) strlen("user");
connectParams.pPassword = "pass01"; 
connectParams.passwordLen = (uint16_t) strlen("pass01");

However I am still getting error -41. I have already configured aws_iot_config.h with the details of my broker. TLS handshake occurs without errors.

What else should I check? Thank you.

**Comment by huguesBouvier** [comment]
Hi,

Is your variable connectParams located on the stack or on the heap? If it is a local variable, try to make it global since password is not copied. That's an easy potential issue I can see.
Hugues

**Comment by borch84** [comment]
Hi @huguesBouvier I moved the connectParams definition to the beginning of the code, just before the definition of HOST variables at line number 46. 

IoT_Client_Connect_Params connectParams;

Then at line 148 I included this line:

connectParams = iotClientConnectParamsDefault;

However I am getting the same error:

ERROR: main L#199 Error(-41) connecting to 192.168.0.16:8883

**Comment by huguesBouvier** [comment]
Hi,

Then the other idea the would come to mind is to use another client than the SDK to connect to you broker. Mosquitto Client could do this I think. Connecting with mosquitto could rule out any potential setup issue in the broker.
If it works, the next step could be looking at the logs and check how they are different, that would help pinpointing the issue in the SDK.
Hugues

**Comment by gordonwang0** [comment]
Hi @borch84,

Please let us know if you need any more help with this.  Closing issue.
