### ISSUE TITLE
Facing issue with the aws_iot_mqtt_yield

### ISSUE THREAD

**Issue by SwamidasSilabs** [aws/aws-iot-device-sdk-embedded-C#1882]
Hi Team,

I am facing one issue with the _aws_iot_mqtt_internal_yield function, Here is my test case.
My module is the client and has called aws_iot_mqtt_yield with a timeout of 1000 milliseconds. The _aws_iot_mqtt_internal_yield has a do-while that loops till the 1000 milliseconds time expires irrespective of whether the data is received. The 1st loop has received the data from the server whereas the 2nd loop hasn't, and it comes out with a timeout error, how can I consume or use the data received in the 1st loop?

**Comment by kstribrnAmzn** [comment]
Hello @SwamidasSilabs! To help. me in my investigation can you please provide which version of the SDK you are using? A specific commit hash/id for that release is even more helpful.

**Comment by kstribrnAmzn** [comment]
I took a look at the latest version of the code with the `_aws_iot_mqtt_internal_yield` function (v3.0.1) and I believe I found how the call to handle the data received is to work.

Overall the function trace looks like...
1. `aws_iot_mqtt_yield` ([line](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/src/aws_iot_mqtt_client_yield.c#L261)) which in turn calls
2. `_aws_iot_mqtt_internal_yield` ([line](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/src/aws_iot_mqtt_client_yield.c#L181)) in turn calling
3. `aws_iot_mqtt_internal_cycle_read` ([line](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/src/aws_iot_mqtt_client_common_internal.c#L581)) which calls
4. `_aws_iot_mqtt_internal_handle_publish` ([line](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/src/aws_iot_mqtt_client_common_internal.c#L532)) which calls
5. `_aws_iot_mqtt_internal_deliver_message` ([line](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/src/aws_iot_mqtt_client_common_internal.c#L492)) which calls a registered message handler provided by the application

The message handlers are set when [subscribing to an MQTT topic](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/src/aws_iot_mqtt_client_subscribe.c#L263-L271). 

Have you set up a message handler for the MQTT topic which you are expecting to receive data on?

**Comment by SwamidasSilabs** [comment]
Hi @kstribrnAmzn 

We haven't registered a message handler to receive the data, But we are synchronously trying to read the data which the SDK has stored in the buffer (pclient->clientData.readBuf).

In my case, the execution is not coming to the _aws_iot_mqtt_internal_handle_publish  function, As from the 2nd iteration I am getting the error because the server is not sending any data to the client from the 2nd iteration. In the aws_iot_mqtt_internal_cycle_read function, there is a condition so the elseif part is executing for me and returning from the function without executing the publish case.

if(MQTT_NOTHING_TO_READ == rc) {
		/* Nothing to read, not a cycle failure */
		return SUCCESS;
	} else if(SUCCESS != rc) {
		return rc;
	}

**Comment by SwamidasSilabs** [comment]
Hi @kstribrnAmzn 

Thanks for your reply, I have registered a message handler and the handler is getting triggered when the data arrives.

I have one more doubt here, Can't we receive the data without registering the message handler, You can assume like a synchronous receive.

Thanks,
Swamidas

**Comment by SwamidasSilabs** [comment]
Thanks @aggarg 

I have registered the message handler and am able to process the data.

**Comment by aggarg** [comment]
Great. I am closing this issue. Feel free to reopen or create a new one if you need anything else.
