### ISSUE TITLE
How can I make the "mqtt_demo_mutual_auth"  to  integrate with custom authentication?

### ISSUE THREAD

**Issue by leozzmc** [aws/aws-iot-device-sdk-embedded-C#1885]
Hi experts!

I try to follow the AWS tutorial to implement the mqtt_mutal_tls and it works successfully.
> https://docs.aws.amazon.com/iot/latest/developerguide/iot-embedded-c-sdk.html

*Screenshot for successfully with mutual TLS*
![image](https://github.com/aws/aws-iot-device-sdk-embedded-C/assets/30616512/2a474b3b-7fa5-4e22-9060-266aef576d21)

However when i want to try custom authentication with username/password with this SDK, I was facing problems.

#### My Setting

- Configure a lambda authorizer witht the Nodejs sample code in[ AWS official documents](https://docs.aws.amazon.com/iot/latest/developerguide/config-custom-auth.html)
> I've test this Lambda authorizer, which works well !
> command for testing:
```bash
 aws iot test-invoke-authorizer --authorizer-name LambdaAuth \
--mqtt-context '{"username":"kevin", "password": "dGVzdA==", "clientId":"testclient"}'
```
- modify the `~/aws-iot-device-sdk-embedded-c/demos/mqtt/mqtt_demo_mutual_auth/demo-config.h`

```c
/**
 * @brief AWS IoT MQTT broker port number.
 *
 * In general, port 8883 is for secured MQTT connections.
 *
 * @note Port 443 requires use of the ALPN TLS extension with the ALPN protocol
 * name. When using port 8883, ALPN is not required.
 */
#ifndef AWS_MQTT_PORT
    #define AWS_MQTT_PORT    ( 443 )
#endif
```
```c
/**
 * @brief The username value for authenticating client to MQTT broker when
 * username/password based client authentication is used.
 *
 * Refer to the AWS IoT documentation below for details regarding client
 * authentication with a username and password.
 * https://docs.aws.amazon.com/iot/latest/developerguide/custom-authentication.html
 * As mentioned in the link above, an authorizer setup needs to be done to use
 * username/password based client authentication.
 *
 * @note AWS IoT message broker requires either a set of client certificate/private key
 * or username/password to authenticate the client. If this config is defined,
 * the username and password will be used instead of the client certificate and
 * private key for client authentication.
 */
 #define CLIENT_USERNAME    "kevin"
 

/**
 * @brief The password value for authenticating client to MQTT broker when
 * username/password based client authentication is used.
 *
 * Refer to the AWS IoT documentation below for details regarding client
 * authentication with a username and password.
 * https://docs.aws.amazon.com/iot/latest/developerguide/custom-authentication.html
 * As mentioned in the link above, an authorizer setup needs to be done to use
 * username/password based client authentication.
 *
 * @note AWS IoT message broker requires either a set of client certificate/private key
 * or username/password to authenticate the client.
 */
 #define CLIENT_PASSWORD    "test"
```
 
- Generate makefile with solely `cmake` command, and compile the files with `make` command.

- The I execute the excutable

```
./mqtt_demo_mutual_demo
``` 
The results shows that the MQTT connection failed

<img width="706" alt="image" src="https://github.com/aws/aws-iot-device-sdk-embedded-C/assets/30616512/5517c980-0223-4e54-96a5-3b6bdcd7db5d">

#### My HOST
- EC2, t2.micro
- AMI: debian-12-amd64-20230711-1438

It there any guidance?

**Comment by chinglee-iot** [comment]
Hi @leozzmc,
I don't have experience with custom authentication demo so probably it will take some time to solve the problem with you. At the same time, I will also consult experienced member.

This first problem I saw from your log is that openSSL is not able to receive data. The reason is when CLIENT_USERNAME is defined, client cert and private key setup will be skipped in the demo. Client cert and private key is still required to connect to AWS IoT core.
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/af6b6efc09d98dea8dadc3db1e2992b593abb104/demos/mqtt/mqtt_demo_mutual_auth/mqtt_demo_mutual_auth.c#L629-L632

Can you give the following fix a try with the following fix and feedback the result?
```c
  // #ifndef CLIENT_USERNAME remove the preprocessor condition
     opensslCredentials.pClientCertPath = CLIENT_CERT_PATH; 
     opensslCredentials.pPrivateKeyPath = CLIENT_PRIVATE_KEY_PATH; 
 // #endif 
```

**Comment by zhengasif** [comment]
hi  
I  meet the same issue and same error msgs can't be resolved now.
And besides ,I configured demo-config.h ,I configure lambda function in my iot console also ,but it does't work yet, I can't figure the reasons out.
I want to use USERNAME/PASSWORD to log in mqtt server,so  CLIENT_CERT_PATH and CLIENT_PRIVATE_KEY_PATH will not provide in my device.

**Comment by chinglee-iot** [comment]
@zhengasif 
Thank you for your feedback. We will look into this problem and reply in this thread again.

**Comment by chinglee-iot** [comment]
@zhengasif
I am able to run the mqtt_demo_mutual_auth with custom authentication. Sorry for my previous post. The client cert and private key are not required for custom authentication.

The are couple of things we can check first:
1. The lambda function to be triggered by AWS IoT Core authorizer. This can be checked with the test in lambda.
2. The AWS IoT Core authorizer and grant the AWS IoT Core service permission to invoke the lambda function

After we create the lambda function and the authorizer, we can check the result with test-invoke-authorizer
```
aws iot test-invoke-authorizer --authorizer-name NAME_OF_AUTHORIZER ...
```
The json returned by the lambda function should be printed out in your console.

3. Ensure the json contains the required attribute and the policy document in json has the permission for the demo. `iot:Connect`, `iot:Publish`, `iot:Subscribe` and `iot:Receive` actions are required for this demo.

4. Configure the demo with the following in demo_config.h and run the demo.
```
#define AWS_IOT_ENDPOINT         "YourAWSIoTEndpoint"
#define AWS_MQTT_PORT             ( 443 )
#define CLIENT_USERNAME           "The client username"
#define CLIENT_PASSWORD           "The password"
```
Now you should be able to connect/subscribe/publish/receive to the AWS IoT Core with the demo.

More detail information can be found in [Creating and managing custom authorizers document](https://docs.aws.amazon.com/iot/latest/developerguide/config-custom-auth.html) to run this demo with custom authentication.

Please feedback which steps you are having problem.

**Comment by chinglee-iot** [comment]
@leozzmc 

It looks like you are able to invoke authorizer. Please check the followings and feedback more information:
* AWS IoT Core clouldwatch log. Cloudwatch logs the event of AWS IoT Core. You can reference the [Monitor AWS IoT using CloudWatch Logs document](https://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html) to view the log. The log shows the authentication status which can help diagnosis the problem.
* The JSON document returned by your lambda function should contains required value and permission in policy documents. `iot:Connect`, `iot:Publish`, `iot:Subscribe` and `iot:Receive` actions are required for this demo.

**Comment by chinglee-iot** [comment]
@leozzmc

Can you help to check the followings in cloudwatch and feedback the result?
1. Do you see any of the following log in AWSIotLogsV2 group?
```
{
    "timestamp": "2023-10-13 18:00:57.244",
    "logLevel": "ERROR",
    "traceId": "6475c73d-d3be-7d1a-b447-843c46917d88",
    "accountId": "......",
    "status": "Failure",
    "eventType": "Connect",
    "protocol": "MQTT",
    "clientId": "testclient",
    "principalId": "xxxxxxxx",
    "sourceIp": ".....",
    "sourcePort": 27487,
    "reason": "AUTHORIZATION_FAILURE",
    "details": "Authorization Failure"
}
```
2. Is your lambda triggered when this demo application trying to connect to the MQTT? The basic lambda permission allows this lambda to create log in cloudwatch. If the lambda function is triggered, there will be cloudwatch log.
3. Does the policy document returned by your lambda function contain valid permission?

I am able to run your lambda function with invalid password. The following is the cloudwatch log. I didn't try valid password with base64 encoding. I have not problem connect to the IoT core if I update your lambda to allow any password.
```
2023-10-16T10:51:20.841Z	.....	INFO	authResponse --> 
{
    "isAuthenticated": true,
    "principalId": "principalId",
    "policyDocuments": [
        {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": "iot:Connect",
                    "Effect": "Deny",
                    "Resource": "arn:aws:iot:us-west-2:....:*"
                },
                {
                    "Action": "iot:Subscribe",
                    "Effect": "Deny",
                    "Resource": "arn:aws:iot:us-west-2:.....:*"
                },
                {
                    "Action": "iot:Publish",
                    "Effect": "Deny",
                    "Resource": "arn:aws:iot:us-west-2:.....:*"
                },
                {
                    "Action": "iot:Receive",
                    "Effect": "Deny",
                    "Resource": "arn:aws:iot:us-west-2:....:*"
                }
            ]
        }
    ],
    "disconnectAfterInSeconds": 3600,
    "refreshAfterInSeconds": 600
}
```

**Comment by chinglee-iot** [comment]
@leozzmc 
In my test, I use the default authorizer with [set-default-authorizer](https://docs.aws.amazon.com/cli/latest/reference/iot/set-default-authorizer.html).

We are also trying to set the custom authorizer in username and will reply the test result in this thread later.
```
#define CLIENT_NAME "Test?x-amz-customauthorizer-name=TestAuth2"
```

**Comment by chinglee-iot** [comment]
@leozzmc 
In the demo, the metrics parameter is already appended to the CLIENT_USERNAME_WITH_METRICS.
```c
#define METRICS_STRING             "?SDK=" OS_NAME "&Version=" OS_VERSION "&Platform=" HARDWARE_PLATFORM_NAME "&MQTTLib=" MQTT_LIB

#define CLIENT_USERNAME_WITH_METRICS    CLIENT_USERNAME METRICS_STRING
```

Therefore, adding extra parameters in CLIENT_USERNAME would result in invalid format.

For example, with previous example
```c
#define CLIENT_USERNAME "Test?x-amz-customauthorizer-name=TestAuth2"
```
The resulting string will have two question marks, which is invalid format.
```
Test?x-amz-customauthorizer-name=TestAuth2?SDK=" OS_NAME "&Version=" OS_VERSION "&Platform=" HARDWARE_PLATFORM_NAME "&MQTTLib=" MQTT_LIB
                                          ^ The extra question mark
```
We will bring back this problem for discussion and come out a solution to allow user to append parameters in CLIENT_USERNAME. To unblock your development, you may use default authorizer or update the `METRICS_STRING` with the following code as a temporary workaround.
```c
#define METRICS_STRING               "&SDK=" OS_NAME "&Version=" OS_VERSION "&Platform=" HARDWARE_PLATFORM_NAME "&MQTTLib=" MQTT_LIB
                                      ^ Replace '?' with '&'
```

**Comment by chinglee-iot** [comment]
The PR #1893 to fix this issue is merged. We will close this issue. Thank you for creating this issue and feel free to reopen it if any new observation.
