### ISSUE TITLE
OpenSSL 3.X support

### ISSUE THREAD

**Issue by nawata-akihiro** [aws/aws-iot-device-sdk-embedded-C#1886]
As you know, OpenSSL 1.1.1 is EOL.

Does anyone have any information on wheter aws-iot-devece-sdk-embedded-C works with OpenSSL3.X ?

**Comment by chinglee-iot** [comment]
Hi @nawata-akihiro

From the OpenSSL [migration guide](https://www.openssl.org/docs/man3.0/man7/migration_guide.html), most of the demos built with OpenSSL 1.1.1 should work with OpenSSL 3.x.
>  It is the intention that the large majority of applications will work unchanged with OpenSSL 3.0 if those applications previously worked with OpenSSL 1.1.1.

Please feedback if you have any problem using aws-iot-device-sdk-embedded-C with OpenSSL 3.x. We will discuss with you here.

**Comment by chinglee-iot** [comment]
Close this issue first. Feel free to reopen this issue if you have any problem using this SDK with OpenSSL3.X.
