### ISSUE TITLE
OTA with file larger than 16 MB

### ISSUE THREAD

**Issue by giuspen** [aws/aws-iot-device-sdk-embedded-C#1888]
I can successfully run the 2 OTA demos.

I'm trying though to run an OTA with a binary file transfer that is larger than 16 MB but this is forbidden when generating the Job in the web interface.

Is there a way to increase that limit?

**Comment by chinglee-iot** [comment]
Hi giuspen,
Thank you for the question about OTA service file size resource quota. We will consult with other team member and get back to you.

**Comment by chinglee-iot** [comment]
Hi giuspen,

"File size" limit referenced here: https://docs.aws.amazon.com/general/latest/gr/amazon-freertos.html#limits-ota-manager cannot be increased, it is a hard limit.
Feel free to reopen this issue if you have any further question.
