### ISSUE TITLE
mbedtls_ssl_handshake returned -0x7780

### ISSUE THREAD

**Issue by yasiralijaved** [aws/aws-iot-device-sdk-embedded-C#1898]
I am stuck for days into this problem with ESP32 WROOM 32D. I created a thing in aws iot core and downloaded the certificates. Then setup the tls_mutual_auth example in VS Code from https://github.com/espressif/esp-aws-iot/tree/master/examples/mqtt/tls_mutual_auth.
Modified the cert folder with downloaded certificates but getting the error.
Although the same certificates are working FINE when using MQTTX in Windows, it can connect, subscribe and publish without any issue.

```
esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x7780
esp-tls-mbedtls: Certificate verified.
esp-tls: Failed to open new connection

coreMQTT: A clean MQTT connection is established. Cleaning up all the stored outgoing publishes.
coreMQTT: Subscribing to the MQTT topic MyDevice/example/topic.
coreMQTT: sendMessageVector: Unable to send packet: Network Error.
.
.
.
mbedtls: ssl_msg.c:4799 is a fatal alert message (msg 70)

mbedtls: ssl_msg.c:3942 mbedtls_ssl_handle_message_type() returned -30592 (-0x7780)

mbedtls: ssl_tls12_client.c:1199 mbedtls_ssl_read_record() returned -30592 (-0x7780)
.
.
```

**Comment by ydhuang28** [comment]
Hi @yasiralijaved, thank you for reporting this to us. We will investigate this issue and get back to you.

**Comment by zhangshouyin** [comment]
hi,  @ydhuang28    look  this link:   https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/1904#issue-2195154845

**Comment by AniruddhaKanhere** [comment]
Hello @yasiralijaved, can you look into the link posted by @zhangshouyin?

It seems that their issue was resolved.

Thanks.

**Comment by moninom1** [comment]
Hello @yasiralijaved ,
Can you please check and let us know if the issue is resolved?

**Comment by ActoryOu** [comment]
Closing the issue  due to lack of response for an extended period. Please feel free to create new issue if the problem persist.
