### ISSUE TITLE
Build aws iot sdk for linux as shared library 

### ISSUE THREAD

**Issue by embeddedgeeks** [aws/aws-iot-device-sdk-embedded-C#19]
any plan to build the sdk for Linux as a shared library ?

**Comment by rongaws** [comment]
There's no immediate plan for creating a library for the SDK, as it is mainly targeted for embedded devices with limited sharing needs. However it's not hard to modify the Makefile to generate a statically or dynamically linked library, for example, this is how I modified the Makefile in the shadow_sample directory (I used the final archive downloaded here https://s3.amazonaws.com/aws-iot-device-sdk-embedded-c/linux_mqtt_openssl-latest.tar for simplicity reasons) to produce a statically linked library and them link shadow_sample.c against it. You could do the similar to generate a .so library. I also attached a patch file for the below - [Makefile.patch.zip](https://github.com/aws/aws-iot-device-sdk-embedded-C/files/248217/Makefile.patch.zip)

<pre>
% diff -urN Makefile.orig Makefile
--- Makefile.orig       2016-05-03 23:23:12.697386104 -0700
+++ Makefile    2016-05-03 23:21:18.717556823 -0700
@@ -63,7 +63,7 @@
 INCLUDE_ALL_DIRS += $(APP_INCLUDE_DIRS)

 SRC_FILES += $(MQTT_SRC_FILES)
-SRC_FILES += $(APP_SRC_FILES)
+#SRC_FILES += $(APP_SRC_FILES)
 SRC_FILES += $(IOT_SRC_FILES)

 # Logging level control
@@ -79,8 +79,15 @@

 MAKE_CMD = $(CC) $(SRC_FILES) $(COMPILER_FLAGS) -o $(APP_NAME) $(EXTERNAL_LIBS) $(LD_FLAG) $(INCLUDE_ALL_DIRS)

-all:
-       $(DEBUG)$(MAKE_CMD)
+
+all: libAwsIotSdk.a
+       $(CC) $(APP_NAME).c -o $(APP_NAME) -L. -lAwsIotSdk  $(EXTERNAL_LIBS) $(LD_FLAG) $(INCLUDE_ALL_DIRS)
+
+libAwsIotSdk.a: $(SRC_FILES:.c=.o)
+       ar rcs $@ $^
+
+%.o : %.c
+       $(CC) -c $< -o $@ $(COMPILER_FLAGS) $(EXTERNAL_LIBS) $(INCLUDE_ALL_DIRS)

 clean:
        rm -f $(APP_DIR)/$(APP_NAME)

</pre>

**Comment by chaurah** [comment]
A sample has been added that demonstrates how to build the Embedded C SDK as a library and then use it in an application. Closing this issue.

Rahul
