### ISSUE TITLE
Periodic disconnects

### ISSUE THREAD

**Issue by atlascoder** [aws/aws-iot-device-sdk-embedded-C#191]
I use this client to connect to AWS IoT and it works just fine, but I observe disconnections with period from 1 to several hours. I don't use auto-reconnect feature and do it myself when get false on `aws_iot_mqtt_is_client_connected`.
I understand that if I would use auto-reconnect feature then I would not see disconnections at all, because it would happened silently.

So, the question - is it normal behavior or not?

**Comment by gordonwang0** [comment]
Hi @atlascoder,

This probably isn't normal behavior -- but's it's impossible to know without more information about your setup/network.  Do you have any log messages regarding the disconnects?

**Comment by atlascoder** [comment]
Thanks for reply @gordonwang0 it looks like I've solved the issue, but need a few days to check. I will update this thread

**Comment by gordonwang0** [comment]
Hi @atlascoder,

Please let me know if you need any more help with this.  Closing issue.

**Comment by atlascoder** [comment]
Sorry, @gordonwang0 , I forget to update. I just used `aws_iot_mqtt_attempt_reconnect` after `iot_is_mqtt_connected` returned false and it does reconnect silently. but I suppose that periodic disconnects are really happening when auto-reconnect feature is enabled.

**Comment by gordonwang0** [comment]
Thanks for the update.  If you're ok with your solution to the disconnects, I'll leave this issue closed.  Otherwise, if you can provide more information on your setup, I'll reopen this.

**Comment by atlascoder** [comment]
I am OK, thanks for the support!
