### ISSUE TITLE
MQTT publish offline message queuing limits in aws-iot-device-sdk-embedded-C

### ISSUE THREAD

**Issue by ravichandhraRean** [aws/aws-iot-device-sdk-embedded-C#192]
I am unable find the max number of mqtt publish messages we can store in queue while device has no network(offline) and till what time it will persists the messages
Where to configure offlineQueueMaxSize.  (for other device sdks this option is provided eg. aws-iot-device-sdk-js)

**Comment by gordonwang0** [comment]
Hi @ravichandhraRean,

This SDK does not queue publish messages if the network is offline.  `aws_iot_mqtt_publish` will return immediately with code `NETWORK_DISCONNECTED_ERROR` if the network is offline.

**Comment by ravichandhraRean** [comment]
Hi @gordonwang0 

Thank you for your quick reply. 

FYI

**a)** We have tried publishing messages with QoS1 when the network is online, we have received 
          SUCCESS for every message.

**b)** After that network is offline(means we disconnected WiFi )

  **b.1)**  mqtt_connection alive till (1.5 x keep-alive-duration)seconds- 
                in our case (1.5 x 30 = 45)seconds

**c)** We have tried publishing messages with QoS1 when the network is offline(means immediately 
          after WiFi disconnect) we have received MQTT_REQUEST_TIMEOUT_ERROR for every message 
          after 20 seconds (we expected it because the mqttCommandTimeout is 20000 ms)

 **c.1)** If network comes online (means WiFi connects) before (1.5 x keep-alive-duration)seconds - in 
             our case (1.5 x 30 = 45)seconds all offline published messages got pushed to AWS IoT broker.
 **c.2)** If network comes online (means WiFi connects) after (1.5 x keep-alive-duration)seconds - in 
             our case (1.5 x 30 = 45)seconds all offline published messages are lost.

Note:  **c.2** is expected because AWS IoT message broker does not support persistent sessions

But I want to know in case of **c.1** how many messages we can store in queue. And I want to know the  why this feature not introduced in this SDK (because I found this feature in other SDKs like aws-iot-device-sdk-js and python SDK)

waiting for your response.

**Comment by gordonwang0** [comment]
Hi @ravichandhraRean,

In scenario **c.1**, the SDK isn't queuing anything.  Rather, it's waiting in a loop attempting to send or receive data on the network.
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/src/aws_iot_mqtt_client_common_internal.c#L292-L303
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/src/aws_iot_mqtt_client_common_internal.c#L663-L670

Each of your calls to publish has its own instance of that loop, and once the network comes back online, they all manage to send their data (or get PUBACK).  The number of messages you can queue this way depends on the resources available on your system.

As to why there's no true queuing of requests -- This SDK was originally designed with highly constrained devices in mind.  We didn't want to force these devices to reserve memory for queuing requests.

**Comment by ravichandhraRean** [comment]
Hi @gordonwang0 

Thank you for your in-detailed explanation, now I understood.
