### ISSUE TITLE
AWS MQTT disconnect issue - publish data is sometimes not comming to cloud

### ISSUE THREAD

**Issue by jomon-neona** [aws/aws-iot-device-sdk-embedded-C#194]
SDK version using 
2.2.1

We have currently getting error while publish data to the cloud, sometimes data not reaching to the cloud. The error message is given in below.

WARN: disconnectCallbackHandler L#269 MQTT Disconnect
Auto Reconnect is enabled, Reconnecting attempt will start now
attempting reconnect mqtt.
DEBUG: iot_tls_connect L#129
. Seeding the random number generator...
DEBUG: iot_tls_connect L#137 . Loading the CA root certificate ...
DEBUG: iot_tls_connect L#143 ok (0 skipped)

DEBUG: iot_tls_connect L#145 . Loading the client cert. and key...
DEBUG: iot_tls_connect L#158 ok

DEBUG: iot_tls_connect L#160 . Connecting to aclugxc4jtbld.iot.us-east-2.amazonaws.com/8883...
DEBUG: iot_tls_connect L#179 ok

DEBUG: iot_tls_connect L#181 . Setting up the SSL/TLS structure...
DEBUG: iot_tls_connect L#213

SSL state connect : 0
DEBUG: iot_tls_connect L#216 ok

DEBUG: iot_tls_connect L#218

SSL state connect : 0
DEBUG: iot_tls_connect L#219 . Performing the SSL/TLS handshake...
DEBUG: _iot_tls_verify_cert L#49
Verify requested for (Depth 2):

DEBUG: _iot_tls_verify_cert L#51 cert. version : 3
serial number : 18:DA:D1:9E:26:7D:E8:BB:4A:21:58:CD:CC:6B:3B:4A
issuer name : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
issued on : 2006-11-08 00:00:00
expires on : 2036-07-16 23:59:59
signed using : RSA with SHA1
RSA key size : 2048 bits
basic constraints : CA=true
key usage : Key Cert Sign, CRL Sign

DEBUG: _iot_tls_verify_cert L#54 This certificate has no flags

DEBUG: _iot_tls_verify_cert L#49
Verify requested for (Depth 1):

DEBUG: _iot_tls_verify_cert L#51 cert. version : 3
serial number : 3F:92:87:BE:9D:1D:A4:A3:7A:9D:F6:28:2E:77:5A:C4
issuer name : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5

**Comment by gordonwang0** [comment]
Hi @jomon-neona,

I don't see any error message in those logs.  Can you check again?

Thanks.

**Comment by jomon-neona** [comment]
We find out the problem. It is due to using same client id for different devices.

**Comment by gordonwang0** [comment]
Ok, glad you figured it out!  Closing issue.
