### ISSUE TITLE
ERROR: main L#191 Error(-12) connecting to a1######t.$$-south-1.amazonaws.com:443

### ISSUE THREAD

**Issue by Emprotek** [aws/aws-iot-device-sdk-embedded-C#195]
Hello I am testing AWS IOT example subscribe_publish_sample.c . 

Any one know why below  error coming ??

ERROR: main L#191 Error(-12) connecting to a1######t.$$-south-1.amazonaws.com:443

Please give me suggestion.

**Comment by gordonwang0** [comment]
Hi @Emprotek,

This error is usually an issue with policy.  Can you take a look at #183 and verify your policy allows you to connect?

Let me know if you need any help with this.

**Comment by Emprotek** [comment]
Thank you for reply. Now I got below error 

**### Update Timeout--

====================================================

On Device: window state false
Update Shadow: {"state":{"reported":{"temperature":26.500000,"windowOpen":false}}, "clientToken":"Temp-4546-2"}
*****************************************************

ERROR: main L#263 An error occurred in the loop -34
Disconnecting**

**Comment by gordonwang0** [comment]
Hi @Emprotek,

When a shadow is rejected, an error code and message is published to $aws/things/**thingName**/shadow/update/rejected.  You can subscribe to this topic to see the error.  A description of the errors are available [here](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-error-messages.html).

If you let me know what the error code and message are, I can better assist you.

**Comment by Emprotek** [comment]
Hello @gordonwang0 
Thank you for helping me. Everything is working fine. Now,I want port this code into LPC1768 Platform. So,How can I do that ? If any sample code please share with me.
Thanks,
Dinesh

**Comment by gordonwang0** [comment]
Hello @Emprotek,

Please let me know if you need any more help on this.  Closing issue.
