### ISSUE TITLE
Subscribing and mbedtls question

### ISSUE THREAD

**Issue by atlascoder** [aws/aws-iot-device-sdk-embedded-C#197]
I use the client in several projects and face the same problems..
After some priod of time, the client disconnects by an error from mbedtls and I found that there appears some kind of delayed memory release and mbedtls becomes a state with exhausted buffers. This will not be seen here, but this point is important, because it was the starting step of all my workarounds.

When I found that, I decided just to recreate client connection and SSL conext as well. So, once the client gets disconnected, I make this:

```
	client.clientStatus.clientState = CLIENT_STATE_DISCONNECTED_ERROR;
	client.networkStack.disconnect(&(client.networkStack));
	client.networkStack.destroy(&(client.networkStack));
```
and recreate client again.

And now I need to monitor AWS connection and reconnect manually.

This solution halped me for some time, but I still observe often reconnections. No problem, it's bad, but it works for long period of time.

Next issue, I faced when reconnecting and resubscribing the client - I start to get MQTT_MAX_SUBSCRIPTIONS_REACHED_ERROR. Then I decided that, OK, maybe I will try to reconnect once by using 

```
    aws_iot_mqtt_attempt_reconnect(&client);
    if (aws_iot_mqtt_is_client_connected(&client)) {
        aws_iot_mqtt_resubscribe(&client);
    }
```

But it also looks like not working solution.

Below is relevant code.

```
static bool init_aws_client()
{
    IoT_Client_Init_Params mqttInitParams = iotClientInitParamsDefault;

    mqttInitParams.enableAutoReconnect = false;
    mqttInitParams.pHostURL = aws_HostAddress;
    mqttInitParams.port = aws_port;

    mqttInitParams.pRootCALocation = (const char *)aws_root_ca_pem_start;
    mqttInitParams.pDeviceCertLocation = (const char *)aws_cert;
    mqttInitParams.pDevicePrivateKeyLocation = (const char *)aws_pri_key;

    mqttInitParams.mqttCommandTimeout_ms = 20000;
    mqttInitParams.tlsHandshakeTimeout_ms = 5000;
    mqttInitParams.isSSLHostnameVerify = true;
    mqttInitParams.disconnectHandler = disconnect_callback_handler;
    mqttInitParams.disconnectHandlerData = NULL;

    rc = aws_iot_mqtt_init(&client, &mqttInitParams);
    if(SUCCESS == rc) return true;

    ESP_LOGE(TAG, "aws_iot_mqtt_init returned error : %d ", rc);
    return false;
}

static void on_connection_broken()
{
	client.clientStatus.clientState = CLIENT_STATE_DISCONNECTED_ERROR;
	client.networkStack.disconnect(&(client.networkStack));
	client.networkStack.destroy(&(client.networkStack));
	if(on_connection_changed) on_connection_changed(false);
}

static bool connect_aws_client()
{
    ESP_LOGI(TAG, "Connecting to AWS...");

    IoT_Client_Connect_Params connectParams = iotClientConnectParamsDefault;
    connectParams.keepAliveIntervalInSec = 10;
    connectParams.isCleanSession = true;
    connectParams.MQTTVersion = MQTT_3_1_1;
    connectParams.pClientID = device_id;
    connectParams.clientIDLen = (uint16_t) strlen(device_id);
    connectParams.isWillMsgPresent = false;

	rc = aws_iot_mqtt_connect(&client, &connectParams);
	if(SUCCESS == rc) {
		ESP_LOGI(TAG, "Aws client connected.");
		return true;
	}
	else {
		ESP_LOGW(TAG, "Aws client failed on connection (%d)", rc);
		return false;
	}
}

void aws_iot_task(void *param)
{
	struct timeval prev, now;
	gettimeofday(&prev, NULL);
	if (connect_aws_client()) {
		on_connection_established();
		do {
			if (aws_iot_mqtt_is_client_connected(&client)) {
				aws_iot_mqtt_yield(&client, 1000);
			}
			if (aws_iot_mqtt_is_client_connected(&client)) {
				gettimeofday(&now, NULL);
				if (now.tv_sec - prev.tv_sec > 59) {
					publish_ping();
					gettimeofday(&prev, NULL);
				}
			}
			else {
				aws_iot_mqtt_attempt_reconnect(&client);
				if (aws_iot_mqtt_is_client_connected(&client)) {
					aws_iot_mqtt_resubscribe(&client);
				}
			}
		} while (aws_iot_mqtt_is_client_connected(&client));
	}
	on_connection_broken();
	task_handle = NULL;
	vTaskDelete(NULL);
}

```

And logs

```
I (2229) wifi: n:1 0, o:1 0, ap:255 255, sta:1 0, prof:1
I (3219) wifi: state: init -> auth (b0)
I (3229) wifi: state: auth -> assoc (0)
I (3229) wifi: state: assoc -> run (10)
I (3289) wifi: connected with Biedermann Family Network, channel 1
I (5439) event: ip: 192.168.1.79, mask: 255.255.255.0, gw: 192.168.1.254
I (5439) WiFi: got ip
I (5439) WiFi: ip: 192.168.1.79
I (5439) WiFi: netmask: 255.255.255.0
I (5439) WiFi: gw: 192.168.1.254
W (5449) WiFi: WiFi connected
I (5449) SSDP: Joining mcast group 239.255.255.250:1900
I (5449) SCHEDULE: Initializing SNTP
I (5459) SSDP: Join successful
I (5459) SSDP: Responder started
I (5469) HTTP: HTTP server started in operating mode
I (5469) MAIN: State changed to: AWS connection
I (5479) AWS: Connecting to AWS...
I (13239) wifi: pm start, type:0
I (22879) AWS: Aws client connected.
I (22879) MAIN: State changed to: AWS Online
I (22879) AWS: Subscribing to topic B4E62D98F3B5/command
I (22969) AWS: Subscribing to topic update/1.19
I (23059) AWS: Subscribing to topic B4E62D98F3B5/schedule
I (23159) AWS: Publish message "{"version":"1.19", "mac":"B4E62D98F3B5", "uptime":"23"}" to boot topic
W (129759) AWS: MQTT Disconnect with state 12
W (227479) AWS: MQTT Disconnect with state 12
W (514059) AWS: MQTT Disconnect with state 12
W (628019) AWS: MQTT Disconnect with state 12
W (724149) AWS: MQTT Disconnect with state 12
W (871819) AWS: MQTT Disconnect with state 12
E (881599) aws_iot: failed! mbedtls_ssl_handshake returned -0x6800
I (881599) MAIN: State changed to: AWS reconnection
I (882599) MAIN: State changed to: AWS connection
I (882599) AWS: Connecting to AWS...
E (893679) aws_iot: failed! mbedtls_ssl_handshake returned -0x6800
W (893679) AWS: Aws client failed on connection (-4)
I (893679) MAIN: State changed to: AWS reconnection
I (894689) MAIN: State changed to: AWS connection
I (907119) AWS: Aws client connected.
I (907119) MAIN: State changed to: AWS Online
I (907119) AWS: Subscribing to topic B4E62D98F3B5/command
I (907269) AWS: Subscribing to topic update/1.19
I (907429) AWS: Subscribing to topic B4E62D98F3B5/schedule
E (907429) AWS: Error subscribing on schedule : -34
I (907429) MAIN: State changed to: AWS reconnection
I (908439) MAIN: State changed to: AWS connection
I (908439) AWS: Connecting to AWS...
E (917849) aws_iot: failed! mbedtls_ssl_handshake returned -0x6800
W (917849) AWS: Aws client failed on connection (-4)
I (917849) MAIN: State changed to: AWS reconnection
I (918859) MAIN: State changed to: AWS connection
I (918859) AWS: Connecting to AWS...
E (934499) aws_iot: failed! mbedtls_ssl_handshake returned -0x6800
W (934499) AWS: Aws client failed on connection (-4)
I (934499) MAIN: State changed to: AWS reconnection
I (935509) MAIN: State changed to: AWS connection
I (935509) AWS: Connecting to AWS...
E (945039) aws_iot: failed! mbedtls_ssl_handshake returned -0x6800
W (945039) AWS: Aws client failed on connection (-4)
I (945039) MAIN: State changed to: AWS reconnection
I (946049) MAIN: State changed to: AWS connection
I (946049) AWS: Connecting to AWS...
I (961429) AWS: Aws client connected.
I (961429) MAIN: State changed to: AWS Online
I (961429) AWS: Subscribing to topic B4E62D98F3B5/command
E (961429) AWS: Error subscribing : -34
I (961429) MAIN: State changed to: AWS reconnection
``` 
I see and understand that the root cause is in mbedtls, because I started to create all this crutches tring to get it working after `mbedtls` error. 
And I am OK to have some trade-off without of diving into `mbedtls` patching and just to get it working even on crutches. But it looks like I do something wrong due to misunderstanding of the client's interface.

Please help..

**Comment by ravibhagavandas** [comment]
`aws_iot_mqtt_attempt_reconnect` will reconnect to AWS broker and also resubscribes all the topics for you, so you don't need to explicitly call `aws_iot_mqtt_resubscribe` again.
Also `aws_iot_mqtt_resubscribe` does not subscribe to a new topic, so `MQTT_MAX_SUBSCRIPTIONS_REACHED_ERROR` will be coming from a different place in the code. It might be from `on_connection_established()` call, where you are subscribing to the topics again ?

Lastly, its recommended to enable auto reconnect from within the library itself using `aws_iot_mqtt_autoreconnect_set_status` function call. This way you don't need to handle reconnects, instead `aws_iot_mqtt_yield` will attempt to reconnect internally during disconnects.  For more details on the usage you can check `subscribe_publish_sample.c`  sample.

**Comment by atlascoder** [comment]
Thanks @ravibhagavandas, you are right, `MQTT_MAX_SUBSCRIPTION_REACHED_ERROR` appear when `on_connection_established` is called. I wrote, that this call is performed when the task is deleted (with its SSL context) after `aws_iot_mqtt_attempt_reconnect` has no success.

Yes `aws_iot_mqtt_resubscribe` is called by `aws_iot_mqtt_attempt_reconnect` and is surplus in my case.

But in fact, I always subscribe to the same set of topics - it is not extending. So, if I trap in `MQTT_MAX_SUBSCRIPTION_REACHED_ERROR` it does mean that somehow if I subscribe to the same topic twice - it means really 2 subscription. Unexpected for me, but it makes sense because it makes possible to connect several callbacks to the same topic.

So, I am changing my code like below, and will post results here. I said, that when I used auto-reconnect feature I faced issue with `mbedtls` that, how I've found, meant that buffers for SSL wrapper were exhausted. @ravibhagavandas, do you know something about such behavior?

```
void aws_iot_task(void *param)
{
	struct timeval prev, now;
	gettimeofday(&prev, NULL);
	if (connect_aws_client()) {
		on_connection_established();
		do {
			if (aws_iot_mqtt_is_client_connected(&client)) {
				aws_iot_mqtt_yield(&client, 1000);
			}
			if (aws_iot_mqtt_is_client_connected(&client)) {
				gettimeofday(&now, NULL);
				if (now.tv_sec - prev.tv_sec > 59) {
					publish_ping();
					gettimeofday(&prev, NULL);
				}
			}
			else {
				aws_iot_mqtt_attempt_reconnect(&client);
			}
		} while (aws_iot_mqtt_is_client_connected(&client));
	}
	on_connection_broken();
	task_handle = NULL;
	vTaskDelete(NULL);
}
```

**Comment by atlascoder** [comment]
BTW, is there any function like `aws_iot_mqtt_deinit` ?

**Comment by ravibhagavandas** [comment]
@ravibhagavandas, do you know something about such behavior?
No, to the best of my knowledge, there was no such behavior reported before. 
After checking the code, client library do free the stack, whenever it receives a network error (like SSL Read/Write timeout) within `aws_iot_mqtt_yield`. Were you receiving disconnects during publish or while reading from within yield function ? What error code were you receiving at application side?

There is no function called `aws_iot_mqtt_deinit ` in csdk. You can instead use `aws_iot_mqtt_disconnect` which will send disconnect as well as free up the network stack.

**Comment by atlascoder** [comment]
@ravibhagavandas, now I have not issues with `MQTT_MAX_SUBSCRIPTION_REACHED_ERROR` - thank you!

I think this issue can be closed, bacause, I have not fixed mbedtls errors when they were appearing. When I will face that - I'll report with new issue.

So far, everything is OK, thanks again!
