### ISSUE TITLE
README architecture doc link

### ISSUE THREAD

**Issue by carsonmcdonald** [aws/aws-iot-device-sdk-embedded-C#2]
This architecture document link to from the README isn't accessible:  

http://aws-iot-device-sdk-embedded-c-docs.s3-website-us-east-1.amazonaws.com/index.html

I assume that is the same thing as the doxygen documentation found in the docs directory of the tarballs.

**Comment by bhadrip** [comment]
Hello,

The link is fixed now. 
Yes, It is the same doxygen generated document that is distributed with the tarball.

Thanks for letting us know.

**Comment by carsonmcdonald** [comment]
No problem
