### ISSUE TITLE
Please use 'extern "C"' in the headers files

### ISSUE THREAD

**Issue by mcclellansws** [aws/aws-iot-device-sdk-embedded-C#20]
Please add 'extern "C"' in the headers files to make them easier to use from C++. 

#ifdef __cplusplus
extern "C" {
#endif

...

#ifdef __cplusplus
}
#endif

external_libs/jsmn/jsmn.h does this, but none of the "internal" header files.

**Comment by rongaws** [comment]
Thanks for the advise. This is a good suggestion and we are considering making similar changes to those APIs exposed by the SDK.

**Comment by chaurah** [comment]
Hi @mcclellansws,
            We have added 'extern "C"' to the header/code files and also added a C++ sample. I am closing this issue now. Please do let us know if you have any further suggestions. Thank you for using AWS IoT.

Rahul
