### ISSUE TITLE
Shadow Connection Error - AWS IOT Sample Connecting With AWS Greengrass Device

### ISSUE THREAD

**Issue by ChittepuVenkat** [aws/aws-iot-device-sdk-embedded-C#202]
Hello,

We have setup a device and configured AWS Greengrass on it. We have followed the steps documented to setup AWS Greengrass. 

We are trying to connect to AWS greengrass using the AWS IOT shadow sample that is packaged along with the AWS IOT SDK. In the aws_iot_config.h file we have changed the end point to AWS Greengrass device.

When shadow sample tries to communicate with AWS greengrass device it results in **Shadow Connection Error**(MQTT_CONNACK_NOT_AUTHORIZED_ERROR = -41)

Here is the debug log:
---------------------------------------
Shadow Init
Shadow Connect
DEBUG:   iot_tls_connect L#130
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to 127.0.0.1/8883...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#224

SSL state connect : 0
DEBUG:   iot_tls_connect L#227  ok

DEBUG:   iot_tls_connect L#229

SSL state connect : 0
DEBUG:   iot_tls_connect L#230   . Performing the SSL/TLS handshake...
DEBUG:   iot_tls_connect L#247  ok
    [ Protocol is TLSv1.2 ]
    [ Ciphersuite is TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384 ]

DEBUG:   iot_tls_connect L#249     [ Record expansion is 29 ]

DEBUG:   iot_tls_connect L#254   . Verifying peer X.509 certificate...
DEBUG:   iot_tls_connect L#263  ok

DEBUG:   iot_tls_connect L#273   . Peer certificate information    ...

DEBUG:   iot_tls_connect L#275       cert. version     : 3
      serial number     : 6A:46:92:FE:D3:92:C0:8E:D9:14:DA:72:55:B0:9B:8B:18:45:7A:78
      issuer name       : C=US, O=Amazon.com Inc., OU=Amazon Web Services, ST=Washington, L=Seattle, CN=017298249862:61198f19-dfdb-4cce-a5db-cb3579bf1dda
      subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com Inc., OU=Amazon Web Services, CN=MG3_Core
      issued  on        : 2018-07-12 12:11:25
      expires on        : 2018-07-19 12:11:25
      signed using      : RSA with SHA-256
      RSA key size      : 2048 bits
      basic constraints : CA=false
      subject alt name  :
      ext key usage     : TLS Web Server Authentication

ERROR: main L#292 Shadow Connection Error

----------------------------------

Any thoughts on what is going wrong. 

Please help us to overcome this issue

Regards,
Venkat

**Comment by huguesBouvier** [comment]
Hello,

A common problem in that case is that the greengrass group doesn't have the proper subscription.
Shadow is used over MQTT so make share your thing has the proper topics enabled in:
- The greengrass group subscriptions
- The thing's certificate.

Hugues

**Comment by ChittepuVenkat** [comment]
Hi Hugues,

Thanks 

We have defined subscriptions as follows.

Subscriptions:
**Source:** DevX
**Target:** Local Shadow Service
**Topic:**  $aws/things/DevX/shadow/update

**Source:** Local Shadow Service
**Target:** DevX
**Topic:**  $aws/things/DevX/shadow/update/accepted

**Source:** Local Shadow Service
**Target:** DevX
**Topic:**  $aws/things/DevX/shadow/update/rejected

Hope the above configurations are correct.

------------------------

We tried node js samples as well. Even that example returns as Connection not authorized error. See the output below.

Command:
sudo node node_modules/aws-iot-device-sdk/examples/device-example.js --private-key=xxxxxxx.private.key --client-certificate=xxxxxxx.cert.pem --port=8883 --protocol=mqtts --ca-certificate=root-ca.crt --host-name=192.168.1.47 --clientId testClient --debug

Output:
{ keyPath: 'xxxxxxx.private.key',
  certPath: 'xxxxxxx.cert.pem',
  caPath: 'root-ca.crt',
  clientId: 'testClient',
  region: undefined,
  baseReconnectTimeMs: 4000,
  keepalive: 300,
  protocol: 'mqtts',
  port: 8883,
  host: '192.168.1.47',
  debug: true,
  username: '?SDK=JavaScript&Version=2.2.1',
  reconnectPeriod: 4000,
  fastDisconnectDetection: true,
  resubscribe: false,
  key: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 52 53 41 20 50 52 49 56 41 54 45 20 4b 45 59 2d 2d 2d 2d 2d 0a 4d 49 49 45 6f 77 49 42 41 41 4b 43 41 51 45 41 73 47 ... >,
  cert: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 44 57 54 43 43 41 6b 47 67 41 77 49 42 41 67 49 55 4c 53 ... >,
  ca: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 45 46 54 43 43 41 76 32 67 41 77 49 42 41 67 49 56 41 4a ... >,
  requestCert: true,
  rejectUnauthorized: true }
attempting new mqtt connection...
error { Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/home/venkat/clientserver/node_modules/mqtt/lib/client.js:872:15)
    at MqttClient._handlePacket (/home/venkat/clientserver/node_modules/mqtt/lib/client.js:319:12)
    at work (/home/venkat/clientserver/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/home/venkat/clientserver/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/home/venkat/clientserver/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/venkat/clientserver/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/home/venkat/clientserver/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7) code: 5 }
offline
connection lost - will attempt reconnection in 4 seconds...
close

It would helpful for everyone if the steps are documented to connect to aws greengrass using aws iot core embedded c SDK.

Regards,
Venkat

**Comment by huguesBouvier** [comment]
Hello,

I see the sample you provided was for the java SDK. Is it running on the C SDK correctly now?
Currently greengrass support is not integrated with the C SDK.

Hugues

**Comment by ravichandhraRean** [comment]
Hi Venkat,

aws-iot-device-sdk-embedded-C supporting greengrass connection and MQTT Pub/Sub but you should follow the setup procedure.

1. did you downloaded/get your greengrasscore group root certificate(you should use this root certificate) and connection information
https://docs.aws.amazon.com/greengrass/latest/developerguide/gg-discover-api.html or you can use aws greengrass cli to get the connection information and group-root-certificate.

2. I found this in your post
**DEBUG: iot_tls_connect L#161 . Connecting to 127.0.0.1/8883...**
DEBUG: iot_tls_connect L#180 ok
means are you setup your greengrass core and devices both on same system

3. go to iot core-->greengrass-->groups-->click on your group-->settings--> 
there instead of automatic ip detection choose manual and give your greengrass core device ip address and 8883 port

4. https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/samples/linux/subscribe_publish_sample/subscribe_publish_sample.c#L170
it should be  mqttInitParams.isSSLHostnameVerify = false;

5. https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_shadow.c#L91
it should be  mqttInitParams.isSSLHostnameVerify = false;

Thank you,

**Comment by ChittepuVenkat** [comment]
Thanks Hugues.

We tried with C shadow sample first since it didn't work we tried the node js sample.

In **aws-iot-device-sdk-embedded-C-master/src/aws_iot_mqtt_client_connect.c** file - line number 303 returns a value of 5 instead of 0. Value 5 refers to CONNACK_NOT_AUTHORIZED_ERROR.

Line 303:  **connack_rc_char = aws_iot_mqtt_internal_read_char(&curdata);**

Let us know if we have any suggestions to address this issue.
------------------
Ravi Thanks for the detailed steps. 

We were following the same steps except that in the settings it was always set to automatic instead of manual. We tried having greengrass core and devices on the same machine as well as different machines but the result is same. We tried manual option as well.

The C SDK returns CONNACK_NOT_AUTHORIZED_ERROR(5). 

Regards,
Venkat

**Comment by huguesBouvier** [comment]
Hello,

This helps a lot. It means you are successfully establishing a secure connection but fail to connect to the MQTT broker.
A common problem for this is the policy that is attached to your certificate. Is your policy authorizing connection?
For example:
{
    "Version": "2012-10-17",
    "Statement": [
    {
        "Effect": "Allow",
        "Action": "iot:Connect",
        "Resource":"arn:aws:iot:<aws-region>:<aws-account-id>:*"
	}, 
    {
        "Effect": "Allow",
        "Action": "iot:Publish",
        "Resource": "arn:aws:iot:<aws-region>:<aws-account-id>:*"
    },
    {
         "Effect": "Allow",
         "Action": "iot:Subscribe",
         "Resource": "arn:aws:iot:<aws-region>>:<aws-account-id>:*"
    },
    {
         "Effect": "Allow",
         "Action": "iot:Receive",
         "Resource": "arn:aws:iot:<aws-region>:<aws-account-id>:*"
    }
    ]
}

Hugues

**Comment by ChittepuVenkat** [comment]
Thanks Hugues 

We have the policy as below

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Subscribe",
        "iot:Connect",
        "iot:Receive"
      ],
      "Resource": [
        "*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "greengrass:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}

------------------------
We have tried with this as well but the result is same(CONNACK_NOT_AUTHORIZED_ERROR). 

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "*"
      ],
      "Resource": [
        "*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "greengrass:*"
      ],
      "Resource": [
        "*"
      ]
    }
  ]
}

Regards,
Venkat

**Comment by huguesBouvier** [comment]
Hello,

For resources you should specify a topic or put a *
You have: {
"Effect": "Allow",
"Action": [
"iot:Publish",
"iot:Subscribe",
"iot:Connect",
"iot:Receive"
],
"Resource": [
""
]
},
You should put ressource with a * or the topic you want it on:
"Resource": [
"*"
] 

Regards,
Hugues

**Comment by ChittepuVenkat** [comment]
Thanks.

Yes the Resource do have a *. In my earlier post while copying it got delete before I sent. But the thing have the * as part of the policy.

Regards,
Venkat

**Comment by huguesBouvier** [comment]
Hello,

Another approach is to look at the logs on the greegrass side. They could give a more detailed reason of why the connection is getting refused.
The documentation about the logs can be found here:https://docs.aws.amazon.com/greengrass/latest/developerguide/gg-troubleshooting.html#troubleshooting-logs
Could you look at your Greengrass logs and past relevant information?

Thank you,

Hugues

**Comment by ChittepuVenkat** [comment]
Thanks.

Finally we were able to figure out the issue. After assigning thingname for AWS_IOT_MQTT_CLIENT_ID, it was able to communicate with greengrass. The logs were not reporting any error if we substitute with different value.

One more strange thing what we noticed is we tried running **subscribe_publish_sample** and **shadow_sample** with the same thingname and certificates, the subscribe_publish_sample ran without any issues but shadow_sample reports the following error.

----
DEBUG:   _iot_tls_verify_cert L#57 cert. version     : 3
serial number     : 0B:3D:B8:A6:BE:A1:A9:34:CA:CE:9C:79:EE:57:DF:C5:A0:A0:0B:21
issuer name       : C=US, O=Amazon.com Inc., OU=Amazon Web Services, ST=Washington, L=Seattle, CN=XXXXXXXXXXXX:3badeefe-dc76-4f11-8795-e5e7a03048ed
subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com Inc., OU=Amazon Web Services, CN=Test_Core
issued  on        : 2018-07-31 03:47:30
expires on        : 2018-08-07 03:47:30
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  :
ext key usage     : TLS Web Server Authentication


ERROR: iot_tls_connect L#232  failed
  ! mbedtls_ssl_handshake returned -0x2700

ERROR: iot_tls_connect L#239     Unable to verify the server's certificate. Either it is invalid,
    or you didn't set ca_file or ca_path to an appropriate value.
    Alternatively, you may want to use auth_mode=optional for testing purposes.

ERROR: main L#212 Shadow Connection Error
-----

We set mbedtls_ssl_conf_authmode(&(tlsDataParams->conf), MBEDTLS_SSL_VERIFY_NONE) to make the shadow_sample to work.

Any thoughts on whats is going on. Do we need to generate certificates differently?

Regards,
Venkat

**Comment by huguesBouvier** [comment]
Hello,

Shadow is re-using MQTT in the background. Actually to start shadow you have to specify a MQTT client:
IoT_Error_t aws_iot_shadow_init(AWS_IoT_Client *pClient, ShadowInitParameters_t *pParams)
- There should not be any changes in the certificate between the two.
- There could be a change in policy if you specified a particular topic but it is not the case here since you are using a "*" topic.

The error you are experiencing is probably because the root certificate is incorrect.
It could be worth printing the root certificate that is being used in the shadow vs MQTT and double check they are similar.

Hugues

**Comment by ChittepuVenkat** [comment]
Thanks Hugues.

I have reverted back the changes I have done
- Uncommneted #define MBEDTLS_SSL_SERVER_NAME_INDICATION in mbetTLS/include/config.h line number 1495
- Commented mbedtls_ssl_conf_authmode(&(tlsDataParams->conf), MBEDTLS_SSL_VERIFY_NONE) line I have added in /platform/linux/mbedtls/network_mbedtls_wrapper.c.  I added this line just to avoid using certificates

I have set the  mqttInitParams.isSSLHostnameVerify to false on line 91 in /src/aws_iot_shadow.c file

After that both samples(shadow_sample and subscribe_publish_sample) started working with the same set of certificates and thing.

Looks like there is some issue in mbedTLS that is the reason its reporting as invalid root certificate

Thanks again for your timely help to address the issue. You can close this issue.

Regards,
Venkat

**Comment by prashantrar** [comment]
@ChittepuVenkat is there any update on this issue? could you narrow down and confirm that the issue is certainly in mbedtls? Off late I have also started facing the same issue with device certificates that were previousy working

**Comment by ChittepuVenkat** [comment]
> @ChittepuVenkat is there any update on this issue? could you narrow down and confirm that the issue is certainly in mbedtls? Off late I have also started facing the same issue with device certificates that were previousy working

Based on our analysis the issue was in mbedtls. The changes I have mentioned in my earlier posts have been tested and working. We never had a working version prior to these changes.
