### ISSUE TITLE
fail to call aws_iot_mqtt_yield()

### ISSUE THREAD

**Issue by surmo** [aws/aws-iot-device-sdk-embedded-C#203]
I had porting the sdk to my stm32 chip, and it success to connect to server, But it wil fail when I call aws_iot_mqtt_yield to chect the mqtt state evry time. 

DEBUG:   connectAndPublish L#105 rootCA CA_str
DEBUG:   connectAndPublish L#106 clientCRT certificate
DEBUG:   connectAndPublish L#107 clientKey privateKey
Connecting...
DEBUG:   iot_tls_connect L#148 
  . Seeding the random number generator...
data_sumo:0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜?š›œžŸ ¡¢£¤¥¦§¨©ª«¬­®¯H5 ,len=128

DEBUG:   iot_tls_connect L#156   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#162  ok (0 skipped)

DEBUG:   iot_tls_connect L#164   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#177  ok

DEBUG:   iot_tls_connect L#179   . Connecting to a1mak9f5rjymuj.iot.us-east-2.amazonaws.com/443...
DEBUG:   iot_tls_connect L#198  ok

DEBUG:   iot_tls_connect L#200   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#241 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#244  ok

DEBUG:   iot_tls_connect L#246 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#247   . Performing the SSL/TLS handshake...
ready to send 176 byte

send suceess, have send =176

ready to read 5 byte,timeout=8000

rec success, have read=5 byte

ready to read 2615 byte,timeout=8000

rec success, have read=2615 byte

DEBUG:   _iot_tls_verify_cert L#56 
Verify requested for (Depth 2):

DEBUG:   _iot_tls_verify_cert L#58 cert. version     : 3
serial number     : 18:DA:D1:9E:26:7D:E8:BB:4A:21:58:CD:CC:6B:3B:4A
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name      : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
issued  on        : 2006-11-08 00:00:00
expires on        : 2036-07-16 23:59:59
signed using      : RSA with SHA1
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#61   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#56 
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#58 cert. version     : 3
serial number     : 3F:92:87:BE:9D:1D:A4:A3:7A:9D:F6:28:2E:77:5A:C4
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name      : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
issued  on        : 2015-05-12 00:00:00
expires on        : 2025-05-11 23:59:59
signed using      : RSA with SHA-256
EC key size       : 256 bits
basic constraints : CA=true, max_pathlen=0
subject alt name  : 
key usage         : Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#61   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#56 
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#58 cert. version     : 3
serial number     : 3C:75:FE:30:01:DD:A3:B9:EF:72:DC:F6:7A:5C:A2:54
issuer name       : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.iot.us-east-2.amazonaws.com
issued  on        : 2017-10-12 00:00:00
expires on        : 2018-10-13 23:59:59
signed using      : ECDSA with SHA256
EC key size       : 256 bits
basic constraints : CA=false
subject alt name  : iot.us-east-2.amazonaws.com, *.iot.us-east-2.amazonaws.com
key usage         : Digital Signature
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#61   This certificate has no flags

ready to send 877 byte

send suceess, have send =877

ready to send 75 byte

send suceess, have send =75

ready to send 269 byte

send suceess, have send =269

ready to send 6 byte

send suceess, have send =6

ready to send 69 byte

send suceess, have send =69

ready to read 5 byte,timeout=8000

rec success, have read=5 byte

ready to read 1 byte,timeout=8000

rec success, have read=1 byte

ready to read 5 byte,timeout=8000

rec success, have read=5 byte

ready to read 64 byte,timeout=8000

rec success, have read=64 byte

DEBUG:   iot_tls_connect L#263  ok
    [ Protocol is TLSv1.2 ]
    [ Ciphersuite is TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA ]

DEBUG:   iot_tls_connect L#266     [ Record expansion is 41 ]

DEBUG:   iot_tls_connect L#271   . Verifying peer X.509 certificate...
DEBUG:   iot_tls_connect L#280  ok

DEBUG:   iot_tls_connect L#290   . Peer certificate information    ...

DEBUG:   iot_tls_connect L#292       cert. version     : 3
      serial number     : 3C:75:FE:30:01:DD:A3:B9:EF:72:DC:F6:7A:5C:A2:54
      issuer name       : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
      subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.iot.us-east-2.amazonaws.com
      issued  on        : 2017-10-12 00:00:00
      expires on        : 2018-10-13 23:59:59
      signed using      : ECDSA with SHA256
      EC key size       : 256 bits
      basic constraints : CA=false
      subject alt name  : iot.us-east-2.amazonaws.com, *.iot.us-east-2.amazonaws.com
      key usage         : Digital Signature
      ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

countdown_ms 20000ms

ready to send 85 byte

send suceess, have send =85

countdown_ms 2000ms

ready to read 5 byte,timeout=5000

rec success, have read=5 byte

ready to read 48 byte,timeout=5000

rec success, have read=48 byte

countdown_sec 600 s

connect ok----

Subscribing...
countdown_ms 20000ms

ready to send 101 byte

send suceess, have send =101

countdown_ms 2000ms

ready to read 5 byte,timeout=5000

rec success, have read=5 byte

ready to read 48 byte,timeout=5000

rec success, have read=48 byte

countdown_ms 4000ms

countdown_ms 2000ms

ready to read 5 byte,timeout=5000

read  timeout
read  timeout
read  timeout
read  timeout
read  timeout

it alway timeout at this place

**Comment by huguesBouvier** [comment]
Hello,

Could you please indicate the line number where it times out? Or give the C SDK error message?
I can see it times out from the error message:"read timeout"
But I have no idea where it happens.
Thank you,

Hugues

**Comment by surmo** [comment]
The “read outtime“ problem happens in this function：int mbedtls_net_recv_timeout( void *ctx, unsigned char *buf, size_t len, uint32_t timeout ) ，
In order to adapt to my platform, I rewritten the code for the receiving part，The reason for this problem is that receiving the specified byte from the server has timed out. I have not modified the other parts, just modify this data receiving interface.

Here is the content of the function：

int mbedtls_net_recv_timeout( void *ctx, unsigned char *buf, size_t len,
                      uint32_t timeout )
{
    int ret;
		int i,j=0;
		unsigned char byte;
	  printf("ready to read %d byte,timeout=%d\r\n",len,timeout);
		for(i=0;i<len;i++)
	  {
		 if( xQueueReceive( xQueueRxBuf, &(byte), ( TickType_t ) pdMS_TO_TICKS(timeout) ) )
        {
           *(buf+i)=byte;
					 j++;
        }
				else
				{
					printf("read  timeout\r\n");
				}
   }
	
		IOT_INFO("rec success, have read=%d byte\r\n",j);

    return j;
}


I make sure it works because the client is already connected to the server.
Thank you.

**Comment by gordonwang0** [comment]
Hi @surmo,

How is `xQueueRxBuf` being filled?  Can you provide that code as well?

Also, can you point out where in the code the 5 bytes that timeout are read?  Which SDK function is performing the network read that times out?

Thank you.

**Comment by surmo** [comment]
Hi @gordonwang0 
In this interruption，xQueueRxBuf will be filled.

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
	if(huart->Instance==huart2.Instance)
	{
		if(xQueueSendFromISR(xQueueRxBuf,&resData,0)!=pdTRUE)
		{
			printf("Rxbuf error-----------------------------------------------\r\n");
		}
		HAL_UART_Receive_IT(&huart2,&resData,1);
	}
}

Each time a byte is received from a server, the bytes are saved to the “xQueueRxBuf”.


I use “samples/linux/subscribe_publish_sample/subscribe_publish_sample.c” as the test program，

This problem occurs when the program runs to line 229.
![image](https://user-images.githubusercontent.com/16445666/42800220-7e509c58-89cd-11e8-8056-e7ea808fdf34.png)

thank you.

**Comment by huguesBouvier** [comment]
Hello,

From the code you put, it seems you are using an external chip to receive ethernet traffic, then read from it with the UART. 
Why are you performing "HAL_UART_Receive_IT" after queuing the data? 
Is "HAL_UART_Receive_IT" always successful? What if data is being queued, then an error happens on "HAL_UART_Receive_IT"?

Hugues

**Comment by surmo** [comment]
Hello @huguesBouvier 
Yes，I am using an external chip to receive ethernet traffic, "HAL_UART_Receive_IT(&huart2,&resData,1);" means to prepare for receiving the next byte, when a byte is received, “HAL_UART_RxCpltCallback()” will be triggered. This is an interrupt trigger, so it won't block. So “HAL_UART_RxCpltCallback()” will be triggered whenever it receives data from the server.

**Comment by huguesBouvier** [comment]
Hello @surmo,

So if I understand correctly:
1. resData is being written by the UART peripheral directly
2. When the operation is completed, the data is being queued.

The potential problem I see with Byte by byte receiving: though it depends on the application, is that if there are other interrupts, a byte could be missed, especially if it is byte by byte receiving and the receiving frequency is high.

Also, is it failing in subscribing? I see "Subscribing..." but not subscribing success.
I suppose the higher level failing function is subscribing.
Another potential issue: The certificate attached to your thing doesn't have the subscribing policy.
A good check would be to try to run the SDK on an other OS (linux for example) and see if it works.

Hugues

**Comment by surmo** [comment]
Hi @huguesBouvier 
Your are right, resData  is written when a byte is received.
I think it should not be caused by the interruption of the frequency too high,
Because the TLS handshake has a larger amount of data, the communication is still successful. And this timeout problem happens every time in the same place. So I think it should be caused by other reasons.

I have successfully run the SDK on Linux, it can connect, subscribe, and publish. So I sure the policy is right.

Here is the log data running on Linux:

AWS IoT SDK Version 3.0.1-

DEBUG:   main L#162 rootCA CA_str
DEBUG:   main L#163 clientCRT certificate
DEBUG:   main L#164 clientKey privateKey
Connecting...
DEBUG:   iot_tls_connect L#139 
  . Seeding the random number generator...
data_sumo:0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~������������������������������������������������ ,len=128
DEBUG:   iot_tls_connect L#147   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#153  ok (0 skipped)

DEBUG:   iot_tls_connect L#155   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#168  ok

DEBUG:   iot_tls_connect L#170   . Connecting to a1mak9f5rjymuj.iot.us-east-2.amazonaws.com/443...
DEBUG:   iot_tls_connect L#189  ok

DEBUG:   iot_tls_connect L#191   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#232 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#235  ok

DEBUG:   iot_tls_connect L#237 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#238   . Performing the SSL/TLS handshake...
ready to write 176 byte
write 176 byte succeeds
ready to read 5 byte
read 5 byte succeeds
ready to read 2616 byte
read 1355 byte succeeds
ready to read 1261 byte
read 1261 byte succeeds
DEBUG:   _iot_tls_verify_cert L#58 
Verify requested for (Depth 2):

DEBUG:   _iot_tls_verify_cert L#60 cert. version     : 3
serial number     : 18:DA:D1:9E:26:7D:E8:BB:4A:21:58:CD:CC:6B:3B:4A
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name      : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
issued  on        : 2006-11-08 00:00:00
expires on        : 2036-07-16 23:59:59
signed using      : RSA with SHA1
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#63   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#58 
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#60 cert. version     : 3
serial number     : 3F:92:87:BE:9D:1D:A4:A3:7A:9D:F6:28:2E:77:5A:C4
issuer name       : C=US, O=VeriSign, Inc., OU=VeriSign Trust Network, OU=(c) 2006 VeriSign, Inc. - For authorized use only, CN=VeriSign Class 3 Public Primary Certification Authority - G5
subject name      : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
issued  on        : 2015-05-12 00:00:00
expires on        : 2025-05-11 23:59:59
signed using      : RSA with SHA-256
EC key size       : 256 bits
basic constraints : CA=true, max_pathlen=0
subject alt name  : 
key usage         : Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#63   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#58 
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#60 cert. version     : 3
serial number     : 3C:75:FE:30:01:DD:A3:B9:EF:72:DC:F6:7A:5C:A2:54
issuer name       : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.iot.us-east-2.amazonaws.com
issued  on        : 2017-10-12 00:00:00
expires on        : 2018-10-13 23:59:59
signed using      : ECDSA with SHA256
EC key size       : 256 bits
basic constraints : CA=false
subject alt name  : iot.us-east-2.amazonaws.com, *.iot.us-east-2.amazonaws.com
key usage         : Digital Signature
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#63   This certificate has no flags

ready to write 877 byte
write 877 byte succeeds
ready to write 75 byte
write 75 byte succeeds
ready to write 269 byte
write 269 byte succeeds
ready to write 6 byte
write 6 byte succeeds
ready to write 69 byte
write 69 byte succeeds
ready to read 5 byte
read 5 byte succeeds
ready to read 1 byte
read 1 byte succeeds
ready to read 5 byte
read 5 byte succeeds
ready to read 64 byte
read 64 byte succeeds
DEBUG:   iot_tls_connect L#255  ok
    [ Protocol is TLSv1.2 ]
    [ Ciphersuite is TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA ]

DEBUG:   iot_tls_connect L#257     [ Record expansion is 41 ]

DEBUG:   iot_tls_connect L#262   . Verifying peer X.509 certificate...
DEBUG:   iot_tls_connect L#271  ok

DEBUG:   iot_tls_connect L#281   . Peer certificate information    ...

DEBUG:   iot_tls_connect L#283       cert. version     : 3
      serial number     : 3C:75:FE:30:01:DD:A3:B9:EF:72:DC:F6:7A:5C:A2:54
      issuer name       : C=US, O=Symantec Corporation, OU=Symantec Trust Network, CN=Symantec Class 3 ECC 256 bit SSL CA - G2
      subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.iot.us-east-2.amazonaws.com
      issued  on        : 2017-10-12 00:00:00
      expires on        : 2018-10-13 23:59:59
      signed using      : ECDSA with SHA256
      EC key size       : 256 bits
      basic constraints : CA=false
      subject alt name  : iot.us-east-2.amazonaws.com, *.iot.us-east-2.amazonaws.com
      key usage         : Digital Signature
      ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication


ready to write 85 byte
write 85 byte succeeds
ready to read 5 byte
read 5 byte succeeds
ready to read 48 byte
read 48 byte succeeds
connect ok----

Subscribing...
ready to write 101 byte
write 101 byte succeeds
ready to read 5 byte
read 5 byte succeeds
ready to read 48 byte
read 48 byte succeeds
-->sleep
ready to write 85 byte
write 85 byte succeeds
ready to write 85 byte
write 85 byte succeeds
ready to read 5 byte
read 5 byte succeeds
ready to read 48 byte
read 48 byte succeeds
-->sleep

Thank you.

**Comment by huguesBouvier** [comment]
Hello,

Do you still need help on the issue? If not can I close it?

Hugues
