### ISSUE TITLE
AWS IoT life cycle events connected/disconnected support in AWS greengrass

### ISSUE THREAD

**Issue by ravichandhraRean** [aws/aws-iot-device-sdk-embedded-C#209]
Hi Team,

**Lifecycle Events:**
AWS IoT publishes lifecycle events on the MQTT topics discussed in the following sections. These messages allow you to be notified of lifecycle events from the message broker.

**Connect/Disconnect Events**
AWS IoT publishes a message to the following MQTT topics when a client connects or disconnects.

$aws/events/presence/connected/clientId  or $aws/events/presence/disconnected/clientId

**Subscribe/Unsubscribe Events**
AWS IoT publishes a message to the following MQTT topic when a client subscribes or unsubscribes to an MQTT topic.

$aws/events/subscriptions/subscribed/clientId  or  $aws/events/subscriptions/unsubscribed/clientId

Source: https://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html

Is subscribe to lifecycle events supported in aws greengrass?

If yes How can I subscribe to lifecycle events?

Thank you.

--Regards,
Ravichandhra Palla

**Comment by huguesBouvier** [comment]
Hello,

Lifecycle is not supported in Greengrass. 
You could potential work around the problem by creating a lambda function in your greengrass to simulate the event service: https://aws.amazon.com/blogs/aws/aws-greengrass-run-aws-lambda-functions-on-connected-devices/

Hugues

**Comment by ravichandhraRean** [comment]
Hi Hugues,

Thank you for your reply, we will try to implement it using user lambdas.

Ravichandhra Palla
