### ISSUE TITLE
Shadow connect fails when using explicit client ID in iot:Connect policy action

### ISSUE THREAD

**Issue by lencia68** [aws/aws-iot-device-sdk-embedded-C#21]
In aws_iot_shadow_connect(), “ConnectParams.clientIDLen” is not being set prior to calling aws_iot_mqtt_connect(). It remains zero when aws_iot_mqtt_internal_write_utf8_string() is called in _aws_iot_mqtt_serialize_connect() .

Note, a policy action of iot:* (or iot:Connect) with a resource of “*” is not impacted by this issue (i.e., many will not see the problem).

Also, in example subscribe_publish_sample.c the setting of “clientIDLen” is missing as well (and it would seem that AWS_IOT_MQTT_CLIENT_ID should be used for setting both “pClientID” and “clientIDLen”).

**Comment by chaurah** [comment]
Hi @lencia68,
       Thank you for pointing out this issue. This looks like a very good test case as well. We are tracking this issue internally and a fix will be included in the next release of the SDK. Please do let us know if you notice any other issues. The 2.0.0 release has been a fairly large change and we appreciate any suggestions for further improvement.


Rahul

**Comment by chaurah** [comment]
Hi @lencia68,
          The code has been updated with a fix for this issue. Client ID Length is passed to the underlying client now. Please let us know if you have further issues. Thank you for using AWS IoT.

Rahul
