### ISSUE TITLE
disconnection event is not immediately

### ISSUE THREAD

**Issue by kingmayko** [aws/aws-iot-device-sdk-embedded-C#210]
I use shadow example as [https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/master/samples/linux/shadow_sample]
When I disable wifi at access point , I didn't receive disconnection event until about 15 minute later.  
And even network is enable before 15 minute,  the data can't publish to aws iot. 

Is there config to set. or I need use aws_iot_is_autoreconnect_enabled by my self when publish has error.

**Comment by gordonwang0** [comment]
Hi @kingmayko,

There's no configuration you can set in the SDK for this scenario.  The behavior you see when disconnecting the network depends heavily on your OS.  The SDK has no way of knowing if the network is disconnected, or just unreasonably slow; in both cases, it will receive a timeout on a network SSL operation and retry.  You may be able to use a function provided by your OS to check the true status of the network and modify the SDK to respond based on that.

**Comment by kingmayko** [comment]
Thanks.   I get it.
