### ISSUE TITLE
Feature change to AWS TLS port layer

### ISSUE THREAD

**Issue by umanayana** [aws/aws-iot-device-sdk-embedded-C#211]
Hi, 
I was reviewing the TLS porting layer for the sdk and I think it's not generic enough. 
I think the `TLSConnectParams` structure should be defined by the port layer. 

What if the caller requires more configuration parameter to setup there TLS layer? A specific problem I have run into is that I need two server certificates and two client certificates.  But these certificates are stored in DER format. Thus I cannot append them in `pRootCALocation` or `pDeviceCertLocation` because if I append one DER formatted cert to the other I won't be able to parse them. 

Converting the certs to PEM is not possible due to memory constraint. Also these certificates are actually stored in flash, and I can't copy them to RAM because of memory constraints.

Additional the the method `aws_iot_mqtt_init` check to see if  struct `IoT_Client_Init_Params::pRootCALocation`, `IoT_Client_Init_Params::pDevicePrivateKeyLocation` and `IoT_Client_Init_Params::pDeviceCertLocation` are NULL. But it's perfectly valid for these things to be NULL because the porting layer may be doing something differently. Especially if hardware secure element is used the private key will not be on the actual device.

I think it should the up to the porting layer to define this.

**Comment by lt72** [comment]
HI @umanayana, you bring up an excellent point. 
We will prioritize your design change proposal against our roadmap and get back to you.

**Comment by gordonwang0** [comment]
Hi @umanayana,

This has been addressed in [version 4 beta](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta).  The equivalent of the TLS connect params is defined by the platform layer, and the platform layer is separated from the MQTT library.  Please let me know if you have any questions on this.
