### ISSUE TITLE
Feature change on how `Network::destroy` callback is called throughout the stack 

### ISSUE THREAD

**Issue by umanayana** [aws/aws-iot-device-sdk-embedded-C#212]
In the stack the `Network::destroy` method is called after every `Network::disconnect`. This isn't a very inefficient and can lead to memory fragmentation.  The destroy method only needs to be called if the intent is to tear down the stack. 

I am using the mbedTLS library for all TLS. After the TLS context are setup they do not need to be destroyed if a reconnected strategy is required. All that needs to be done is a socket connection reestablished and a new handshake attempt is done.
Every-time a destroy is called memory is freed, then on reconnect that memory needs to be recreated. This is a major concern on small MCU with little RAM which need to run 24/7 without failure.

I have gotten around this by never making `Network::destroy` cleanup the TLS context is it's already initialised. I've also added some special code to `Network::connect` to do a reconnect and not reinitialise the TLS context, if already initialised. 

On a side note if a client losses connection is a destroy called anywhere along the chain?

**Comment by gordonwang0** [comment]
Hi @umanayana,

You bring up a good point.  We'll consider this in our future designs for this SDK.

To answer your question: Yes, if the client looses disc`iot_tls_destroy` may be called as part of the disconnect process if a client fails to send of receive data.

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/8094f1e444b0aac92eda6371b956a2c619a40a42/src/aws_iot_mqtt_client_yield.c#L211-L212

(The call to disconnect on 212 will call TLS destroy).

**Comment by gordonwang0** [comment]
Hi @umanayana,

I've taken this into account with [v4 beta](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta).  Disconnecting the network connection is only followed by a destroy when shutting down.  Please take a look at v4 beta if you have time.
