### ISSUE TITLE
NETWORK_SSL_WRITE_TIMEOUT_ERROR should not trigger disconnect

### ISSUE THREAD

**Issue by umanayana** [aws/aws-iot-device-sdk-embedded-C#214]
Hi, 
So I have been reviewing the stack some more. In the `_aws_iot_mqtt_internal_yield()` method the error code `NETWORK_SSL_WRITE_TIMEOUT_ERROR` will cause a disconnect I don't think this is efficient. Consider a multi threaded system where other task need to do work it's perfectly acceptable that we don't have enough time to send all the data we wanted to send in one go. But disconnecting and reconnecting is not the solution this means the device has to re-handshake, which is very processor intensive.

A connection which times out should check to see if some bytes were sent, if some bytes were sent it should send the remaining bytes when it has time to do so. This will require a TX buffer though as it appears these messages are places on the stack.

A write timeout should not indicate that the TLS connection has died as it appears this how the stack is using this error code. If there is a actual error on the write the porting layer should indicate there is an error and not indicate a `NETWORK_SSL_WRITE_TIMEOUT_ERROR`.

**Comment by lt72** [comment]
@umanayana thank you for your review. We will consider this issue and circle back.

**Comment by gordonwang0** [comment]
Hi @umanayana,

It's actually part of the MQTT standard for a client to [disconnect on what they call "transient errors"](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718110), such as being unable to send data.

However, I understand that it's not ideal to re-handshake, as you mentioned.  This has been somewhat addressed in [version 4 beta](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta).  Version 4 separates the network stack implementation from MQTT, and takes a [function pointer for disconnect](https://docs.aws.amazon.com/freertos/latest/lib-ref/html3/mqtt/structAwsIotMqttNetIf__t.html#ab9a2789f64776e34c4f1d653049a672f).  You may set this to `NULL`, and then the MQTT library will not disconnect for any reason.  Or, you may set this to some custom function, and choose whether to disconnect the network in this function implementation.
