### ISSUE TITLE
ECC server root CA instead of RSA 

### ISSUE THREAD

**Issue by umanayana** [aws/aws-iot-device-sdk-embedded-C#215]
Hi,

I am using the RSA root CA for server validation. The CA can be found in the link below. Is there an alternative version for this using ECC? Using RSA is extremely processor intensive and the handshake takes around 7 seconds. 

VeriSign Class 3 Public Primary G5 root CA certificate
https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem

AWS documentation 
https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html

**Comment by gordonwang0** [comment]
Hi @umanayana,

This should be possible.  I believe that if your client advertises that it only supports EC cipher suites, you will get an EC server certificate.  Can you give this a try?

However, as that documentation says, you'll always have to include the VeriSign Class 3 Primary root CA cert.

**Comment by umanayana** [comment]
Do you know why the Versign cert is required?

**Comment by gordonwang0** [comment]
Hi @umanayana,

The VeriSign root CA cert is used to determine the trustworthiness of the other certificates.  It's required to verify if the server certificate can be trusted.

**Comment by gordonwang0** [comment]
Hi @umanayana,

Please let me know if you need any more assistance with this.  Closing issue.
