### ISSUE TITLE
Can we connect to Greengrass Core device using this library

### ISSUE THREAD

**Issue by fanghuaqi** [aws/aws-iot-device-sdk-embedded-C#216]
Hi, I am wondering whether we can use this library to connect to Grassgrass core, and what is the relationship between this library and amazon_freertos?

Thanks
Huaqi

**Comment by lt72** [comment]
Hi @fanghuaqi, yes you can connect to greengrass, e.g. take a look at #202. 
This library duplicates the same set of services that FreeRTOS libs offer
The intended users are those developers that either do not want/need to use FreeRTOS (e.g. they want/need to use a different RTOS or OS, e.g. embedded Linux), or that do not want to use and RTOS at all.

**Comment by fanghuaqi** [comment]
Hi @lt72 , thanks for your declaration, at first I thought this amazon_freertos is the only way to connect to Greengrass Core, btw, is there any official documentation about how to connect to Greengrass core. I will also take a look at the issue discussion.

Thanks
Huaqi

**Comment by lt72** [comment]
@fanghuaqi I believe this is the documentation: https://aws.amazon.com/documentation/greengrass/
@gordonwang0 any other pointers we can offer?

**Comment by gordonwang0** [comment]
Hi @fanghuaqi,

This SDK doesn't "officially" support Greengrass, but many customers have successfully connected to GG.

Here are some helpful posts if you encounter any issues: #209, #208, #202, #193
