### ISSUE TITLE
configure the certificate as trusted in C AWS IOT SDK

### ISSUE THREAD

**Issue by muradali362** [aws/aws-iot-device-sdk-embedded-C#219]
I am trying to connect to greengrass core using arduino AWS-IOT example for esp32 
Manually entering root CA of my greenGrass core and host address(IP OF GREENGRASS CORE )
 
ERROR OCCURRING :
ERROR: iot_tls_connect L#222 failed
! mbedtls_ssl_handshake returned -0x2700

Please help me in
1)Disabling the SNI? 
don't know where to disable SNI in sdk?

2)configure the certificate as trusted?
Please help 

Many thanks in advance.

**Comment by huguesBouvier** [comment]
Hello,

You should disable the SNI by doing the following command:
Set the mqttInitParams.isSSLHostnameVerify to false

If you are passing the root CA in the MQTT param like this:
mqttInitParams.pRootCALocation = pParams->pRootCA;
mqttInitParams.pDeviceCertLocation = pParams->pClientCRT;
mqttInitParams.pDevicePrivateKeyLocation = pParams->pClientKey;
it should be set automatically as trusted inside the TLS wrappers. You should not have to do that.
Best,

Hugues

**Comment by muradali362** [comment]
Thank you so much sir. I will try this tomorrow. Can i contact you if i
face any issue. And if possible can i get your skype id please

**Comment by muradali362** [comment]
it worked

**Comment by huguesBouvier** [comment]
Great :). I'll close the issue then.
