### ISSUE TITLE
CMake

### ISSUE THREAD

**Issue by jdelaune** [aws/aws-iot-device-sdk-embedded-C#22]
Is it possible to include CMake files in the examples? Thanks

**Comment by chaurah** [comment]
Hi @jdelaune,
     We have plans to introduce CMake in a future release of the SDK. I can't give you an exact timeline yet though. I will update this issue as soon as we have a release out that includes CMake files.

Rahul

**Comment by revmischa** [comment]
:-1: due to CMake being a giant trash heap

**Comment by chaurah** [comment]
Hi @revmischa,
        You don't need to worry :) If CMake will not replace Makefiles completely. When we include it, it will be as a sample. I am curious though if you have any build process suggestions that you would like to see included. It might be useful information for further improvements.

Rahul

**Comment by revmischa** [comment]
I have a very minor improvement to the makefiles in https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/26
I think we could refactor the common make stuff into a make include file.
I use a modified version of the makefiles in https://github.com/revmischa/cloudcam/blob/master/Makefile
This is also working and running okay on OSX. All of the stuff named "linux" could probably be renamed "posix".
