### ISSUE TITLE
MQTT Connection Closed

### ISSUE THREAD

**Issue by heezes** [aws/aws-iot-device-sdk-embedded-C#221]
Hello,
I'm using a GSM with SSL with paho client for connecting to the AWS IoT broker. I'm able to publish and subscribe to the broker but the client gets disconnected from broker after some time ( some time 5- 10 min other time even 1 hour). The client sends the Ping request (keepalive interval 30 sec) but there is no response from the broker even after the grace period and then the SSL connection is closed ad re connection happens after several retries. I have checked the network stability and it is steady. What is more confusing after the reconnect sometimes the MQTT connect request has no reply from server. Anybody knowing about this issue please help.

**Comment by lt72** [comment]
@heezes hi, do you have any logs from the device?

**Comment by heezes** [comment]
Hi there, 
Currently the GSM modules does not gives any tcp or ssl dump which can be reviewed for debugging but i'm in talks with manufacturers technical team regarding the debug logs. Will provide them as soon as i get them.
Thanks.

**Comment by lt72** [comment]
We are not familiar with your GSM module and likely we will not be able to help with that, although it could still be interesting to take a look at them.
I was actually referring to logs from the MQTT liband/or the C-SDK in general. Those will be certainly useful.

**Comment by heezes** [comment]
As of of now the paho embedded client i'm using has no debug o/p but i will add that and share them here soon.

**Comment by lt72** [comment]
I did not catch you are using the Paho client. If you use our MQTT client then we can support you.

**Comment by gordonwang0** [comment]
Hi @heezes,

Please let us know if you need any further assistance with this.  Closing issue.
