### ISSUE TITLE
AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS setting it to 0?

### ISSUE THREAD

**Issue by umanayana** [aws/aws-iot-device-sdk-embedded-C#223]
Hi, 

Is it save to set the `AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS` parameter to `0` if the application code is not making any calls to `aws_iot_mqtt_subscribe()`?

If not what is the minimum value required for the stack top run MQTT? MQTT ping request must still occur. 

Thanks

**Comment by gordonwang0** [comment]
Hi @umanayana,

You can safely set `AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS` to `0` if you don't use subscriptions. Pings do not use the subscription handler.

**Comment by lt72** [comment]
Hi @umanayana, I will close the issue. Please re-open if you need to,
