### ISSUE TITLE
AWS SDK 3.0.1 hang with MAX_ACKS_TO_COMEIN_AT_ANY_GIVEN_TIME=512

### ISSUE THREAD

**Issue by prashanthtandel** [aws/aws-iot-device-sdk-embedded-C#224]
Hi All,
I am using AWS IoT SDK v3.0.1 in one project. We upgraded the sdk from 1.1.2 to 3.0.1. 
We are planning to use the same aws_iot_config.h in 3.0.1 that we used with 1.1.2. Out of all the parameters, it has been observed that setting MAX_ACKS_TO_COMEIN_AT_ANY_GIVEN_TIME to 512 causes sdk to go in some unknown state.
The call to aws_iot_shadow_connect() does not return. If we change the macro value to 100 instead of 512 then everything works fine and shadow update works as expected.

Please let me know if anymore details are required.

**Comment by gordonwang0** [comment]
Hi @prashanthtandel,

The maximum allowed value for `MAX_ACKS_TO_COMEIN_AT_ANY_GIVEN_TIME` is 255.

**Comment by prashanthtandel** [comment]
Thank you @gordonwang0 for your answer.
I would greatly appreciate if you can help me get the answers for following.
- So, is the maximum limit for this macro (255) changed for this sdk version (v3.0.1)? We have been using 512 in SDK v1.1.2 without any issues.
- Where can I find the maximum limit for these parameters? Is there any documentation?
- We are using following parameters in our aws_iot_config.h and would like to know the maximum and optimum value for them.
#define AWS_IOT_MQTT_TX_BUF_LEN
#define AWS_IOT_MQTT_RX_BUF_LEN
#define AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS
#define MAX_SIZE_OF_UNIQUE_CLIENT_ID_BYTES
#define MAX_ACKS_TO_COMEIN_AT_ANY_GIVEN_TIME
#define MAX_THINGNAME_HANDLED_AT_ANY_GIVEN_TIME
#define MAX_JSON_TOKEN_EXPECTED
#define MAX_SHADOW_TOPIC_LENGTH_WITHOUT_THINGNAME
#define MAX_SIZE_OF_THING_NAME
#define MAX_SHADOW_TOPIC_LENGTH_BYTES
#define AWS_IOT_MQTT_MIN_RECONNECT_WAIT_INTERVAL
#define AWS_IOT_MQTT_MAX_RECONNECT_WAIT_INTERVAL

**Comment by gordonwang0** [comment]
Hi @prashanthtandel,

- Between version 1.1.2 and version 3.0.1, the type for iterating across the ACK list was changed from `int32_t` to `uint8_t`.  This is what decreased the maximum value of `MAX_ACKS_TO_COMEIN_AT_ANY_GIVEN_TIME`.
- Unfortunately, there is no documentation for this.  I will look into getting the documentation updated.

The maximum size of the constants you list is generally the maximum valuable of its data type or some value defined by the MQTT or [AWS IoT service limits](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html).  The optimal value depends on your application; I would recommend leaving the default values that are in `aws_iot_config.h`.

According to the AWS IoT service limits, the maximum values are as follows.
- `AWS_IOT_MQTT_TX_BUF_LEN` and `AWS_IOT_MQTT_RX_BUF_LEN`  8KB (max size of a Shadow) for the vast majority of use cases.
- `AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS` 500,000
- `MAX_SIZE_OF_UNIQUE_CLIENT_ID_BYTES` 128
- `MAX_ACKS_TO_COMEIN_AT_ANY_GIVEN_TIME` 255
- `MAX_THINGNAME_HANDLED_AT_ANY_GIVEN_TIME` 128
- `MAX_JSON_TOKEN_EXPECTED` depends on the size of your Shadow.
- `AWS_IOT_MQTT_MIN_RECONNECT_WAIT_INTERVAL` and `AWS_IOT_MQTT_MAX_RECONNECT_WAIT_INTERVAL` are unlimited. Depends on your network connection.

**Comment by gordonwang0** [comment]
You're welcome!  I will close this issue now.
