### ISSUE TITLE
Calling aws_iot_mqtt_publish() method from within a subscriber callback

### ISSUE THREAD

**Issue by umanayana** [aws/aws-iot-device-sdk-embedded-C#227]
Is it safe to call `aws_iot_mqtt_publish()` method from within a MQTT subscriber callback `pApplicationHandler_t()`.

I have a scenario where when I get incoming payload on a topic I have to send back a message on another topic when I parse the payload. The payload parsing occurs within the callback because I can't copy memory anywhere.

Thanks

**Comment by gordonwang0** [comment]
Hi @umanayana,

You can call `aws_iot_mqtt_publish` in a subscribe callback.

**Comment by gordonwang0** [comment]
Hi @umanayana,

Please let me know if you need any more help with this.  Closing issue.
