### ISSUE TITLE
AWS IoT NOT CLEARING THE DESIRED SECTION AFTER GETTING REPORTED

### ISSUE THREAD

**Issue by ravichandhraRean** [aws/aws-iot-device-sdk-embedded-C#229]
we want operate a device lock both remotely and manually.

device is locked initially and at the time of connecting to IoT it sets it's shadow like this { "reported" : { "LOCK": "locked" } }

after someone remotely sets shadow desired to unlocked like this { "desired" : { "LOCK" : "unlock" } } so the shadow now will be like this { "desired" : { "LOCK" : "unlock" } , "reported" : { "LOCK": "locked" }, "delta" : { "LOCK" : "unlock" } }

device received the delta message and unlocked and reported back like this { "reported" : { "LOCK" : "unlock" } } so the shadow now will be like this { "desired" : { "LOCK" : "unlock" } , "reported" : { "LOCK": "unlock" }}

Till this point everything working fine,

but now someone manually locked the device so device reported it's current state to shadow like this
like this { "reported" : { "LOCK" : "locked" } } so here the problem comes now because the AWS IoT NOT CLEARING THE DESIRED SECTION AFTER GETTING REPORTED the shadow now will be like this
{ "desired" : { "LOCK" : "unlock" } , "reported" : { "LOCK": "locked" }, "delta" : { "LOCK" : "unlock" } }
and immediately getting callback to device with delta message (which is not required / previously desired).

so we are not able to solve this and AWS IoT NOT SUPPORTING BOTH REMOTE AND MANUAL OPERATION OF DEVICE(this is one use-case there will be many use-cases where both required)

thank you.

Regards,
Ravichandhra Palla
ravichandhra.palla@reancloud.com
REAN Cloud

**Comment by gordonwang0** [comment]
Hi @ravichandhraRean,

You are correct, the Shadow service does not clear the `desired` state after getting a new `reported` state.  However, this is the expected behavior of the Shadow service.

You will have to clear the `desired` state yourself.  Let's say the current Shadow is:
```json
{
    "state" :
    {
        "desired": { "LOCK": "unlock" },
        "reported": { "LOCK": "lock"}
    }
}
```

You should send the following Shadow update:
```json
{
    "state" :
    {
        "desired": null,
        "reported": { "LOCK": "unlock"}
    }
}
```

That update will set the `reported` state and clear the `desired` state; no more delta documents will be generated.

**Comment by ravichandhraRean** [comment]
Hi @gordonwang0,

thank you for your quick response , 

yes we are also doing the same what you are mentioned in your reply, but we are using that setting "desired" parameters null to reject requests / indicate failures  from device side.

And one more we can't set entire desired state to null because there will be some pending requests needs response from device are still waiting in desired state.

We thought it would be better If AWS consider this clearing reported delta.

Thank you,

Regards,
Ravichandhra Palla
ravichandhra.palla@reancloud.com
REAN Cloud

**Comment by gordonwang0** [comment]
Hi @ravichandhraRean,

I see.  The changes you propose are service-side.  I suggest creating a [forum post](https://forums.aws.amazon.com/forum.jspa?forumID=210), as our team here only manages the SDK and not the service.

**Comment by ravichandhraRean** [comment]
@gordonwang0  / @lt72 

I raised this in forum https://forums.aws.amazon.com/thread.jspa?threadID=289936
could you please redirect it to that team so I can get reply on this.

Thank you,

Regards,
Ravichandhra Palla
ravichandhra.palla@reancloud.com
REAN Cloud

**Comment by gordonwang0** [comment]
Hi @ravichandhraRean,

Please let us know if you need any more help with this.  Closing issue.

**Comment by matwerber1** [comment]
@ravichandraRean,

Note that you can remove individual prepped toes from desired state by setting the target property to null, rather than setting the entire desired stage to null.

For example, you can publish this message to remove property2 while keeping property1:
‘’’
desired: {
  property1: “on”,
  property2: “null
}
‘’’
