### ISSUE TITLE
Shadows 'isThingAttached' will not work if Client ID and Thing Name are different values.

### ISSUE THREAD

**Issue by lt72** [aws/aws-iot-device-sdk-embedded-C#232]
Client ID and Thing Name can be set to different values for Shadows.
Though we can use different values, the use of different values stop one from using the isThingAttached clause. At the very least this need be clarified as a pre-requisite/implementation guidance in public facing documentation which describes the isThingAttached example. Developers should know the implications of the choice around using the same/different value across Client ID and Thing Name.

**Comment by gordonwang0** [comment]
Thing Attributes will only work for matching Thing Names.  [Documentation](https://docs.aws.amazon.com/iot/latest/apireference/API_ThingAttribute.html).  Will reference that.
