### ISSUE TITLE
aws_iot_shadow_add_reported should be incremental or a non-variadic version should be available

### ISSUE THREAD

**Issue by aztecrex** [aws/aws-iot-device-sdk-embedded-C#233]
This is a set operation but its name indicates (at least to me) that it is an incremental add operation. However, it might be better to make it an incremental add rather than a set.  Or at least make a version that takes an array instead of variadic parameters. 

As it is, the function doesn't easily support a collection of actuator states that update independently. What I would like to happen is for the "desired" state handler to update a queue of pending "reported" updates. Then, the main loop of the task can gather all the awaiting updates and set them in one operation. 

To use the function now, I either have to send each actuator update individually, or send the status of every actuator whether it has changed or not. Either solution results in way more traffic than needed. It also requires more logic in clients consuming foreign updates on actuator states.

It seems like it would be common to want to update part of the shadow depending on runtime conditions. But to use this function now, we need to know exactly what will be updated at compile time.

**Comment by gordonwang0** [comment]
Hi @aztecrex,

Apologies for the delayed response.

I understand the problem you're facing.  The fix is to be implemented in the next major release of this SDK.  We are actively working on that, though I'm not able to provide an ETA at this time.

**Comment by qiutongs** [comment]
Thank you for reporting the problem. We are tracking this issue internally.
