### ISSUE TITLE
AWS Greengrass core connection probing.

### ISSUE THREAD

**Issue by amarnath87** [aws/aws-iot-device-sdk-embedded-C#234]
Hi,

How to check regularly whether AWS Greengrass core is connected to cloud or not. My application is running on ubuntu and conneting GG on other device. How to verify that GG core has lost the connection.

Thanks,
Amarnath

**Comment by amarnath87** [comment]
Hi, 

Any update on this.

Amarnath

**Comment by huguesBouvier** [comment]
Hi,

I am still waiting on an answer, I will see them in person today. I though of something that could work:
=> By using the lambda feature and last will and testament.
MQTT does have a last will and testament feature that will send a message to all devices through the proper MQTT channel when that message gets disconnected. 

If you setup a lamba on the GG that reccords a Last will and testament then if your GG get disconnected, you lambda will also lose its connection and the MQTT server will send its last will.

You can combine the LW and testament with shadows:
https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-data-flow.html

Can this help?

Hugues

**Comment by amarnath87** [comment]
Hi,

Thank you for the  information. Let me try as you told and come back on it.

Amarnath

**Comment by gordonwang0** [comment]
Hi @amarnath87,

Please let us know if you need any more help with this.  Closing issue.
