### ISSUE TITLE
Build a MQTT Client Application how to

### ISSUE THREAD

**Issue by DiazSo** [aws/aws-iot-device-sdk-embedded-C#236]
Hi All, 

I would like to use this SDK to build a MQTT Client application for my embedded platform, is there any example ? 
My embedded platform is MIPS cpu core, linux OS.
It is necessary to use cross-compile tool to make this SDK, is there any example?
and in advance, is there any example that is running on linux embedded platform?

Thanks!

**Comment by gordonwang0** [comment]
Hi @DiazSo,

The [samples/linux](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/master/samples/linux) directory in this repo contains SDK samples running on Linux.

If you are cross-compiling, you will have to modify the Makefile in each sample directory to use your cross-compiler by changing `CC` and `LD_FLAG` if necessary.

**Comment by gordonwang0** [comment]
Hi @DiazSo,

Please let me know if you need any more help with this.  Closing issue.
