### ISSUE TITLE
Failed to setup TLS session when run sample on test decvice

### ISSUE THREAD

**Issue by Leesphone** [aws/aws-iot-device-sdk-embedded-C#237]
Hi All,

I had tried run those samples on our device but failed with below procedure, could anyone help take a look?
 a. Create a thing thru AWS console, define thing name and download cert/key
 b. Update aws_iot_config.h thing name base on #a.
 c. Install cert/key on device and then run it but got error "! mbedtls_net_connect returned -0x52"

Notes: we did tried ping "console.aws.amazon.com" to make sure network connectivity is okay before we run those samples

Detail logs attached as below:

/mnt/ramdisk/certs # jobs_sample 
DEBUG:   main L#248 rootCA /mnt/ramdisk/certs/../../../certs/rootCA.crt
DEBUG:   main L#249 clientCRT /mnt/ramdisk/certs/../../../certs/cert.pem
DEBUG:   main L#250 clientKey /mnt/ramdisk/certs/../../../certs/privkey.pem
Connecting...
DEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to /443...
ERROR: iot_tls_connect L#164  failed
  ! mbedtls_net_connect returned -0x52

ERROR: main L#280 Error(-23) connecting to :443
/mnt/ramdisk/certs #

**Comment by gordonwang0** [comment]
Hi @Leesphone,

> ERROR: main L#280 Error(-23) connecting to :443

It looks like you didn't set your `AWS_IOT_MQTT_HOST` in `aws_iot_config.h`.  This can be found on the "Settings" page of AWS IoT Core web console, and has a format of `X.iot.Y.amazonaws.com`.

**Comment by Leesphone** [comment]
Hi Gordon,

Appreciate for your comments, tried update MQTT HOST and meet a new error as below:

/mnt/ramdisk/root # jobs_sample 
DEBUG:   main L#248 rootCA /mnt/ramdisk/root/../../../certs/rootCA.crt
DEBUG:   main L#249 clientCRT /mnt/ramdisk/root/../../../certs/cert.pem
DEBUG:   main L#250 clientKey /mnt/ramdisk/root/../../../certs/privkey.pem
Connecting...
DEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to apg7f0u84gxki-ats.iot.us-west-2.amazonaws.com/443...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 2):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 06:6C:9F:CF:99:BF:8C:0A:39:E2:F0:78:8A:43:E6:96:36:5B:CA
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, CN=Amazon Root CA 1
issued  on        : 2015-05-26 00:00:00
expires on        : 2038-01-17 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 06:7F:94:57:85:87:E8:AC:77:DE:B2:53:32:5B:BC:99:8B:56:0D
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
issued  on        : 2015-10-22 00:00:00
expires on        : 2025-10-19 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true, max_pathlen=0
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 0F:63:0F:0F:C5:33:AF:F1:EC:D8:5B:39:0F:4D:AB:35
issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
subject name      : CN=*.iot.us-west-2.amazonaws.com
issued  on        : 2018-08-02 00:00:00
expires on        : 2019-08-02 12:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : iot.us-west-2.amazonaws.com, *.iot.us-west-2.amazonaws.com
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

**ERROR: iot_tls_connect L#232  failed
  ! mbedtls_ssl_handshake returned -0x7780**

ERROR: main L#280 Error(-4) connecting to apg7f0u84gxki-ats.iot.us-west-2.amazonaws.com:443
/mnt/ramdisk/root #

**Comment by gordonwang0** [comment]
Hi @Leesphone,

Error -4/mbedTLS -0x7780 usually means there's an issue with your client certificate.  Please verify that your client certificate is valid and correctly formatted (PEM-encoded).

**Comment by Leesphone** [comment]
Those certificate are download from AWS IOT when create a new thing, it's already PEM encoded when download from web site, anything wrong here?

**Comment by gordonwang0** [comment]
Hi @Leesphone,

I believe certificates downloaded from the AWS IoT console will work.  However, the -4 error generally happens when the certificate is malformed.  Can you verify that the certificate you downloaded was renamed 'cert.pem', and the private key 'privkey.pem' and that the certificates were not modified?  Or try parsing the certificate with something like OpenSSL to make sure that it's valid?

**Comment by Leesphone** [comment]
Hi Gordon,

1. I'm pretty sure the file name is exact same as the named we used in sample code, if file name is not correct (tried rename), it will report error as below:
    /mnt/ramdisk/certs # jobs_sample 
DEBUG:   main L#248 rootCA /mnt/ramdisk/certs/../../../certs/rootCA.crt
DEBUG:   main L#249 clientCRT /mnt/ramdisk/certs/../../../certs/cert.pem
DEBUG:   main L#250 clientKey /mnt/ramdisk/certs/../../../certs/privkey.pem
Connecting...
DEBUG:   iot_tls_connect L#130 

2. Tried using openSSL to verify the cert.pem, it present good. 
    #openssl x509 -in cert.pem -text
   For cert.pem and privkey.pem, just rename base on file download from AWS, don't do any modification to the cert.
    "a8898cdd29-certificate.pem.crt" -> cert.pem
    "a8898cdd29-private.pem.key" -> privkey.pem
    "a8898cdd29-public.pem.key" -> Do we need merge to cert.pem? or ? Now we don't put this file to "/certs" folder.

**Comment by gordonwang0** [comment]
Hi @Leesphone,

You only need cert.pem and privkey.pem from the console.  You can discard the publish key file.

Can you also check your [AWS IoT policy](https://docs.aws.amazon.com/iot/latest/developerguide/iot-policies.html) to make sure that it allows you to connect?

**Comment by Leesphone** [comment]
Tried re-generate the cert/key and test again, looks like the error reason is different now. Any idea?

/mnt/ramdisk/root # jobs_sample 
DEBUG:   main L#248 rootCA /mnt/ramdisk/root/../../../certs/rootCA.crt
DEBUG:   main L#249 clientCRT /mnt/ramdisk/root/../../../certs/cert.pem
DEBUG:   main L#250 clientKey /mnt/ramdisk/root/../../../certs/privkey.pem
Connecting...
DEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to apg7f0u84gxki-ats.iot.ap-northeast-1.amazonaws.com/443...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 2):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 06:6C:9F:CF:99:BF:8C:0A:39:E2:F0:78:8A:43:E6:96:36:5B:CA
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, CN=Amazon Root CA 1
issued  on        : 2015-05-26 00:00:00
expires on        : 2038-01-17 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 06:7F:94:57:85:87:E8:AC:77:DE:B2:53:32:5B:BC:99:8B:56:0D
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
issued  on        : 2015-10-22 00:00:00
expires on        : 2025-10-19 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true, max_pathlen=0
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 03:B5:C7:CB:A2:25:0D:1C:68:0A:9C:70:97:40:28:C3
issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
subject name      : CN=*.iot.ap-northeast-1.amazonaws.com
issued  on        : 2018-08-02 00:00:00
expires on        : 2019-08-02 12:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : iot.ap-northeast-1.amazonaws.com, *.iot.ap-northeast-1.amazonaws.com
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   iot_tls_connect L#246  ok
    [ Protocol is TLSv1.2 ]
    [ Ciphersuite is TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384 ]

DEBUG:   iot_tls_connect L#248     [ Record expansion is 29 ]

DEBUG:   iot_tls_connect L#253   . Verifying peer X.509 certificate...
DEBUG:   iot_tls_connect L#262  ok

DEBUG:   iot_tls_connect L#272   . Peer certificate information    ...

DEBUG:   iot_tls_connect L#274       cert. version     : 3
      serial number     : 03:B5:C7:CB:A2:25:0D:1C:68:0A:9C:70:97:40:28:C3
      issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
      subject name      : CN=*.iot.ap-northeast-1.amazonaws.com
      issued  on        : 2018-08-02 00:00:00
      expires on        : 2019-08-02 12:00:00
      signed using      : RSA with SHA-256
      RSA key size      : 2048 bits
      basic constraints : CA=false
      subject alt name  : iot.ap-northeast-1.amazonaws.com, *.iot.ap-northeast-1.amazonaws.com
      key usage         : Digital Signature, Key Encipherment
      ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication


ERROR: main L#280 Error(-12) connecting to apg7f0u84gxki-ats.iot.ap-northeast-1.amazonaws.com:443
/mnt/ramdisk/root # 
/mnt/ramdisk/root # 
/mnt/ramdisk/root # 
/mnt/ramdisk/root # subscribe_publish_sample 

AWS IoT SDK Version 3.0.1-

DEBUG:   main L#159 rootCA /mnt/ramdisk/root/../../../certs/rootCA.crt
DEBUG:   main L#160 clientCRT /mnt/ramdisk/root/../../../certs/cert.pem
DEBUG:   main L#161 clientKey /mnt/ramdisk/root/../../../certs/privkey.pem
Connecting...
DEBUG:   iot_tls_connect L#130 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#138   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#144  ok (0 skipped)

DEBUG:   iot_tls_connect L#146   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#159  ok

DEBUG:   iot_tls_connect L#161   . Connecting to apg7f0u84gxki-ats.iot.ap-northeast-1.amazonaws.com/443...
DEBUG:   iot_tls_connect L#180  ok

DEBUG:   iot_tls_connect L#182   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#223 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#226  ok

DEBUG:   iot_tls_connect L#228 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#229   . Performing the SSL/TLS handshake...
DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 2):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 06:6C:9F:CF:99:BF:8C:0A:39:E2:F0:78:8A:43:E6:96:36:5B:CA
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, CN=Amazon Root CA 1
issued  on        : 2015-05-26 00:00:00
expires on        : 2038-01-17 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 06:7F:94:57:85:87:E8:AC:77:DE:B2:53:32:5B:BC:99:8B:56:0D
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
issued  on        : 2015-10-22 00:00:00
expires on        : 2025-10-19 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true, max_pathlen=0
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#49 
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#51 cert. version     : 3
serial number     : 03:B5:C7:CB:A2:25:0D:1C:68:0A:9C:70:97:40:28:C3
issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
subject name      : CN=*.iot.ap-northeast-1.amazonaws.com
issued  on        : 2018-08-02 00:00:00
expires on        : 2019-08-02 12:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : iot.ap-northeast-1.amazonaws.com, *.iot.ap-northeast-1.amazonaws.com
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#54   This certificate has no flags

DEBUG:   iot_tls_connect L#246  ok
    [ Protocol is TLSv1.2 ]
    [ Ciphersuite is TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384 ]

DEBUG:   iot_tls_connect L#248     [ Record expansion is 29 ]

DEBUG:   iot_tls_connect L#253   . Verifying peer X.509 certificate...
DEBUG:   iot_tls_connect L#262  ok

DEBUG:   iot_tls_connect L#272   . Peer certificate information    ...

DEBUG:   iot_tls_connect L#274       cert. version     : 3
      serial number     : 03:B5:C7:CB:A2:25:0D:1C:68:0A:9C:70:97:40:28:C3
      issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
      subject name      : CN=*.iot.ap-northeast-1.amazonaws.com
      issued  on        : 2018-08-02 00:00:00
      expires on        : 2019-08-02 12:00:00
      signed using      : RSA with SHA-256
      RSA key size      : 2048 bits
      basic constraints : CA=false
      subject alt name  : iot.ap-northeast-1.amazonaws.com, *.iot.ap-northeast-1.amazonaws.com
      key usage         : Digital Signature, Key Encipherment
      ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication


ERROR: main L#190 Error(-12) connecting to apg7f0u84gxki-ats.iot.ap-northeast-1.amazonaws.com:443
/mnt/ramdisk/root #

**Comment by gordonwang0** [comment]
Hi @Leesphone,

Please let me know if you need any more help with this.  Closing issue.

**Comment by ronakdudhatra** [comment]
Hi @Leesphone 
Why is the validity of X.509(Peer certificate information) is 1 year ? Is it always valid for year? For real time application will it be affected in runtime? What is the purpose of this validation?
