### ISSUE TITLE
shadow_sample.c: get cert directory from command line argument does not work

### ISSUE THREAD

**Issue by SrikanthKrish** [aws/aws-iot-device-sdk-embedded-C#238]
Directly running the shadow sample and sending the certificate directory via command line argument will not work, move call to **parseInputArgsForconnectParams(argc,argv) before the sprintf's** right above it. 

        getcwd(CurrentWD, sizeof(CurrentWD));
	snprintf(rootCA, PATH_MAX + 1, "%s/%s/%s", CurrentWD, certDirectory, AWS_IOT_ROOT_CA_FILENAME);
	snprintf(clientCRT, PATH_MAX + 1, "%s/%s/%s", CurrentWD, certDirectory, AWS_IOT_CERTIFICATE_FILENAME);
	snprintf(clientKey, PATH_MAX + 1, "%s/%s/%s", CurrentWD, certDirectory, AWS_IOT_PRIVATE_KEY_FILENAME);

	IOT_DEBUG("rootCA %s", rootCA);
	IOT_DEBUG("clientCRT %s", clientCRT);
	IOT_DEBUG("clientKey %s", clientKey);

       parseInputArgsForConnectParams(argc, argv);

**Comment by gordonwang0** [comment]
Hi @SrikanthKrish,

Thanks for bringing this to my attention!  I've created a pull request (#241) to fix it.
