### ISSUE TITLE
mbedtls_ssl_write not returning when network disconnects

### ISSUE THREAD

**Issue by njenwei** [aws/aws-iot-device-sdk-embedded-C#239]
Hi

I've experienced occasions when the network does not disconnect gracefully and the subsequent call to `aws_iot_mqtt_publish` blocks at `mbedtls_ssl_write` on line 293 of network_mbedtls_wrapper.c. This blocks the client state on `CLIENT_STATE_CONNECTED_PUBLISH_IN_PROGRESS`. I am then unable to return from the `aws_iot_mqtt_publish` call until about 1000 seconds later when the disconnect callback is called.

Calling `aws_iot_mqtt_yield` from another thread returns `MQTT_CLIENT_NOT_IDLE_ERROR` and bypassing that point causes the yield to block trying to disconnect, with the state at `CLIENT_STATE_DISCONNECTING`. `aws_iot_mqtt_disconnect` also blocks at `mbedtls_ssl_close_notify` on line 356 of network_mbedtls_wrapper.c.

Have you seen this issue before?

I have tried this with the sdk `v2.2.1` and `v3.0.1`, and mbedtls `v2.7.4` and `v2.13.0`. The device I am working with has a 3g modem, which makes the network connection very unreliable, and can take a while to realise that it has been disconnected from the network.

**Comment by gordonwang0** [comment]
Hello @njenwei,

In your case, I believe mbedTLS is waiting until it times out before calling the disconnect callback.

Can you try modifying the `network_mbedtls_wrapper.c` file and put a call to `mbedtls_net_poll` before the call to `mbedtls_ssl_write`?  Something like the following:
```c
/* Line 292 in network_mbedtls_wrapper.c */
while(!has_timer_expired(timer))
{
    /* Check if it's possible to write without blocking. */
    ret = mbedtls_ssl_poll(&(tlsDataParams->server_fd),
                           MBEDTLS_NET_POLL_WRITE,
                           <a small timeout>);
    if((ret & MBEDTLS_NET_POLL_WRITE) == 0) {
        /* It's not possible to write without blocking.
         * Perhaps the network is disconnected? */
    }

    ret = mbedtls_ssl_write(&(tlsDataParams->ssl), pMsg + written_so_far, len - written_so_far);
    if(ret > 0) {
        break;
    }
    if(ret != MBEDTLS_ERR_SSL_WANT_READ && ret != MBEDTLS_ERR_SSL_WANT_WRITE) {
        IOT_ERROR(" failed\n  ! mbedtls_ssl_write returned -0x%x\n\n", -ret);
        /* All other negative return values indicate connection needs to be reset.
         * Will be caught in ping request so ignored here */
        isErrorFlag = true;
        break;
    }
}
```

The code above should allow you to detect when the network connection can't be written to and handle that accordingly case quicker than waiting for `mbedtls_ssl_write` to time out.  Please let me know if it works for you.

**Comment by njenwei** [comment]
Hi @gordonwang0 

With the `mbedtls_net_poll`, I am able to detect a network timeout within 1.5 seconds of the last message successfully received by aws. It takes 2.2s since the last successful message for `mbedtls_ssl_write` to block in my case.
```
Sending message @ 1540284581.840975  // last message received by aws
Sending message @ 1540284581.904316
Sending message @ 1540284581.967656
... 
Sending message @ 1540284583.168876
Sending message @ 1540284583.232247
Sending message @ 1540284583.295425, mbedtls_net_poll WRITE TIMEOUT // 1.5s since last successful message
Sending message @ 1540284583.360562, mbedtls_net_poll WRITE TIMEOUT
...
Sending message @ 1540284583.946354, mbedtls_net_poll WRITE TIMEOUT
Sending message @ 1540284584.014678, mbedtls_net_poll WRITE TIMEOUT, mbedtls_ssl_write BLOCKS // 2.2s since last successful message
```

I handle the write timeout by escaping the loop.
```c
/* Line 292 in network_mbedtls_wrapper.c */
while(!has_timer_expired(timer)) {

  /* Check if it's possible to write without blocking. */
  ret = mbedtls_net_poll(&(tlsDataParams->server_fd), MBEDTLS_NET_POLL_WRITE, 0);
  if((ret & MBEDTLS_NET_POLL_WRITE) == 0) {
    /* It's not possible to write without blocking.
     * Perhaps the network is disconnected? */
    isErrorFlag = true;
    break;
  }

  ret = mbedtls_ssl_write(&(tlsDataParams->ssl), pMsg + written_so_far, len - written_so_far);
  if(ret > 0) {
    break;
  }
  if(ret != MBEDTLS_ERR_SSL_WANT_READ && ret != MBEDTLS_ERR_SSL_WANT_WRITE) {
    IOT_ERROR(" failed\n  ! mbedtls_ssl_write returned -0x%x\n\n", -ret);
    /* All other negative return values indicate connection needs to be reset.
    * Will be caught in ping request so ignored here */
    isErrorFlag = true;
    break;
  }
}
```

Also, I pushed the write error up the stack, so that it is not overridden when `_ENABLE_THREAD_SUPPORT_` is enabled and so the publish call receives it.
```c
/* Line 272 in aws_iot_mqtt_client_common_internal.c */
#ifdef _ENABLE_THREAD_SUPPORT_
IoT_Error_t threadRc;
#endif

FUNC_ENTRY;

if(NULL == pClient || NULL == pTimer) {
  FUNC_EXIT_RC(NULL_VALUE_ERROR);
}

if(length >= pClient->clientData.writeBufSize) {
  FUNC_EXIT_RC(MQTT_TX_BUFFER_TOO_SHORT_ERROR);
}

#ifdef _ENABLE_THREAD_SUPPORT_
threadRc = aws_iot_mqtt_client_lock_mutex(pClient, &(pClient->clientData.tls_write_mutex));
if(SUCCESS != threadRc) {
  FUNC_EXIT_RC(threadRc);
}
#endif

sentLen = 0;
sent = 0;

while(sent < length && !has_timer_expired(pTimer)) {
  rc = pClient->networkStack.write(&(pClient->networkStack),
           &pClient->clientData.writeBuf[sent],
           (length - sent),
           pTimer,
           &sentLen);
  if(SUCCESS != rc) {
    /* there was an error writing the data */
    break;
  }
  sent += sentLen;
}

#ifdef _ENABLE_THREAD_SUPPORT_
threadRc = aws_iot_mqtt_client_unlock_mutex(pClient, &(pClient->clientData.tls_write_mutex));
if(SUCCESS != threadRc) {
  FUNC_EXIT_RC(threadRc);
}
#endif
```

These two changes seem work for me.

Just to note, this only happens with `QOS0`. `QOS1` messages will throw a `MQTT_REQUEST_TIMEOUT_ERROR` after time `mqttCommandTimeout_ms` as expected.

**Comment by gordonwang0** [comment]
Hi @njenwei,

Thanks for reporting back.  Good to hear that everything worked out.

I will close this issue now.  Please reopen if you have any additional questions.
