### ISSUE TITLE
 example implementations link error

### ISSUE THREAD

**Issue by JacksonLv** [aws/aws-iot-device-sdk-embedded-C#24]
In the  [`Sample porting`](https://github.com/aws/aws-iot-device-sdk-embedded-c/blob/master/PortingGuide.md/) , the link of the [ example implementations](https://github.com/marvell-iot/aws_starter_sdk/tree/master/wmsdk/external/aws_iot/aws_iot_src/protocol/mqtt/aws_iot_embedded_client_wrapper/platform_wmsdk) is wrong

**Comment by gkwicker** [comment]
Hi @JacksonLv, thanks for letting us know about this and for using AWS IoT.  We'll fix it in an upcoming release.
