### ISSUE TITLE
Hardware requirements

### ISSUE THREAD

**Issue by MarceC85** [aws/aws-iot-device-sdk-embedded-C#242]
Hi people, I want to ask you which are hardware minimum requirements.
Is it compatible with Arduino Uno?
I read many examples using wifi, is it possible to develop a solution using gprs, 3g or 4g?

Best regards.

**Comment by ravibhagavandas** [comment]
Hi,
Csdk is designed for resource constrained devices, and as such doesn't have any strict hardware requirements. You can follow the [porting guide ]( https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/PortingGuide.md ) to get more information on how to port to your hardware.

**I read many examples using wifi, is it possible to develop a solution using gprs, 3g or 4g?**
Csdk connects to AWS Iot using a secure TLS connection over TCP/IP protocol stack and as such can be ported to any network which supports this. You can refer to the porting guide more on how to implement the networking functions.

**Comment by gordonwang0** [comment]
Hi @MarceC85,

Please let us know if you need any more help with this.  Closing issue.

**Comment by MarceC85** [comment]
> Hi @MarceC85,
> 
> Please let us know if you need any more help with this. Closing issue.

Hi @gordonwang0 we will try it. It's ok. Regards.
