### ISSUE TITLE
The variable length was changed to size_t. This calculation forgets to remove the type cast.

### ISSUE THREAD

**Issue by joectchan** [aws/aws-iot-device-sdk-embedded-C#243]
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/ebe1a848244da534ebcb3f06c23f56d9db343b6a/src/aws_iot_shadow_json.c#L498

**Comment by gordonwang0** [comment]
Hi @joectchan,

Thanks for bringing this to my attention.  I was just making some changes to that file, so I included this fix in #244

**Comment by gordonwang0** [comment]
That PR was merged, I am closing this issue.  Please let me know if you find anything else.
