### ISSUE TITLE
subscribed topic can't receive callback in some case

### ISSUE THREAD

**Issue by tidyjiang8** [aws/aws-iot-device-sdk-embedded-C#245]
Here are the sequence to reproduce this issue:
- Subscribe two topics, topic_A and topic_B.
- Unsubscribe topic_A.
- Do some thing to make MQTT reconnect, such as turn off network of your device where your program is running on and turn on it again later, or just call `aws_iot_mqtt_disconnect()` first and then `aws_iot_mqtt_attempt_reconnect()` .
- Then, the callback of topic_B can't be called anymore when you publish something to this topic from other client.

The root cause of this issue is that, when you unsubscribe topic_A, aws iot mqtt just set its topic filed in internal array message handler array item to NULL. At the moment, API `_aws_iot_mqtt_get_free_message_handler_index()` will **return 0, not 1, That's the problem**. So, when MQTT is reconnected, it will not resubscribe topic_B.

In order to fix this issue, I meant to move last message handler to the index where unsubscribed topic_A was. But I noticed that there is a comment in `_aws_iot_mqtt_internal_unsubscribe()` saying that: 
```
/* Remove from message handler array */
for(i = 0; i < AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS; ++i) {
	if(pClient->clientData.messageHandlers[i].topicName != NULL &&
	   (strcmp(pClient->clientData.messageHandlers[i].topicName, pTopicFilter) == 0)) {
		pClient->clientData.messageHandlers[i].topicName = NULL;
               ////////////////////////////////COMMENT HERE////////////////////////////////////////
		/* We don't want to break here, in case the same topic is registered
                 * with 2 callbacks. Unlikely scenario */
	}
}
```
I don't know why? I didn't find any side-effect even though the callbacks are registered on one same topic. If I DO move last handler to here, is the any side-effect?

**Comment by gordonwang0** [comment]
Hi @tidyjiang8,

Apologies for the late reply.  I've taken a look and have been able to reproduce this issue.  I'll get back to you once we have a fix.

**Comment by qiutongs** [comment]
Thank you for reporting the issue. We are tracking it internally.
