### ISSUE TITLE
Misleading certificate parse error if certificate has insufficient IOT policy

### ISSUE THREAD

**Issue by LeviDooley** [aws/aws-iot-device-sdk-embedded-C#246]
If a certificate has an IOT policy that doesn't support publishing or subscribing to a particular topic, attempting to publish or subscribe to the topic results in a certificate parse error. More specifically, a `MBEDTLS_ERR_PK_FILE_IO_ERROR` (-0x3e00). 

```
ERROR: iot_tls_connect L#149  failed
  !  mbedtls_x509_crt_parse returned -0x3e00 while parsing device cert
```

This is a very misleading error because it implies that there's something wrong with the certificate file or path. It took me quite awhile to figure out the issue because of this error.

**Comment by gordonwang0** [comment]
Hi @LeviDooley,

I haven't been able to reproduce this... When I use a policy that only allows connect (not subscribe or publish) the mbedTLS error I see is -0x7880 (Peer closed connection).

The log you posted points to an error in `iot_tls_connect`, not subscribe/publish.  Can you check the error from `iot_tls_read` when your policy does not allow subscribe/publish?

**Comment by gordonwang0** [comment]
Hi @LeviDooley,

Please let me know if you have any more questions on this.  Closing issue.
