### ISSUE TITLE
receiving multiple copies of published messages

### ISSUE THREAD

**Issue by dougmiller0** [aws/aws-iot-device-sdk-embedded-C#247]
As far as I can tell, we are publishing only one time to a topic.  We are receiving the message multiple times.  When publishing we are using QOS1.  I had assumed that the client would PUBACK and we would only get one copy of the message to our callback.  However, this doesn't seem to be happening.

Here's a timeline, should that help.  We are using the 3.0.1 release, and only have our platform additions with no modified SDK portions.

14:29:01 - Published message.

On our aws-iot-device-sdk-embedded-C device:
14:29:02 - Received message.
14:29:28 - Received message. (repeat)
14:29:59 - Received message. (repeat)
14:30:47 - Received message. (repeat)
14:32:39 - Received message. (repeat)
14:37:28 - Received message. (repeat)

I'm trying to track down if these are caused by our side or if this is expected using QOS1 publish.

The AWS IoT client (the 'Test' tab on the AWS console) seems to only allow publishing of QOS0 messages to a topic so I'm not fully replicating with my testing of publishes via that channel.

Though if I subscribe to the same topic, with QOS1, using the AWS IoT client (the 'Test' tab on the AWS console) I am never seeing duplicates, even though I still see them with the aws-iot-device-sdk-embedded-C device.

It's almost like the embedded client isn't sending in PUBACKs?

Any ideas on this?

**Comment by gordonwang0** [comment]
Hi @dougmiller0,

Is your program regularly calling `aws_iot_mqtt_yield`?  The embedded C SDK only sends PUBACKs through the `aws_iot_mqtt_yield` function.

**Comment by gordonwang0** [comment]
That probably indicates an error; `yield` should always return `0` (SUCCESS).  Any other return value generally indicates that there's a problem.

`96` doesn't appear to be a valid return code though... The return code from `yield` should be one of [these](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/c11e34a98bea019814e3a21dc2702bb63c08049d/include/aws_iot_error.h#L40).  Can you check again?  Thanks.

**Comment by lt72** [comment]
@gordonwang0: please consider integrating the suggestion.

**Comment by qiutongs** [comment]
Thanks for reporting the issue and providing suggestion. We are tracking it internally.
