### ISSUE TITLE
Not being able to compile samples

### ISSUE THREAD

**Issue by kaanTgun** [aws/aws-iot-device-sdk-embedded-C#256]
I'm trying to compile the sample subscribe_publish_sample file by using make -f Makefile but I'm getting this and it's not working. I'm using cpputest-3.6 , mbedtsl 2.16.0 and I have filled my header file correctly. 
how would I be able to fix this? 
Thanks 

`
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../../../external_libs/mbedTLS
 CC    aes/aescrypt2.c
  CC    aes/crypt_and_hash.c
  CC    hash/hello.c
  CC    hash/generic_sum.c
  CC    pkey/dh_client.c
  CC    pkey/dh_genprime.c
  CC    pkey/dh_server.c
  CC    pkey/ecdh_curve25519.c
  CC    pkey/ecdsa.c

  CC    pkey/gen_key.c
  CC    pkey/key_app.c
  CC    pkey/key_app_writer.c
  CC    pkey/mpi_demo.c
  CC    pkey/pk_decrypt.c
  CC    pkey/pk_encrypt.c
  CC    pkey/pk_sign.c
  CC    pkey/pk_verify.c
  CC    pkey/rsa_genkey.c
  CC    pkey/rsa_decrypt.c
  CC    pkey/rsa_encrypt.c
  CC    pkey/rsa_sign.c
  CC    pkey/rsa_verify.c
  CC    pkey/rsa_sign_pss.c
  CC    pkey/rsa_verify_pss.c
  CC    ssl/dtls_client.c
  CC    ssl/dtls_server.c
  CC    ssl/ssl_client1.c
  CC    ssl/ssl_client2.c
  CC    ssl/ssl_server.c
  CC    ssl/ssl_server2.c
  CC    ssl/ssl_fork_server.c
  CC    ssl/mini_client.c
  CC    ssl/ssl_mail_client.c
  CC    random/gen_entropy.c
  CC    random/gen_random_havege.c
  CC    random/gen_random_ctr_drbg.c
  CC    test/ssl_cert_test.c
  CC    test/benchmark.c
  CC    test/selftest.c
  CC    test/udp_proxy.c
  CC    test/zeroize.c
  CC    util/pem2der.c
  CC    util/strerror.c
  CC    x509/crl_app.c
  CC    x509/cert_req.c
  CC    x509/cert_write.c
  CC    x509/req_app.c
../../../src//aws_iot_shadow_json.c:136:18: warning: passing an object that undergoes default argument promotion to 'va_start' has
      undefined behavior [-Wvarargs]
        va_start(pArgs, count);
                        ^
../../../src//aws_iot_shadow_json.c:128:99: note: parameter of type 'uint8_t' (aka 'unsigned char') is declared here
IoT_Error_t aws_iot_shadow_add_desired(char *pJsonDocument, size_t maxSizeOfJsonDocument, uint8_t count, ...) {
                                                                                                  ^
../../../src//aws_iot_shadow_json.c:206:18: warning: passing an object that undergoes default argument promotion to 'va_start' has
      undefined behavior [-Wvarargs]
        va_start(pArgs, count);
                        ^
../../../src//aws_iot_shadow_json.c:197:100: note: parameter of type 'uint8_t' (aka 'unsigned char') is declared here
IoT_Error_t aws_iot_shadow_add_reported(char *pJsonDocument, size_t maxSizeOfJsonDocument, uint8_t count, ...) {
                                                                                                   ^
2 warnings generated.`

**Comment by lt72** [comment]
@kaanTgun: can you try to change the function signature and its usages to uint32_t rather than
so, from:
```IoT_Error_t aws_iot_shadow_add_desired(char *pJsonDocument, size_t maxSizeOfJsonDocument, uint8_t count, ...)```
to
```IoT_Error_t aws_iot_shadow_add_desired(char *pJsonDocument, size_t maxSizeOfJsonDocument, uint32_t count, ...)```

@yuhui-zheng: Can you please see to fix this according to kaanTgun requirements?

**Comment by kaanTgun** [comment]
@lt72 Yes That worked perfectly 
Thanks a lot!
