### ISSUE TITLE
why doesn't ShadowInitParameters_t contain user provided data member?

### ISSUE THREAD

**Issue by David-Haim** [aws/aws-iot-device-sdk-embedded-C#269]
In my company we're using the C sdk in our C++ application since we've preferred to use the more robust C sdk than the buggish C++ sdk.

we're wrapping the C sdk with an extremely thin C++ wrapper and currently we cannot send any context to the disconnection callback in the device shadow case (and hence, no way of informing your app instance the client is disconnected).

we need this feature :)

**Comment by gordonwang0** [comment]
Hi @David-Haim,

We're currently in the process of releasing v4 beta of this SDK, so it's the right time for feature requests 😄 

I've added a disconnect callback with a user context to v4 beta's network abstraction (#272).  This will allow us to eventually add the same disconnect callback to the Shadow library as well.  Unfortunately, I currently don't have an estimate for when we can complete this.  I'll update this thread once I have more information.

**Comment by gordonwang0** [comment]
Hi @David-Haim,

An MQTT disconnect callback has been implemented in #324.  This callback takes a parameter `void * pCallbackContext`, which allows you to pass a context to the callback function.

I am closing this issue.  Please let me know if you have any further questions.
