### ISSUE TITLE
platform/linux is actually quite generic

### ISSUE THREAD

**Issue by revmischa** [aws/aws-iot-device-sdk-embedded-C#27]
How about renaming it POSIX or something? It works just fine on OSX.

**Comment by chaurah** [comment]
Hi @revmischa,
         I don't know if calling it POSIX would be the best idea. There are a lot of POSIX based systems in use and I hesitate to call this out without having some sort of automated testing for them. We will consider this in the future but for now, I don't think this is a valid issue.

That being said, please do keep providing suggestions. Your thoughts have been very helpful.

Rahul

**Comment by revmischa** [comment]
Okay, may I suggest hooking up Travis-CI then with some basic smoke tests to make sure things compile? You can have it run on ubuntu, debian, centos, OSX, etc.
I will continue developing with this library on OSX. If someone breaks it I'll yell at them. I don't think other POSIX environments are very common besides linux/OSX. 
My point was though calling it "linux" makes people think they need to use this on linux, which is not true. Maybe call it "generic". Or "posix". Or "linux_darwin". I don't know.

**Comment by chaurah** [comment]
We are already working on improvements to automatically test on multiple platforms. I should have been clearer in my original post. I am not saying I disagree with you. It does make more sense to call it POSIX. I just don't want to do it until I am assured that every release that goes out has automated testing for the major linux distributions and OSX. We will definitely revisit this when that is in place.

But don't hesitate to let us know if it breaks on OSX at any point. We will address any bugs that are found in future releases :)

Rahul
