### ISSUE TITLE
Changing definitions in aws_iot_error.h

### ISSUE THREAD

**Issue by xcoder123** [aws/aws-iot-device-sdk-embedded-C#275]
Hi,

Could we change SUCCESS and FAILURE definition in aws_iot_error.h to be less generic.

When implementing AWS in ST micro-controller, we experienced a collision with ST's HAL library. Where SUCCESS is already defined/enumerated. 

It could be as simple as changing definition from SUCCESS to AWS_SUCCESS, and FAILURE to AWS_FAILURE

Kind Regards

**Comment by lt72** [comment]
@xcoder123: thank you for your feature request, we will add it to our roadmap and prioritize accordingly.
As a side note, I'd like to point you to the v4 beta release in the [v4_beta ](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta)branch. If you have any feedback, please let us know. Thank you!

**Comment by gordonwang0** [comment]
Hi @xcoder123,

We have made this change to v4 beta, where names are prefixed with `IOT_`.  However, since this would be a breaking change to v3, we will not make this change to v3.

Please let me know if you have any other concerns.

**Comment by xcoder123** [comment]
Hi @lt72 and @gordonwang0,

That's brilliant, I think we can close this then.
