### ISSUE TITLE
Getting Error : MQTT_CLIENT_NOT_IDLE_ERROR on aws_iot_shadow_get() 

### ISSUE THREAD

**Issue by shubhamkumargupta** [aws/aws-iot-device-sdk-embedded-C#30]
Hi,
I am trying to get shadow for two (could be more) different devices simultaneously by creating two separate threads, its a continuous polling process. 
From main program I have created two threads and each thread have separate session by keeping Client-Id = Device-Id (unique). 
Problem is one of the two thread returns error code : - 30 (MQTT_CLIENT_NOT_IDLE_ERROR) just after aws_iot_shadow_get and other thread gets the shadow successfully. This behavior is quite random between thread.

I wish to ask if this parallel polling of get shadow is possible or not from single Process using multiple Thread and Unique session for each Thread to poll shadow for different devices.

**Comment by johnrotach** [comment]
Hello @shubhamkumargupta,

You should be able to do get requests from multiple threads.  A good example of doing something similar can be found in the [basic connectivity integration test](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/8aa5c18efe9efacb28425beec8ddbb5dfdbd2fcb/tests/integration/src/aws_iot_test_basic_connectivity.c).  In this test if the client receives MQTT_CLIENT_NOT_IDLE_ERROR it waits until the MQTT client is idle and then retries its operation.

John
AWS IoT

**Comment by shubhamkumargupta** [comment]
Hi John,

Thanks for responding so quickly. 
I got the basic connectivity integration test implementation. Its basically waiting in loop until return value is not equal to MQTT_CLIENT_NOT_IDLE_ERROR.
But, still I have a doubt that is at a time only one Client can make a request and after completion of request next Request will be served until then other client's request will be in waiting state. So, there is no as such parallelism in serving multiple requests at a time. Its a Block_wise implementation. Let me know if got it wrong or right.

Shubham

**Comment by johnrotach** [comment]
Hello @shubhamkumargupta,

You are correct, these calls are synchronous.  You can access the client from multiple threads but the operations are synchronous.  Adding an asynchronous API to the embedded C client is in our backlog.

John

**Comment by shubhamkumargupta** [comment]
Hi John,

Thanks for your quick support.
1. One more thing I want to clarify that, when a thread make a **[aws_iot_shadow_connect(AWS_IoT_Client *pClient, ShadowConnectParameters_t *pParams)](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/8aa5c18efe9efacb28425beec8ddbb5dfdbd2fcb/src/aws_iot_shadow.c)** call, internally it will call **[initializeRecords(AWS_IoT_Client *pClient)](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/8aa5c18efe9efacb28425beec8ddbb5dfdbd2fcb/src/aws_iot_shadow_records.c)** with pClient as a parameter. 
2. In initializeRecords(AWS_IoT_Client *pClient) function at line : 291 pMqttClient = pClient is being initialized, where as **[pMqttClient](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/8aa5c18efe9efacb28425beec8ddbb5dfdbd2fcb/src/aws_iot_shadow_records.c)**  is global parameter declared at [line : 57](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/8aa5c18efe9efacb28425beec8ddbb5dfdbd2fcb/src/aws_iot_shadow_records.c). 
3. So while making shadow related request from multiple threads, it is using only one client that is initialized by global parameter pMqttClinet. As a result of this shadow api's are returning random error code.
4.And in normal aws_iot_mqtt_connect() call there is no such pMqttClient  global parameter, so its working fine with mqtt_connect.

Correct me if I am wrong.

Shubham

**Comment by johnrotach** [comment]
Hi @shubhamkumargupta,

In number 3, what error codes are you receiving?

John

**Comment by shubhamkumargupta** [comment]
Hello John,

**In number 3**, Error Codes are quite random mostly received : -4, -11, -24, -27, -47 error code. In some case all request from multiple thread are successful with no error message, but Json Shadow Data was no received. Only one thread got Json Shadow Data, other threads got No Data.

**In number 2**, pMqttClient is common for all the Shadow Connect being a global parameter. Is this correct or not. If yes, are you planning to fix this or this is some design constraint.

Shubham

**Comment by bhadrip** [comment]
Hello Shubham,

Thanks for the detailed debug messages. 
You are correct, current design does not allow multiple shadows. We will fix this in a future release.

Regards
Bhadri

**Comment by chaurah** [comment]
Hi @shubhamkumargupta,
    We now have a C++ SDK that allows Multiple shadows. You can find it [here](https://github.com/aws/aws-iot-device-sdk-cpp). We are working on including this option in the next release of Embedded C SDK as well.

Rahul

**Comment by eugene345** [comment]
Hi Rahul,

Do you plan to include an asynchronous API in the next release of Embedded C SDK? I need to publish messages to different topics using the same MQTT client, but, unfortunately, now not possible to do it asynchronously.

Best regards,
Eugene
