### ISSUE TITLE
Unable to build SDK v4_beta for cross-compiler

### ISSUE THREAD

**Issue by shaahad** [aws/aws-iot-device-sdk-embedded-C#300]
Hi, 

I tried to build the new AWS IoT SDK embedded C V4 beta to try the new design. However, I am getting alot of errors regarding the designated initializers  errors. Not all compilers support this way of initializing structures. 

I am using a gcc cross-compiler for linux.

Thank you

**Comment by lt72** [comment]
Hi @shaahad, we do not support cross-compiling (yet), but rather just compiling and testing on Linux, using GCC. We do require C99 compliant compilers.
I will note your remark as a feature request, but in the meantime it would be useful to know which target you are trying to build for and which compiler you are using.

**Comment by daraghmc** [comment]
I am cross compiling for arm/linux and it works fine, but I also have a problem with designated initializers. My compiler is GCC 4.4.1 (old, I know, but the toolchain will not be updated). While this compiler should be C99 compliant, there are bugs with designated initializers that weren't addressed until GCC 4.6. While designated intiializers are convenient, they aren't indispensable. It would be great if the SDK could avoid using them for greater backwards compatibility.

**Comment by gordonwang0** [comment]
Hi @daraghmc and @shaahad,

Based on the feedback here, we'll remove the usage of the initializers from *library* code.  However, we will still use them in demos and encourage their usage.  You can choose to not use the initializers in your applications if your toolchain doesn't support them and initialize each struct member explicitly.

Note that the initializers are important for forward compatibility.  We may modify the parameter structures, but we'll always update the initializer to give new members "sensible" default values.  If you don't use the initializers and we add struct members, these new members will be uninitialized and may cause crashes.
