### ISSUE TITLE
cmake install command

### ISSUE THREAD

**Issue by shelterz** [aws/aws-iot-device-sdk-embedded-C#309]
CMake install command not found , would it be added in future?
Beacause i want use the sdk as a third party library in my own iot cmake projects.

**Comment by gordonwang0** [comment]
Hi @shelterz,

Thanks for trying out the new SDK!

Yes, we will add an install command in the near future.

**Comment by shelterz** [comment]
That sounds great!

**Comment by rafajpet** [comment]
Hi,
How It looks like with cmake install functionality ?

**Comment by abhidixi11** [comment]
Hello @rafajpet, 
It is not yet implemented, we do have a plan to implement it, but I don't have any official date for you at this time.
Thanks.

**Comment by yourslab** [comment]
Hi @shelterz @rafajpet

The C SDK now supports installation.

Documentation can be found in the [README](https://github.com/aws/aws-iot-device-sdk-embedded-C#installation).
