### ISSUE TITLE
OpenSSL builds for 2.X releases

### ISSUE THREAD

**Issue by srware** [aws/aws-iot-device-sdk-embedded-C#31]
Are there any plans to release OpenSSL builds for newer versions of the SDK for Intel platforms, Raspberry Pi and other Linux platforms? It seems that make files for non-mbed systems are no longer available...

**Comment by chaurah** [comment]
Hi @srware,
At the moment there are no plans to bring OpenSSL back for Embedded C SDK. If you are interested in porting however, you can still find the OpenSSL wrapper in the 1.x branch. You will need to make some changes to match the new Network wrapper and the latest OpenSSL release. We might bring this back in at a future date, but as of now, MbedTLS will be the only reference layer we provide.

I will leave this open for now in case you have further questions. Thank you for using AWS IoT.

Rahul
