### ISSUE TITLE
Understanding MQTT client Identifier SDK V4_beta

### ISSUE THREAD

**Issue by shaahad** [aws/aws-iot-device-sdk-embedded-C#311]
Hi, 

I am using the new SDK V4_Beta and I noticed that with the new SDK unique client identifier need to be added to the connection information to establish MQTT connection and the max character of the identifer is 23. Is there is a reason for the max characters of the ID to be 23 ? Will it be configurable in the future like the old SDK ? 

The older version of the SDK master that option was not compulsory. How did the SDK handle it ?

Thank you,

**Comment by gordonwang0** [comment]
Hi @shaahad,

The 23 character limit comes from the [MQTT 3.1.1 spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc384800404):

> The Server MUST allow ClientIds which are between 1 and 23 UTF-8 encoded bytes in length
> ...
> The Server MAY allow ClientId’s that contain more than 23 encoded bytes.

Note that the 23 character limit in v4 of the SDK is not strictly enforeced -- you will just receive a warning log message if your client identifier is longer.  You may still use client identifiers longer than 23 characters.  SDK v3 (the previous version) did not print any warning logs in this case.

**Comment by shaahad** [comment]
Thank you for the Clarification @gordonwang0
