### ISSUE TITLE
The use of 'extern "C"' in the headers files (SDK V4_beta)

### ISSUE THREAD

**Issue by shaahad** [aws/aws-iot-device-sdk-embedded-C#314]
Hi, 

Could you please add 'extern "C"' in the headers files for V4_beta of the SDK to make them easier to use from C++.The SDK master branch support them. 

ifdef __cplusplus
extern "C" {

endif
...

ifdef __cplusplus
}

endif

Thank you

**Comment by shelterz** [comment]
You can add it in your own projects, otherwise symbols would not found. 
That 's my workaround.

**Comment by gordonwang0** [comment]
We're currently evaluating the effect that `extern "C"` will have on our codebase.  I haven't tested v4 with a C++ compiler at all. 

For now, as a workaround, you may add in your application code:
```c
extern "C" {
#include "iot_mqtt.h"
}
```

**Comment by qiutongs** [comment]
Hi, this is still an ongoing discussion.
In the meantime, can you provide the error message you got during compiling? We want to see what the problem you are trying to solve.
