### ISSUE TITLE
cmake support on the master branch

### ISSUE THREAD

**Issue by shelterz** [aws/aws-iot-device-sdk-embedded-C#334]
I wonder to know whether the master branch will support cmake in future or not?

**Comment by lt72** [comment]
Hi @shelterz, yes it will as soon as beta becomes an official release, by June 2019 or earlier.

**Comment by gordonwang0** [comment]
Hi @shelterz,

To clarify, when v4 Beta is released, it will become the master branch and its CMake build system will move there.

We currently have no plans to add a CMake build system to SDK v3.

**Comment by shelterz** [comment]
@gordonwang0 
Ok, Thanks a lot.
