### ISSUE TITLE
Questions about JITP

### ISSUE THREAD

**Issue by David-Haim** [aws/aws-iot-device-sdk-embedded-C#343]
hello all!
I followed the instructions written here [here](https://aws.amazon.com/blogs/iot/setting-up-just-in-time-provisioning-with-aws-iot-core/) and it works. sort of. 
I have a few questions:

1) I gave my device an indicative name (hardcoded into the config header file) but when I looked at the thing-registry, I saw the thing added as an un-indicative number/ID. is this the expected behaviour? How do I force the thing name to be added as the string I pass to the client object?

2) In my team, we debated whether it's possible to give a specific thing permissions to subscribe and publish to a small set of topics, is it possible? from the look of the API, every thing can publish an subscribe to every topic.

3) If (2) is true, can it be done directly with JITP? the way it works right now is that you attach a policy to your CA cert, and this policy is attached automatically to every new thing that uses certs signed by that CA. again, assuming (2) is true, can it be done directly with JITP? if not, can the permissions be changed programmatically (server side, of course) and retroactively?

4) We also discovered [AWS CVM](https://github.com/awslabs/aws-iot-certificate-vending-machine), how does this feature work with JITP and is CVM a replacement for JITP?

**Comment by alexa-noxon** [comment]
Hi David,

1. Your thing name can be derived from the field indicated by the template you set up.  
In the example template on this link (https://docs.aws.amazon.com/iot/latest/developerguide/jit-provisioning.html), the ThingName will be generated from the CommonName field in the client certificate.  One way to sync the thing name between AWS and your device is to set up your template to generate the thing name from a certificate field and then parse the certificate on your device.  Would this work with your use case?

1. Yes it is possible to limit the topics your things can subscribe and publish to.  This can be done by modifying the policy that is attached to the certificate attached to the thing.

1. Yes this can be done via JITP by modifying the Policy contained in the JITP template.  The policy in the template determines what policy is attached to certificates of newly created things.

1. JITP is used when you have registered a CA certificate with AWS and are able to provision your device with a certificate issued by that CA.   It gives you the option of generating your private key on the device.  It looks like CVM is used when you are unable to register a CA and provision devices with certificates issued by the registered CA.

**Comment by David-Haim** [comment]
Thanks for the detailed reply!

Maybe I'm asking XY questions, let me explain out use cases, and then let's figure out if we need to use JITP or a different mechanism

1) our product is mass produced and needs to connect to AWS IOT. since SSL certificates expire at some point, it's up to the device itself to create the certificates and our servers will register them.
2) in order to keep our API consistent, we want the newly-created thing name to be our UUID we anyway give our devices.
3) every device can only pub/sub to a topic in the format /<thing name>/<inner topic>

The way I see it, JITP is a bit problematic for our scenario because the template is associated with a CA certificate and not a private/public key pair, but we look for device-specific information that doesn't exist when you register the CA cert with it template. 

should we try working with JITP as is, or use a different mechanism or maybe a combo of the two?

again, thanks for the help!

**Comment by alexa-noxon** [comment]
Hi David,

Using JITP doesn't prevent you from using your UUID as your Thing Name. If certificate signing requests are generated with the UUID used in one of the certificate fields that can be referenced by the provisioning template (ex: CommonName), then the UUID contained in the certificate can be used to name your Thing in JITP.

Using JITP, your flow would be something like
(Before programming any devices)
1. Generate CA public-private key pair and certificate
1. Register CA with AWS
1. Set up your JITP flow & template (making sure to use a policy that specifies the pub/sub topic restrictions you want)

(Later, for each device)
1. Generate the device public-private key pair (on device or with other trusted, crytographically approved source)
1. Export device UUID and device public key into a certificate signing request for the device certificate.  Specifiy the "Common Name" field to be the the device certificate UUID.
1. Present device certificate signing request to be signed by CA 
1. Import the just signed certificate back into the device 
1. Connect device using certificate, triggering JITP mechanism

This allows you to use the JITP flow to create your things without knowing what the UUIDs are at the time of CA registration, and also provide these things policies that allow them to subscribe and publish to certain topics.

Would this work for you?
Alexa


P.S. Something to keep in mind when picking your thing name is that the maximum thing name length is 128 characters, so as long as your UUID is expressed as 128 characters or less this should be fine. If you are using the Shadow library in SDKv3, please also keep in mind that client tokens are by default generated from your thing name (https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_shadow_json.c#L65), and client tokens have a maximum length of 64 bytes.  (You can modify the client token generation to get around this issue. Also note that this is not a problem in SDKv4)

**Comment by alexa-noxon** [comment]
Hi David,

Please let me know if you need any more help with this.  In the meantime, I will close the issue.
