### ISSUE TITLE
My device can not receive the server answer, who can tell me why?

### ISSUE THREAD

**Issue by YuqingGuoo** [aws/aws-iot-device-sdk-embedded-C#362]
My device has already connected to the server ,and sent the Subscribing topic to the server, but the server publish a message that the device can not receive the message.
follow the log:
DEBUG:   main L#159 rootCA /home/exdroid/aws-iot-sdk-c-master/samples/linux/subscribe_publish_sample/../../../certs/rootCA.crt
DEBUG:   main L#160 clientCRT /home/exdroid/aws-iot-sdk-c-master/samples/linux/subscribe_publish_sample/../../../certs/cert.pem
DEBUG:   main L#161 clientKey /home/exdroid/aws-iot-sdk-c-master/samples/linux/subscribe_publish_sample/../../../certs/privkey.pem
FUNC_ENTRY:   aws_iot_mqtt_init L#160 
FUNC_ENTRY:   aws_iot_mqtt_set_connect_params L#130 
FUNC_EXIT:   aws_iot_mqtt_set_connect_params L#152 Return Code : 0 
FUNC_EXIT:   aws_iot_mqtt_init L#223 Return Code : 0 
Connecting...
**** RUNNING ON LITTLE-ENDIAN SYSTEM ****
FUNC_ENTRY:   aws_iot_mqtt_connect L#462 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#54 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#59 Return Code : 1 
FUNC_ENTRY:   aws_iot_mqtt_set_client_state L#101 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#54 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#59 Return Code : 1 
FUNC_EXIT:   aws_iot_mqtt_set_client_state L#126 Return Code : 0 
FUNC_ENTRY:   _aws_iot_mqtt_internal_connect L#385 
FUNC_ENTRY:   aws_iot_mqtt_set_connect_params L#130 
FUNC_EXIT:   aws_iot_mqtt_set_connect_params L#152 Return Code : 0 
DEBUG:   iot_tls_connect L#120 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#128   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#134  ok (0 skipped)

DEBUG:   iot_tls_connect L#136   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#149  ok

DEBUG:   iot_tls_connect L#151   . Connecting to atg3vndjqb7dp-ats.iot.ap-southeast-1.amazonaws.com/8883...
DEBUG:   iot_tls_connect L#170  ok

DEBUG:   iot_tls_connect L#172   . Setting up the SSL/TLS structure...
DEBUG:   iot_tls_connect L#204 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#207  ok

DEBUG:   iot_tls_connect L#209 

SSL state connect : 0 
DEBUG:   iot_tls_connect L#210   . Performing the SSL/TLS handshake...
DEBUG:   _iot_tls_verify_cert L#41 
Verify requested for (Depth 2):

DEBUG:   _iot_tls_verify_cert L#43 cert. version     : 3
serial number     : 06:6C:9F:CF:99:BF:8C:0A:39:E2:F0:78:8A:43:E6:96:36:5B:CA
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, CN=Amazon Root CA 1
issued  on        : 2015-05-26 00:00:00
expires on        : 2038-01-17 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#46   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#41 
Verify requested for (Depth 1):

DEBUG:   _iot_tls_verify_cert L#43 cert. version     : 3
serial number     : 06:7F:94:57:85:87:E8:AC:77:DE:B2:53:32:5B:BC:99:8B:56:0D
issuer name       : C=US, O=Amazon, CN=Amazon Root CA 1
subject name      : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
issued  on        : 2015-10-22 00:00:00
expires on        : 2025-10-19 00:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=true, max_pathlen=0
key usage         : Digital Signature, Key Cert Sign, CRL Sign

DEBUG:   _iot_tls_verify_cert L#46   This certificate has no flags

DEBUG:   _iot_tls_verify_cert L#41 
Verify requested for (Depth 0):

DEBUG:   _iot_tls_verify_cert L#43 cert. version     : 3
serial number     : 0C:D2:AE:1B:AC:8B:71:6C:53:96:10:04:0F:8A:F5:4E
issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
subject name      : CN=*.iot.ap-southeast-1.amazonaws.com
issued  on        : 2018-08-02 00:00:00
expires on        : 2019-08-02 12:00:00
signed using      : RSA with SHA-256
RSA key size      : 2048 bits
basic constraints : CA=false
subject alt name  : iot.ap-southeast-1.amazonaws.com, *.iot.ap-southeast-1.amazonaws.com
key usage         : Digital Signature, Key Encipherment
ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

DEBUG:   _iot_tls_verify_cert L#46   This certificate has no flags

DEBUG:   iot_tls_connect L#227  ok
    [ Protocol is TLSv1.2 ]
    [ Ciphersuite is TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256 ]

DEBUG:   iot_tls_connect L#229     [ Record expansion is 29 ]

DEBUG:   iot_tls_connect L#234   . Verifying peer X.509 certificate...
DEBUG:   iot_tls_connect L#243  ok

DEBUG:   iot_tls_connect L#253   . Peer certificate information    ...

DEBUG:   iot_tls_connect L#255       cert. version     : 3
      serial number     : 0C:D2:AE:1B:AC:8B:71:6C:53:96:10:04:0F:8A:F5:4E
      issuer name       : C=US, O=Amazon, OU=Server CA 1B, CN=Amazon
      subject name      : CN=*.iot.ap-southeast-1.amazonaws.com
      issued  on        : 2018-08-02 00:00:00
      expires on        : 2019-08-02 12:00:00
      signed using      : RSA with SHA-256
      RSA key size      : 2048 bits
      basic constraints : CA=false
      subject alt name  : iot.ap-southeast-1.amazonaws.com, *.iot.ap-southeast-1.amazonaws.com
      key usage         : Digital Signature, Key Encipherment
      ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication

FUNC_ENTRY:   _aws_iot_mqtt_serialize_connect L#160 
FUNC_ENTRY:   _aws_iot_get_connect_packet_length L#123 
FUNC_EXIT:   _aws_iot_get_connect_packet_length L#140 Return Code : 25 
FUNC_ENTRY:   aws_iot_mqtt_internal_init_header L#189 
FUNC_EXIT:   aws_iot_mqtt_internal_init_header L#264 Return Code : 0 
FUNC_ENTRY:   aws_iot_mqtt_internal_write_len_to_buffer L#60 
FUNC_EXIT:   aws_iot_mqtt_internal_write_len_to_buffer L#71 Return Code : 1 
FUNC_EXIT:   _aws_iot_mqtt_serialize_connect L#239 Return Code : 0 
FUNC_ENTRY:   aws_iot_mqtt_internal_send_packet L#272 
FUNC_EXIT:   aws_iot_mqtt_internal_send_packet L#312 Return Code : 0 
FUNC_ENTRY:   aws_iot_mqtt_internal_wait_for_read L#619 
FUNC_ENTRY:   _aws_iot_mqtt_internal_decode_packet_remaining_len L#324 
FUNC_EXIT:   _aws_iot_mqtt_internal_decode_packet_remaining_len L#345 Return Code : 0 
FUNC_ENTRY:   aws_iot_mqtt_internal_write_len_to_buffer L#60 
FUNC_EXIT:   aws_iot_mqtt_internal_write_len_to_buffer L#71 Return Code : 1 
FUNC_EXIT:   _aws_iot_mqtt_internal_read_packet L#417 Return Code : 0 
FUNC_EXIT:   aws_iot_mqtt_internal_wait_for_read L#639 Return Code : 0 
FUNC_ENTRY:   _aws_iot_mqtt_deserialize_connack L#259 
FUNC_ENTRY:   aws_iot_mqtt_internal_decode_remaining_length_from_buffer L#84 
FUNC_EXIT:   aws_iot_mqtt_internal_decode_remaining_length_from_buffer L#103 Return Code : 0 
FUNC_EXIT:   _aws_iot_mqtt_deserialize_connack L#322 Return Code : 0 
FUNC_EXIT:   _aws_iot_mqtt_internal_connect L#437 Return Code : 0 
FUNC_ENTRY:   aws_iot_mqtt_set_client_state L#101 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#54 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#59 Return Code : 2 
FUNC_EXIT:   aws_iot_mqtt_set_client_state L#126 Return Code : 0 
FUNC_EXIT:   aws_iot_mqtt_connect L#488 Return Code : 0 
FUNC_ENTRY:   aws_iot_mqtt_autoreconnect_set_status L#279 
FUNC_EXIT:   aws_iot_mqtt_autoreconnect_set_status L#284 Return Code : 0 
Subscribing...
FUNC_ENTRY:   aws_iot_mqtt_subscribe L#293 
FUNC_ENTRY:   aws_iot_mqtt_is_client_connected L#234 
FUNC_EXIT:   aws_iot_mqtt_is_client_connected L#265 Return Code : 1 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#54 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#59 Return Code : 3 
FUNC_ENTRY:   aws_iot_mqtt_set_client_state L#101 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#54 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#59 Return Code : 3 
FUNC_EXIT:   aws_iot_mqtt_set_client_state L#126 Return Code : 0 
FUNC_ENTRY:   _aws_iot_mqtt_internal_subscribe L#213 
FUNC_ENTRY:   _aws_iot_mqtt_serialize_subscribe L#67 
FUNC_ENTRY:   aws_iot_mqtt_internal_init_header L#189 
FUNC_EXIT:   aws_iot_mqtt_internal_init_header L#264 Return Code : 0 
FUNC_ENTRY:   aws_iot_mqtt_internal_write_len_to_buffer L#60 
FUNC_EXIT:   aws_iot_mqtt_internal_write_len_to_buffer L#71 Return Code : 1 
FUNC_EXIT:   _aws_iot_mqtt_serialize_subscribe L#102 Return Code : 0 
FUNC_ENTRY:   _aws_iot_mqtt_get_free_message_handler_index L#176 
FUNC_EXIT:   _aws_iot_mqtt_get_free_message_handler_index L#184 Return Code : 0 
FUNC_ENTRY:   aws_iot_mqtt_internal_send_packet L#272 
FUNC_EXIT:   aws_iot_mqtt_internal_send_packet L#312 Return Code : 0 
FUNC_ENTRY:   aws_iot_mqtt_internal_wait_for_read L#619 
FUNC_EXIT:   aws_iot_mqtt_internal_wait_for_read L#639 Return Code : -28 
FUNC_EXIT:   _aws_iot_mqtt_internal_subscribe L#242 Return Code : -28 
FUNC_ENTRY:   aws_iot_mqtt_set_client_state L#101 
FUNC_ENTRY:   aws_iot_mqtt_get_client_state L#54 
FUNC_EXIT:   aws_iot_mqtt_get_client_state L#59 Return Code : 6 
FUNC_EXIT:   aws_iot_mqtt_set_client_state L#126 Return Code : 0 
FUNC_EXIT:   aws_iot_mqtt_subscribe L#321 Return Code : -28 
ERROR: main L#207 Error subscribing : -28

**Comment by abhidixi11** [comment]
Hello @YuqingGuoo ,
Based on the logs, subscribe to the topic is failing, that's why you are not receiving any messages.  The device sends the subscribe and then waits for subscribe ack. It times out in waiting for subscribe ack. (code -28 is timeout)
`FUNC_ENTRY: aws_iot_mqtt_internal_wait_for_read L#619
 FUNC_EXIT: aws_iot_mqtt_internal_wait_for_read L#639 Return Code : -28`
Have you checked you subscribe parameters like topic name? 
Have you checked on AWS console to see if the connection was successful ?
Thanks.

**Comment by yuhui-zheng** [comment]
Hi @YuqingGuoo, 

I'm closing this thread, since this thread has been inactive for 10 days. I'm assuming things are working on your end now? If this is not the case, please reach out again.
