### ISSUE TITLE
Suggestion for improvement: Namespace prefix for enums

### ISSUE THREAD

**Issue by tim-nordell-nimbelink** [aws/aws-iot-device-sdk-embedded-C#39]
Currently the AWS IOT library defines some fairly generic enumerations, such as "SUCCESS", and "FAILURE".  It'd be nice if these enums were prefixed with something such as AWS_IOT so that they become AWS_IOT_SUCCESS, or AWS_IOT_FAILURE.

(Unfortunately some of the STM microcontroller vendor code for supporting their hardware also defines SUCCESS which is why I've hit this when trying to invoke both the STM microcontroller specific code and the AWS IOT specific code from the same function.)

**Comment by chaurah** [comment]
Hi Tim,
Thank you for pointing this out. I will include this as a change to be made for the next release. Please let us know if you have any further issues.

Rahul

**Comment by eugene345** [comment]
Hi @gordonwang0 ,

Please, re-open the issue. This feature is still important.

**Comment by oscarh** [comment]
Hi,

What's the status on this? The comment from 2016 claims:
> I will include this as a change to be made for the next release.

**Comment by lt72** [comment]
HI Oscar, we are still working on this feature, since we decided to attack this issue and others as well. I apologize for the long wait, please wait a bit longer.

**Comment by gordonwang0** [comment]
Hello everyone,

We have implemented this in version 4, currently available as a beta version on [this branch](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/README.md).  Please give it a try if you have time.

Please let me know if you have any questions.
