### ISSUE TITLE
Callback for receiving incoming publish messages from server to client (SDK v4_Beta)

### ISSUE THREAD

**Issue by shaahad** [aws/aws-iot-device-sdk-embedded-C#392]
Hi, 

I am trying to receive incoming messages from server and the only way I am receiving them is through the subscription callback, which works and I get the message from server.However, through the same callback I get the publish messages from client to server, Is this the correct behavior ? or is there a setting or a configuration that I can do to enable the callback to only receive the incoming messages from server ?

Regards, 
Shaahad Shaamile

**Comment by gordonwang0** [comment]
Hi @shaahad,

This is expected; if you have a subscription callback set for a topic, then all messages on that topic will be received.

**Comment by shaahad** [comment]
Thank you @gordonwang0  for the clarification
