### ISSUE TITLE
CMake Error Failed

### ISSUE THREAD

**Issue by agilesai1294** [aws/aws-iot-device-sdk-embedded-C#399]
CMake Error at third_party/tinycbor/CMakeLists.txt:2 (add_library):
  Cannot find source file:

    tinycbor/src/cborencoder.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: tinycbor
CMake Error: Cannot determine link language for target "tinycbor".

**Comment by gordonwang0** [comment]
Hi @agilesai1294,

TinyCBOR was recently submoduled into the third_party directory.  You'll have to clone the submodule.
```
git submodule init
git submodule update
```
(I'll modify the build system to automatically clone it at some point.)

**Comment by gordonwang0** [comment]
Hi @agilesai1294,

Please let me know if you need any more help with this.  Closing issue.
