### ISSUE TITLE
Loop Error -11

### ISSUE THREAD

**Issue by boneyt92** [aws/aws-iot-device-sdk-embedded-C#40]
I tried to run the sample shadow update program given with the sdk. After successfully executing for some time, it exists the loop throwing the error, "Error Occured in the Loop -11. and the program crashes. Please help me to solve the program and help to find the root cause of the error.

**Comment by johnrotach** [comment]
Hello @boneyt92,

Can you post any debug messages you received before the error message?  This might help us track down what is happening.

John

**Comment by boneyt92** [comment]
The flow is like this..
After shadow update message, Data Accepted Message will come.. this happens
sometimes and after sometime may be after around 60 messages published,
Loop exists popping the error message. Main #line number, Loop exists -11.
This is the error message.

**Comment by johnrotach** [comment]
Hi @boneyt92,

We are investigating an issue with timeouts in TLS reads in the SDK.  Any additional information you could provide would help us out.  Are you running this on a PC/laptop or device?  WiFi?  Is the shadow sample modified from the example provided?  Is the error consistently reproducible?

Thank you for reporting this issue.

John

**Comment by chaurah** [comment]
Closing this since there has been no response for a while.
