### ISSUE TITLE
varargs

### ISSUE THREAD

**Issue by mindcruzer** [aws/aws-iot-device-sdk-embedded-C#43]
What's the reason `aws_iot_shadow_add_reported()` and `aws_iot_shadow_add_desired()` were implemented to take varargs of `jsonStruct_t` instead of simply passing an array? On the device I'm developing it's possible that only a subset of inputs are configured any given time, and varargs makes it difficult to only report a subset of possible keys in a single message. For example, a customer might buy a device that has 15 inputs max, but say they only have 3 configured. I would like to only report the 3 rather than all 15 in order to potentially save on message size charges. As it is currently, I'd have to select between all 15 variations of the function call, or always report the state of all 15 inputs. Neither of these is too appealing.

Is there another way to do this with the SDK that I'm not seeing?

**Comment by chaurah** [comment]
Hi @mindcruzer,
       Can you please clarify if I am understanding the question correctly here. You want to be able to modify only certain values of the shadow at a time and not all of them. Is that correct? If that is the case, you are correct, you will have to choose between the different variations of the function call depending on what you are doing.

I do think using an Array would have been a better API now that you have pointed this out. I will discuss internally with the team and see if we can add APIs for that with the next release. 

Please let me know if you have any further questions. Thank you for using AWS IoT.

Rahul

**Comment by mindcruzer** [comment]
Hi Rahul, 

That's correct. I essentially want to be able to do partial updates of the shadow. 

Thanks

**Comment by chaurah** [comment]
Hi @mindcruzer,
        Unfortunately, you are correct that this is the only way you can do partial updates at the moment. I will update this post again when we have a release that provides more options to allow partial updates.

Please let me know if you have any further questions.

Rahul

**Comment by rodamn** [comment]
I agree with mindcruzer. Using varargs here seems like a poor decision versus going with a pointer (array) and size. Varargs are useful when the type of the objects may vary and the client may choose to send a combination 0..n different objects, however this function accepts 0..n `jsonStruct_t`'s. The better route from an SDK-client standpoint would be `int struct_count; const jsonStruct_t *json` for example.

The real difference from a SDK client (our) point of view is that params for varargs are set at compile time, while we need to able to choose which params are passed at run-time, which the pointer-count arguments achieves.

Thank you.

**Comment by chaurah** [comment]
@rodamn,
      Thank you for letting us know. It definitely makes sense to have APIs which can take an Array and size as input. I have already added this to our list of tasks for the next release. Please do let us know if you have any further thoughts on how we can improve the design of the APIs.

Rahul
