### ISSUE TITLE
Create Certificate from CSR

### ISSUE THREAD

**Issue by agilesai1294** [aws/aws-iot-device-sdk-embedded-C#434]
How do i register a certificate on AWS IoT from csr using AWS IoT Embedded C SDK?

**Comment by gordonwang0** [comment]
Hi @agilesai1294,

This SDK is the *Device* SDK, which does not support registering a private CA certificate.

You will need to use the AWS console, AWS CLI, or an AWS (not *Device*) SDK to do this.  There is no AWS SDK for C, so you may consider the [AWS SDK for C++](https://github.com/aws/aws-sdk-cpp) instead.

**Comment by gordonwang0** [comment]
Hi @agilesai1294,

Please let me know if you need any more help with this.  Closing issue.
