### ISSUE TITLE
WSS support needed. 

### ISSUE THREAD

**Issue by Marc-Graham** [aws/aws-iot-device-sdk-embedded-C#44]
Hi,

We are currently using aws iot in our development for an upcoming project. We rolled our own WSS support for the paho lib. 

We would like to take advantage shadows, so using the AWS SDK would be great.

**Comment by liuszeng** [comment]
Hi @Marc-Graham ,

Thank you very much for your interest in AWS IoT Embedded C SDK!

We are actively working on the WebSocket support for AWS IoT Embedded C SDK. Please stay tuned for our future releases.

Thanks,
Liusu

**Comment by chaurah** [comment]
Hi @Marc-Graham,
We now have a C++ SDK that WebSocket connections. You can find it [here](https://github.com/aws/aws-iot-device-sdk-cpp). Apologies for the delay in addressing this for Embedded C. We are working on including support for this in the next release.

Rahul

**Comment by hedeshianaws** [comment]
AWS IoT C++ SDK provides WebSocket support. At this time, we have no plans to introduce WSS support into the C SDK.
