### ISSUE TITLE
Make certificate and private key pointers device based configurable struct 

### ISSUE THREAD

**Issue by nikitanerkar** [aws/aws-iot-device-sdk-embedded-C#45]
Hi,

Currently, the network_interface.h consists of TLSConnectParams struct which is used to hold TLS specific information. 
The certificate and private key pointers are char pointers to hold certificate file path. But for embedded devices like mw300, it will be convenient to keep the pointer type device specific for following reasons,
- For not all devices, stored certificates and private key can be accessed using file path 
- It is convenient to store additional information like certificate type (pem or compressed form der) with the certificate and certificate size

Could you please make the necessary changes in the next release.

**Comment by chaurah** [comment]
Hi @nikitanerkar,
     We have plans for the Network type to be initialized separately from the Client instance itself from the next release onwards. That way, developers are free to initialize the Network instance with whatever method they choose. The SDK will simply call connect on a pre-initialized Network instance. I think this should address the issue. If you have any additional thoughts on how we can make this easier to work with, please do let me know. Thank you for using AWS IoT.

Rahul

**Comment by nikitanerkar** [comment]
Oh great. Looking forward to it.

**Comment by tim-nordell-nimbelink** [comment]
+1.  Looking forward to this as well.

**Comment by chaurah** [comment]
Hi @nikitanerkar,
We now have a C++ SDK that allows you to initialize and configure the Network Connection I mentioned above. You can find it [here](https://github.com/aws/aws-iot-device-sdk-cpp). We are still working on including this feature in the Embedded C SDK. I will update this thread when the next release is out.

Rahul

**Comment by vareddy** [comment]
This issue is duplicated by #61 so I'm closing this issue. Please let us know if you have any more questions.
Thanks!
Varun
