### ISSUE TITLE
Questions about QoS1

### ISSUE THREAD

**Issue by nwerl** [aws/aws-iot-device-sdk-embedded-C#457]
Hi.
I have some questions about QoS1.

I reconnected after the connection was disconnected but didn't receive any message using QoS 1.
Are messages that do not receive Ack from QoS 1 republish when reconnected?
Is it necessary to implement?

thank you.

**Comment by gordonwang0** [comment]
Hello,

Unacknowledged messages published at QoS 1 will only be transmitted to a reconnected client if you are using [persistent sessions](https://docs.aws.amazon.com/iot/latest/developerguide/mqtt-persistent-sessions.html).  By default, the MQTT clients in this SDK use clean sessions, so you will not receive unacknowledged QoS 1 messages on reconnection.

To connect using a persistent session, you should modify the flags sent with MQTT connect.
In version 3, the flag to set is [IoT_Client_Connect_Params.isCleanSession](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/64ab0465ec91646b3c369f574a5c97b05f595c59/include/aws_iot_mqtt_client.h#L137).
In version 4 beta, the flag to set is [IotMqttConnectInfo_t.cleanSession](https://docs.aws.amazon.com/freertos/latest/lib-ref/html3/mqtt/structIotMqttConnectInfo__t.html#a7c1ee639c15085caa74f16aacf5d6c8c).

When using a persistent session, you will receive unacknowledged QoS 1 messages when reconnecting with the same MQTT client identifier.  Note that per AWS Service Limits, AWS IoT may delete persistent sessions if they are unused for more than 1 hour.

**Comment by nwerl** [comment]
Thanks for answering @gordonwang0 

I have one more question.

I know publishing clients will republish the same message when they do not receive acknowledge, but I wonder if this is implemented.

thanks.

**Comment by gordonwang0** [comment]
Hi @nwerl,

Retransmission of QoS 1 messages is implemented in Version 4 Beta, but not in Version 3.

Version 4's retransmission mechanism is documented [here](https://docs.aws.amazon.com/freertos/latest/lib-ref/html3/mqtt/structIotMqttPublishInfo__t.html#details).

**Comment by nwerl** [comment]
I really apperciate @gordonwang0. thanks.

**Comment by zhanglongqi** [comment]
> Hi @nwerl,
> 
> Retransmission of QoS 1 messages is implemented in Version 4 Beta, but not in Version 3.
> 
> Version 4's retransmission mechanism is documented [here](https://docs.aws.amazon.com/freertos/latest/lib-ref/html3/mqtt/structIotMqttPublishInfo__t.html#details).

the link is not working anymore. Could you update the link? thanks.

**Comment by zhanglongqi** [comment]
> Hi @nwerl,
> 
> Retransmission of QoS 1 messages is implemented in Version 4 Beta, but not in Version 3.
> 
> Version 4's retransmission mechanism is documented [here](https://docs.aws.amazon.com/freertos/latest/lib-ref/html3/mqtt/structIotMqttPublishInfo__t.html#details).

https://docs.aws.amazon.com/zh_cn/freertos/latest/lib-ref/c-sdk/mqtt/structIotMqttPublishInfo__t.html
is this the one?

**Comment by gordonwang0** [comment]
> https://docs.aws.amazon.com/zh_cn/freertos/latest/lib-ref/c-sdk/mqtt/structIotMqttPublishInfo__t.html

Correct, this is the new documentation link.
