### ISSUE TITLE
Server Certificate Verification failed

### ISSUE THREAD

**Issue by geekalgo** [aws/aws-iot-device-sdk-embedded-C#46]
HI,
I have created certificate in aws and downloaded the corresponding  certificate.I have updated the information in the aws_iot_config.h file also.but i am keep on getting ssl hand shake error(9). refer below logs
Server Certificate Verification failed error number is 9
Error(-3) connecting to ardd8p5btb49v.iot.us-west-2.amazonaws.com:8883

**Comment by liuszeng** [comment]
Hi @geekalgo ,

Thank you very much for using AWS IoT Embedded C SDK!

Have you attached a policy to the certificate that regulates the permission? In order to have the SDK connected to AWS IoT, you need to grant certain permissions to that identity (certificate). Please check out the following documentation link for detailed steps:
Create a policy:
http://docs.aws.amazon.com/iot/latest/developerguide/create-iot-policy.html
Attach a policy to the certificate:
http://docs.aws.amazon.com/iot/latest/developerguide/attach-policy-to-certificate.html

Thanks,
Liusu

**Comment by geekalgo** [comment]
Hi liuszeng,
Thank you for the replay.
I have created and attached the policy still i am facing same probllem.

Thanks

**Comment by geekalgo** [comment]
Hi liusezeng,
Thanks For the update.
Failure in the ConnectOrTimeoutOrExitOnError() function.verify is not related to any system time right?

**Comment by geekalgo** [comment]
I am Attaching Code below with prints enabled.
`IoT_Error_t ConnectOrTimeoutOrExitOnError(SSL *pSSL, int timeout_ms){

	enum{
		SSL_CONNECTED = 1,
		SELECT_TIMEOUT = 0,
		SELECT_ERROR = -1
	};

	IoT_Error_t ret_val = NONE_ERROR;
	int rc = 0;
	fd_set readFds;
	fd_set writeFds;
	struct timeval timeout = { timeout_ms / 1000, (timeout_ms % 1000) * 1000 };
	int errorCode = 0;
	int select_retCode = SELECT_TIMEOUT;

	do{
		rc = SSL_connect(pSSL);
		printf("SSL_connect = rc %d \n",rc);
		if(SSL_CONNECTED == rc){
			ret_val = NONE_ERROR;
			break;
		}

		errorCode = SSL_get_error(pSSL, rc);
		printf("errorCode = %d \n",errorCode);
		if(errorCode == SSL_ERROR_WANT_READ){
			printf("errorCode == SSL_ERROR_WANT_READ\n");
			FD_ZERO(&readFds);
			FD_SET(server_TCPSocket, &readFds);
			select_retCode = select(server_TCPSocket + 1, (void *) &readFds, NULL, NULL, &timeout);
			if (SELECT_TIMEOUT == select_retCode) {
				printf(" SSL Connect time out while waiting for read \n");
				ret_val = SSL_CONNECT_TIMEOUT_ERROR;
			} else if (SELECT_ERROR == select_retCode) {
			    printf(" SSL Connect Select error for read %d \n", select_retCode);
				ret_val = SSL_CONNECT_ERROR;
			}
		}

		else if(errorCode == SSL_ERROR_WANT_WRITE){
			printf("errorCode == SSL_ERROR_WANT_WRITE \n");
			FD_ZERO(&writeFds);
			FD_SET(server_TCPSocket, &writeFds);
			select_retCode = select(server_TCPSocket + 1, NULL, (void *) &writeFds, NULL, &timeout);
			if (SELECT_TIMEOUT == select_retCode) {
				printf(" SSL Connect time out while waiting for write \n");
				ret_val = SSL_CONNECT_TIMEOUT_ERROR;
			} else if (SELECT_ERROR == select_retCode) {
				printf(" SSL Connect Select error for write %d \n", select_retCode);
				ret_val = SSL_CONNECT_ERROR;
			}
		}

		else{
			printf("ret_val = SSL_CONNECT_ERROR  \n");
			ret_val = SSL_CONNECT_ERROR;
		}

	}while(SSL_CONNECT_ERROR != ret_val && SSL_CONNECT_TIMEOUT_ERROR != ret_val);

	return ret_val;
}

calling function  looks like below

ret_val = ConnectOrTimeoutOrExitOnError(pSSLHandle, params.timeout_ms);
long ret1 = SSL_get_verify_result(pSSLHandle);
if(X509_V_OK != ret1){
	printf(" Server Certificate Verification failed %ld retval = %d\n",ret1,ret_val);
	ret_val = SSL_CONNECT_ERROR;
	} 
`

I am Attaching Logs below

SSL_connect = rc -1 
errorCode = 2 
errorCode == SSL_ERROR_WANT_READ
SSL_connect = rc -1 
errorCode = 2 
errorCode == SSL_ERROR_WANT_READ
SSL_connect = rc -1 
errorCode = 2 
errorCode == SSL_ERROR_WANT_READ
SSL_connect = rc -1 
errorCode = 1 
ret_val = SSL_CONNECT_ERROR  
Server Certificate Verification failed 9 retval = -9


Thanks
geekalgo

**Comment by chaurah** [comment]
Hi @geekalgo,
       The error code indicates that the cert you are using is not valid yet. This would indicate an issue with the system time. Which device/platform are you running the SDK on? Can you check the system time on the device?

Rahul

**Comment by geekalgo** [comment]
Hi I am using our embedded device. In this device i cant change the date.
Can you suggest ??

**Comment by geekalgo** [comment]
Hi System time are extract by countdown_ms() function . I have hard codded to current ntp time. Still did'nt  work ?

**Comment by geekalgo** [comment]
Hi chaurah,
Thanks. I have updated my date and time to
Fri Oct  7 18:35:47 GMT 2016
still i am facing  the same  problem ?

**Comment by geekalgo** [comment]
Hi,
In tls_server_certificate_verify() hostname is  **ardd8p5btb49v.iot.us-west-2.amazonaws.com.**
but dns name is **iot.us-west-2.amazonaws.com** in server certficate.
tls_server_certificate_verify function is failing ???

**Comment by geekalgo** [comment]
HI @chaurah,
In iot_tls_connect(),
SSL_get_peer_certificate(pSSLHandle) returning NULL on each time.what would be the problem ?

**Comment by geekalgo** [comment]
Hi I am using openwrt embeded device.

**Comment by chaurah** [comment]
Hi @geekalgo,
     That error is usually returned when the connection attempt didn't succeed or the server did not present a certificate. The second option should never happen, our servers always return a certificate when a TLS connection is established. Are you seeing this error intermittently or does it happen every time? Can you try increasing the TLS handshake timeout and see if that helps in the cert being downloaded properly?

Please let me know if you are able to get a stable connection.

Rahul

**Comment by geekalgo** [comment]
Hi @chaurah,
Thanks for the support.This issue has been fixed. For the first two to three day everything will work. After 2 days my device is not even connecting to cloud. If we change again thing name and certificate it will work again. What would be the issue? In my certificate the validity period is till 2040.

**Comment by chaurah** [comment]
Hi @geekalgo,
    Can you please check the SDK/Cloudwatch logs? Do they list any specific error codes on the Connect attempt?

Rahul

**Comment by chaurah** [comment]
Closing this since there haven't been any comments for a while now.
