### ISSUE TITLE
Packet overflow(SDK V4_beta)

### ISSUE THREAD

**Issue by MrZhuGe** [aws/aws-iot-device-sdk-embedded-C#466]
Hello, I used the SDK and found that when the packet exceeds a certain size, the packet will be incomplete. After analysis, it was found that uint16_t conversion was caused when serializing data. Can you change it to uint64_t?

**Comment by gordonwang0** [comment]
Hi @MrZhuGe,

Can you link the line of code that does the conversion?

Many values are specified by the MQTT spec to be 2 bytes, and are therefore represented as `uint16_t`.

**Comment by MrZhuGe** [comment]
Hello, I found that the SDK uses dynamic allocation of memory, so the setting here is not reasonable, the conversion code is 1379 lines in the iot_mqtt_serialize.c file.

**Comment by MrZhuGe** [comment]
Hello, I found that the SDK uses dynamic allocation of memory, so the setting here is not reasonable, the conversion code is 1379 lines in the iot_mqtt_serialize.c file.

**Comment by gordonwang0** [comment]
Hi @MrZhuGe,

I looked at those lines; those casts are not needed there.  I've removed them.

**Comment by MrZhuGe** [comment]
Very good！
