### ISSUE TITLE
Incorporate latest jsmn for bugfixes

### ISSUE THREAD

**Issue by tim-nordell-nimbelink** [aws/aws-iot-device-sdk-embedded-C#48]
I've encountered a bug that is fixed within jsmn's repository, but not within this repository.  Please update the internal copy to match the latest version.

(Specifically, this commit fixes the bug I've hit: https://github.com/zserge/jsmn/commit/d0664f9a2ee942e0edaa255309f67b3f77e04b50)

Thanks,
Tim

**Comment by chaurah** [comment]
Hi @tim-nordell-nimbelink,
    Thank you for pointing this out. The Json library fix is a part of the next release of the C SDK already. I will update this issue after the release. Thank you for using AWS IoT and please do let us know if you have any further suggestions.

Rahul

**Comment by hedeshianaws** [comment]
Fixed @ https://github.com/aws/aws-iot-device-sdk-embedded-C/commit/a713027195e26668e1d28f74511023b5757a8715
