### ISSUE TITLE
Is SHADOW_JSON_STRING supported as value type in delta

### ISSUE THREAD

**Issue by macinfox** [aws/aws-iot-device-sdk-embedded-C#49]
Hello,

I'm wondering if I'm overlooking something.  I want to use a string as the value for my delta. For example {"desired": {"light": "on"},"reported": {"light": "off"}}.

However, I have traced where I believe the string should get stored in UpdateValueIfNoObject() and there is not a case for SHADOW_JSON_STRING.

I added the following and everything works as expected:

else if(pDataStruct->type == SHADOW_JSON_STRING) {
	    ret_val = parseStringValue((char *) pDataStruct->pData, pJsonString, &token);
}

Is this an oversight or am I doing something wrong?

Thanks!

**Comment by chaurah** [comment]
Hi @macinfox,
  You can see an example of how we were expecting the update function to be used [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/samples/linux/shadow_sample/shadow_sample.c#L245). You can directly use add_reported and add_desired APIs to update shadows. The APIs are present in [this](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/include/aws_iot_shadow_json_data.h#L70) file.

I should emphasize that while there's nothing inherently wrong with the changes you have made, we have Not tested this and we are already aware of issues with Nested JSON parsing in the current version of the SDK. This might cause issues for you later on.

Please let me know if you have any further questions. Thank you for using AWS IoT.

Rahul

**Comment by macinfox** [comment]
Hi Rahul,

Thanks for the response.  I think we may be talking about different issues.  I'm referring to parsing an incoming delta message where the value for the token is a string {"light":"on"}.

Thanks!

**Comment by chaurah** [comment]
Hi @macinfox,
I see what you mean now. You are correct, this looks like an oversight. We will add this to our list of issues to be fixed before the next release. Thank you for pointing it out. Please let us know if you find any other issues.

Rahul

**Comment by nesatArcelik** [comment]
@macinfox thank you very much, you saved my day.

@chaurah why do you update the fix of a SHOW STOPER bug after 1 year?

Furthermore, Json Type Null is still  is missing in your SDK.

Is there another repository which is more up-to-date? We may give up using AWS for our IoT structure if we face a similar bug.
