### ISSUE TITLE
Delta token callback called for metadata

### ISSUE THREAD

**Issue by macinfox** [aws/aws-iot-device-sdk-embedded-C#50]
Hello,

I'm testing using multiple tokens by calling aws_iot_shadow_register_delta() and storing them in tokenTable[].  My shadow looks like:

{"desired":{"light":"on","volume":5},"reported":{"light":"on","volume":3}}

the message published on the delta topic looks like:

{"version":23,"timestamp":1478810833,"state":{"volume":5},"metadata":{"light":{"timestamp":1478810830},"volume":{"timestamp":1478810830}},"clientToken": "myThing-0"}

However when in isJsonKeyMatchingAndUpdateValue the token for light in the metadata section is found and it's callback is called (even though there was no delta for the light token).

I'd added the following to isJsonKeyMatchingAndUpdateValue

else if(jsoneq(pJsonDocument, &(jsonTokenStruct[i]), "metadata") == 0) {
    return false;
}

this works as expected assuming I don't want to do anything with the metadata.

Is there a better way to handle this?

Thanks!

**Comment by chaurah** [comment]
Hi @macinfox,
  This seems to be an oversight, we have added reworking this part to the list of changes needed for the next release. I will update this post once we have the next release out. Thank you for pointing this out. Please do let us know if you have any further suggestions.

Rahul

**Comment by hedeshianaws** [comment]
Fixed: https://github.com/aws/aws-iot-device-sdk-embedded-C/commit/316107b4887b45aab45bcdaafc36bec05422a711
