### ISSUE TITLE
Build with library without C99 I/O format support failed

### ISSUE THREAD

**Issue by fanghuaqi** [aws/aws-iot-device-sdk-embedded-C#52]
Hi, 

I tried to port aws iot c sdk to Synopsys ARC processor using GNU toolchain, but the library was built without C99 I/O format support. So the file aws_iot_json_utils.c build failed. I take a look at the inttypes.h, and found the following lines:

```c
#define PRId8           __PRI8(d)
#define PRIi8           __PRI8(i)
#define PRIo8           __PRI8(o)
#define PRIu8           __PRI8(u)
#define PRIx8           __PRI8(x)
#define PRIX8           __PRI8(X)

/* Macros below are only enabled for a newlib built with C99 I/O format support. */
#if defined(_WANT_IO_C99_FORMATS)

#define SCNd8           __SCN8(d)
#define SCNi8           __SCN8(i)
#define SCNo8           __SCN8(o)
#define SCNu8           __SCN8(u)
#define SCNx8           __SCN8(x)
```

It seems that we need to rebuild the newlib to support this marco, but in older release of AWS IoT C SDK 1.0, it works fine, it used ``PRIi8`` and ``PRIu8``` instead of `SCNu8` and `SCNi8`, do you have any suggestion to solve this build failing issue.

Thanks
Huaqi

**Comment by chaurah** [comment]
Hi @fanghuaqi,
The entire SDK was built assuming C99 as the baseline. You can continue to use the older version of the json_utils file and it should work without any major issues. But we have Not tested that so I would recommend that you do a lot of on-device testing before putting this code into production.

You can find the older versions of the SDK using the Release tags. The last 1.x release of the json_utils file is [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v1.1.2/aws_iot_src/utils/aws_iot_json_utils.c).

Please let me know if you have any further questions. Thank you for using AWS IoT.

Rahul

**Comment by jflynn129** [comment]
any plans to revise this issue and fix the compile failure, it also fails on gcc-arm-none-eabi-7-2017-q4-major which is the latest compiler release.
