### ISSUE TITLE
The message sending callback cannot correspond to the specific message problem(SDK v4.0.0beta)

### ISSUE THREAD

**Issue by MrZhuGe** [aws/aws-iot-device-sdk-embedded-C#528]
@gordonwang0 Hello, I found that in the callback function that the message was sent successfully or failed, there is no sign that allows me to know which message is sent. In this case, I don't know which message the callback succeeds or fails. How can I handle it?

![image](https://user-images.githubusercontent.com/9351429/61680500-5f4c7500-ad3c-11e9-9e99-80b003be3288.png)

**Comment by ravibhagavandas** [comment]
Hi @MrZhuGe,

The callback function for publish ( or for any other operation ) completion, also has a context variable which can be passed in by the user at the time of publishing the message. 
This context variable can be used by the application to set a value which can be later retrieved from the callback. To see an example of setting the publish count in the context variable check the demo [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/demos/source/iot_demo_mqtt.c#L643).

**Comment by MrZhuGe** [comment]
Really, thank you very much.
