### ISSUE TITLE
request: help using ecc508 hardware crypo chip

### ISSUE THREAD

**Issue by larsonmpdx** [aws/aws-iot-device-sdk-embedded-C#53]
microchip has advertised their ecc508 chip as being suitable for use with AWS IOT:

http://www.atmel.com/applications/iot/aws-zero-touch-secure-provisioning-platform/default.aspx

from what I've gathered, it's only currently supported in the following sample code which is meant for their demo board and uses wolfssl with a special plugin:

https://github.com/MicrochipTech/AWS-Secure-Insight/tree/master/sw/FW/aws_kit_demo/aws_demo_kit/src/aws/wolfmqttsdk/wolfssl/wolfplugin/atecc508

I'd like to use the the aws C or C++ library with the ecc508.  I'm willing to put some effort into integrating things.  Can I get some pointers for where to start?

**Comment by larsonmpdx** [comment]
a little more research: http://www.atmel.com/tools/Atmel-HW-TLS.aspx lists both wolfssl and openssl as supported libraries.  so, maybe I could use the aws iot C++ sdk which supports openssl, and configure my system's openssl to use the ecc508?  I don't yet see how I can use a private key stored in the ecc508 though.

**Comment by chaurah** [comment]
Hi @larsonmpdx,
    You have both options. If you stick to the Embedded C SDK, you will need to port the Network layer for either WolfSSL or OpenSSL. You will also need to modify the Network interface slightly to pass the private key as a string instead of the file path that the SDK currently expects. With C++, the OpenSSL wrapper is not linked to the SDK and can be initialized in any way required.

Do you have a particular preference for one language or the other? Please keep in mind that the C++ SDK requires a C++11 based compiler. Either way, I will be happy to help you get started. Please let me know what further questions you have.

Rahul

**Comment by larsonmpdx** [comment]
Thank you.  I would much prefer C++, I initially used the C library only because it was available first.

When using the atecc508a for hardware key storage, passing a private key as a string isn't possible; the private key can never leave the device (this is how it adds security).  Instead, you must ask the device to perform the signing operation.  This is the part that I need help with - how do I get the aws iot library to make this request instead of looking into a key file?  There is some sample openssl code here:

https://github.com/AtmelCSO/cryptoauth-openssl-engine/blob/master/engine_atecc/engine_meth/eccx08_ecdsa_sign.c

the atecc508a also provides hardware crypto acceleration but this would be a side benefit as the cpu cost on my target platform is trivial.

**Comment by schielimicrochip** [comment]
Indeed, the private key never leaves the ECC508A.
You can indeed use our OpenSSL patch (adds the ECC508A interface to the OpenSSL engine API) available here: https://github.com/AtmelCSO/cryptoauth-openssl-engine/tree/master/engine_atecc/cryptoauthlib

This is a patch that can be applied on OpenSSL. It contains all the necessary hooks to defer all crypto handling to the ECC508A.

If you are using the AWS IoT library with a standard OpenSSL implementation (with keys and crypto in software), replacing the OpenSSL implementation by the one patched should redirect all necessary calls to the ECC508A.

Please email me directly if you are still having trouble with this: Nicolas.schieli at microchip.com

**Comment by larsonmpdx** [comment]
great! thanks.  so it should work on the ecc508a side.

for the aws iot library, should I put in fake key/cert files, which will then be ignored by this patched openssl?  It looks like it still expects the files to exist during setup, see:

passing the file paths:
https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/samples/PubSub/PubSub.cpp#L146

opening the files:
https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/network/OpenSSL/OpenSSLConnection.cpp#L260

**Comment by schielimicrochip** [comment]
Could you please send an email directly to Nicolas.schieli at microchip.com from your email system and not Github?
We'll involve the support team and publish the resolution to GitHub once completed

**Comment by chaurah** [comment]
Hi @larsonmpdx,
The C++ SDK itself doesn't require the Network to be initialized in any particular way. Each client instance simply expects to be provided an instance of the Network Connection which it can work with for the entire instance lifetime. You can simply modify the Initialization of the certs/key and convert it to whatever is required.
There's a Network Layer implementation guide located [here](https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/network/README.md) with more information. I think a wrapper for OpenSSL that uses the OpenSSL implementation provided by microchip above should be sufficient.

Please let me know if you have any further questions.
Rahul

**Comment by gojimmypi** [comment]
hi @schielimicrochip - wondering what's the status of getting the ATECC508A to work with AWS & more generic C library? In particular, I'd like to use the ESP8266 to talk to AWS.

**Comment by pietrushnic** [comment]
@gojimmypi you should use [CryptoAuthLib](http://www.atmel.com/tools/cryptoauthlib.aspx?tab=overview) which is plain C and can be ported to support various HALs. You can read more about using it [here](http://www.atmel.com/applications/iot/aws-zero-touch-secure-provisioning-platform/default.aspx?tab=documents). I don't like mongoose OS, but this probably easiest way to integrate - more about that you can find [here](https://mongoose-os.com/blog/mongoose-esp8266-atecc508-aws/).

**Comment by paclema** [comment]
Hi everyone and @schielimicrochip I am also trying to register devices with Debian using the AWS IoT with Boto3 python library. But I don't know really well how to create certificates (required for this AWS python library) using this ecc508 chip.

I understand then that I need to install the [OpenSSL](https://github.com/MicrochipTech/cryptoauth-openssl-engine/wiki/ATECC508A:-Platform-Integration) Integrating the ATECC508A to create the certificates that AWS needs, as it is explained on this Just In Timer Registration process from AWS:
https://aws.amazon.com/es/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/

However, those credentials have to be stored on the ATECC508A chip instead to be on files, but how can I access to them that python can send them to register new devices?

How can I use afterward those certificates with the aws-sdk for python?

Thank you in advance!

**Comment by pietrushnic** [comment]
@paclema you need HAL for your system and use OpenSSL with engine to generate correct certificates and key. They if your engine works you can create CSR which will save private key inside ECC508A and generate certificates. After that you can use TLS engine support in mosquitto (patches are not merged yet, but you can find those [here](https://github.com/eclipse/mosquitto/pull/202)) to do JITR with AWS. Of course this requires correct configuration of AWS side what was described in mentioned blog post.

**Comment by paclema** [comment]
@pietrushnic thank you for your answers and info!
Do you know where is the documentation of the i2c protocol to communicate with the ECC508A that I can develop the HAL for python?

**Comment by pietrushnic** [comment]
@paclema it is is extended documentation from Microchip which is under NDA. You can figure out most things from [CryptoAuthLib](http://www.atmel.com/tools/cryptoauthlib.aspx). Unfortunately some additional work have to be done if you want to use Python instead of C.

Please note recently new chip pop up [ECC608A](http://www.microchip.com/wwwproducts/en/ATECC608A)

**Comment by gordonwang0** [comment]
Closing issue due to age.  Please let us know if you need any more help.
