### ISSUE TITLE
Dead link in Porting Guide

### ISSUE THREAD

**Issue by Lotterleben** [aws/aws-iot-device-sdk-embedded-C#536]
Hi,
The [Sample Porting:](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/PortingGuide.md#sample-porting) Section of the Porting Guide links to https://github.com/marvell-iot/aws_starter_sdk/tree/master/sdk/external/aws_iot/platform/wmsdk. However, this link is dead (https://github.com/marvell-iot does not appear to contain any public repositories). Can the sample files be found somewhere else and if so, would it make sense to link to them?

**Comment by gordonwang0** [comment]
Hi @Lotterleben,

Thanks for bringing this up.  I'll take a look to see if I can track down that file, but we may remove this link if I can't find it.

**Comment by gordonwang0** [comment]
Hi @Lotterleben,

I've removed the dead link from the porting guide.  Please let me know if you have any more questions.
