### ISSUE TITLE
Bug in aws_iot_mqtt_client.c related to password

### ISSUE THREAD

**Issue by newdreamlj** [aws/aws-iot-device-sdk-embedded-C#54]
```c
141:	pClient->clientData.options.pPassword = pNewConnectParams->pUsername;
```

It really takes me a long time to find this but a critical typo, especially for those MQTT broker requiring password.

The phenomenon is, TLS connection could be successfully established but as soon sending serialized connection msg, ALERT is returned from server and "    close notify" is got.

**Comment by chaurah** [comment]
Hi @newdreamlj,
     Thank you for pointing this out. I have added tracking for a fix for this issue internally and it will be fixed in the next release of the Embedded C SDK. I should point out however that AWS IoT does not support the username and password fields at the moment. If you try to use your code which requires password with AWS IoT, the client will not be able to connect.

Please let me know if you have any further issues. Thank you for using AWS IoT.

Rahul

**Comment by hedeshianaws** [comment]
Fixed: https://github.com/aws/aws-iot-device-sdk-embedded-C/commit/2567e5c7e3a72b8f8eb6761d5d7dca64aef62bc3
