### ISSUE TITLE
Memory leak(SDK v4.0 beta)

### ISSUE THREAD

**Issue by MrZhuGe** [aws/aws-iot-device-sdk-embedded-C#541]
@gordonwang0 I found that the SDK has a memory leak, and in the process of heartbeat, the memory is constantly rising.

**Comment by MrZhuGe** [comment]
@gordonwang0 Hello, after testing, there is no memory leak in the process of performing heartbeat alone, but there is still a memory leak in the process of subscribing to messages and publishing messages. Please check it out, thank you.

**Comment by gordonwang0** [comment]
Hi @MrZhuGe,

How are you measuring memory usage?  Also, could you provide the code you are using so I can take a look?  Thanks.

**Comment by MrZhuGe** [comment]
我先仔细确认一下是不是我自己的问题
Wǒ xiān zǐxì quèrèn yīxià shì bùshì wǒ zìjǐ de wèntí
17/5000
I will carefully confirm if it is my own problem.

**Comment by MrZhuGe** [comment]
I will carefully confirm if it is my own problem.

**Comment by MrZhuGe** [comment]
After troubleshooting, the problem is identified as a problem with the business code, the issue has been fixed.
