### ISSUE TITLE
When version 4.0 will be released? 

### ISSUE THREAD

**Issue by RavilN** [aws/aws-iot-device-sdk-embedded-C#546]
Hello,

Currently version 4.0 is Beta only, not released. Could you please provide estimate, when release is expected?

Thank you, Ravil

**Comment by danhorner** [comment]
Hello, 
Amazon hasn't announced a date for general availability of version 4.0 of the C SDK. 

Note though that the version of the C SDK in the current FreeRTOS release is derived from the 4.0 branch. That might help you to gauge stability.

**Comment by RavilN** [comment]
Hello,
Could you please clarify, what is "the current FreeRTOS  release"? Is it some other project at GitHub?

**Comment by danhorner** [comment]
Hi @RavilN, 
Yes, see the [Amazon FreeRTOS Repository](https://github.com/aws/amazon-freertos)
