### ISSUE TITLE
When shadow client is configured with LWT, the broker fails to send the msg on subscribed topic when client disconnects abrubtly

### ISSUE THREAD

**Issue by nikitanerkar** [aws/aws-iot-device-sdk-embedded-C#55]
Hi,

I made following changes in AWS IoT agent to enable LWT support,
connectParams.isWillMsgPresent = true;
And modified,
#define IoT_MQTT_Will_Options_Initializer { {'M', 'Q', 'T', 'W'}, NULL, 0, NULL, 0, false, QOS0 }
as
#define IoT_MQTT_Will_Options_Initializer { {'M', 'Q', 'T', 'W'}, "test", 5, "clientDied", 11, false, QOS0 }

The shadow_sample application connects with the AWS_IoT thing shadow and keeps publishing data. Also another client subscribes to the topic "test". When execution of shadow_sample is stopped abruptly, the client subscribed to the topic "test" does not receive any message.

Is the LWT support broken for embedded C?

**Comment by chaurah** [comment]
Hi @nikitanerkar,
     If you are using shadow_sample you would need to set the Will options parameter in the shadow connect call. Am I right in assuming you have modified the connectParams.isWillMsgPresent in the aws_iot_shadow.c file?

If you have, this should work. Where are you trying to see if the LWT message was published? In the console? Can you see any cloudwatch logs for when the client is disconnected?

The LWT message should get published when the server disconnects the client after the keepalive interval has passed. You should be able to see a Publish action in the Cloudwatch logs when this happens.

Please let me know if you are able to figure things out with the above information.

Rahul

**Comment by nikitanerkar** [comment]
Hi Rahul,

Yes I am using shadow_sample application and I did modify aws_iot_shadow.c to set ConnectParams.isWillMsgPresent = true; Also I modified and configured,
#define IoT_MQTT_Will_Options_Initializer { {'M', 'Q', 'T', 'W'}, "test", 5, "clientDied", 11, false, QOS0 } 
in aws_iot_mqtt_client.h
After making these changes when I executed shadow_sample application, I could see AWS IoT logs getting captured on CloudWatch in the following format,

####### 2016-12-08 08:25:48.656 TRACEID:5d532d8f-xxxx-1ef6-xxxx-xxxxxxxxxxxx PRINCIPALID:NThing1 [INFO] EVENT:UpdateThingShadow TOPICNAME:$aws/things/NThing1/shadow/update THINGNAME:NThing1

But when the client disconnects which is shadow_sample application execution is stopped, no publish is captured on CloudWatch.

Nikita

**Comment by chaurah** [comment]
Hi Nikita,
    I replicated what you have mentioned above and I was able to see the Will message being published as expected. The only difference was that the length that I used does not use the null character as you seem to be doing above. your initializer should be { {'M', 'Q', 'T', 'W'}, "test", 4, "clientDied", 10, false, QOS0 }. When you pass any length values to any of the SDK APIs please avoid including the null character. Depending on what is in the next memory location, it can cause issues.

Rahul
