### ISSUE TITLE
Please provide openssl version of AWS-IOT Embedded C SDK

### ISSUE THREAD

**Issue by technobilly** [aws/aws-iot-device-sdk-embedded-C#56]
I wish you would provide the openssl version of the embedded C IOT SDK. Many fairly complex embedded systems already have openssl libraries, which makes mbedTLS redundant, adding to build time, image size, etc. In addition openssl is more likely to get security updates. It may also be easier to undergo device security compliance testing using openssl instead of using mbedTLS because it is well-known.

**Comment by chaurah** [comment]
Hi @technobilly,
We are already working on bringing OpenSSL support for v1.0.2 onwards to the Embedded C SDK. We still don't have a release timeframe for that however. If you are interested in porting right now, you can still find the OpenSSL wrapper in the 1.x branch. You will need to make some changes to match the new Network wrapper and the latest OpenSSL release. Another option would be that you use the C++ Device SDK that you can find [here](https://github.com/aws/aws-iot-device-sdk-cpp) which already supports OpenSSL as the default network library.

I will update this issue when a new release with OpenSSL support is out for Embedded C. Please let me know if you have any further questions.

Rahul

**Comment by technobilly** [comment]
@chaurah,
Thanks for the quick reply. That is great news, I am glad to hear you are already working on it. I can use mbedTLS for now and  change to openssl when you release it.

**Comment by jchirschy** [comment]
This porting will be greatly appreciated. Thanks @chaurah

**Comment by ambrosechoy** [comment]
@technobilly @jchirschy 
Not sure if you guys are aware but there's an openssl version that I've used from this tutorial http://docs.aws.amazon.com/iot/latest/developerguide/iot-embedded-c-sdk.html

@chaurah Will the openssl support be added to this repository at some point?

**Comment by miaoichi** [comment]
I have ported openssl wrapper from 1.1.2 to 2.1.1, currently It works fine.

**Comment by aricop** [comment]
Hello guys,
 
i am currently beginning with AWS IOT and i am trying port AWS IOT embedded  C SDK to atmel SAM devices. I am working with SAMW25 Xplained Pro that contains SAMD21 + WINC1500. 

i have already ported timer functions but i don´t know how port Network functions and what resources i need use for do that. 
 
Did someone get port Network functions? Could someone help me to understand what steps a have to follow?
 
Any help is appreciated.
Thanks in advance.

**Comment by gordonwang0** [comment]
Hi everyone,

We are providing an OpenSSL network implementation as part of [v4 beta](https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/v4_beta).  Please give it a try if you have time.
