### ISSUE TITLE
<unistd.h> is a POSIX header and should be avoided

### ISSUE THREAD

**Issue by nelsonpina** [aws/aws-iot-device-sdk-embedded-C#57]
Compilers like IAR for ARM Cortex-M don't provide headers like `<unistd.h>`

FYI: I'm porting the SDK to embedded systems running on bare metal or RTOS with very limited features (e.g. task scheduler only).

**Comment by chaurah** [comment]
Hi @nelsonpina,
   Thank you for pointing this out. I assume you found that header in the [aws_iot_mqtt_client_common_internal](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_mqtt_client_common_internal.c) file? That should not have been present and you should be able to safely remove it. I will add a bugfix to our next release for making this change. Please do let us know if you find any similar issues as you make progress on your porting or if you have any other issues. Thank you for using AWS IoT.

Rahul

**Comment by nelsonpina** [comment]
Hi @chaurah,
yes it is included in the `aws_iot_mqtt_client_common_internal` and can be removed.

cheers,
nelson
