### ISSUE TITLE
functions returning IoT_Error_t type are declared with char as returning type

### ISSUE THREAD

**Issue by nelsonpina** [aws/aws-iot-device-sdk-embedded-C#58]
static `char` _aws_iot_mqtt_internal_is_topic_matched(char *pTopicFilter, char *pTopicName, uint16_t topicNameLen)  {

	char *curf, *curn, *curn_end;

	if(NULL == pTopicFilter || NULL == pTopicName) {
		return NULL_VALUE_ERROR;
	}

**Comment by chaurah** [comment]
Hi @nelsonpina,
   Thank you for pointing this out. I have added this to our internal list of fixes to be made before the next release. Please do let us know if you find any further issues.

Rahul

**Comment by fedex03** [comment]
Any new about this issue?

How can I fix it?

Thanks!
