### ISSUE TITLE
Callback function on subscribe not being called

### ISSUE THREAD

**Issue by gmussi** [aws/aws-iot-device-sdk-embedded-C#591]
Hello, I am currently using SDK 3.0.1, but the problem also happens with all versions until 2.1.1.

I can connect to AWS and publish messages to a topic, but the subscribe is not working for me.

`aws_iot_mqtt_subscribe` returns success. I can see the correct subscribe event in the Iot LifeCycle events. But nevertheless, the callback function is not called.

My code:

```
pSubCallBackHandler_t subApplCallBackHandler = 0;

void iot_subscribe_callback_handler(AWS_IoT_Client *pClient, char *topicName, uint16_t topicNameLen,
        IoT_Publish_Message_Params *params, void *pData) 
{
    ESP_LOGW(TAG, "MESSAGE ARRIVED");
    if(subApplCallBackHandler != 0) //User call back if configured
    subApplCallBackHandler(topicName,params->payloadLen,(char *)params->payload);
}

int AWS_IOT::subscribe(char *subTopic, pSubCallBackHandler_t pSubCallBackHandler)
{
    IoT_Error_t rc;
    
    subApplCallBackHandler = pSubCallBackHandler;

    ESP_LOGI(TAG, "Subscribing...");
    rc = aws_iot_mqtt_subscribe(&client, subTopic, strlen(subTopic), QOS0, iot_subscribe_callback_handler, NULL);
    if(SUCCESS != rc) {
        ESP_LOGE(TAG, "Error subscribing : %d ", rc);
        return rc;
    }
    ESP_LOGI(TAG, "Subscribing... Successful");
    
    return rc;
}
```
The "Subscribing... Successful" is printed, but "MESSAGE ARRIVED" is never printed, now matter how many times i publish to topic. (I can see the messages on IOT TEST CONSOLE)

How can I debug this problem? (If I subscribe via mosquitto_sub or javascriot sdk, it works)

**Comment by gordonwang0** [comment]
Hello,

Are you calling [aws_iot_mqtt_yield](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/0da78ce48508a754d2acf2843f5584aaeca91db2/include/aws_iot_mqtt_client_interface.h#L192)?  Since v3 of the C SDK is a single-threaded API, you must call yield to provide the library with time to process incoming messages.

**Comment by gmussi** [comment]
Hello, yes. I have the following loop:
```
IoT_Error_t rc = SUCCESS;
    while(1) {
        //Max time the yield function will wait for read messages
        rc = aws_iot_mqtt_yield(&client, 200);
        
        if(NETWORK_ATTEMPTING_RECONNECT == rc) {
            // If the client is attempting to reconnect we will skip the rest of the loop.
            continue;
        }
        vTaskDelay(1000 / portTICK_RATE_MS);
    }
```
(The code run using Arduino ESP32).

**Comment by gmussi** [comment]
I now realize my code is running out of memory when execuing the yield method. So the problem seems to be related to the esp32 code, not aws sdk. I will close this ticket.
