### ISSUE TITLE
Any plan to support mbedtls certs and keys in memory?

### ISSUE THREAD

**Issue by fanghuaqi** [aws/aws-iot-device-sdk-embedded-C#61]
Hi, guys,

I am using AWS IoT C SDK with mbedtls in [embARC](https://www.embarc.org/), and we have done a demo based on this sdk, you can take a look at it in Youtube.

Learn about the components of the smart home application example using embARC Open Software Platform and Amazon AWS IoT Service. Please see the other videos in this series: 
Part 1 – Introduction to Smart Home Demo Application https://youtu.be/O4B9GkRF_NU
Part 2 – Host and Target Development Environment Requirements https://youtu.be/SgDwNKnW5Fc
Part 3 – Host and Target Development Environment Setup Instructions https://youtu.be/Xu33U0MBXo8
Part 4 – Configuring the Amazon AWS IoT Cloud Service https://youtu.be/gt-ii5bj0VU
Part 5 – Building and Running the Application https://youtu.be/LpmkDyBEp74
`
But this AWS IoT C SDK required that we need to prepare certs and key files in a filesystem, but for many embedded systems, there might not have a filesystem support.  As I look deep into the source code of aws c sdk, it didn't provide a way to store the keys and certs in memory, but mbedtls support that use case, so do you have any plan to support that use case in future?
       
If supported, we want to protect the key and cert in a memory, so malware can't access to the keys.

Thanks
Huaqi

**Comment by chaurah** [comment]
Hi fanghuaqi,
 Thank you for working on those excellent Demos. They will be extremely helpful to many people. We are already working on adding that support to the SDK as it has been requested by many customers. However, we do not have a timeline on the next SDK release yet. In the meantime, unless you're on a heavily constrained device, you can use the [C++ Device SDK](https://github.com/aws/aws-iot-device-sdk-cpp) which allows you to initialize the network separately from the MQTT Client.

I will update this issue when the next release of the SDK is out. If you have any further issues that you would like us to work on, please do let us know. Feedback from our customers is very important for us. Thank you for using AWS IoT.

Rahul

**Comment by fanghuaqi** [comment]
Thanks Rahul, I will wait for the next release of AWS IoT C SDK.


Huaqi

**Comment by Borschtsch** [comment]
Talking about mbedTLS, it already has this functionality built in. There is no need to wait for next AWS IoT SDK release. All you need is to enable parsing certificate straight from the text/binary buffer instead of a file.

For example, you have a certificate in a PEM format.
Then instead of mbedtls_x509_crt_parse_file(), you should use mbedtls_x509_crt_parse(), which is enabled by adding MBEDTLS_X509_CRT_PARSE_C and MBEDTLS_PEM_PARSE_C to the config.h, MBEDTLS_FS_IO could be removed then.
There might be a bit more to configure, but you should get the point now.

**Comment by fanghuaqi** [comment]
Hi Borschtsch,
Thanks for your advice and steps about how to achieve this.
Yeah, we can change the port layer of AWS IoT C SDK to achieve this functionality, but it seems not quite formal, maybe we can try it.

Thanks
Huaqi

**Comment by chaurah** [comment]
Hi @fanghuaqi,
    @Borschtsch is correct and that is indeed the change we will be including in the next version of the SDK where we will allow the Network to be initialized separately from the MQTT Client itself. Porting the SDK to suit your needs is an intended use case here. It does take a little bit of effort. We are working on making sure the effort is reduced considerably from the next release. But for now, you can unblock yourself much faster by making the suggested changes.

Please let me know if you get stuck somewhere. I will be happy to help you work through the modifications.

@Borschtsch: Thank you for pitching in. If you have any further suggestions on how we can improve the SDK, please do let us know.

Rahul

**Comment by gustavomassa** [comment]
@chaurah 

My suggestion for the next release is to add add a new option for the certs file system inside "aws_iot_config", something like that:
`#define AWS_IOT_CERTIFICATE_FILESYSTEM `

Then you can modify the "iot_tls_connect" function inside "network_mbedtls_wrapper":

	```
IOT_DEBUG("  . Loading the CA root certificate ...");
#ifdef AWS_IOT_CERTIFICATE_FILESYSTEM
	ret = mbedtls_x509_crt_parse_file(&(tlsDataParams->cacert), pNetwork->tlsConnectParams.pRootCALocation);
#else
	ret = mbedtls_x509_crt_parse(&(tlsDataParams->cacert), (const unsigned char *) tlsDataParams->ca_cert_str, strlen(tlsDataParams->ca_cert_str) + 1);
#endif
	if(ret < 0) {
		IOT_ERROR(" failed\n  !  mbedtls_x509_crt_parse returned -0x%x while parsing root cert\n\n", -ret);
		printf("\nfailed!  mbedtls_x509_crt_parse returned -0x%x while parsing root cert", -ret);
		return NETWORK_X509_ROOT_CRT_PARSE_ERROR;
	}

	IOT_DEBUG("  . Loading the client cert ...");
#ifdef AWS_IOT_CERTIFICATE_FILESYSTEM
	ret = mbedtls_x509_crt_parse_file(&(tlsDataParams->clicert), pNetwork->tlsConnectParams.pDeviceCertLocation);
#else
	 ret = mbedtls_x509_crt_parse(&(tlsDataParams->clicert), (const unsigned char *) tlsDataParams->client_cert_str, strlen(tlsDataParams->client_cert_str) + 1);
#endif
	if(ret != 0) {
		IOT_ERROR(" failed\n  !  mbedtls_x509_crt_parse returned -0x%x while parsing device cert\n\n", -ret);
		printf("\nfailed! mbedtls_x509_crt_parse returned -0x%x while parsing device cert", -ret);
		return NETWORK_X509_DEVICE_CRT_PARSE_ERROR;
	}

	IOT_DEBUG("  . Loading the client key ...");
#ifdef AWS_IOT_CERTIFICATE_FILESYSTEM
	ret = mbedtls_pk_parse_keyfile(&(tlsDataParams->pkey), pNetwork->tlsConnectParams.pDevicePrivateKeyLocation, "");
#else
	ret = mbedtls_pk_parse_key(&(tlsDataParams->pkey), (const unsigned char *) tlsDataParams->client_key_str, strlen(tlsDataParams->client_key_str) + 1, NULL, 0);
#endif
	if(ret != 0) {
		IOT_ERROR(" failed\n  !  mbedtls_pk_parse_key returned -0x%x while parsing private key\n\n", -ret);
		printf("\nfailed! mbedtls_pk_parse_key returned -0x%x while parsing private key", -ret);
		return NETWORK_PK_PRIVATE_KEY_PARSE_ERROR;
	}

```

**Comment by mkhan3088** [comment]
AWS IoT SDK Version 2.0.0-

DEBUG:   main L#150 rootCA /home/pi/aws_iot/myapp/samples/linux/subscribe_publish_sample/../../../certs/rootCA.crt
DEBUG:   main L#151 clientCRT /home/pi/aws_iot/myapp/samples/linux/subscribe_publish_sample/../../../certs/b0-certificate.pem.crt
DEBUG:   main L#152 clientKey /home/pi/aws_iot/myapp/samples/linux/subscribe_publish_sample/../../../certs/b08a-private.pem.key
Connecting...
DEBUG:   iot_tls_connect L#109 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#117   . Loading the CA root certificate ...
ERROR: iot_tls_connect L#120  failed
  !  mbedtls_x509_crt_parse returned -0x3e00 while parsing root cert


ERROR: main L#183 Error(-19) connecting to **********.iot.us-east-2.amazonaws.com:8883
Subscribing...
ERROR: main L#199 Error subscribing : -13 
ERROR: main L#251 An error occurred in the loop.

**Comment by mkhan3088** [comment]
how to store root ca certificate
In which folder i have to keep root ca certificate
