### ISSUE TITLE
Unable to build sdk

### ISSUE THREAD

**Issue by mikegre68** [aws/aws-iot-device-sdk-embedded-C#612]
I downloaded the SDK, downloaded mbedTLS (2.16.3 from GitHub) and when I attempt to build the SDK, I'm getting an error:

make -C ../../../external_libs/mbedTLS
make[1]: Entering directory '/home/pi/aws-iot-device-sdk-embedded-c/external_libs/mbedTLS'
make[2]: Entering directory '/home/pi/aws-iot-device-sdk-embedded-c/external_libs/mbedTLS/library'
Makefile:84: ../crypto/3rdparty/Makefile.inc: No such file or directory
make[2]: *** No rule to make target '../crypto/3rdparty/Makefile.inc'.  Stop.
make[2]: Leaving directory '/home/pi/aws-iot-device-sdk-embedded-c/external_libs/mbedTLS/library'
make[1]: *** [Makefile:19: lib] Error 2
make[1]: Leaving directory '/home/pi/aws-iot-device-sdk-embedded-c/external_libs/mbedTLS'
make: *** [Makefile:64: all] Error 2

Looking at the aws-iot-device-sdk-embedded-c/external_libs/mbedTLS/crypto directory, it is empty. Is there a known issue with the mbedTLS repo?

**Comment by deeplyembeddedWP** [comment]
Download the mbedTLS from [here](https://tls.mbed.org/). And then copy its contents into the mbedTLS directory present in the external libs. Then run make for a sample application.

**Comment by mikegre68** [comment]
That is where I downloaded it from. But that download does not have all the
files needed according to the compiler error I get.

**Comment by deeplyembeddedWP** [comment]
1. How do you invoke the build for SDK? Do you try run make in a sample application, for e.g. subscribe_publish_sample?. 
2. Which SDK  version are you using?
3. In your question, you mention downloaded from"mbedTLS (2.16.3 **from GitHub**) ". The link I shared above is not Github. It is the official site.
I also don't see any directory called crypto in the mbedTLS checked out from the above link I shared.

**Comment by gordonwang0** [comment]
Hi @mikegre68,

mbed TLS has changed their repo so that mbed TLS crypto is a Git submodule.  You'll have to download [mbedTLS crypto](https://github.com/ARMmbed/mbed-crypto/tree/3cdb3da3a0c1631e14434a219dfa787513a915a7) too.  It should be placed in the crypto directory of your mbed TLS download that you mentioned.

**Comment by gordonwang0** [comment]
Hi @mikegre68,

Please let us know if you need any more help with this.  Closing issue.
