### ISSUE TITLE
websocket support

### ISSUE THREAD

**Issue by tljdebrouwer** [aws/aws-iot-device-sdk-embedded-C#630]
Are there any plans to make this library support the use of websockets with temporary credentials?

It doesn't seem to support it now.

**Comment by dnoal** [comment]
Our Embedded C SDK library does not support websockets at this time.  Please advise if this feature is important for your application.  We would appreciate any supporting details you can provide on the use case.

**Comment by tljdebrouwer** [comment]
Thanks for your prompt response.

Our use case would be to take advantage of the authentication with STS. We did productize a device authentication flow from OAuth to STS, which then uses these tokens to authenticate to the IoT core.

Not having to manage certificates (and especially revoking the certificates) is a huge advantage is there is already a user base in an IAM system.

On our case, when a user is inactivated in the IAM system, within 12 hours the IoT device is disconnected because of expired OAuth tokens (and as such not being able to refresh them, which leads to unable to connect to the IoT core.)

**Comment by yuhui-zheng** [comment]
Since we have it in our backlog, I'm going to close this thread for now. Thank you for the input.
