### ISSUE TITLE
Integrating with Telit LE910

### ISSUE THREAD

**Issue by jasdeepdhillon13** [aws/aws-iot-device-sdk-embedded-C#633]
The setup I have is an STM32F407 connected to a Telit LE910 module and trying to get MQTT setup on it. I was going through the source code but couldn't see any AT commands or if this library can be used with the Telit LE910 module. I was wondering if this code can be used with the LE910 to do mqtt publish and subscribe?

**Comment by lundinc2** [comment]
Hello @jasdeepdhillon13 , 

We currently do not support cellular. If you would like to use MQTT with the Telit LE910 module it will be necessary to port the MQTT library to it. Here is a link to the C-SDK porting guide. https://docs.aws.amazon.com/freertos/latest/lib-ref/c-sdk/main/guide_developer_porting.html.

**Comment by lundinc2** [comment]
To amend my statement. We lack examples of cellular, but others have been able to use cellular with this C-SDK.
