### ISSUE TITLE
AWS IoT identify my device using its public key but not CN name in device certificate for provisioning

### ISSUE THREAD

**Issue by xiongyu0523** [aws/aws-iot-device-sdk-embedded-C#635]
Trying to port the SDK to a WiFi MCU and I have a problem during the device provisioning phase.  

**The MCU receive a new device certificate very time it reboot** and it is signed by a CA certificate (This CA certificate is successfully registered on AWS IoT Core). Each certificate's CN name is the same, but it has different public key. (and of course with private key in MCU). I observe the AWS IoT Core treat my device as a new device every time and try to auto register it in certificate pool and hold in pending.ACTIVATION status as the first step of a JITR process. If I reboot 3 times, I got 3 device registered in pending activation state. 

I'm wondering why AWS would recognize my device using its public in the certificate but not the CN name of the certificate. Or Is something I have missed can handle this.  Thank.

**Comment by lundinc2** [comment]
Hello @xiongyu0523, 

Are you developing on this C-SDK or Amazon FreeRTOS? This SDK does not provide any provisioning logic. 

If you are not using Amazon FreeRTOS, what operating system are you using, and what are you using to provision your device? 

We have a demo available on Amazon FreeRTOS for how you can provision a new device. Found here: https://github.com/aws/amazon-freertos/tree/master/demos/dev_mode_key_provisioning.

If you are indeed using Amazon FreeRTOs, could you migrate this issue to the GitHub repository found at https://github.com/aws/amazon-freertos. This contributing guide lists some more information you can provide to help us diagnose this bug report. https://github.com/aws/amazon-freertos/blob/master/CONTRIBUTING.md

**Comment by xiongyu0523** [comment]
Yes I'm using c-sdk. The example you show me about provisioning is specifically to key provisioning on device. While what I was talking is the device provisioning on the AWS IoT Core.

**Comment by lundinc2** [comment]
Hello @xiongyu0523,

I apologize, for misunderstanding and the delay. From what you have said so far, this appears to be working as intended. 

IOT Core treats a second certificate out of the same key-pair as a different request. The certificate is the unique identifier. In order to avoid multiple certificates in PENDING_ACTIVE state, make sure that your Lambda does not exit with any errors and handle the case of aborting a JITR cycle.

Could you describe in more detail what your use case is?

**Comment by xiongyu0523** [comment]
Thanks. 

"IOT Core treats a second certificate out of the same key-pair as a different request". You are saying if a device come online with a new key-pair (even the same CN name), IoT core treat it as a new device, right? From my understanding, key pair is used to encryption and decryption. Should not be used to identify someone. What do you think?

I did not use Lambda to do batch provisioning at this time. Now just for test, I manually move the certificate under PENDING_ACTIVE state to ACTIVE state and associate policy and thing. Later I plan to use Lambda to auto this task but I do not see a difference. If every time IoT core treat my device as a new device (since it has different key pair), my device will not able to connect IoT core unless I register a new device every time.

**Comment by lundinc2** [comment]
Hello @xiongyu0523,

The registration process is a one time process. As once you have completed the JITR process your device will be authenticated to IoT core and able to connect. 

> From my understanding, key pair is used for encryption and decryption ops only. It should not be used to identify someone. What do you think?

In this case when you are registering your device, they are being used for authentication as well. See:  https://aws.amazon.com/blogs/iot/understanding-the-aws-iot-security-model/

Here are some additional security resources:
https://aws.amazon.com/blogs/iot/ten-security-golden-rules-for-iot-solutions/ 
https://docs.aws.amazon.com/iot/latest/developerguide/iot-provision.html
https://docs.aws.amazon.com/iot/latest/developerguide/security-best-practices.html
https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/

**Comment by xiongyu0523** [comment]
Sorry your answer did not address my issue. I have to make it clear:

My device has naturally different device certificate provide to Server during TLS handshake stage every time. Almost all field are different expect for two things. CN name is the same, and it is signed by the same CA certificate which is already registered on IoT Core. 

If AWS IoT Core treat my device always as a new device then I can't talk to AWS IoT Core.

**Comment by abhidixi11** [comment]
Hello xiongyu0523,

Apologies for delay in response.  

>>>My device has naturally different device certificate present to Server during TLS handshake stage every time after a reboot. 

Based on the conversion above, you are observing that when you change the device cert and the public key, IOT core treats it as a different device and you are looking for device provisioning. 
Let me find some information and get back to you.

Meanwhile,  have you checked out our new Fleet Provisioning beta release ?
https://github.com/aws/aws-iot-device-sdk-embedded-C/tree/FleetProvisioning_beta
Not sure if that addresses your problem. 

Thanks!

**Comment by xiongyu0523** [comment]
Yes you right. Just one reminder: A key information is the CN name of the certificate is never changed. CN name should be the only factor to identify someone.

The Fleet provisioning does not work for me. my device come with own device certificates signed by a CA certificate, the trust chain should never be break

**Comment by abhidixi11** [comment]
Thanks for pointing out the problem.
Based on what I know right now, IOT core will treat it as a different device when certificate is changed.  This is not really a CSDK problem but IOT core issue.  Although it is beyond scope of CSDK, we'll try to get more information on this.

**Comment by dcgaws** [comment]
Hello @xiongyu0523 you are correct that AWS IoT looks at the entire certificate during its client authorization check, and not just the CN. However, with either [Just in Time Registration](https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/) (JITR) or [Just in Time Provisioning](https://aws.amazon.com/blogs/iot/setting-up-just-in-time-provisioning-with-aws-iot-core/) (JITP), as long as automatic certificate activation is enabled, your device will be able to authenticate after each power cycle as you describe.

In your case, you may wish to create a script that periodically cleans up the old certificate and Thing records in your registry.

Note, for the JITR case, since you control the logic of your Lambda, it's possible that you could implement the desired behavior.

**Comment by xiongyu0523** [comment]
@dcgaws Thanks for your support. 

Follow your suggestions I think I need go for JITR to get full control of the flow. 
Another special thing is my device certificate is valid for only 24 hours, if when I connect with IoT core using a long connection like MQTT, what happens when 24 hour limit is arrived. Will server actively disconnect device?

**Comment by dcgaws** [comment]
No, the server will not disconnect the device in that situation. Certificate time validity is only evaluated during the connection attempt. However, please keep in mind that any other network hiccup during that time could cause the connection to be dropped. Therefore, I suggest that you implement your firmware in such a way that it handles unexpected disconnects and will gracefully retry.

**Comment by xiongyu0523** [comment]
Thanks all. I think we can close this ticket.
