### ISSUE TITLE
Garbage data in the requestBuffer

### ISSUE THREAD

**Issue by techguyzz** [aws/aws-iot-device-sdk-embedded-C#636]
Hi 

While checking the function aws_iot_jobs_json_serialize_update_job_execution_request() in the file src/aws_iot_jobs_json.c.
Input argument 

> > char *request buffer

received in the function has garbage data which makes the Unit test fails in some cases.

**Comment by lundinc2** [comment]
Hello @techguyzz,

Thank you again for bringing this issue to our attention. As this issue is very similar to issue #637, I will close this issue and track this problem in https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/637.
