### ISSUE TITLE
How to Cross Compile AWS client code and still make  AWS_IOT_MY_THING_NAME dynamic

### ISSUE THREAD

**Issue by mishradk** [aws/aws-iot-device-sdk-embedded-C#64]
Hello All,
I have one embedded device whose software is cross compiled.
The same firmware is put in all the embedded devices which are on field.

I differentiate the devices based on Device Serial Number. And expect my AWS thing to be created based on the device serial number.
Now Below are my issues. 
1.	I cannot put AWS CLI in my embedded device. My device has very minimal software which does not support AWS CLI to run there.
2.	I looked at the aws-iot-device-sdk-embedded-C and I have already ported the SDK for our gateway. (To the cross compile environment)  
I cross compile the AWS client application code. And in the provided examples in aws-iot-device-sdk-embedded-C it is expected that AWS_IOT_MQTT_HOST,  AWS_IOT_MQTT_PORT ,  AWS_IOT_MQTT_CLIENT_ID ,  AWS_IOT_MY_THING_NAME ,  AWS_IOT_ROOT_CA_FILENAME , AWS_IOT_CERTIFICATE_FILENAME,   AWS_IOT_PRIVATE_KEY_FILENAME  to be available during compile time. 
Whereas I expect those to be dynamic. So that based on our device , we create those things and establish the communication. We are interested in using JITR method for registering our device. 

Hope I am able to explain you my situation.
If anyone can get some quick info on how to get this things done, It will be a great help. I am stuck at this point from quite a long time. 
Regards
MishraDK

**Comment by chaurah** [comment]
Hi @mishradk,
     As I understand, you are trying to have dynamic initialization of configuration. The parameters you have mentioned above are only required by the samples. That is to make it easy for people to get those parameters from the console by simply copying and pasting a block of text. They are all dynamically passed to the client instance when it is created. You can find code for that in the sample beginning [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/samples/linux/subscribe_publish_sample/subscribe_publish_sample.c#L154).

Please let me know if you have further questions.

Rahul

**Comment by mishradk** [comment]
Thank you Rahul for the info. I think this will help me in passing the arguments dynamically. 
I have one more question which is linked with the above problem. 

I also want to dynamically create the Things similar to JITR. 
But in JITR example I observed that aws cli is used. Can I achieve the same using the C SDK ? 

My intention is to create the things initiated from embedded IOT device during runtime without using aws cli based interface. 

I highly appreciate your suggestion and help in this.  
Regards
MishraDK

**Comment by chaurah** [comment]
Hi @mishradk,
    Unfortunately, this is the AWS IoT Device SDK and is data plane only. It has no APIs for performing Control plane operations. Creating a thing is a control plane operation. To get control plane APIs you would have to use the AWS SDKs. Would it be possible for you to use C++11 instead of C?

Rahul

**Comment by mishradk** [comment]
Thank you @chaurah Rahul for your reply. 

I may not be able to use C++ 11 .. But is there any option available if I use C++ 11 ?

As I see in the post https://aws.amazon.com/blogs/mobile/use-your-own-certificate-with-aws-iot/ and https://aws.amazon.com/about-aws/whats-new/2016/08/aws-iot-announces-support-for-just-in-time-registration-of-device-certificates/ aws cli is used. 

I just want to avoid that and do that with some API calling using some library from AWS. or if some info is provided I may write that application my self. 
 
Could you be kind enough to tell me what is the basic requirement for running aws cli ?
Thanks and best regards.
MishraDK

**Comment by chaurah** [comment]
Hi @mishradk,
     If you can use C++, we have the AWS C++ SDK located [here](https://github.com/aws/aws-sdk-cpp) which provides control plane APIs. We also have the AWS IoT Device SDK for C++ which is for data plane operations located [here](https://github.com/aws/aws-iot-device-sdk-cpp).

As for running the AWS CLI, that depends on what device you are using. From the description in your first post, I am assuming its not going to be as simple as doing a pip install. You can find the CLI on github [here](https://github.com/aws/aws-cli). Could you please see if it is possible for you to directly use it? If not, we can work through where you are stuck or even ask questions on their github repo and get further help from there.

Please let me know if this unblocks you or if you are facing any further issues.

Rahul
