### ISSUE TITLE
Support MQTT username/password authentication

### ISSUE THREAD

**Issue by dcgaws** [aws/aws-iot-device-sdk-embedded-C#641]
Customers are requesting Embedded C SDK support for existing devices that use username and password to authenticate to their MQTT broker. That capability is part of the MQTT open standard. Related, there is an IANA-standardized protocol name, "mqtt", that should be used as an ALPN extension for TLS when negotiating the above.

**Comment by gordonwang0** [comment]
Completed with merged PR.
