### ISSUE TITLE
Strange behavior after publishing of big message

### ISSUE THREAD

**Issue by celsium** [aws/aws-iot-device-sdk-embedded-C#65]
Hello guys!
After publishing a big message (json, ~4 kb), I can not receive any message. SDK does not report any error, connection is ON and yield done with no errors. This happens only on Dragino (OpenWrt, big endian) device. On ubuntu x86 works as expected. I did cross compilation with "-DREVERSED" flag. Also "O2" optimization flag removed from CMakeLists.txt file on mbedtls library.
Buffer constants on my aws_iot_config.h are
#define AWS_IOT_MQTT_TX_BUF_LEN 1048576 
#define AWS_IOT_MQTT_RX_BUF_LEN 1048576

**Comment by chaurah** [comment]
Hi @celsium,
     I would need to see trace logs to determine exactly where you are getting the issue. However, there are two thing you can check for. The first one is that you can enable cloudwatch logs in your AWS IoT Console dashboard. This would let you see server side logs for your devices and may be able to tell you why the messages were not delivered as expected. A second problem could be that you are running into the default MbedTLS buffer size limit. It is defined as 16KB by [default](https://tls.mbed.org/api/ssl_8h.html#a4a5b73bae4d762a05684812ad6c6b1b2). You can modify it either in the MbedTLS ssl.h file directly or in the MbedTLS config.h file.

Please let me know if this helps. Thank you for using AWS IoT.

Rahul
