### ISSUE TITLE
[AWS][JITP] is there a JITP demo on linux?

### ISSUE THREAD

**Issue by ustccw** [aws/aws-iot-device-sdk-embedded-C#670]
i am not sure this repo has a AWS JITP service.
would aws engineers please help to give any ideas?

**Comment by abhidixi11** [comment]
Hello ustccw,
Thanks for the question. This repo is CSDK , the client side and does not have JITP service code. Although you should able to follow JITP instructions and use this code.
https://docs.aws.amazon.com/iot/latest/developerguide/jit-provisioning.html
Thanks.

**Comment by ustccw** [comment]
@abhidixi11 thanks for your information. it looks good.
