### ISSUE TITLE
Hardcoded value instead of Enum

### ISSUE THREAD

**Issue by techguyzz** [aws/aws-iot-device-sdk-embedded-C#671]
Hi,

In the file https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_mqtt_client_connect.c Line 530 value "0" is hard coded instead of enum "SUCCESS". 

This caused issue when I tried to alter enum value in header file 
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/include/aws_iot_error.h

**Comment by dan4thewin** [comment]
Hi, @techguyzz .
I'd like to understand better what change you were trying to make to the header file.  Would you please explain.

**Comment by techguyzz** [comment]
Hi Dan,

If I change the enum value of SUCCESS =0 to SUCCESS=10 in the file https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/include/aws_iot_error.h Line 54, then the condition check in the file https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_mqtt_client_connect.c Line 530 will fail.

Reason for Changing default enum Header file:
This happened because, my compiler showed warning on using negative values in the enum declaration. So I changed the enum values all positive with custom values.

**Comment by dan4thewin** [comment]
@techguyzz , can I ask you to try our v4 beta branch?

**Comment by techguyzz** [comment]
Hi Dan,

I already fixed the issue by replacing it with proper enum "SUCCESS" and I just reported for current version.

**Comment by dan4thewin** [comment]
I've submitted PR https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/680 with your fix.  Thank you.
