### ISSUE TITLE
Error Linking iot_demo_mqtt [SDK_v4.0]

### ISSUE THREAD

**Issue by stephendpmurphy** [aws/aws-iot-device-sdk-embedded-C#678]
**SDK VERSION:** v4.0
**COMMIT:** 5b0ea3893f2beea29e6a6dc8c382b625b0dd183d

**Desc:** I am getting an error when running "make all", which occurs during the linking of the iot_demo_mqtt

> Scanning dependencies of target iot_demo_mqtt
[ 88%] Building C object demos/CMakeFiles/iot_demo_mqtt.dir/src/iot_demo_mqtt.c.o
[ 89%] Building C object demos/CMakeFiles/iot_demo_mqtt.dir/app/iot_demo.c.o
[ 90%] Building C object demos/CMakeFiles/iot_demo_mqtt.dir/app/iot_demo_arguments.c.o
[ 91%] Linking C executable ../output/bin/iot_demo_mqtt
/opt/poky-atmel/2.6.3/sysroots/x86_64-pokysdk-linux/usr/libexec/arm-poky-linux-gnueabi/gcc/arm-poky-linux-gnueabi/8.2.0/real-ld: warning: libmbedtls.so, needed by ../output/lib/libiotbase.so, not found (try using -rpath or -rpath-link)

The mbedtls lib is in fact being recognized as "needed" and is being compiled. The .so is located in the correct spot (build/output/lib/libmbedtsl.so), however I still get the above error that it can not be found.

**Comment by gordonwang0** [comment]
Hi @stephendpmurphy,

Could you try building static libraries by passing `-DBUILD_SHARED_LIBS=OFF` to CMake and doing a clean build?  I have seen some toolchains have problems linking shared libraries.

**Comment by stephendpmurphy** [comment]
@gordonwang0 that resolved the issue. Thanks for the quick response!
