### ISSUE TITLE
String parsing issue

### ISSUE THREAD

**Issue by Borschtsch** [aws/aws-iot-device-sdk-embedded-C#68]
Hello,

Function parseStringValue() may overwrite other device variables/data due to the lack of the buffer size check when parsing strings in json file.

	IoT_Error_t parseStringValue(char *buf, const char *jsonString, jsmntok_t *token) {
		uint16_t size = 0;
		if(token->type != JSMN_STRING) {
			IOT_WARN("Token was not a string.");
			return JSON_PARSE_ERROR;
		}
		size = (uint16_t) (token->end - token->start);
		memcpy(buf, jsonString + token->start, size);  // Buffer may be smaller than the actual data
		buf[size] = '\0';
		return SUCCESS;
	}

There is no knowledge of the buffer size before doing the mem copy. Json string may become big enough to overwrite whatever data is allocated next to the buffer. The function should have a knowledge of a buffer size to adjust amount of data copied to it.

I know that current SDK release does not parse string values due to the overlook. However, this could be getting come back in the new release and needs to be fixed.

Thanks,
-Dmitry

**Comment by chaurah** [comment]
Hi @Borschtsch,
      Thank you for pointing this out. We already have an improved version of the Json Parser ready for the next SDK release. That includes fixes for issues like this. I will update and close this issue when the next release is out.
Please do let us know if you have any further suggestions. Thank you for using AWS IoT.

Rahul

**Comment by Borschtsch** [comment]
Hi @chaurah ,

Thanks for the answer!
Are you saying you are going to get rid of a jsmn parser? I was about to complain that it brings a lot of overhead (RAM consumption) in case of a big Shadow. Would you parser natively support arrays and objects?

Thanks!
-Dmitry

**Comment by chaurah** [comment]
Hi @Borschtsch,
   Unfortunately, there's no way to completely remove the parser short of defining some sort of fixed ture and length API for parsing shadows. We are working on a few different ideas. I can't comment on exactly what we will end up with at this moment. But if you have any specific suggestions I will be happy to include them in our internal discussions.

Rahul

**Comment by Borschtsch** [comment]
Hi @chaurah,
I do have some ideas, but they are pretty radical.

First of all, the jsonStruct already has all the necessary information to parse JSON containing only primitive JSON types - it has key, value type (which also defines a size, except for string). This is enough to parse the JSON and directly feed the associated parameters with data from it, without need of the intermediate parser. 
Also, AWS uses jsmn to verify if a JSON Shadow is malformed before sending it to AWS. This is not needed, as your team tests the library that it correctly handles all the data types correctly and created file is correctly formed. Getting rid of jsmn will save CPU power when parsing the file and when sending the Shadow update. This is important for the battery powered devices when most of the time they need to sleep.

Second, the AWS library only suggests to use aws_iot_shadow_add_reported() to add static list of parameters to a "reported" section. In practice, to save the bandwidth at the runtime we only need to report parameters which values have changed, and it is better to supply either an array of updated parameters or add individual parameters. For the wireless devices, like the ones that use GSM modems, the less time spend in transmission, the more battery power we save to last longer.

The last, but not the least. Imagine a Thing Shadow that besides other parameters needs to receive in Shadow update 20 geozones with 20 points (lat, lon) and a geozone type. Just this gives you more than 800 tokens stored in RAM if you are using jsmn parser to build a json tree. Each token (unpacked) is 14 bytes size, which consumes more than 11 kB of RAM just to hold this json tree. AWS itself consumes a LOT of RAM when one needs to send/receive big Shadows. For the device with limited resources this is a very significant issue.

However, the AWS library does not support arrays and structures. To get the most benefit of library, my implementation is combining all three ideas - get rid of jsmn as a parser, add support of arrays and structures, report only parameters that actually have been updated. 
jsmn is naturally not needed at all, when the layout of each element in JSON Shadow is known and fully described. All you need to do is to follow the JSON text file, find a key, find correspondent jsonStruct instance and parse the key value in accordance to the type defined in jsonStruct.
To add the support of the arrays and structures you do not need really much - jsonStruct has to be turned into the single linked list element, with two extra fields 'numElements' and 'size'.
numElements will give you the knowledge of how big the array is or how many fields in the structure.
size - gives you the size of the parameter which helps to solve issues like the one that started this discussion.

	/**
	 * @brief This is the struct form of a JSON Key value pair
	 */
	struct jsonStruct {
		const char *pKey; ///< JSON key
		void *pData; ///< pointer to the data (JSON value)
		JsonPrimitiveType type; ///< type of JSON
		jsonStructCallback_t cb; ///< callback to be executed on receiving the Key value pair
		jsonStruct_t *pDataStruct; ///< Layout of the parameter
        	        		///<  simple - NULL, defined by type
	                		///<  pointer to a descriptor of single array element
                 			///<  pointer to the array describing object fields
		uint16_t numElements; ///< simple parameter: 0, array: number of elements, structure: number of fields
		uint16_t size; ///< size of the shadow parameter or the element of array or structure field.
	};

This kind of layout can be defined statically with minimal RAM footprint or even in the flash with minimal or without any use of RAM.
In my case, I use several macros to simplify description of the complex parameters and place everything in the Flash (jsonStruct_t *pDataStruct is declared const in my case).

Thanks for reading :)

-Dmitry

**Comment by chaurah** [comment]
Hi @Borschtsch,
     That actually makes a lot of sense. We have something similar that we were working on as well but yours is going much farther. Might actually make sense. I will have an internal discussion about your approach as well. We have been working on ways to improve performance here for a while now. It makes sense for a json parser to be present for larger devices. There's no point in not having one if the device has enough memory to support one. That is one of the reasons why we moved up to rapidjson for C++. But for smaller devices, approaches like yours seem to be the way to go.

Thank you for this suggestion. Please keep them coming. I know we have been slow in doing C SDK releases but your suggestions are always valuable.

Rahul

**Comment by Borschtsch** [comment]
Hi @chaurah,
If you are interested, I might have some code in a separate branch here on GitHub for the reference.

-Dmitry

**Comment by chaurah** [comment]
Hi @Borschtsch,
     That would be great. If you would prefer to create a pull request, I would be happy to make sure you get proper credit for your suggestions too.


Rahul

**Comment by gustavomassa** [comment]
@Borschtsch 

I really liked your solution, I'm using a ESP8266, after the TLS Handshake I just have about 7kb of free heap memory, so it really needs to be improved as you pointed above.
Would you mind sharing your code with me?

Thank you,
Regards

**Comment by Borschtsch** [comment]
@gustavomassa 

I cannot share the whole solution right now. The code is a part of a commercial application and I cannot act on my own. But our company does have plans to share our version of AWS IoT SDK. Unfortunately I cannot tell when this will happen.

Our solution is based on my version of JSON traversal tool that can substitute the jsmn parser in SDK, but you can only get the real benefit if 1) you need objects and arrays support 2) you have to store a lot of data in it (our device stores hundreds of values in the two shadows). The tool is called jett and you can get it here - [https://github.com/Borschtsch/jett](https://github.com/Borschtsch/jett). 
The jett completely eliminates the need to store JSON file metadata and SDK can be pretty easily adopted to use jett instead of jsmn. I can provide couple code snippets if you would like. 

However, even without the full-featured low-ram SDK I can recommend on how to optimize the memory consumption of your application. It all depends on how many and which objects you need to store in the device shadow file. The more parameters (fields, structures, array values) you need to store the bigger RX buffer is required - the reason is that when you report these values to the server the server confirmation from /accepted topic will contain confirmation from server that values were accepted and it will also attach the timestamp of each value into this response. This will double or triple the requirements for the RX memory buffer. 
SDK is using accepted to track Shadow version and make sure the values sent are actually accepted by the server.
One of the ways is not to subscribe to the /accepted topic and rely on the /rejected one - if you do not have anything in it, you are good, but this will require updating SDK for sure and makes it less reliable.
Better way to do is to trim the /accepted message by republishing this message to another topic (and subscribe to it) but with metadata and shadow state completely removed (SDK only uses shadow version to track it).
[Here is the instruction to do such thing](http://docs.aws.amazon.com/iot/latest/developerguide/using-thing-shadows.html#thing-shadow-trim-messages).

However, we found (also I can see similar complains on forums) that AWS does not always republishes the message to another topic - success rate is about 50% or something like that, which is a bummer.
@chaurah can you comment on this please? We would really want to have message republish work all the time :)

Regards

**Comment by Borschtsch** [comment]
Hi @hedeshianaws 
In my last message I asked @chaurah if he can comment on the issue we (and others also) experience with message republish. He seems not active here anymore, so maybe you can provide any feedback on this, please?

Thanks,
