### ISSUE TITLE
Fix for broken deleteActionHandler in shadow API

### ISSUE THREAD

**Issue by johnhopwood** [aws/aws-iot-device-sdk-embedded-C#69]
The deleteActionHandler mechanism does not invoke the callback when shadows are deleted. To fix, make the `deleteAcceptedTopic` buffer static in `aws_iot_shadow.c`:

`static char deleteAcceptedTopic[MAX_SHADOW_TOPIC_LENGTH_BYTES];`

Currently, the handler is not found by `_aws_iot_mqtt_internal_deliver_message` b/c the topic was created on the stack.

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_shadow.c#L92

**Comment by chaurah** [comment]
Hi @johnhopwood,
   Thank you for pointing this out. I have added a bugfix to our list of tasks for the next SDK release. I will update this issue and close when the release is out.
Please do let us know if you find any more issues with the SDK or have any further suggestions. Thank you for using AWS IoT.

Rahul
