### ISSUE TITLE
Sometimes cannot connect to AWS -STM32F7 - AWS IoT SDK Version 3.0.1

### ISSUE THREAD

**Issue by gbarac** [aws/aws-iot-device-sdk-embedded-C#692]
Sometimes connecting to AWS with my STM32F7 with AWS IoT SDK Version 3.0.1 I receive this error.
(Error -22 it's the error NET_ERROR_DISCONNECTED              -22  /*!< Connection dropped during the operation. */ )

```
ERROR: ../Lib/STM32_Connect_Library/services/net_mbedtls.c:468 mbedtls_net_recv() : error -22 in recv() - requestedLen=5
0x2000baa0 => ../Lib/MbedTLSLib/src/ssl_tls.c:3956: mbedtls_ssl_fetch_input() returned -27648 (-0x6c00)
0x2000baa0 => ../Lib/MbedTLSLib/src/ssl_tls.c:3820: mbedtls_ssl_read_record_layer() returned -27648 (-0x6c00)
0x2000baa0 => ../Lib/MbedTLSLib/src/ssl_tls.c:4783: mbedtls_ssl_read_record() returned -27648 (-0x6c00)
ERROR: ../Lib/STM32_Connect_Library/services/net_mbedtls.c:302  failed
  ! mbedtls_ssl_handshake returned -0x6c00
ERROR: iot_tls_connect L#130 Could not open the socket at adjhr9mynboqd-ats.iot.eu-central-1.amazonaws.com port 8883.
ERROR: ../Lib/STM32_Connect_Library/core/net_socket.c:681 Invalid socket.
ERROR: iot_tls_disconnect L#240 net_closesocket() failed.
```

Or this error
```
ERROR: ../Lib/STM32_Connect_Library/core/net_socket.c:354 Connection cannot be established.
ERROR: iot_tls_connect L#130 Could not open the socket at adjhr9mynboqd-ats.iot.eu-central-1.amazonaws.com port 8883.
```
I'm connected to ther internet with a stable LAN connection.
Trying loggin in 10 times, only 6-7 succeded, the other 3-4 fails with such kind of errors. When the connection is successfull could be also the third attempt.

I've try to rise the SSLREAD_TIMEOUT from 10 to 20 seconds but nothing changes.
What can I try?
Kind regards

**Comment by gordonwang0** [comment]
Hello,

The mbed TLS error you are receiving `-0x6c00` is `MBEDTLS_ERR_SSL_INTERNAL_ERROR: Internal error (eg, unexpected failure in lower-level module`.

Perhaps there is something wrong with the STM32 port?  Unfortunately, I'm unable to tell you more since I'm not familiar with it.

**Comment by dcgaws** [comment]
@gbarac hello here are some things you can investigate.

First, TCP port 8883 is more likely to be blocked than port 443. Anecdotal experience has shown that such traffic blocking can happen on your corporate LAN and/or by your ISP. AWS IoT allows you to send native traffic over 443, but only if you use an ALPN option (i.e. as defined by the TLS standard). For an example of setting the latter with mbedTLS, please see https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/ports/common/src/iot_network_mbedtls.c#L591. The protocol name you want to use is "x-amzn-mqtt-ca", per https://aws.amazon.com/blogs/iot/mqtt-with-tls-client-authentication-on-port-443-why-it-is-useful-and-how-it-works/. 

Second, just to confirm, mbedTLS offers verbose/debug level logging output. Per the output you pasted above, it looks like you may already be using that, though.

Third, if you're using the developer board that offers both Ethernet and Wi-Fi, it would be interesting to check if you observe different results based on network media type. Regarding Wi-Fi, we have observed that signal strength to your AP can have a bigger impact than expected when using IoT dev boards.

Fourth, you can take a network sniff to capture one of the failed connections. Obviously, this tends to be easier with Ethernet than with Wi-Fi.

Fifth, depending on how your firmware is performing the connection loop you mentioned, you may not be allowing the underlying driver (and/or radio firmware) sufficient time to disconnect.

**Comment by aggarg** [comment]
To add to the network capture for WiFi - the way I have done it in the past is:

* Start a WiFi hotspot on your laptop.
* Connect your micro-controller to the above AP. 
* Start Wireshark on your laptop and capture the traffic. A capture filter (device IP or destination port) can be applied to only capture the traffic of interest.

Thanks.

**Comment by gordonwang0** [comment]
Hello @gbarac,

Please let us know if you need any more assistance with this.  Closing issue.
