### ISSUE TITLE
Race condition with accepted/delta publish messages

### ISSUE THREAD

**Issue by Borschtsch** [aws/aws-iot-device-sdk-embedded-C#70]
Hello,

Many times I had a situation when device was receiving 'delta' message and library was complaining that data received in 'delta' JSON file is older than one that device owns and thus, device ignored the delta. I know that I can set the flag to disable this check, but it seems like this either a server problem or issue on the library side.
The shadow version number in library is always updated from the 'accepted' JSON (which could have the same content as the device just reported).

	if(isAckForMyThingName(topicName)) {
		uint32_t tempVersionNumber = 0;
		if(extractVersionNumber(shadowRxBuf, pJsonHandler, tokenCount, &tempVersionNumber)) {
			if(tempVersionNumber > shadowJsonVersionNum) {
				shadowJsonVersionNum = tempVersionNumber;
			}
		}
	}

But when delta comes after it, it will be ignored if version check is enabled.
I wonder, since the 'accepted' not necessarily has a new data (just a version of a reported values), is it right to send newer version of shadow file in the 'accepted' message at all? Or maybe library should only update internal shadow version when we only receive 'delta'?
What is the use case to update shadow version from 'accepted' message? 

Thanks!
-Dmitry

**Comment by chaurah** [comment]
Hi @Borschtsch,
      We are actually working on fixing this issue which is a sync issue on the SDK side. We had some issues with properly syncing both the messages and we are trying to implement a proper interface for shadows which also addresses some of the other issues that you and others have raised. Apologies for the exact same response as the other thread, but we are definitely going to have a much better version of the API for using shadows in the next release.

All of that being said. Your suggestions make sense. What we have been trying to do is standardize on a method where the json update itself is always received in the delta request but the accepted request still gets used properly to record a succesful update. This should serve both purposes but we want to test it for a large number of use cases before we commit to anything. If you have some specific cases you want to make sure we address, please do let us know.

As always, looking forward to hearing your suggestions.

Rahul
