### ISSUE TITLE
Unhandled race condition in _IotMqtt_ProcessKeepAlive

### ISSUE THREAD

**Issue by dcgaws** [aws/aws-iot-device-sdk-embedded-C#716]
Per https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/700#discussion_r363508505, there is a pre-existing issue in that block of code. The issue is that the Atomic_CompareAndSwap_u32 call and subsequent assert are assuming that the device hasn’t yet received a response to the ping sent on https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/700/files/cd668d2e6221284f3cb27b90e8ab23fdea2d0cf3#diff-f3611134e9ebdc90a7d08fccb3f96c64R348. However, network operations are asynchronous (i.e. which is why locking is being used for that context flag in the first place). It is therefore possible that the app thread was interrupted after sending the ping and that the server response was already received. In that case, when the app thread is running again, the logic following the atomic operation is making a false assumption. Specifically, the proper follow-up is keep-alive time, not response wait time.

**Comment by yanjos-dev** [comment]
I'm closing this issue because we are tracking it internally.
