### ISSUE TITLE
Is yield required if just publishing?

### ISSUE THREAD

**Issue by js1972** [aws/aws-iot-device-sdk-embedded-C#719]
I want to simply publish messages to a topic and nothing else. Is it necessary to call the yield function as well?
All the samples are combined publish and subscribe. I'm not sure if "not" calling yield occasionally will cause issues with the connection dropping?
Not sure if this is the write place for general questions - but I'm not sure where else? ;-)

**Comment by sarenameas** [comment]
Hello js1972,

It is necessary to call the yield function, aws_iot_mqtt_yield(), every so often to send MQTT Keep Alive messages. As you may already know, the keep alive messages are needed for keeping the connection from dropping.

**Comment by js1972** [comment]
Thankyou @sarenameas .

As my program calls publish when an event happens - in a separate thread - where and how often is it best to call yield. I'm only publishing and not interested in receiving any data, so I I have the connection setup with a keep alive of 600 seconds, I guess I could call yield at least once every 600 seconds at a minimum to keep the connection perpetually alive...
Would you just setup a timer in man() to call yield for this?

Is their a forum dedicated to the C SDK where we can ask questions like this that are not actual bugs/issues?

**Comment by sarenameas** [comment]
Hello js1972,

It is best to call aws_iot_mqtt_yield() in the same thread that is publishing and yes you will want to call it at a repeated interval of less than 600 seconds as noted in the API documentation: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/include/aws_iot_mqtt_client_interface.h#L178. If performance of your application allows, you may want to call it after every publish to make things easier. 

This is the main page for CSDK inquiries. You can also post in the Amazon FreeRTOS AWS forum: https://forums.aws.amazon.com/forum.jspa?forumID=276&start=0, but for CSDK specific this Github issues tab is preferred.

**Comment by js1972** [comment]
Hi sarenameas,

I have a gstreamer application that processing an incoming video stream. When certain events are detected in the video stream a recording pipeline is added to save the video to a file - this happens in a separate thread. It is in this event handler where I am publishing an IoT message.

This event handler is not long-lived so I can't keep it running with a loop to continually call yield().
I can always call yield() just the one before and/or after (you seem to be suggesting after is better?) the call to publish().

I would have to call yield in a loop (or by using a timer) from the main application thread - do you see any concerns with this?

**Comment by sarenameas** [comment]
Calling aws_iot_mqtt_yield() while a publish is going on in another thread may have issues. We recommend trying to do all your MQTT operations in the same thread for the v3 API. 

Multi-threaded operations have been more extensively tested on v4_beta. If you can switch to v4_beta that will have better results for the multi-threaded design that you desire.

**Comment by js1972** [comment]
Following this: https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/158 I have multi thread support enabled. I also read somewhere that with this enabled publishing and subscribing are thread safe; but shadow is not yet... it does seem to suggest it’s a good practice to have yield running in a separate thread. 
Let me try it out and see how it goes and I’ll update here.... if not; I’ll upgrade to the new beta version. 

If all else fails I’ll just have to setup the connection; publish one message and the disconnect each time.

**Comment by js1972** [comment]
Did some testing and without calling yield at all, it still seems to work ok.
I have the keep-alive set to 10mins when initiating the connection and have auto-reconnect enabled.
So if there is greater than ten minutes between publishes it just automatically sets up the connection again and publishes successfully.
So if the small amount of time lag for re-connection is okay then I guess this will do...

I'm yet to test running yield in a different thread to see how that goes.

**Comment by gordonwang0** [comment]
Hi @js1972,

Please let us know if you need any more help with this.  Closing issue.
