### ISSUE TITLE
Potential threading issues

### ISSUE THREAD

**Issue by Borschtsch** [aws/aws-iot-device-sdk-embedded-C#72]
Hi,

I think the library has at least two threading issues, which may not be an issue if correctly stated in the interface description ;) 
One is related to registering deltas, another one is how the delta updates are processed.
1. In multi-threaded environment different threads might register for the parameter updates they need.
If function registerJsonTokenOnDelta() is called from different threads after connection has been established, we might be issuing subscription to delta multiple times. Yes, the socket may be blocked by mutex, but we may be executing this code multiple times.

```
	if(!deltaTopicSubscribedFlag) {
		snprintf(shadowDeltaTopic, MAX_SHADOW_TOPIC_LENGTH_BYTES, "$aws/things/%s/shadow/update/delta", myThingName);
==> Thread 1 is preempted here.
		rc = aws_iot_mqtt_subscribe(pMqttClient, shadowDeltaTopic, (uint16_t) strlen(shadowDeltaTopic), QOS0,
									shadow_delta_callback, NULL);
		deltaTopicSubscribedFlag = true; <== Thread 2 has finished subscription and setting the flag which prevents multiple subscription requests after Thread 1 has already performed a check.
	}
```

The worst case here is when tokenTableIndex is getting incremented while another thread is in the middle of setting the tokenTable.

```
	tokenTable[tokenTableIndex].pKey = pStruct->pKey;
	tokenTable[tokenTableIndex].callback = pStruct->cb;
==> Thread 1 is preempted here by another thread
	tokenTable[tokenTableIndex].pStruct = pStruct;
	tokenTable[tokenTableIndex].isFree = false;
	tokenTableIndex++;  <== Thread 2 is incrementing index, Thread 1 when gain control later on and will overwrite Thread 2 entry pStruct.
```

2. Second issue is harder to resolve. Delta messages are processed withing the yield call, which is recommended (and really makes sense) to run in a separate thread or the same thread where all the AWS IoT library calls happen. And this is the problem.

shadow_delta_callback() function processes delta by directly copying data in the set of calls behind isJsonKeyMatchingAndUpdateValue()
```
	for(i = 0; i < tokenTableIndex; i++) {
		if(!tokenTable[i].isFree) {
			if(isJsonKeyMatchingAndUpdateValue(shadowRxBuf, pJsonHandler, tokenCount,
											   (jsonStruct_t *) tokenTable[i].pStruct, &dataLength, &DataPosition)) {
				if(tokenTable[i].callback != NULL) {
					tokenTable[i].callback(shadowRxBuf + DataPosition, dataLength,
										   (jsonStruct_t *) tokenTable[i].pStruct);
				}
			}
		}
	}
```

The data associated with 'delta' parameters may be statically allocated in multiple threads, however AWS IoT library will directly update this data by doing memcopy or sscanf, like it fully owns it. (As a reminder, this SDK is targeted for any kind of embedded platforms, and I am specifically talking about small devices with limited resources where dynamic allocation is not possible or prohibited.)
This problem is specific to data types which access is not atomic on the used platform (i.e. doubles and strings). There is more than that - user application may have a set of parameters which can only be updated/accessed atomically.
If jsonStruct is associated with a copy of the parameter actually used by a thread, then this sort of mitigates the problem (library has a callback which may notify the thread that new value for 'delta' parameter is available, so thread may copy new values safely), but this is not helping when we talk about atomic update/access of a set of the parameters.
If objects and arrays are supported then approach mentioned above solves the issue, because parameters may be grouped in a structure and thread will be notified only when the whole set is updated, but still we have to pay the price by allocating memory twice. If Thing Shadow is filled with data up to the limit, the memory consumption on a Thing side will be significant. Smaller devices have to suffer again :) 

To avoid that extra memory allocation, the SDK may provide a way to supply lock/unlock callback functions for the parameters that may require protection during update/access, but this only makes sense when objects and arrays are also supported with SDK.

Thanks,
-Dmitry

p.s. The very same problem may arise if a separate thread is building the Shadow with values from other threads (can be avoided if each thread is taking care only of its own Shadow parameters). However, solving problem mentioned above we all get a solution for this one also.

**Comment by chaurah** [comment]
Hi @Borschtsch,
    Thank you for pointing this out. You are correct of course and we have been working on modifying the shadow API to better support multi-threading as well. There are places where the ownership and memory allocations are not strictly defined and that causes issues like the ones you have identified. There are sync and ordering related issues as well that can arise which ideally I would like to handle at the SDK level going forward instead of burdening anyone using the SDK to handle.

I have made a note of your comments in our internal tracker. I will try to convert them into useful test cases for the updated APIs so we can directly address your concerns. As always, please do let us know if you have further suggestions.

Rahul
