### ISSUE TITLE
Get payload from MQTT Subscribe function

### ISSUE THREAD

**Issue by Preemali** [aws/aws-iot-device-sdk-embedded-C#732]
Hi,

I'm trying to create a simple mqtt client and subscribe to a particular topic. I need to take the payload(the received message) from Subscribe function. Can someone let me know how to do it?

Thank you

**Comment by gordonwang0** [comment]
Hi @Preemali

Could you clarify what you mean?  The MQTT subscribe function does not take a payload.  Messages received on MQTT subscriptions will be available on callbacks passed to subscribe.

**Comment by Preemali** [comment]
Hi @gordonwang0 

Thanks for the reply.
Yes. I'm looking for messages received from subscriptions. And I tried to get it using **IoT_Publish_Message_Params *params** in **iot_subscribe_callback_handler**. 
I'm not sure whether I can take the payload from there. However, I used the following code.

```
// Subscribing
    IOT_INFO("Subscribing...");
    rc = aws_iot_mqtt_subscribe(&client, "xxx/in/clientxxxx", 17, QOS0, iot_subscribe_callback_handler, NULL);

    if(SUCCESS != rc)
    {
        IOT_ERROR("Error subscribing : %d ", rc);
    }

    // Display PayLoad on screen
    paramsQOS0.payload = (void *) sPayload;    // Showing path to client key instead of payload string
    char * sp = &sPayload[100];
    ShowMessage(sp);
```

And as I have mentioned in comments,I got the absolute path for client key as the output.
Output: "/xxx/xxx/certs/clientxxxx.private.key"

**Comment by gordonwang0** [comment]
Hello,

The members `payload` and `payloadLen` of `IoT_Publish_Message_Params` provide the payload and payload length, respectively.

Upon receiving a message on a subscription, the function you specified (`iot_subscribe_callback_handler`) will be invoked, and you can get the payload of the received message from the members named above.

You will need to make a call to `aws_iot_mqtt_yield` in your application to process incoming messages.  Have you looked at [this example](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/samples/linux/subscribe_publish_sample/subscribe_publish_sample.c)?  It provides an application that subscribes, publishes, and receives messages.

**Comment by gordonwang0** [comment]
Hi @Preemali,

Please let me know if you need any more help with this.  Closing issue.

**Comment by qiutongs** [comment]
Hi @Preemali ,

It seems your issue has not been resolved. So I re-opened this. What does your subscribe callback handler look like?

Example: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/fc99012f242ee32e6d36102dfc7a569f4faafc79/samples/linux/subscribe_publish_sample/subscribe_publish_sample.c#L61

**Comment by Preemali** [comment]
Hi @qiutongs 

Thanks for re-opening this issue.
My subscribe callback handler look like below.

`static void iot_subscribe_callback_handler(AWS_IoT_Client *pClient, char *topicName, uint16_t topicNameLen,
									IoT_Publish_Message_Params *params, void *pData)`
`IOT_UNUSED(pData);`
`IOT_UNUSED(pClient);`
`IOT_INFO("Subscribe callback");`
`IOT_INFO("%.*s\t%.*s", topicNameLen, topicName, (int) params->payloadLen, (char *) params->payload);}`

I used the same function as in sample code. And my Subscribe function look like below.
`rc = aws_iot_mqtt_subscribe(&client, "mot/in/client2780", 17, QOS0, iot_subscribe_callback_handler, NULL);`

**Comment by qiutongs** [comment]
Which line you saw the payload has content of the path to client's private key? 
Who is the publisher? What content is publishes and you expect the subscribe to see?

**Comment by Preemali** [comment]
I used the following code to check payload.

`// Display PayLoad on screen
	paramsQOS0.payload = (void *) sPayload;       // Showing client key instead of payload string
	char * sp = &sPayload[100];
	ShowMessage(sp);`

The publisher is an AWS server and I'm the subscriber. And they will publish a json script with several key-value pairs.

**Comment by qiutongs** [comment]
Hi, thank you for providing the information but I don't understand your code. If you can share your entire code base, that would be helpful. 
I don't see where sPayload is from. 

I assume you do something similar in the following? 
```
static void iot_subscribe_callback_handler(AWS_IoT_Client *pClient, char *topicName, uint16_t topicNameLen,
									IoT_Publish_Message_Params *params, void *pData) {
        // ...
	char * sp = params->payload;
        ShowMessage(sp);
}
```

**Comment by beary** [comment]
@qiutongs
Maybe you need to read the documents about AWS IoT Core and MQTT protocol first.

**Comment by aggarg** [comment]
I notice that you are subscribing to the topic ```mot/in/client2780```. In the MQTT terminology, subscribing to a topic means that you are listening to that topic and any message published on that topic should be delivered to you. The successful subscription to a topic i.e. a successful call to ```aws_iot_mqtt_subscribe``` does not mean that any payload has been received on that
topic. Payload will only be received when someone publishes on that topic. The code below, therefore, does not seem correct:

```c
IoT_Publish_Message_Params paramsQOS0;
rc = aws_iot_mqtt_subscribe(&client, "mot/in/client2780", 17, QOS0, iot_subscribe_callback_handler, NULL);

    //aggarg - Where is this paramsQOS0 getting populated?
    // Display PayLoad on screen
    paramsQOS0.payload = (void *) sPayload; // Showing client key instead of payload string`
    char * sp = &sPayload[100];
    ShowMessage(sp);
```

When any payload is published on the topic ```mot/in/client2780```, ```iot_subscribe_callback_handler``` will be called and given your definition below, you will see the received payload in the logs:

```c
static void iot_subscribe_callback_handler( AWS_IoT_Client *pClient,
                                            char *topicName,
                                            uint16_t topicNameLen,
                                            IoT_Publish_Message_Params *params,
                                            void *pData )
{
    IOT_UNUSED(pData);
    IOT_UNUSED(pClient);
    IOT_INFO("Subscribe callback");

    //aggarg - This log statement will print the payload received.
    IOT_INFO("%.*s\t%.*s", topicNameLen, topicName, (int) params->payloadLen, (char *) params->payload);
}
```
To make it more clear, look at the following diagram:

```
Device              AWS IoT            Publisher
    |                  |                  |
    |   1. Subscribe   |                  |
    +----------------->|                  |
    |    2. SUBACK     |                  |
    |<-----------------+                  |
    |                  |                  |
    |                  |    3. Publish    |
    |                  |<-----------------+
    |                  |    4. PUBACK     |
    |                  +----------------->|
    |                  |                  |
    |    5. Publish    |                  |
    |<-----------------+                  |
    |    6. PUBACK     |                  |
    +----------------->|                  |
    |                  |                  |
```

Below are the explanations of the interactions:

1. The device subscribes to the topic ```mot/in/client2780```. No payload is exchanged.
2. The AWS IoT MQTT broker responds by saying that a successful subscription has been established - it is when ```aws_iot_mqtt_subscribe returns```. Note that no payload is exchanged yet.
3. The publisher publishes payload on the topic ```mot/in/client2780```.
4. The AWS IoT MQTT broker acknowledges that the above payload has been received.
5. The AWS IoT MQTT broker sends the payload received in step 3 to all the subscribers who have subscribed to the topic ```mot/in/client2780```. Since the device is subscribed to this topic, it gets this payload - it is when ```iot_subscribe_callback_handler``` gets called and ```params->payload``` contains the actual payload.
6. The device acknowledges the receipt of the payload to the AWS IoT MQTT broker. The library does that for you and you do not need to do it explicitly.

So in your specific scenario, you need to ensure that whosoever the publisher is, it is publishing the same content as you are receiving in the ```iot_subscribe_callback_handler```.

Hope that clarifies. 

Thanks.
