### ISSUE TITLE
SSL/TLS setup fail

### ISSUE THREAD

**Issue by seopyoon** [aws/aws-iot-device-sdk-embedded-C#74]
Hello,

I am trying to use the sdk for my bluetooth module.  And I get the following error, while trying to set up SSL/TLS.

```
AWS IoT SDK Version 2.1.1-

Connecting...
DEBUG:   iot_tls_connect L#129 
  . Seeding the random number generator...
DEBUG:   iot_tls_connect L#137   . Loading the CA root certificate ...
DEBUG:   iot_tls_connect L#143  ok (0 skipped)

DEBUG:   iot_tls_connect L#145   . Loading the client cert. and key...
DEBUG:   iot_tls_connect L#158  ok

DEBUG:   iot_tls_connect L#160   . Connecting to (my_iot).iot.ap-northeast-2.amazonaws.com/8883...
DEBUG:   iot_tls_connect L#179  ok

DEBUG:   iot_tls_connect L#181   . Setting up the SSL/TLS structure...
ERROR: iot_tls_connect L#206  failed
  ! mbedtls_ssl_setup returned -0x7f00


ERROR: aws_iot_mqtt_task L#529 Error(-4) connecting to (my_iot).iot.ap-northeast-2.amazonaws.com:8883
abort() was called at PC 0x40106e33
```
Hence rebooting... 

Please assist me in solving the issue.  Thanks a lot in advance.

**Comment by liuszeng** [comment]
Hi @seopyoon ,

Thank you very much for your interest in AWS IoT Embedded C SDK!

The error code you saw is actually from the mbedTLS indicating that the memory allocation for setting up the SSL context failed. More details can be found here:
https://tls.mbed.org/api/ssl_8h.html#af79cb539a0ee6ac20cf9c574f4c3b343
https://tls.mbed.org/api/ssl_8h.html#a701ee611f7a16a261b306466c8602177
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/70071112bd5e1c5b9f150894fafe199637b4f63a/platform/linux/mbedtls/network_mbedtls_wrapper.c#L197

A good place to start would be to check if your device is out of memory for running mbedTLS.

Thanks,
Liusu

**Comment by pramodjaiswal5** [comment]
Hi ,
Even i am getting same error.
Please help me to solve this issues.

Thanks
Pramod

**Comment by hedeshianaws** [comment]
@pramodjaiswal5 Thank you for trying AWS IoT. Please open a new issue since you are seeing a different code (-23) instead of (-4). Also since you are replying to a closed issue, it will not get picked up by our trackers.
