### ISSUE TITLE
Jobs auto-generated client token is unlikely to be unique

### ISSUE THREAD

**Issue by dcgaws** [aws/aws-iot-device-sdk-embedded-C#745]
In many scenarios, a token generated [in this way](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/da072e033916ac7b1bcc897c44622e0254cda129/libraries/aws/jobs/src/aws_iot_jobs_serialize.c#L441) will be identical across a fleet of devices (and, for a single device, across reboots).

**Comment by dan4thewin** [comment]
There are no security ramifications of the jobs clientToken.  It is merely some bytes added to a request that are reflected in the response.  The autogeneration is not present in the refactored jobs library.
