### ISSUE TITLE
connection and other callbacks and loopForever related

### ISSUE THREAD

**Issue by mishradk** [aws/aws-iot-device-sdk-embedded-C#76]
Hello all,
I have few questions. 
1. Callback related
I observed that only disconnection callback can be set with init parameters. Is it possible to create one on_connect kind of callback? And how do I know if my autoreconnect is successful so that I can start calling other APIs (ex publish / subscribe)?

2.   LoopForever
I want to manage my iot_subscribe_callback_handler in a different thread and I want the thread to remain blocked till any new messages is arrived (calling some function similar to mosquitto_loop_forever) 
Is it possible?

regards
Mishra

**Comment by chaurah** [comment]
Hi @mishradk,
1) There's no existing callback for on_connect, I will put this on our backlog and add it in if we get more requests for it. However, its a simple enough thing to add. Just add another function pointer similar to the disconnect callback and call it at the end of the Connect API code. When auto reconnect is succesful, the yield call will return with a NETWORK_RECONNECTED return code. Also, subsequent yield calls will return normally with a SUCCESS return code. Once that happens, you can start calling other APIs. Alternatively, you can simply continue calling APIs and check the return code from the API call. Not the best idea but will still work.
2) Not directly via the current SDK code. We have a better multi-threading implementation planned for the next version of the SDK, but at the moment, the thread that called yield, will be the one where the subscribe handler runs. However we don't limit what you can do with the handler either. Its perfectly fine, to simply unblock the other thread in the callback and return.

Please let me know if you have further questions. Thank you for using AWS IoT.

Rahul

**Comment by mishradk** [comment]
Hi @chaurah Thank you for your reply. I will try implementing  on_connect  and let you know.. 

By the way could you please suggest some example for last Will related sample code ? 

Best regards
Mishra

**Comment by liuszeng** [comment]
Hi @mishradk,

Thank you very much for your interest in AWS IoT Embedded C SDK.

I have the following code piece working for last will. You can check if there is any difference in your code:

        ...
        // Will config                                                                                                                                        
        IOT_INFO("Configuring last will...");
        connectParams.isWillMsgPresent = true;  // This needs to be set to true so that server will continue parsing the packet and look for last will configuration
        connectParams.will = iotMqttWillOptionsDefault; // This also configure the last will to be QoS0
        connectParams.will.pTopicName = "testCSDK/lastWill";
        connectParams.will.topicNameLen = strlen("testCSDK/lastWill");
        connectParams.will.pMessage = "This is my last will!";
        connectParams.will.msgLen = strlen("This is my last will!");
        ...

Related SDK source:
connectParams: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/70071112bd5e1c5b9f150894fafe199637b4f63a/include/aws_iot_mqtt_client.h#L139
Last Will options: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/70071112bd5e1c5b9f150894fafe199637b4f63a/include/aws_iot_mqtt_client.h#L120

And the screen shot from MQTT client in AWS IoT Console:
<img width="661" alt="screen shot 2017-02-14 at 12 06 36 pm" src="https://cloud.githubusercontent.com/assets/14796906/22946974/22c03d42-f2ae-11e6-85ba-6ab69ac350df.png">

Thanks,
Liusu

**Comment by mishradk** [comment]
Hi @liuszeng  it was quite helpful. 
I think I was adding a \0 to the end and thats why I was not able to receive the message.. 
Any way thank you for your help again.
Best Regards
Mishra
