### ISSUE TITLE
V4 Release

### ISSUE THREAD

**Issue by sanjayrd** [aws/aws-iot-device-sdk-embedded-C#764]
Hi

I'm currently building an application that uses the v4 branch of the SDK and was wondering when an official release would come out?

I'm looking for an [official release or tag](https://github.com/aws/aws-iot-device-sdk-embedded-C/releases) here that I can build off of rather than the head of the v4 branch.

Thanks,
Sanjay

**Comment by dnoal** [comment]
Discussed offline and coordinated on release planning.  Closing issue.

**Comment by eugene345** [comment]
Hi @dnoal,

May you share the information about release planning publicly, please?

Thanks,
Eugene
