### ISSUE TITLE
Hardcoded keepalive interval in shadow connect

### ISSUE THREAD

**Issue by lencia68** [aws/aws-iot-device-sdk-embedded-C#79]
In "aws_iot_shadow_connect" a hardcoded value of 10 is used for "ConnectParams.keepAliveIntervalInSec". It would be highly desirable for this to be user specified and passed via "ShadowConnectParameters_t *pParams" (similar to pMqttClientId and mqttClientIdLen).

**Comment by chaurah** [comment]
Hi @lencia68,
    Thank you for pointing this out. We are already working on this for the next release of the SDK. The MQTT Init/Connect params hardcoding will be removed for all params when shadow is being used. I will update this issue when the release is out.

Please do let us know if you have any further suggestions. Thank you for using AWS IoT.

Rahul

**Comment by pctj101** [comment]
I had to make this modification to stay connected.
https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/110

**Comment by chrismrutherford** [comment]
I have had to patch my local copy with #110.  I'm running on and STM32F7 with FreeRTOS over a GPRS link.  Are there any plans to fix this soon?
