### ISSUE TITLE
Iot device will disconnect after a period of running without any error

### ISSUE THREAD

**Issue by laoyouji007** [aws/aws-iot-device-sdk-embedded-C#798]
Hello ! My program running an daemon of subscribe_publish_sample, but sometime it will disconnect without any error. I run MQTT.fx to subscribe to wathing it's state. Do you have any suggestions ？

I subscribed to the following topics：
 @**$aws/events/presence/connected/clientId**
And get the following result:
{
  "clientId" : "xxxxxxxxxxxx",
  "timestamp" : 1581575287746,
  "eventType" : "disconnected",
  "clientInitiatedDisconnect" : false,
  "sessionIdentifier" : "346ab046-7401-4199-af1c-7ed551d8e7a7",
  "principalIdentifier" : "26d0bf97a84122fadba2078e4f76af761694aedb5de41996e188385c67ef931f",
  "disconnectReason" : "CONNECTION_LOST",
  "versionNumber" : 105
}

Thanks !

**Comment by laoyouji007** [comment]
Adding device log : 
WARN:  disconnectCallbackHandler L#479 MQTT Disconnect
Auto Reconnect is enabled, Reconnecting attempt will start now
Subscribing topic: Puppod/LambdaToDispenser/74EE2A44DFEA ...
ERROR: coa_iot_init_subscribing L#880 Error subscribing : -13

**Comment by aggarw13** [comment]
Hi @laoyouji007, we had recently rolled a fix for a disconnect handler related issue through this PR: https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/793.
Can you try with the fixed version on the master branch?

**Comment by yanjos-dev** [comment]
Since we have not heard back, I'm closing this issue. Please feel free to post a response here or open a new issue if you are still facing any problems.

**Comment by laoyouji007** [comment]
@yanjos-dev @aggarw13 
I found my code is base on the newest version of V3.0.1, which is download in December 2018. Does it mean that I use your latest program and still have this problem?
