### ISSUE TITLE
aws_iot_mqtt_yield - about the yield time in poor network

### ISSUE THREAD

**Issue by wxiangcheng** [aws/aws-iot-device-sdk-embedded-C#799]
Hi,
i'm porting this 3.0.1 SDK into our embedded board. The basic test is ok but I found some problems in poor netwrok. I used yield time=10ms in aws_iot_mqtt_yield. But I found the real read time in my driver ssl_read is about 100ms. For example, the RX buffer size i set in aws_iot_config.h is 3000bytes. When I called ssl_read(3000) the total time is about 100ms. This seems not correct compared with mqtt yield time =10ms. Is that correct or should I change any setting？
As I test with Amazon AIS, it will always read too fast and make my device in overrun state. So, what is the typical value of mqtt yield time? In poor network, what should I do? Thanks.

**Comment by aggarg** [comment]
Are you talking about the rate at which you call ```aws_iot_mqtt_yield``` or the ```timeout_ms``` parameter of the ```aws_iot_mqtt_yield``` API.

For the former, here is the recommendation from the docs:
```
 /* Yield() must be called at a rate faster than the keepalive interval.  It must also be called
 * at a rate faster than the incoming message rate as this is the only way the client receives
 * processing time to manage incoming messages.
 */
```

For the later, you need to ensure to pass a big enough value so that the MQTT client gets a chance to process PING requests and responses. Would you please try with 1000ms and see if that works?

Thanks.

**Comment by wxiangcheng** [comment]
Thanks Aggarg. Your suggestion is great. The peformance is good as I manually use time_ms=500. This proves that MQTT client got the chance to send necessary PING request or others. But the side-effect is still comming(not sure). I can observe that my driver ssl_read could not read all AUDIO data(due to poor network?). It will bring Network timeout error. Likes aws_iot_mqtt_yield  reads 3000bytes, but it can only read about 2500bytes. Does 3.0.1 SDK have some solution to handle this case? Or should I do workaournd in application layer? Any sample code can I do refer from?

**Comment by aggarg** [comment]
Just to make sure that I understand your problem correctly - You are receiving a PUBLISH message from the AWS IoT MQTT broker and the MQTT client is failing to read the complete data off the socket resulting in a timeout.

If my understanding is correct, we need to see why the network layer is timing out. Which TCP/IP stack and TLS stack are you using? Are there any debug logging available in your TCP/IP and TLS stacks? Is it possible for you to do a network capture to understand whether the data is coming correctly to the device?

Also, which hardware are you using? I ask this to see if there is a way for us to reproduce your problem at our end. 

Thanks.

**Comment by wxiangcheng** [comment]
Your understanding is right. I tried to capture the sniffer log and it can be found the packet from server is very unstable - high latency at most up to 2seconds. 

As the unstable network latency, I'm wondering if I can do some workaournd to fix it on my board. I do think this issue may be about network issue not hardware platform related.
If my local buffer is big, I can buffer more data. But I could not control the read speed -- it is in aws_iot_mqtt_yield(timeout_ms). So I ask "Can I adjust yield timeout_ms dynamically?" Is my understanding correct?
ie, if I set timeout_ms=10, that means in aws_iot_mqtt_yield, tls_read can only read data in 10ms, then it switched to other thread/tasks to handle data. If I set timeout_ms=1000ms, tls_read can read more data. As I notice in _aws_iot_mqtt_internal_yield there is while loop. If the rate to call aws_iot_mqtt_yield is fixed, the bigger timeout, the more data Device can read out. Is that right?

**Comment by aggarg** [comment]
> if I set timeout_ms=10, that means in aws_iot_mqtt_yield, tls_read can only read data in 10ms, then it switched to other thread/tasks to handle data. If I set timeout_ms=1000ms, tls_read can read more data. As I notice in _aws_iot_mqtt_internal_yield there is while loop. If the rate to call aws_iot_mqtt_yield is fixed, the bigger timeout, the more data Device can read out. Is that right?

Yes, your understanding is right. Since ```timeout_ms``` is a parameter to the ```aws_iot_mqtt_yield```, you can surely adjust it dynamically i.e. you can vary it for different calls to ```aws_iot_mqtt_yield```. Does that solve your problem?

Thanks,
Gaurav

**Comment by wxiangcheng** [comment]
My issue is not fixed yet... but this thread can be closed. Thanks again.

**Comment by aggarg** [comment]
I am sorry to hear that the issue is not fixed - I want to ensure that it gets fixed. Would it be possible for you to provide a sample which I can use to reproduce the issue at my end? Would you like to setup call to go over it?

Thanks.

**Comment by yanjos-dev** [comment]
@wxiangcheng This topic has become inactive so I'm going to close the issue. Please reopen this if you would like any further assistance.
