### ISSUE TITLE
client stuck when network changes

### ISSUE THREAD

**Issue by larsonmpdx** [aws/aws-iot-device-sdk-embedded-C#80]
- I'm running a test client inside a vm (with vmware player)
- I get it connected then change the VM's network adapter and it disconnects the test client
- when I bring the VM's network adapter back, I expect the test client to be able to reconnect.  I'm not using the auto reconnect stuff, just running an event loop and calling aws_iot_mqtt_connect() as needed
- it tries to reconnect with aws_iot_mqtt_connect() and returns "NETWORK_ALREADY_CONNECTED_ERROR"
- I run aws_iot_mqtt_disconnect() and it returns "FAILURE"

so my program ends up stuck in a state where it can't connect and can't disconnect.  What should I change to make this work?  I can create a minimal reproducer based on subscribe_publish_sample if needed

**Comment by hedeshianaws** [comment]
Thank you for your interest in AWS IoT.

I'm looking into what might be causing disconnect() to fail. When you are calling disconnect, what is the state of the adapter? In other words, between which two steps is the disconnect getting called?

1. adapter is up and has IP
2. adapter is down
3. adapter is up but no IP / DHCP pending
4. adapter is up and has IP

**Comment by larsonmpdx** [comment]
the device is running a loop, disconnect is being called every N seconds forever and the two error codes for connect/disconnect are the steady state.  so this is after 4, adapter is up and I can browse to google

it's the generic "FAILURE" return code - https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/include/aws_iot_error.h#L56

**Comment by hedeshianaws** [comment]
Looking at the SDK implementation, I have a few comments and things you can try.

aws_iot_mqtt_disconnect() tries to do a graceful disconnect by closing the session with the server. If the underlying TLS session and network layer sockets are in a bad state, then this disconnect can fail. It looks like we return that very unspecific error code in a few different places, and it would help to find out where. You could try instrumenting the SDK in the following places to see where the disconnect is failing:
- https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/include/aws_iot_mqtt_client_interface.h#L193
- https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_mqtt_client_connect.c#L526

The second thing you may want to reconsider is using the reconnect() API after the disconnect failure:
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/include/aws_iot_mqtt_client_interface.h#L193

**Comment by larsonmpdx** [comment]
you're right, it's the graceful disconnect, it's getting "FAILURE" here: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_mqtt_client_connect.c#L517

I looked at adding the reconnect() API but I want to be careful that I get the logic right.  currently I have:

start
-are we connected?
no: try to connect
&nbsp;&nbsp;&nbsp;&nbsp;connect fails: was the error "NETWORK_ALREADY_CONNECTED_ERROR"?
&nbsp;&nbsp;&nbsp;&nbsp;no: wait some time and try again at start
&nbsp;&nbsp;&nbsp;&nbsp;yes: call disconnect(), then wait some time and try again at start
yes: send messages in a loop

it sounds like you're proposing the above, plus adding a reconnect() call after a disconnect() failure.  This gets to be a bit complicated and I'm worried about making odd edge cases for myself.  Can you modify the disconnect() routine to forcefully disconnect if it can't send a packet?  Or simplify this some other way?

**Comment by larsonmpdx** [comment]
I'd like to go the other direction, I want to simplify this to just "are we connected? if no, wait with some backoff and connect.  if yes, send messages in a loop" but I got stuck on the "already connected" error.  Ideally the only APIs I'd ever call would be connect() and is_connected().

**Comment by hedeshianaws** [comment]
Were  you able to make progress with the reconnect() API? I agree that disconnect should ideally not fail.
We'll take your API feedback under advisement for the next release of the API. However, in the meantime, you can try to make the modification to the disconnect code. You could try removing that error check from line 517.

**Comment by larsonmpdx** [comment]
I haven't tried reconnect(), adding it to the decision tree above gives something like 8-10 states to think about

I'll get rid of the line 517 error and see what happens to my tests, that's a good idea

**Comment by chaurah** [comment]
Please reopen if you are still facing this issue.
