### ISSUE TITLE
Can we use this SDK in Zephyr OS

### ISSUE THREAD

**Issue by md-jamal** [aws/aws-iot-device-sdk-embedded-C#807]
Hi Guys,

I have an embedded application running on Zephyr OS

I want to push the sensor data on AWS IOT, there is no sample application for AWS in Zephyr, but there are for Azure and Google IOT.

Do you have any sample application already written for AWS or can we use this SDK in Zephyr OS

**Comment by dnoal** [comment]
Thanks for this inquiry.  If you try to accomplish this integration, we would provide support on that effort as needed.  You could choose either our V3 (GA) or V4-beta versions. We don't have any sample application available integrating our C SDK with Zephyr OS as of now.  It is absolutely intended that this SDK (AWS IoT Device SDK for Embedded C) can be used on platforms like Zephyr OS.
