### ISSUE TITLE
Memory usage and mbedtls setup

### ISSUE THREAD

**Issue by gustavomassa** [aws/aws-iot-device-sdk-embedded-C#81]
Hello,

I have some questions regarding the mbedtls setup and memory usage.

1 - What is the lowest value for the max_content_length that mbedtls can use (lowest value that the server is able to handle from the client and still have a stable connection).
2 - On the mqtt_sub_pub sample the value of SSL_READ_TIMEOUT is just 10ms, what is the lowest and highest value that can be handled?

I have some concerns about the SDK memory usage:
3 - I’m using an ESP8266 with freeRRTOS (40kb of heap available), when using the original paho embedded c client with a simple mbedtls ssl wrapper, the MQTT Task need a stack of size 2048. Although when using the aws embedded c sdk, for the same MQTT Task, it requires at least a stack of size 6000+. I haven’t tested the shadow connection yet.

I also have two questions regarding the configuration of the mqtt client:
4 - What is the correct value for the keepalive value?
5 - What is the relation of the keepalive with the yield? Normally on the MQTT Task I’ve been using 1 second for yield.

Thank you,
Best Regards

**Comment by chaurah** [comment]
Hi @gustavomassa,
Answering your questions below:
1) We haven't tested any SDK specific values. The default values used in MbedTLS is 16K, there should be no reason to not have a lower value.
2) Depends on your device. This is something that needs to be tested in your expected usage scenario.
3) There are significant implementation differences between the original paho SDK and the current version of our SDK. I agree that the stack size needs to be reduced. We are making some progress on the next release of the SDK that directly addresses the size issues.
4) Again depends on your use case. Its easy to set this to the maximum value, but you may want to test expected usage scenarios and fine tune this.
5) The yield function is where the Ping request/response processing happens. Its not ideal, but currently yield needs to be called at least once every keepalive interval duration. If the duration is exceeded and there's no ping response waiting already, the SDK will assume a disconnect and attempt to reconnect. If the duration is exceed and no other mqtt operation was performed (the server receives no messages), then the connection will be disconnected on the server side.

I know some of the answers basically say, "test it yourself". Unfortunately, there is no one right answer for a generic SDK in these cases. These numbers can be affected by everything from device performance to network configuration and need to be tested in the specific use case you have for the SDK. That being said, I will be happy to help you figure out any issues you see with particular values.
Please let me know if you have any further questions or concerns. Thank you for using AWS IoT.

Rahul

**Comment by gustavomassa** [comment]
@chaurah 

Thank you for the responses, I was able to make it work correctly, I've removed some certs debug functions and bufs to save memory.
The mbedtls max_content_lenght must be >= 3256 to be able to communicate correctly with the server, if this value is lower than 3256 then the sdk will receive an MBEDTLS_ERR_SSL_INVALID_RECORD error during the handshake.  I've realized that during the ssl_invalid_record error the sdk automatically attemps to reconnect to the server, but it seems there is a memory leak betwheen the handshake retries.
About the MQTT Task stack size, I was able to set a value of 2256 using the mbedtls max_content_lenght with value 3256. The mbedtls RAM usage seems to be about 22k.

I have new questions about the SDK:
1 - We're charged for MQTT Ping messages, therefore all the yields will be charged at least 1 message. I would like to remove the ping request from the Yield function and call it separately when needed, or the sdk should call it automatically depending on the keepAlive time.
2 - Let's say I need a real-time communication between my iot device and the aws broker, I must call Yield to receive/send all messages? If my iot device receive/send more than 1 message between Yields interval, those messages will be saved in a queue or the data will be lost?
3 - Let's say that I remove the ping requests from the Yield function, then I can use a Yield interval of 1 second, so every second my iot device will check for new messages and send pending messages to aws broker. Since the yield is not sending ping, I won't pay for any ping messages, just for the published messages, right? Also the Yield function without the ping request does not charge any messages?
4 - About the IOT Shadow, when I connect using the shadow _connect I'll be able to sub/publish normally? Or I need to instantiate a mqtt client and a shadow client separately?
5 - About the IOT Shadow, If I set a Yield interval of 5 minutes, when the AWS IOT receive an shadow state update and send it to the IOT device, the SDK will wait 5 minutes to receive the message during the Yield to update the shadow state? Or the SDK automatically triggers a callback independently of the yield?


Thank you,
Best Regards

**Comment by chaurah** [comment]
Hi @gustavomassa,
       You are correct about the server not support max_fragment_length_extension at the moment. This is something we are working on adding in the future but unfortunately there's no specific timeline on when it will be released. For your SDK questions, responses below:
1) You can find details about the limits imposed by AWS IoT [here](http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_iot). The current maximum allowed value for Keepalive is 1200 seconds.
2) Unfortunately there's no "MQTT message" queuing on the SDK side. That being said, you do not need to yield to send messages. It is a blocking SDK, and all publish requests will be immediately sent out. For receive, the SDK might not buffer any messages, but the TLS layer will. If your TLS buffer size is large enough to store all messages between yield intervals, you should be fine. I realize its not the most reliable method, but implementing queuing in the current version of the SDK was a very messy proposition. We decided that is not something that is worth releasing to customers and making things more complicated then they need to be. We are looking into adding queuing support in the next release of the SDK.

Apologies for the late response on this. Please do let me know if you have any suggestions for improvement or further questions and I will do my best to help you out. Thank you for using AWS IoT.

Rahul
