### ISSUE TITLE
Aws receive callback doesn't work

### ISSUE THREAD

**Issue by laoyouji007** [aws/aws-iot-device-sdk-embedded-C#818]
Hello !
I use "subscribe_publish_sample.c"  to run in my arm board. The premise is that I have subscribe the topics according to the process,  If I don't publish the message, wait for the IOT back-end message to arrive, and then publish the message to the IOT cloud. In this case, it's OK to send and receive data all the time. But, If I publish the message first, and then the device can't receive data any more. I think the problems may be caused by several layers of string processing functions embedded in my send function. Nesting multi-level functions in main function will affect receiving callbacks and that callback will not work. Is there any good idea for me ?

Thank you !

**Comment by leegeth** [comment]
@laoyouji007 ,
Thanks for bringing this question to our attention. Can we get some more details about the what you are trying to do? Especially answers for the below listed questions would help us more.
1. From the description, it seems like you have modified the subscribe_publish_sample.c code, is it possible for you to share the code/ code snippet highlighting the modification?
2. Have you added additional string processing functions? Can you please provide more information about that as well?

**Comment by abhidixi11** [comment]
Hey @laoyouji007 ,

I'm closing the issue. If you have any further questions feel free to re-open or create a new issue. 
Thanks!
