### ISSUE TITLE
Cannot subscribe long name topic

### ISSUE THREAD

**Issue by zxmu** [aws/aws-iot-device-sdk-embedded-C#82]
If topic name is long enough, e.g. exceeding 20 chars, no information can be subscribed. It may be a bug. This issue is critical, topics created vis SNS console, always have a long name.
By the way, Open SSL version is working well, but amazon ios-sdk pointed to this URL.

**Comment by chaurah** [comment]
Hi @zxmu,
    Can you elaborate on what error you are seeing when using topic names exceeding 20 chars? There should be no issue. Also, we don't have OpenSSL support in v2.x, you may be using an older version of the SDK.
Please let me know if you have any further questions as well. Thank you for using AWS IoT.

Rahul
