### ISSUE TITLE
Internal yield loop does not break on a success

### ISSUE THREAD

**Issue by anubhutimittal1** [aws/aws-iot-device-sdk-embedded-C#822]
'Yield' keeps looping internally until the timeout and does not break if it has already received a message or there is no message to read. This causes problems when we have already received a message and are waiting for yield to timeout to take action corresponding to the directive or send back a response in a single threaded application.

**Comment by dachalco** [comment]
HI @anubhutimittal1 

Could you please provide which version of this sdk you are using?

**Comment by anubhutimittal1** [comment]
I am using v3 (master branch commit id: 1c027cf3e9cd398c7486f1befd86b3e02d6aeaf2)

**Comment by dachalco** [comment]
Hi @anubhutimittal1 

Excellent. Thank you! I take it you're talking about `aws_iot_mqtt_yeild`? If there is a message published that is received before the yield timeout frame, then you should expect a function stack trace that looks like 
1. [`aws_iot_mqtt_yield`](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_mqtt_client_yield.c#L313)
2. [`_aws_iot_mqtt_internal_yield`](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_mqtt_client_yield.c#L217)
3. [`aws_iot_mqtt_internal_cycle_read`](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_mqtt_client_common_internal.c#L629)
4. [`_aws_iot_mqtt_internal_handle_publish`](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_mqtt_client_common_internal.c#L578)
5. [`_aws_iot_mqtt_internal_deliver_message`](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_mqtt_client_common_internal.c#L520)

Finally in function 5 you will notice that, assuming everything is nominal and no contingencies have occurred, a message handler will be called. However this assumes the message handler exists and corresponds to the topic of the received message. 

Have you subscribed to the topic of interest with `aws_iot_mqtt_subscribe` and provided a topic message handler via its `pApplicationHandler` parameter?

**Comment by anubhutimittal1** [comment]
Yes, function stack looks correct. I have subscribed to the desired topic and do receive the message through message handler to our callbacks. However the problem is, in function internal_yield, after the success of internal_cycle_read and mqtt_ping_alive functions, yield still keeps looping till the timeout: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_mqtt_client_yield.c#L250.

This causes problems in single threaded applications where the thread calling aws_iot_mqtt_yield will remain on this function till yield timer gets expired even if the subscribed message is received.

**Comment by dachalco** [comment]
I see, so there are other board tasks that need to run in the same thread AFTER the yield. 

**With auto reconnect enabled**, there is contention with how long yield time frame should be. Namely, the longer the time frame, the longer that exponential back-off reconnect attempts can occur in case of disconnect.

Decreasing AWS_IOT_MQTT_MIN_RECONNECT_WAIT_INTERVAL increases the average frequency at which reconnects are attempted. However, in some cases this could result in too high load for the server and a user may instead want to simply increase the duration of time allocated for exponential-back off reconnect attempts.

In a single threaded application, increasing blocking time of yield by _N_ seconds, allows for auto-reconnect attempts to occur for at most _N_ seconds but it also means that operations after the yield are delayed another _N_ seconds which can be problematic such as when the board is meant to service things like button presses, switches, etc. fast enough to be unnoticeable by humans. 

You could decrease the yield time _N_, but that will affect the window of time for receiving messages in one call to yield.

**With auto reconnect disabled**, it's possible to address your issue by decreasing the yield time, attending to other necessary operations, then implementing your own reconnect mechanism using `aws_iot_mqtt_is_client_connected`, `aws_iot_mqtt_reconnect`, and application timers. This way you don't have to supply enough blocking time in yield for reconnect attempts to succeed and you can interleave other board operations with your own calls to `aws_iot_mqtt_reconnect`. Please note that auto-reconnect touches other parts of the API such as publish and subscribe so calls to these would also need adjustment.



It's possible to still use auto-reconnect with small yield time, to minimize delay to other board operations, and preserve a max-time-frame for receiving messages per yield call by locally changing yield to quit early on successful `aws_iot_mqtt_internal_cycle_read`. However please note, in other cases said local modification could be troublesome as it alters timing characteristics of the application. 

As we are no longer accepting changes to c-sdk v3, I have filed a feature request for v4 to address this. Thank you for the feedback.
