### ISSUE TITLE
Updating thing shadows in different AWS regions not working

### ISSUE THREAD

**Issue by kennu** [aws/aws-iot-device-sdk-embedded-C#83]
I'm trying to connect to three different AWS regions and update a thing shadow in each of them. 

This seems to work fine at first when calling `aws_iot_shadow_init()` and `aws_iot_shadow_connect()` to create each MQTT client. But then, when calling `aws_iot_shadow_update()`, all updates are actually going to the MQTT client that was created last.

Looking at https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/8aa5c18efe9efacb28425beec8ddbb5dfdbd2fcb/src/aws_iot_shadow_records.c it seems like the library is overwriting any previous MQTT client and only keeping a reference to the latest one. Is this done on purpose?

**Comment by hedeshianaws** [comment]
This is a known design limitation with the SDK as it stands today. The C-SDK does not support multiple shadows without substantial rework. We have plans to resolve this limitation in a future release.

**Comment by kennu** [comment]
Okay thanks for confirming. I solved my need for now by splitting the application into multiple processes.

**Comment by lightgao** [comment]
is there any updates about the multiple shadows support?
