### ISSUE TITLE
AWS IoT SDK for Embedded C - OS

### ISSUE THREAD

**Issue by FabioPerrone** [aws/aws-iot-device-sdk-embedded-C#831]
Do you see any issue related with using the IoT SDK for Embedded C on devices with OpenWRT? Are there any limitations regarding the CPU architecture?

**Comment by gordonwang0** [comment]
Hi @FabioPerrone,

I don't see any limitations in porting this SDK to OpenWRT.  Please see our porting guide for an understanding of what needs to be ported.

https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/PortingGuide.md
