### ISSUE TITLE
SDK C Timer problem

### ISSUE THREAD

**Issue by fedex03** [aws/aws-iot-device-sdk-embedded-C#84]
Hi there, 
I'm using the AWS IoT SDK for C into my embedded platform (TI CC3200).
I have ported the SDK to my platform through the implementation of software modules that permits to the SDK to use socket and timers.
I'm facing with a problem regarding the timer.
I realised a software module that uses the hardware timer to built several upper counter used to compute delays. And I use this module into AWS_SDK/platform for porting the sdk to my hardware.

Basically the function void "countdown_ms( Timer *timer, uint32_t tms )", need by aws, read the counter value and store the timeout value into Timer struct.
The function "bool has_timer_expired( Timer *timer )" read the counter values, performs a difference between timeout value and counter value and return true if the timer is elapsed.

This AWS timer implementation works only if I add a printf into the above functions. If I remove the printf the timer doesn't works.

Any suggestions?

Thanks

**Comment by bxpan** [comment]
Hi fedex03, 

Could you let us know which function exactly did you have to add the printf , and what printf function did you add ?

Could you also clarify what you mean by "doesn't work" if you did not add the printf function, specifically what behavior did you see , and any error messages ? 

Thanks.

**Comment by fedex03** [comment]
Hi there,

sorry for the late reply. I used in a wrong way my timer suite. Basically I switch to sysTick to permit to AWS IoT SDK to compute the delay.

Thanks for your time
