### ISSUE TITLE
I am getting the below error during the build process of the main makefile.

### ISSUE THREAD

**Issue by kandarp24** [aws/aws-iot-device-sdk-embedded-C#847]
/home/kandarp/aws-iot-device-sdk-embedded-c/external_libs/CppUTest/src/CppUTest/MemoryLeakWarningPlugin.cpp:224:6: error: the program should also define ‘void operator delete(void*, std::size_t)’ [-Werror=sized-deallocation]
 void operator delete(void* mem) UT_NOTHROW
      ^~~~~~~~
/home/kandarp/aws-iot-device-sdk-embedded-c/external_libs/CppUTest/src/CppUTest/MemoryLeakWarningPlugin.cpp:244:6: error: the program should also define ‘void operator delete [](void*, std::size_t)’ [-Werror=sized-deallocation]
 void operator delete[](void* mem) UT_NOTHROW
      ^~~~~~~~
cc1plus: all warnings being treated as errors
src/CppUTest/CMakeFiles/CppUTest.dir/build.make:86: recipe for target 'src/CppUTest/CMakeFiles/CppUTest.dir/MemoryLeakWarningPlugin.cpp.o' failed
make[3]: *** [src/CppUTest/CMakeFiles/CppUTest.dir/MemoryLeakWarningPlugin.cpp.o] Error 1
make[3]: Leaving directory '/home/kandarp/aws-iot-device-sdk-embedded-c/external_libs/CppUTest'
CMakeFiles/Makefile2:981: recipe for target 'src/CppUTest/CMakeFiles/CppUTest.dir/all' failed
make[2]: *** [src/CppUTest/CMakeFiles/CppUTest.dir/all] Error 2
make[2]: Leaving directory '/home/kandarp/aws-iot-device-sdk-embedded-c/external_libs/CppUTest'
Makefile:140: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/kandarp/aws-iot-device-sdk-embedded-c/external_libs/CppUTest'
Makefile:117: recipe for target 'build-cpputest' failed
make: *** [build-cpputest] Error 2
my gcc version 7.5.0

**Comment by lundinc2** [comment]
Hello kandarp24,

This is an issue with CppUTest, please see this thread for the fix: https://github.com/cpputest/cpputest/issues/957.

**Comment by kandarp24** [comment]
Thanks for the reply
