### ISSUE TITLE
AWS-IOT just can send but can't receive data after runs about 15 minutes

### ISSUE THREAD

**Issue by laoyouji007** [aws/aws-iot-device-sdk-embedded-C#855]
Hi, 

     After AWS IOT runs on my board for about 15 minutes, the data on the board can be sent to the server, but the board can't receive the data from the server. Is there any good way or tool to help me to find out the problem?

Thank you !

**Comment by dan4thewin** [comment]
Hi, @laoyouji007 .  You can enable logging in the library.  I'm going to guess that you're using MQTT.  You can use a second client to observe what messages are published on your topics; the AWS console has its own client.  Many development environments permit you to single step through your code with a debugger.  Network packet captures are another way to diagnose a problem.

**Comment by laoyouji007** [comment]
@dan4thewin 
Hello, Can you tell me more about ` enable logging in the library` ?

**Comment by dan4thewin** [comment]
If you're using the master branch, I believe you can define ENABLE_IOT_DEBUG, and the other ENABLE macros visible here: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/include/aws_iot_log.h#L43

If you're using the v4 beta branch, you can read about logging here: https://docs.aws.amazon.com/freertos/latest/lib-ref/c-sdk/logging/index.html

**Comment by dcgaws** [comment]
Hello @laoyouji007 were you able to make progress with logging? Please comment and/or reopen the issue if you're still stuck. Thank you!
