### ISSUE TITLE
Callback handler is not called even a topic has been subscribed

### ISSUE THREAD

**Issue by solankigithub** [aws/aws-iot-device-sdk-embedded-C#857]
Hello,
I am not able to receive the messages on a subscribed topic. Below is the code:

```
    rc = aws_iot_mqtt_init(&client, &mqttInitParams);
    if(SUCCESS != rc) {
        ESP_LOGE(TAG, "aws_iot_mqtt_init returned error : %d ", rc);
        abort();
    }

    connectParams.keepAliveIntervalInSec = 400;
    connectParams.isCleanSession = true;
    connectParams.MQTTVersion = MQTT_3_1_1;
    /* Client ID is set in the menuconfig of the example */
    connectParams.pClientID = CONFIG_AWS_EXAMPLE_CLIENT_ID;
    connectParams.clientIDLen = (uint16_t) strlen(CONFIG_AWS_EXAMPLE_CLIENT_ID);
    connectParams.isWillMsgPresent = false;

    ESP_LOGI(TAG, "Connecting to AWS...");
    do {
        rc = aws_iot_mqtt_connect(&client, &connectParams);
        if(SUCCESS != rc) {
            ESP_LOGE(TAG, "Error(%d) connecting to %s:%d", rc, mqttInitParams.pHostURL, mqttInitParams.port);
            vTaskDelay(1000 / portTICK_RATE_MS);
        }
    } while(SUCCESS != rc);

    ESP_LOGI(TAG, "Connection Established!!!");

    rc = aws_iot_mqtt_autoreconnect_set_status(&client, true);
    if(SUCCESS != rc) {
        ESP_LOGE(TAG, "Unable to set Auto Reconnect to true - %d", rc);
        abort();
    }

    const char *SUB_TOPIC = "backmotor/in";
    const char *PUB_TOPIC = "backmotor/out";

    const int SUB_TOPIC_LEN = strlen(SUB_TOPIC);
    const int PUB_TOPIC_LEN = strlen(PUB_TOPIC);

    ESP_LOGI(TAG, "Subscribing...");
    rc = aws_iot_mqtt_subscribe(&client, SUB_TOPIC, SUB_TOPIC_LEN, QOS0, iot_subscribe_callback_handler, NULL);
    if(SUCCESS != rc) {
        ESP_LOGE(TAG, "Error subscribing : %d ", rc);
        abort();
    }
   
    ESP_LOGI(TAG, "Subscribed!!!");

    sprintf(cPayload, "%s : %d ", "hello from SDK", i);

    paramsQOS1.qos = QOS0;
    paramsQOS1.payload = (void *) cPayload;
    paramsQOS1.isRetained = 0;

    int state=false;
    while((NETWORK_ATTEMPTING_RECONNECT == rc || NETWORK_RECONNECTED == rc || SUCCESS == rc)) {


        //Max time the yield function will wait for read messages
        rc = aws_iot_mqtt_yield(&client, 200);

        if(NETWORK_ATTEMPTING_RECONNECT == rc) {
            // If the client is attempting to reconnect we will skip the rest of the loop.
            continue;
        }

        ESP_LOGI(TAG, "Stack remaining for task '%s' is %d bytes", pcTaskGetTaskName(NULL), uxTaskGetStackHighWaterMark(NULL));
        vTaskDelay(1000 / portTICK_RATE_MS);

        if (rc == MQTT_REQUEST_TIMEOUT_ERROR) {
            ESP_LOGW(TAG, "QOS1 publish ack not received.");
            rc = SUCCESS;
        }
    }

    ESP_LOGE(TAG, "An error occurred in the main loop.");
    abort();

```
Below is the handler method:

```
void iot_subscribe_callback_handler(AWS_IoT_Client *pClient, char *topicName, uint16_t topicNameLen,
                                    IoT_Publish_Message_Params *params, void *pData) {
    ESP_LOGI(TAG, "Subscribe callback");
    ESP_LOGI(TAG, "%.*s\t%.*s", topicNameLen, topicName, (int) params->payloadLen, (char *)params->payload);
}
```

I am getting a success on subscribing a topic.

Is there anything wrong with this code?
The handler method is not triggered once i send message to the subscribed topic.

**Comment by dan4thewin** [comment]
Hi, @solankigithub .  I don't see anything in the code that publishes.  Were you publishing to the topic using a separate client?

**Comment by solankigithub** [comment]
Thanks @dan4thewin 
Yes, i was publishing messages to a topic, but later i removed the code. Irrespective of whether i am publishing or not, i am not receiving the messages i've subscribed to.

Regards

**Comment by dan4thewin** [comment]
Hi, @solankigithub .  It might be useful to enable logging.  If you're using the master branch, I believe you can define ENABLE_IOT_DEBUG, and the other ENABLE macros visible here:
https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/d039f075e1cc2a2a7fc20edc6868f328d8d36b2f/include/aws_iot_log.h#L43

You may further wish to enable logging in whichever TCP stack you're using to see the packets arriving from the broker.

**Comment by solankigithub** [comment]
I did the enable the DEBUG as you suggested:

```
#define ENABLE_IOT_DEBUG 1
#include "aws_iot_config.h"
#include "aws_iot_log.h"
#include "aws_iot_version.h"
#include "aws_iot_mqtt_client_interface.h
```"

But this doesn't give me a debug message on serial monitor. Its strange !

**Comment by solankigithub** [comment]
You can check the code in the below link:
https://github.com/solankigithub/esp32-aws-iot

**Comment by solankigithub** [comment]
hi,
Can i expect some support here?

Thanks

**Comment by solankigithub** [comment]
ok i have managed to fix it.
I was not giving 
      "Effect": "Allow",
      "Action": "iot:Receive",
in the policy document.

**Comment by aws-chasejam** [comment]
> I did the enable the DEBUG as you suggested:
> 
> ```
> #define ENABLE_IOT_DEBUG 1
> #include "aws_iot_config.h"
> #include "aws_iot_log.h"
> #include "aws_iot_version.h"
> #include "aws_iot_mqtt_client_interface.h
> ```
> 
> But this doesn't give me a debug message on serial monitor. Its strange !

I added '#define ENABLE_IOT_DEBUG' per above to the top of 'AWSGreenGrassIoT.cpp' (before the #include aws_iot_log.h) and then re-wrote the macros defined in aws_iot_log.h to output to serial like 'Serial.printf()'. They mention in aws_iot_log.h that you would be expected to change the macro to the desired behavior for different hardware platforms. Perhaps other ways of doing this but that worked for me.
