### ISSUE TITLE
Is it possible to create 2 connections simultaneously

### ISSUE THREAD

**Issue by mishradk** [aws/aws-iot-device-sdk-embedded-C#86]
Hello ,
Is it possible to create two connections using the same certificates simultaneously ?
I compiled the sample programs provided and made a copy of the executable. 

I observed while running that if I run the first program it connects and then once I start the 2nd program, the first one disconnects.
Is it possible to run two concurrent connections? I really need this for my application.

Best regards
Mishra

**Comment by chaurah** [comment]
Hi @mishradk,
     You will need to use two separate MQTT client IDs. You also need to make sure that the policy that is attached to this certificate has permissions to allow both of the client IDs to connect. Once you have done that, it should be just fine to have multiple connections with the same set of certificates. We have a multiple clients integration test that can be used as a reference located [here](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/tests/integration/src/aws_iot_test_multiple_clients.c). Please let us know if you have any further questions. Thank you for using AWS IoT.

Rahul

**Comment by miaoichi** [comment]
Separate client ID is workable. I can connect to IoT for subscribe and shadow client
