### ISSUE TITLE
master: Clang Static Analyzer detected Garbage return value

### ISSUE THREAD

**Issue by vikivivi** [aws/aws-iot-device-sdk-embedded-C#882]
# Clang Static Analyzer detected Garbage return value

* Using master branch
* Clang Static Analyzer detected Garbage-return-value in src/aws_iot_mqtt_client_common_internal.c:359
  * aws_iot_mqtt_internal_send_packet() FUNC_EXIT_RC(rc)
  * Just initialize rc to known value will easily fix this issue.
* See below for procedures to setup analysis with Clang Static Analyzer.

## Install Clang v10.0.0 on Ubuntu 18.04 64bit

```sh
host$ wget -c https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
host$ sudo tar -C /opt -xJvf 'clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz'
# Create symlink
host$ sudo ln -sf clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04 /opt/clang
host$ /opt/clang/bin/clang --version
```

## Install scan-build Python module

* Install Clang's scan-build re-implementation in Python. 
* The original Clang's scan-build can't analyze well with cmake auto-generated Makefile. Often with no attempt of any analysis with auto-generated Makefile.
* Original Clang's scan-build work well with current master branch.
* Will require rizsotto's scan-build for v4_beta branch.
* More info, see https://github.com/rizsotto/scan-build

```sh
# Install 'rizsotto's scan-build' Python module
host$ pip install --upgrade --user scan-build
```

## Build aws-iot-device-sdk-embedded-C (master branch) with clang

* Using mbedtls-2.16.6.tar.gz

```sh
host$ cd aws-iot-device-sdk-embedded-C
# Checking the current commit hash
host$ git rev-parse HEAD
9688f5eff8546ee5e68c7b5549d2498df20d96a3
host$ echo $SHELL
/bin/bash

# Ensure clang found in PATH
host$ export PATH=$PATH:/opt/clang/bin
host$ command -v clang

# Ensure demo applicattion can be build using clang
host$ cd samples/linux/subscribe_publish_sample/
host$ make CC=clang DEBUG="" clean all
```

## Perform Clang Static Analyzer using Clang's scan-build

```sh
# Use Clang's scan-build
host$ /opt/clang/bin/scan-build -analyze-headers -maxloop 15 -o ./static-analysis --use-cc /opt/clang/bin/clang make CC=clang clean all

# Check and run scan-view printed on the last line of analyze-build
host$ scan-view ./static-analysis/2020-04-20-183618-3311-1

# Or use browser to view static analyzer report
host$ firefox ./static-analysis/2020-04-20-183618-3311-1/index.html
```

## Perform Clang Static Analyzer using rizsotto's scan-build

```sh
# Ensure Python scan-build is in PATH and executed. Not Clang's scan-build
host$ command -v scan-build
/home/user/.local/bin/scan-build

# Generate compilation database file
host$ make clean
host$ intercept-build make CC=clang all

# analyze-build required compilation database file
host$ cat compile_commands.json
host$ analyze-build -v -o ./static-analysis --keep-empty --analyze-headers --maxloop 15

# Use scan-view or browser to view static analyzer report
host$ firefox ./static-analysis/scan-build-2020-04-20-18-56-54-479620-2zs1ve0b/index.html
```

**Comment by aggarg** [comment]
Thank you for reporting these issues. The following PR addresses these: https://github.com/aws/aws-iot-device-sdk-embedded-C/pull/895.

**Comment by aggarg** [comment]
I am closing this issue. Please re-open or create a new one in case you have any further question.

Thanks.
