### ISSUE TITLE
GET response parser

### ISSUE THREAD

**Issue by eugene345** [aws/aws-iot-device-sdk-embedded-C#92]
There is aws_iot_shadow_get() to request the latest state. But does SDK parse the response? Looks like it doesn't. Or I just can't find it...
The Device Shadow persists the device state and configuration. So, I think, getting latest state at device boot up has to be implemented completely.

**Comment by chaurah** [comment]
Hi @eugene345,
     Thank you for pointing this out as an issue. We are already working on improving the design of the shadow APIs in the next release of the SDK. We will try to make sure it is easy for everyone to parse the received json strings on shadow APIs.

Please do let us know about any other issues you have faced.

Rahul

**Comment by eugene345** [comment]
Hi @gordonwang0 ,

Please, re-open the issue. This feature is still important.

**Comment by swansolutionsllc** [comment]
@gordonwang0  thanks for re-opening the issue.  Any updates on this?

**Comment by gordonwang0** [comment]
Hi @swansolutionsllc,

Sorry, I don't have any updates on this.  I am unable to share our roadmap for this SDK publicly.

**Comment by dcgaws** [comment]
Hello @swansolutionsllc and @eugene345 please check out our SDK v4 Beta. Per https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/libraries/aws/shadow/src/aws_iot_shadow_parser.c, we have a supplied a purpose-built parser that is suitable for "shallow" shadow documents. 

More complex shadows will require the use of a third-party parser library.
