### ISSUE TITLE
Using SUCCESS constant

### ISSUE THREAD

**Issue by eugene345** [aws/aws-iot-device-sdk-embedded-C#93]
Hello,

Please, don't use SUCCESS constant, if possible. It is already used in the standard header file for STM32F4 microcontrollers (stm32f4xx.h):

`typedef enum 
{
  ERROR = 0U, 
  SUCCESS = !ERROR
} ErrorStatus;`

Best regards,
Eugene.

**Comment by hedeshianaws** [comment]
Hello,

Thank you for pointing this out. We have an action item to clean up multiple name-space conflicts in the next release. We'll make sure this one get addressed as well.

**Comment by tim-nordell-nimbelink** [comment]
Note: This is a duplicate of #39.

**Comment by chaurah** [comment]
Closing this as a duplicate as mentioned by @tim-nordell-nimbelink above.

Rahul
