### ISSUE TITLE
NETWORK_SSL_READ_ERROR AWS IoT Sdk-as-esp-idf

### ISSUE THREAD

**Issue by ahtashambaig** [aws/aws-iot-device-sdk-embedded-C#947]
Hi i am working on project which needs to be connected to multiple MQTT for that i increased the number of topic filters but i am facing issue with NETWORK_SSL_READ_ERROR my configurations are correct for both aws and esp32

**Comment by abhidixi11** [comment]
Hello ahtashambaig,
Thanks for contacting us.
Is this question related to a CSDK or amazon-freertos ? Which version of CSDK you are using ?
>needs to be connected to multiple MQTT
Do you want connect to multiple MQTT servers or do you want to subscribe to multiple topics. ?
Thanks,
Abhijit

**Comment by sarenameas** [comment]
Hello @ahtashambaig,

Are you still facing issues?

**Comment by ahtashambaig** [comment]
@abhidixi11 I am using CSDK esp-idf v3.3 and i want to connect multiple topics using single server AWS 
@sarenameas yes still facing issue for now i am just using single topic, which is working correctly. But connecting to multiple topic repeats the problem, which clarifies there is no issue with configuration

**Comment by abhidixi11** [comment]
@ahtashambaig Thanks for getting back.  I was trying to confirm which version of aws-iot CSDK are you using, didn't realize you are using esp-idf's repository. Is that from here ? 
https://github.com/espressif/aws-iot-device-sdk-embedded-C/tree/299183238ffe7a3e6a5ca0af9db19c10eaca62cf
It looks to me fairly old and looks like it is based upon our v3  CSDK (current master of this repository). Can you give a try to this repository and get the latest master , it should be compatible plus some bug fixes? I would like to see the logs if the failure happens with latest code. 
I'm assuming you are subscribing to more than one topics and then trying receive messages? 
Are you also publishing to the topics?

Thanks!

**Comment by yanjos-dev** [comment]
@ahtashambaig This topic has become inactive so I'm going to close the issue. Please feel free to reopen this if you have any questions or need any further assistance.
