### ISSUE TITLE
Assignment of function parameter has no effect outside the function.

### ISSUE THREAD

**Issue by fedex03** [aws/aws-iot-device-sdk-embedded-C#95]
Hi there,

I'm using the aws-iot-device-sdk-embedded-C into an embedded project and when I run a static code analysis with "CppCheck" I find this error:

> Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?

`pJsonHandler = (void *) jsonTokenStruct;`

into the function **isJsonValidAndParse**. 

> service/aws_mqtt/src/aws_iot_shadow_json.c @ line 364

This bug is already found and fixed or not?

Thanks for the help!

**Comment by hedeshianaws** [comment]
Thank you for reporting this bug. Yes, I believe that line should be

`*pJsonHandler = (void *) jsonTokenStruct;`

We've made a note of it internally.
