### ISSUE TITLE
NETWORK_ALREADY_CONNECTED_ERROR with aws_iot_shadow_connect

### ISSUE THREAD

**Issue by anubhutimittal1** [aws/aws-iot-device-sdk-embedded-C#953]
This is for AWS IoT V3 master branch. aws_iot_shadow_connect performs 2 actions:
1. aws_iot_mqtt_connect
2. aws_iot_mqtt_subscribe(delete topic)

Let say aws_iot_mqtt_connect succeeds and aws_iot_mqtt_subscribe fails for some reason, calling aws_iot_shadow_connect again to subscribe to delete topic gives NETWORK_ALREADY_CONNECTED_ERROR before it can subscribe to delete.

In this case, there is no other way to subscribe to delete topic again unless we disconnect and reconnect. It does not make sense to disconnect just to subscribe successfully when we are already connected.

Is it possible to add one more condition here rc != NETWORK_ALREADY_CONNECTED_ERROR: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/master/src/aws_iot_shadow.c#L131 so that even if we are connected successfully, it tries to subscribe again? 

If not this, is it possible to separate out subscribe part from the function?

**Comment by abhidixi11** [comment]
Hey Anubhuti,

Can the application directly call aws_iot_mqtt_subscribe() with delete topic if subscription fails?
It is public API and all you need is thing name.
You can also set deleteActionHandler to NULL and handle subscribe outside the aws_iot_shadow_connect(). You only need thing name and you can reuse the code 
under the if()statement.

**Comment by anubhutimittal1** [comment]
Will call it outside altogether. Thanks!
