### ISSUE TITLE
Disconnect won't release TLS  memory when network down

### ISSUE THREAD

**Issue by andrew0x0** [aws/aws-iot-device-sdk-embedded-C#96]
_aws_iot_mqtt_internal_disconnect
/* send the disconnect packet */
	if(serialized_len > 0) {
		rc = aws_iot_mqtt_internal_send_packet(pClient, serialized_len, &timer);
		if(SUCCESS != rc) {
			FUNC_EXIT_RC(rc);
		}
	}
Should remove if (), just no matter disconnect packet send out or not just return 0 let caller release TLS memory

**Comment by chaurah** [comment]
Hi @andrew0x0,
     Thank you for pointing this out. I have added a task to our internal tracker for the next release of the SDK. Please let us know if you find any further issues.

Rahul

**Comment by andrew0x0** [comment]
U r welcome!

2017年9月16日 04:58，"Rahul Singh Chauhan" <notifications@github.com>写道：
