### ISSUE TITLE
Frequent disconnects on AWS IOT client when connected over wifi (Mobile Hotspot)) 

### ISSUE THREAD

**Issue by ashokgaddam** [aws/aws-iot-device-sdk-embedded-C#966]
Hello,

My AWS IOT client device works fine with out any disconnections when i use my wireless router as Access point. When i use the mobile hotspot as Wi-Fi, i see every 5 min disconnect callback is invoked and reconnects to host AWS server successfully. Internet speed is good on mobile as i don't see any other failures during publish, connect and subscribe.

I can see client state as CLIENT_STATE_DISCONNECTED_MANUALLY in awsDisconnectCallback() handler

Note: Our device always connects to AWS server and keeps listening for data and take action accordingly.

We use TCP keep alive to monitor the connection at TCP layer. TCP keep alive is set to 5 mins in application. (After connection and listening to host server idle on the network,  every 5 mins TCP keep alive packet is sent to host, if no response probably connection is lost  and invokes the disconnect call back) . Need to understand reason for connection drop 

Any thoughts what might be happening when i use mobile as WiFi hotspot ?
1. Is mobile hotspot allows only for certain duration to connect and communicate to host sever ?
 
AWS C SDK - v3.0.1

Regards,
Ashok

**Comment by aggarg** [comment]
> Is mobile hotspot allows only for certain duration to connect and communicate to host sever ?

The MQTT client library does not know anything about the underlying connection and there is no special restriction for the Mobile hotspot. We need to understand what is causing the disconnect.

Client state `CLIENT_STATE_DISCONNECTED_MANUALLY` means that the application code explicitly called `aws_iot_mqtt_disconnect`. Would you please grep your code to check for the places you are calling `aws_iot_mqtt_disconnect`.

We have made this fix recently to handle delayed ping responses: https://github.com/aws/aws-iot-device-sdk-embedded-C/commit/7f27b0370af651eaa16dbc132d24af8c193d2d90. Would you also take the code from the tip of master and let us know if the problem still persists.

Thanks.

**Comment by ashokgaddam** [comment]
Hi Gaurav,

I don't think it is because of delayed ping response because we are using mqtt keep alive timeout to 20 min.

Also, we check TLS connection is active or not at the TCP layer by sending a small TCP ping packet which is set to 5 mins (which means every 5 mins, TCP ping is sent and waits for response, if response is received the TCP connection is ok, other it is considered connection lost with AWS sever and calls disconnect() handler to re establish the connection).

With the routers as Access point, we don't see any issues. The issue happens only if we use the mobile as wifi hotspot. Our devices opens the connection to AWS broker and keeps listening for data and take actions if any data received on subscribed topic.

1. We use port as 8883 to connect to AWS broker, i am not sure mobile hotspots allow these ports to listen continuously and stay connected for ling time. Do you guys did any testing with mobile as hotspot or any thoughts what could be the reason for connection failure ?

Regards,
Ashok

**Comment by aggarg** [comment]
> We use port as 8883 to connect to AWS broker, i am not sure mobile hotspots allow these ports to listen continuously and stay connected for long time duration. 

I am not aware of anything mobile hotspot specific and we will need to understand who is initiating the disconnect and why. It will be helpful to get a packet capture here. The following is a way to get the packet capture:

1. Start a hotsopt on your laptop - Let's call the SSID `laptop-hotspot`.
1. Start a hotsopt on your Mobile - Let's call the SSID `mobile-hotspot`.
1. Connect your laptop to `mobile-hotspot`.
1. Connect your device to `laptop-hotspot`.

The data flow in this case is:

```
+---------+      +----------+      +----------+
| Device  +----->|  Laptop  |----->|  Mobile  |
+---------+      +----------+      +----------+
```
Now you can run Wireshark on your laptop and get a packet capture. I understand that it is not the exact same setup but let's see if we can reproduce the problem in this setup.

Also, as I mentioned before, please grep your source to check for the places you are calling `aws_iot_mqtt_disconnect`.

Thanks.

**Comment by ashokgaddam** [comment]
Hi Gaurav,

I can still see the issue with the setup mentioned as above. Attached wire shark capture.

At Time = 986 sec,  first connection made successfully to AWS host (syn, followed by syn+ack)
At Time = 1320 sec (after 5 mins from the connection), TCP keep alive packet failed and re connection attempt was made and it got success.  The same sequence continues at every 5 mins  

aws_iot_mqtt_disconnect() is invoked during yield() while reading data from the socket 



Regards,
Ashok

**Comment by aggarg** [comment]
Thank you for sharing the packet capture. 

I am not sure how you determine that the re-connection attempt is made in response to a TCP keep-alive failure. Looking at the image below, I see that packet number 139 (which was sent around 993) was an acknowledgement from the client. And packet number 140 (which was sent around 1302) was a re-connection attempt from the client. 

![packet_seq](https://user-images.githubusercontent.com/33462878/83101552-6ed8d080-a067-11ea-84ad-7bacda176856.JPG)

Assuming your analysis is correct, the symptom you are observing is that the TCP connection is dead after 5 minutes of inactivity - as a result of which TCP keep-alive fails. There are two possible reasons I can think of:

1. There is some local setting of the mobile phone which is terminating the idle connection (for saving battery may be). 
1. Or your network provider is terminating the connection. 

We can isolate if it is some mobile phone setting by connecting your mobile phone to WiFi AP and thereby not relying on the network operator. The data flow in that case will be:

```
+---------+      +----------+      +----------+      +----------+
| Device  +----->|  Laptop  |----->|  Mobile  |----->|   WiFi   |
+---------+      +----------+      +----------+      +----------+
```

Would you please try the above and see what happens.

Thanks.

**Comment by ashokgaddam** [comment]
Hi Gaurav,

I can see this issue (Disconnecting from host server after idle time of 5 - 6 mins) with some of the routers that my team was using. I ensured the internet settings is enabled always instead of connect on demand in the router side so that it won't disconnect the idle listening connection after some time. I am yet to get the wire shark sniffer logs to share.  Any thoughts, is this issue is happening from the ISP some reason ? 

Here is the data flow that i am going to use to get wifi sniffer logs
1. Enable hotspot on laptop
2. Connect Device to the laptop hotspot.
3. Connect Laptop to the wifi access point
4. Run wire shark on the laptop to capture the outgoing traffic
 
+-----------+      +----------+      +----------+      
| Iot Device |----->|  Laptop  |----->|  WiFi  |
+-----------+      +----------+      +----------+      

Regards,
Ashok

**Comment by aggarg** [comment]
>Any thoughts, is this issue is happening from the ISP some reason ?

I am not aware of anything ISP specific and it is difficult to comment. You said that you see the issue with some of the routers - does it mean that you do not see it with other routers? If so, finding out the difference between a working and a non-working router may help to find out the cause of the problem.

Thanks.

**Comment by ashokgaddam** [comment]
Yes, the issue was observed with some routers, no issues with other routers. I am trying to get wire shark logs with the router having this issue.

**Comment by abhidixi11** [comment]
Hello @ashokgaddam  Did you manage to get the logs ?
Thanks.

**Comment by ashokgaddam** [comment]
I am still yet to get the logs. Will post you updates soon.

**Comment by leegeth** [comment]
@ashokgaddam ,

Thanks. Any luck in getting the logs? Please let us know when you have the logs, so that we can continue to assist you with this issue.

**Comment by yanjos-dev** [comment]
@ashokgaddam This topic has become inactive so I'm going to close the issue. Please reopen this if you have any questions or need any further assistance.
