### ISSUE TITLE
Reconnect don't release tls memory too

### ISSUE THREAD

**Issue by andrew0x0** [aws/aws-iot-device-sdk-embedded-C#97]
Hi, guys, it's seems aws_iot_mqtt_attempt_reconnect don't release last time's TLS resource and malloc it again in follow.

/* Ignoring return code. failures expected if network is disconnected */
	rc = aws_iot_mqtt_connect(pClient, NULL);

**Comment by chaurah** [comment]
Hi @andrew0x0,
      Its the same call flow as #96 that you opened a few days ago. I am working on the network layer to address this issue. Closing this one as a duplicate. Thank you for bringing this up.

Rahul

**Comment by andrew0x0** [comment]
No，i thinks is different situation, #96 is about network down but disconnect can't release memory.This one i want to talk about enable auto reconnect , sdk just directly call iot_tls_connect without release memory of last tls connect. Sorry ,if i don't explain cleanly.
