### ISSUE TITLE
New function -  set attribute in desired to null

### ISSUE THREAD

**Issue by eugene345** [aws/aws-iot-device-sdk-embedded-C#98]
Hello,

Is it possible in the next sdk release to add a new function to set an attribute in the "desired" section to null?

Here is a use case for it. Let's say we have a boolean attribute "lightEnable". To enable light we post "lightEnable = true" as desired. Device receives delta, enables light and posts "lightEnable = true" as reported.  But then for some reason device has to switch light off (e.g. based on some sensor).  After switching light OFF device posts  "lightEnable = false" as reported.  But desired section still has "lightEnable = true". And with the next delta (when some another attribute will be updated) device receives "lightEnable = true" again. To prevent such behavior device should set lightEnable to null in desired section.

This use case is very common, I think.

Best regards,
Eugene.

**Comment by hedeshianaws** [comment]
Hello Eugene,

Thank you for your feedback. We in the process of reviewing the behaviour of the shadow APIs. We will take your request into consideration.

**Comment by eugene345** [comment]
One more application for this API. 
Wrong value (e.g. out of range) was posted as "desired". Device receives delta and posts previous or some default value as "reported" (because can't accept wrong value). To prevent the endless loop, device should set to null the wrong attribute in "desired".

**Comment by Borschtsch** [comment]
Hi @eugene345 ,
For such cases we introduced 'status' parameter, which reflects what is actually going with a light - it may tell you the reason why light is off. It is a safer way of handling such situations when actual device state does not match the desired state. And it does not involve manupulating the 'desired' part which usually a sole responsibility of the backend.

We learned from our use cases that Shadow is mostly good for the parameters that set a long-term state only - configuration parameters, alrogithm options, the mode the device should be staying in. But when a device has a choice and its state may not match with 'desired' then the Shadow model does not work so well. In such cases parameters in the 'desired' section just become parameters that have to be confirmed by the device through the 'reported' section and the actual status is reported somehow else.

Also, if you plan to issue a command to the device and get some response (or no response), like 'beep or vibrate right now', then you should better think of using just the MQTT part of the SDK for this - for our project we created special command/response topics that work only when device is online and can actually accept commands. If you put the command through the Shadow, it will record the command and send it to the device when it becomes online. The backend may do some 'desired' clean-up if command didn't go through, but it is so much easier just to have special topics. We modified SDK slightly to support these new topics and it worked great!

Regards,
-Dmitry

**Comment by eugene345** [comment]
Hi @gordonwang0 ,

Please, re-open the issue. This feature is still important.

**Comment by dcgaws** [comment]
Hello @eugene345, please check out version 4 of our Embedded C SDK. Our new API design gives the device complete control over constructing shadow updates. [This section of our shadow demo app](https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/v4_beta/demos/src/aws_iot_demo_shadow.c#L317) shows the handling of a simple shadow document schema without the code-size and RAM overhead of a full JSON parser. We took that approach in order to ensure that our SDK libraries are suitable for a variety of resource-constrained devices.

If your use case calls for a more complex shadow document schema, and your RAM budget allows for that, it may be worthwhile for you to investigate the use of a third-party JSON parser in your app.
