### ISSUE TITLE
Configurable MQTT buffers size

### ISSUE THREAD

**Issue by eugene345** [aws/aws-iot-device-sdk-embedded-C#99]
Hello,

Would be good to have availability to specify MQTT buffers size for each MQTT client separately (or use user provided memory block). In my application I use AWS IoT for device control and another MQTT client for data streaming. And the 2nd client requires 10 times bigger TX buffer size.

Best regards,
Eugene.

**Comment by hedeshianaws** [comment]
Hello,

Thanks for the feedback. Can you give us a little more information about your target device and what capabilities it has? Also, do you require static memory allocation, or can you support dynamic memory allocation in your use-case?

**Comment by eugene345** [comment]
Target device is STM32F446ZE - ARM Cortex M4 MCU with 512 KB flash and 128 KB SRAM, running CMSIS-RTOS2. I'd prefer static memory allocation, because malloc is quite danger in the embedded systems world and for this reason rarely used. 
As you can see, there are not too much memory, so, each byte must be used wisely. But there are lots of embedded systems with even much less RAM.

**Comment by hedeshianaws** [comment]
Thanks for that information. I agree using malloc() is not ideal in your scenario. A while back we floated the idea of having the SDK user provide the buffers at client creation time. That way, you can use whatever allocation mechanism you want without the SDK having to know about it. We shelved the proposal due to lack of interest. That said, I can revive the discussions if you think that would be helpful for you.

**Comment by eugene345** [comment]
Yes, please. User provided buffers would be great!

**Comment by softlong** [comment]
we are receiving the err of "MQTT TX BUFFER TOO SHORT ERROR" as well. it would be better to be able to specify the buffer size using the SDK.

**Comment by chrismrutherford** [comment]
FYI, I have also had to increase the buffer size for my application.  User supplied buffers would less ambiguous.

**Comment by eugene345** [comment]
Hi @gordonwang0 ,

Why this issue has been closed? Is it implemented already?

**Comment by gordonwang0** [comment]
Hi @eugene345,

We decided to close issues that had been open for a while with no replies.  This feature has not been implemented.  If this feature is still important to you, please reopen the issue.  In the meantime, we have noted your input and will address it as our priorities permit.

**Comment by eugene345** [comment]
Hi @gordonwang0 ,

Please, re-open the issue. This feature is still important.
